// SV10 — Destined Rivals (244 cartas)
// Lançamento EN: 2025/05/30
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV10 = [
  {n:'001',dex:127,artist:"GIDORA",name:'Ethan\'s Pinsir',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.15,base:true},
  {n:'002',dex:193,artist:"svlt",name:'Yanma',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'003',dex:469,artist:"takuyoa",name:'Yanmega ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:4.00,base:true},
  {n:'004',dex:204,artist:"YASHIRO Nanaco",name:'Pineco',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'005',dex:285,artist:"IKEDA Saki",name:'Shroomish',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'006',dex:286,artist:"nisimono",name:'Breloom',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'007',dex:315,artist:"nisimono",name:'Cynthia\'s Roselia',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'008',dex:407,artist:"En Morikura",name:'Cynthia\'s Roserade',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.25,base:true},
  {n:'009',dex:479,artist:"Rianti Hidayat",name:'Mow Rotom',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'010',dex:492,artist:"tono",name:'Shaymin',type:'Planta',color:'#4CAF50',rare:'Incomum',price:1.98,base:true},
  {n:'011',dex:557,artist:"Kanami Ogata",name:'Dwebble',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.18,base:true},
  {n:'012',dex:558,artist:"Po-Suzuki",name:'Crustle',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.68,base:true},
  {n:'013',dex:753,artist:"mashu",name:'Fomantis',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'014',dex:754,artist:"Masako Tomii",name:'Lurantis',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.13,base:true},
  {n:'015',dex:824,artist:"buchi",name:'Team Rocket\'s Blipbug',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'016',dex:840,artist:"Tetsu Kayama",name:'Applin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'017',dex:1011,artist:"Shigenori Negishi",name:'Dipplin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'018',dex:1019,artist:"Anesaki Dynamic",name:'Hydrapple',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.21,base:true},
  {n:'019',dex:917,artist:"Saboteri",name:'Team Rocket\'s Tarountula',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'020',dex:918,artist:"Taiga Kasai",name:'Team Rocket\'s Spidops',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.15,base:true},
  {n:'021',dex:928,artist:"Yuka Morii",name:'Smoliv',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'022',dex:929,artist:"Felicia Chen",name:'Dolliv',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.19,base:true},
  {n:'023',dex:930,artist:"PLANETA Tsuji",name:'Arboliva ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:4.99,base:true},
  {n:'024',dex:953,artist:"Toshinao Aoki",name:'Rellor',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'025',dex:954,artist:"N-DESIGN Inc.",name:'Rabsca ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.00,base:true},
  {n:'026',dex:1017,artist:"Tomomi Ozaki",name:'Teal Mask Ogerpon',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.10,base:true},
  {n:'027',dex:58,artist:"ryoma uratsuka",name:'Growlithe',type:'Fogo',color:'#F44336',rare:'Comum',price:0.16,base:true},
  {n:'028',dex:59,artist:"Nisota Niso",name:'Arcanine',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.15,base:true},
  {n:'029',dex:77,artist:"Ayako Ozaki",name:'Ponyta',type:'Fogo',color:'#F44336',rare:'Comum',price:0.20,base:true},
  {n:'030',dex:78,artist:"SIE NANAHARA",name:'Rapidash',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.14,base:true},
  {n:'031',dex:146,artist:"5ban Graphics",name:'Team Rocket\'s Moltres ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:2.90,base:true},
  {n:'032',dex:155,artist:"Susumu Maeya",name:'Ethan\'s Cyndaquil',type:'Fogo',color:'#F44336',rare:'Comum',price:0.15,base:true},
  {n:'033',dex:156,artist:"Souichirou Gunjima",name:'Ethan\'s Quilava',type:'Fogo',color:'#F44336',rare:'Comum',price:0.27,base:true},
  {n:'034',dex:157,artist:"danciao",name:'Ethan\'s Typhlosion',type:'Fogo',color:'#F44336',rare:'Rara',price:1.00,base:true},
  {n:'035',dex:218,artist:"Sanosuke Sakuma",name:'Ethan\'s Slugma',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'036',dex:219,artist:"kodama",name:'Ethan\'s Magcargo',type:'Fogo',color:'#F44336',rare:'Rara',price:0.21,base:true},
  {n:'037',dex:228,artist:"Krgc",name:'Team Rocket\'s Houndour',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'038',dex:229,artist:"Anesaki Dynamic",name:'Team Rocket\'s Houndoom',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.17,base:true},
  {n:'039',dex:250,artist:"aky CG Works",name:'Ethan\'s Ho-Oh ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:3.76,base:true},
  {n:'040',dex:255,artist:"Tika Matsuno",name:'Torchic',type:'Fogo',color:'#F44336',rare:'Comum',price:0.15,base:true},
  {n:'041',dex:256,artist:"yuu",name:'Combusken',type:'Fogo',color:'#F44336',rare:'Comum',price:0.20,base:true},
  {n:'042',dex:257,artist:"Kazumasa Yasukuni",name:'Blaziken',type:'Fogo',color:'#F44336',rare:'Rara',price:0.25,base:true},
  {n:'043',dex:479,artist:"Dsuke",name:'Heat Rotom',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'044',dex:1017,artist:"HYOGONOSUKE",name:'Hearthflame Mask Ogerpon',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.13,base:true},
  {n:'045',dex:54,artist:"Yuu Nishida",name:'Misty\'s Psyduck',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.24,base:true},
  {n:'046',dex:120,artist:"Shinya Komatsu",name:'Misty\'s Staryu',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'047',dex:121,artist:"Natsumi Yoshida",name:'Misty\'s Starmie',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.17,base:true},
  {n:'048',dex:129,artist:"Shimaris Yukichi",name:'Misty\'s Magikarp',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'049',dex:130,artist:"GOSSAN",name:'Misty\'s Gyarados',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.35,base:true},
  {n:'050',dex:131,artist:"En Morikura",name:'Misty\'s Lapras',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.12,base:true},
  {n:'051',dex:144,artist:"Mitsuhiro Arita",name:'Team Rocket\'s Articuno',type:'Aquático',color:'#2196F3',rare:'Rara',price:4.99,base:true},
  {n:'052',dex:349,artist:"kamonabe",name:'Cynthia\'s Feebas',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'053',dex:350,artist:"You Iribi",name:'Cynthia\'s Milotic',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.20,base:true},
  {n:'054',dex:366,artist:"Miki Tanaka",name:'Clamperl',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.15,base:true},
  {n:'055',dex:367,artist:"Scav",name:'Huntail',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.17,base:true},
  {n:'056',dex:368,artist:"Naoyo Kimura",name:'Gorebyss',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.20,base:true},
  {n:'057',dex:418,artist:"Ayako Ozaki",name:'Buizel',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.17,base:true},
  {n:'058',dex:419,artist:"Shibuzoh.",name:'Floatzel',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.10,base:true},
  {n:'059',dex:459,artist:"Tomokazu Komiya",name:'Snover',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'060',dex:460,artist:"kamonabe",name:'Abomasnow',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.10,base:true},
  {n:'061',dex:479,artist:"miki kudo",name:'Wash Rotom',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'062',dex:846,artist:"OKUBO",name:'Arrokuda',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.17,base:true},
  {n:'063',dex:847,artist:"Kyoko Umemoto",name:'Barraskewda',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.10,base:true},
  {n:'064',dex:974,artist:"sui",name:'Cetoddle',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'065',dex:975,artist:"kawayoo",name:'Cetitan ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:2.96,base:true},
  {n:'066',dex:977,artist:"N-DESIGN Inc.",name:'Dondozo ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:2.90,base:true},
  {n:'067',dex:1017,artist:"rika",name:'Wellspring Mask Ogerpon',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.13,base:true},
  {n:'068',dex:125,artist:"Amelicart",name:'Electabuzz',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.10,base:true},
  {n:'069',dex:466,artist:"PLANETA Mochizuki",name:'Electivire ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:3.25,base:true},
  {n:'070',dex:145,artist:"Nurikabe",name:'Team Rocket\'s Zapdos',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.40,base:true},
  {n:'071',dex:172,artist:"Narumi Sato",name:'Ethan\'s Pichu',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.20,base:true},
  {n:'072',dex:179,artist:"Teeziro",name:'Team Rocket\'s Mareep',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.11,base:true},
  {n:'073',dex:180,artist:"Jerky",name:'Team Rocket\'s Flaaffy',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'074',dex:181,artist:"Shiburingaru",name:'Team Rocket\'s Ampharos',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.15,base:true},
  {n:'075',dex:309,artist:"Narano",name:'Electrike',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.11,base:true},
  {n:'076',dex:310,artist:"Izucch",name:'Manectric',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.11,base:true},
  {n:'077',dex:479,artist:"Yoshimi Miyoshi",name:'Rotom',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.17,base:true},
  {n:'078',dex:807,artist:"Ryuta Fuse",name:'Zeraora',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.23,base:true},
  {n:'079',dex:96,artist:"matazo",name:'Team Rocket\'s Drowzee',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'080',dex:97,artist:"Yuya Oka",name:'Team Rocket\'s Hypno',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.20,base:true},
  {n:'081',dex:150,artist:"aky CG Works",name:'Team Rocket\'s Mewtwo ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:4.90,base:true},
  {n:'082',dex:202,artist:"Kazumasa Yasukuni",name:'Team Rocket\'s Wobbuffet',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.20,base:true},
  {n:'083',dex:343,artist:"Tonji Matsuno",name:'Steven\'s Baltoy',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'084',dex:344,artist:"nagimiso",name:'Steven\'s Claydol',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'085',dex:433,artist:"Mina Nakai",name:'Team Rocket\'s Chingling',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'086',dex:703,artist:"Ligton",name:'Steven\'s Carbink',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'087',dex:778,artist:"DOM",name:'Team Rocket\'s Mimikyu',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.20,base:true},
  {n:'088',dex:825,artist:"Scav",name:'Team Rocket\'s Dottler',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'089',dex:826,artist:"Shin Nagasawa",name:'Team Rocket\'s Orbeetle',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.16,base:true},
  {n:'090',dex:56,artist:"Ayako Ozaki",name:'Mankey',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.13,base:true},
  {n:'091',dex:57,artist:"GOTO minori",name:'Primeape',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'092',dex:979,artist:"Shiburingaru",name:'Annihilape',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.21,base:true},
  {n:'093',dex:185,artist:"OKACHEKE",name:'Ethan\'s Sudowoodo',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.07,base:true},
  {n:'094',dex:246,artist:"Kuroimori",name:'Team Rocket\'s Larvitar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'095',dex:247,artist:"Izucch",name:'Team Rocket\'s Pupitar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.14,base:true},
  {n:'096',dex:248,artist:"Ryuta Fuse",name:'Team Rocket\'s Tyranitar',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.20,base:true},
  {n:'097',dex:299,artist:"Oku",name:'Nosepass',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.14,base:true},
  {n:'098',dex:476,artist:"sowsow",name:'Probopass',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.13,base:true},
  {n:'099',dex:307,artist:"MINAMINAMI Take",name:'Meditite',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'100',dex:308,artist:"Whisker",name:'Medicham',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.15,base:true},
  {n:'101',dex:377,artist:"Nisota Niso",name:'Regirock ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:2.90,base:true},
  {n:'102',dex:443,artist:"Tomomi Ozaki",name:'Cynthia\'s Gible',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'103',dex:444,artist:"Taira Akitsu",name:'Cynthia\'s Gabite',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.28,base:true},
  {n:'104',dex:445,artist:"5ban Graphics",name:'Cynthia\'s Garchomp ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:9.80,base:true},
  {n:'105',dex:449,artist:"Minahamu",name:'Hippopotas',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'106',dex:450,artist:"Minahamu",name:'Hippowdon',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.12,base:true},
  {n:'107',dex:749,artist:"Aliya Chen",name:'Mudbray',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.12,base:true},
  {n:'108',dex:750,artist:"Uta",name:'Mudsdale',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.12,base:true},
  {n:'109',dex:948,artist:"Fujimoto Gold",name:'Arven\'s Toedscool',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.09,base:true},
  {n:'110',dex:949,artist:"Yuya Oka",name:'Arven\'s Toedscruel',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.14,base:true},
  {n:'111',dex:1017,artist:"Kazumasa Yasukuni",name:'Cornerstone Mask Ogerpon',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.17,base:true},
  {n:'112',dex:23,artist:"KEIICHIRO ITO",name:'Team Rocket\'s Ekans',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'113',dex:24,artist:"Teeziro",name:'Team Rocket\'s Arbok',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'114',dex:29,artist:"REND",name:'Team Rocket\'s Nidoran♀',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'115',dex:30,artist:"Taiga Kasai",name:'Team Rocket\'s Nidorina',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.11,base:true},
  {n:'116',dex:31,artist:"hncl",name:'Team Rocket\'s Nidoqueen',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'117',dex:32,artist:"buchi",name:'Team Rocket\'s Nidoran♂',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'118',dex:33,artist:"KEIICHIRO ITO",name:'Team Rocket\'s Nidorino',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.25,base:true},
  {n:'119',dex:34,artist:"5ban Graphics",name:'Team Rocket\'s Nidoking ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:3.90,base:true},
  {n:'120',dex:41,artist:"toi8",name:'Team Rocket\'s Zubat',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'121',dex:42,artist:"AKIRA EGAWA",name:'Team Rocket\'s Golbat',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'122',dex:169,artist:"5ban Graphics",name:'Team Rocket\'s Crobat ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:2.80,base:true},
  {n:'123',dex:88,artist:"Mousho",name:'Team Rocket\'s Grimer',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.08,base:true},
  {n:'124',dex:89,artist:"Uta",name:'Team Rocket\'s Muk',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'125',dex:109,artist:"kodama",name:'Team Rocket\'s Koffing',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'126',dex:110,artist:"matazo",name:'Team Rocket\'s Weezing',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  {n:'127',dex:198,artist:"Mugi Hamada",name:'Team Rocket\'s Murkrow',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  {n:'128',dex:215,artist:"GIDORA",name:'Team Rocket\'s Sneasel',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.23,base:true},
  {n:'129',dex:442,artist:"satoma",name:'Cynthia\'s Spiritomb',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'130',dex:509,artist:"REND",name:'Marnie\'s Purrloin',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'131',dex:510,artist:"Hasuno",name:'Marnie\'s Liepard',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.17,base:true},
  {n:'132',dex:559,artist:"Teeziro",name:'Marnie\'s Scraggy',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'133',dex:560,artist:"Kazumasa Yasukuni",name:'Marnie\'s Scrafty',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'134',dex:859,artist:"KEIICHIRO ITO",name:'Marnie\'s Impidimp',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'135',dex:860,artist:"NC Empire",name:'Marnie\'s Morgrem',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'136',dex:861,artist:"PLANETA Mochizuki",name:'Marnie\'s Grimmsnarl ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:5.90,base:true},
  {n:'137',dex:877,artist:"Mina Nakai",name:'Marnie\'s Morpeko',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'138',dex:942,artist:"Mina Nakai",name:'Arven\'s Maschiff',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'139',dex:943,artist:"akagi",name:'Arven\'s Mabosstiff ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:2.99,base:true},
  {n:'140',dex:205,artist:"Wintr Wandr",name:'Forretress',type:'Metal',color:'#78909C',rare:'Incomum',price:0.09,base:true},
  {n:'141',dex:227,artist:"Shin Nagasawa",name:'Skarmory',type:'Metal',color:'#78909C',rare:'Comum',price:0.13,base:true},
  {n:'142',dex:227,artist:"Nisota Niso",name:'Steven\'s Skarmory',type:'Metal',color:'#78909C',rare:'Comum',price:0.10,base:true},
  {n:'143',dex:374,artist:"Takeshi Nakamura",name:'Steven\'s Beldum',type:'Metal',color:'#78909C',rare:'Comum',price:0.12,base:true},
  {n:'144',dex:375,artist:"Anesaki Dynamic",name:'Steven\'s Metang',type:'Metal',color:'#78909C',rare:'Incomum',price:0.15,base:true},
  {n:'145',dex:376,artist:"PLANETA Mochizuki",name:'Steven\'s Metagross ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:3.60,base:true},
  {n:'146',dex:889,artist:"Mitsuhiro Arita",name:'Zamazenta',type:'Metal',color:'#78909C',rare:'Rara',price:0.20,base:true},
  {n:'147',dex:19,artist:"Dsuke",name:'Team Rocket\'s Rattata',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'148',dex:20,artist:"Uninori",name:'Team Rocket\'s Raticate',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.14,base:true},
  {n:'149',dex:52,artist:"Megumi Mizutani",name:'Team Rocket\'s Meowth',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.09,base:true},
  {n:'150',dex:53,artist:"5ban Graphics",name:'Team Rocket\'s Persian ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:2.80,base:true},
  {n:'151',dex:115,artist:"Sanosuke Sakuma",name:'Kangaskhan',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'152',dex:128,artist:"yuu",name:'Tauros',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'153',dex:137,artist:"Oswaldo KATO",name:'Team Rocket\'s Porygon',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.12,base:true},
  {n:'154',dex:233,artist:"Takeshi Nakamura",name:'Team Rocket\'s Porygon2',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.25,base:true},
  {n:'155',dex:474,artist:"Anesaki Dynamic",name:'Team Rocket\'s Porygon-Z',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.23,base:true},
  {n:'156',dex:276,artist:"Ayako Ozaki",name:'Taillow',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'157',dex:277,artist:"Souichirou Gunjima",name:'Swellow',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'158',dex:819,artist:"Oswaldo KATO",name:'Arven\'s Skwovet',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'159',dex:820,artist:"Akira Komayama",name:'Arven\'s Greedent',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.15,base:true},
  {n:'160',dex:931,artist:"Julie Hang",name:'Squawkabilly',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.14,base:true},
  {n:'161',artist:"AYUMI ODASHIMA",name:'Arven\'s Sandwich',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'162',artist:"Studio Bora Inc.",name:'Cynthia\'s Power Weight',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'163',artist:"Cona Nitanda",name:'Emcee\'s Hype',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'164',artist:"Toyste Beach",name:'Energy Recycler',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'165',artist:"Iori Suzuki",name:'Ethan\'s Adventure',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'166',artist:"AYUMI ODASHIMA",name:'Granite Cave',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'167',artist:"kantaro",name:'Judge',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'168',artist:"Eske Yoshinob",name:'Sacred Ash',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'169',artist:"AYUMI ODASHIMA",name:'Spikemuth Gym',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.19,base:true},
  {n:'170',artist:"Hideki Ishikawa",name:'Team Rocket\'s Archer',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.18,base:true},
  {n:'171',artist:"hncl",name:'Team Rocket\'s Ariana',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'172',artist:"Toyste Beach",name:'Team Rocket\'s Bother-Bot',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.13,base:true},
  {n:'173',artist:"imoniii",name:'Team Rocket\'s Factory',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'174',artist:"akagi",name:'Team Rocket\'s Giovanni',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.35,base:true},
  {n:'175',artist:"Toyste Beach",name:'Team Rocket\'s Great Ball',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'176',artist:"GOSSAN",name:'Team Rocket\'s Petrel',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.90,base:true},
  {n:'177',artist:"Naoki Saito",name:'Team Rocket\'s Proton',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'178',artist:"inose yukie",name:'Team Rocket\'s Transceiver',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'179',artist:"Toyste Beach",name:'Team Rocket\'s Venture Bomb',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.14,base:true},
  {n:'180',artist:"AYUMI ODASHIMA",name:'Team Rocket\'s Watchtower',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.30,base:true},
  {n:'181',artist:"Studio Bora Inc.",name:'TM Machine',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.18,base:true},
  {n:'182',name:'Team Rocket\'s Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.50,base:true},
  {n:'183',dex:193,artist:"Ayako Ozaki",name:'Yanma',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:39.80,base:false},
  {n:'184',dex:407,artist:"rika",name:'Cynthia\'s Roserade',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:89.90,base:false,important:true},
  {n:'185',dex:492,artist:"Heisuke Kitazawa",name:'Shaymin',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:89.00,base:false,important:true},
  {n:'186',dex:558,artist:"Takumi Wada",name:'Crustle',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:31.90,base:false},
  {n:'187',dex:918,artist:"NC Empire",name:'Team Rocket\'s Spidops',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:43.89,base:false},
  {n:'188',dex:1019,artist:"Jerky",name:'Hydrapple',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:18.90,base:false},
  {n:'189',dex:78,artist:"Rond",name:'Rapidash',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:44.90,base:false,important:true},
  {n:'190',dex:157,artist:"GIDORA",name:'Ethan\'s Typhlosion',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:100.00,base:false,important:true},
  {n:'191',dex:229,artist:"nagimiso",name:'Team Rocket\'s Houndoom',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:67.99,base:false,important:true},
  {n:'192',dex:257,artist:"kodama",name:'Blaziken',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:55.00,base:false,important:true},
  {n:'193',dex:54,artist:"OKACHEKE",name:'Misty\'s Psyduck',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:299.90,base:false,important:true},
  {n:'194',dex:131,artist:"Orca",name:'Misty\'s Lapras',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:244.90,base:false,important:true},
  {n:'195',dex:366,artist:"Mori Yuu",name:'Clamperl',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:24.90,base:false},
  {n:'196',dex:309,artist:"Nakamura Ippan",name:'Electrike',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:22.90,base:false},
  {n:'197',dex:479,artist:"Taiga Kayama",name:'Rotom',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:18.50,base:false},
  {n:'198',dex:826,artist:"HYOGONOSUKE",name:'Team Rocket\'s Orbeetle',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:16.90,base:false},
  {n:'199',dex:110,artist:"Yukihiro Tada",name:'Team Rocket\'s Weezing',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:68.99,base:false,important:true},
  {n:'200',dex:198,artist:"Akira Komayama",name:'Team Rocket\'s Murkrow',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:49.90,base:false,important:true},
  {n:'201',dex:889,artist:"Takumi Wada",name:'Zamazenta',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:29.89,base:false},
  {n:'202',dex:20,artist:"Mékayu",name:'Team Rocket\'s Raticate',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:42.00,base:false},
  {n:'203',dex:52,artist:"Shimaris Yukichi",name:'Team Rocket\'s Meowth',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:99.90,base:false,important:true},
  {n:'204',dex:115,artist:"Mékayu",name:'Kangaskhan',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:39.90,base:false,important:true},
  {n:'205',dex:820,artist:"Natsumi Yoshida",name:'Arven\'s Greedent',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:19.90,base:false},
  {n:'206',dex:469,artist:"takuyoa",name:'Yanmega ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:12.00,base:false},
  {n:'207',dex:930,artist:"PLANETA Tsuji",name:'Arboliva ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:24.99,base:false},
  {n:'208',dex:146,artist:"5ban Graphics",name:'Team Rocket\'s Moltres ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:26.50,base:false},
  {n:'209',dex:250,artist:"aky CG Works",name:'Ethan\'s Ho-Oh ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:32.75,base:false},
  {n:'210',dex:975,artist:"PLANETA Tsuji",name:'Cetitan ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:9.70,base:false},
  {n:'211',dex:977,artist:"N-DESIGN Inc.",name:'Dondozo ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:8.00,base:false},
  {n:'212',dex:466,artist:"PLANETA Mochizuki",name:'Electivire ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:8.50,base:false},
  {n:'213',dex:150,artist:"aky CG Works",name:'Team Rocket\'s Mewtwo ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:89.90,base:false,important:true},
  {n:'214',dex:377,artist:"PLANETA Mochizuki",name:'Regirock ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:8.00,base:false},
  {n:'215',dex:445,artist:"5ban Graphics",name:'Cynthia\'s Garchomp ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:34.75,base:false},
  {n:'216',dex:34,artist:"5ban Graphics",name:'Team Rocket\'s Nidoking ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:22.00,base:false},
  {n:'217',dex:169,artist:"5ban Graphics",name:'Team Rocket\'s Crobat ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:19.80,base:false},
  {n:'218',dex:943,artist:"PLANETA Igarashi",name:'Arven\'s Mabosstiff ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:8.90,base:false},
  {n:'219',dex:53,artist:"5ban Graphics",name:'Team Rocket\'s Persian ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:29.89,base:false},
  {n:'220',artist:"Cona Nitanda",name:'Emcee\'s Hype',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:19.00,base:false},
  {n:'221',artist:"Iori Suzuki",name:'Ethan\'s Adventure',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:36.00,base:false},
  {n:'222',artist:"kantaro",name:'Judge',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:23.00,base:false},
  {n:'223',artist:"Hideki Ishikawa",name:'Team Rocket\'s Archer',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:29.90,base:false},
  {n:'224',artist:"hncl",name:'Team Rocket\'s Ariana',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:49.00,base:false},
  {n:'225',artist:"akagi",name:'Team Rocket\'s Giovanni',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:69.99,base:false},
  {n:'226',artist:"GOSSAN",name:'Team Rocket\'s Petrel',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:94.00,base:false,important:true},
  {n:'227',artist:"Naoki Saito",name:'Team Rocket\'s Proton',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:31.90,base:false},
  {n:'228',dex:469,artist:"Tonji Matsuno",name:'Yanmega ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:89.90,base:false,important:true},
  {n:'229',dex:146,artist:"AKIRA EGAWA",name:'Team Rocket\'s Moltres ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:299.90,base:false,important:true},
  {n:'230',dex:250,artist:"Atsushi Furusawa",name:'Ethan\'s Ho-Oh ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:589.00,base:false,important:true},
  {n:'231',dex:150,artist:"Iwamoto05",name:'Team Rocket\'s Mewtwo ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:1398.90,base:false,important:true},
  {n:'232',dex:445,artist:"HICO KIM",name:'Cynthia\'s Garchomp ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:949.99,base:false,important:true},
  {n:'233',dex:34,artist:"Uninori",name:'Team Rocket\'s Nidoking ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:349.90,base:false,important:true},
  {n:'234',dex:169,artist:"cochi8i",name:'Team Rocket\'s Crobat ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:369.90,base:false,important:true},
  {n:'235',dex:943,artist:"Yuriko Akase",name:'Arven\'s Mabosstiff ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:85.00,base:false,important:true},
  {n:'236',artist:"Kariya",name:'Ethan\'s Adventure',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:179.90,base:false,important:true},
  {n:'237',artist:"Yoshioka",name:'Team Rocket\'s Ariana',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:160.00,base:false,important:true},
  {n:'238',artist:"Krgc",name:'Team Rocket\'s Giovanni',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:289.90,base:false,important:true},
  {n:'239',dex:250,artist:"aky CG Works",name:'Ethan\'s Ho-Oh ex',type:'Fogo',color:'#F44336',rare:'Hiper Rara',price:101.25,base:false,important:true},
  {n:'240',dex:150,artist:"aky CG Works",name:'Team Rocket\'s Mewtwo ex',type:'Psíquico',color:'#9C27B0',rare:'Hiper Rara',price:335.00,base:false,important:true},
  {n:'241',dex:445,artist:"5ban Graphics",name:'Cynthia\'s Garchomp ex',type:'Lutador',color:'#FF9800',rare:'Hiper Rara',price:169.99,base:false,important:true},
  {n:'242',dex:169,artist:"5ban Graphics",name:'Team Rocket\'s Crobat ex',type:'Sombrio',color:'#607D8B',rare:'Hiper Rara',price:89.90,base:false,important:true},
  {n:'243',artist:"AYUMI ODASHIMA",name:'Jamming Tower',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:74.90,base:false,important:true},
  {n:'244',artist:"MARINA Chikazawa",name:'Levincia',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:45.00,base:false,important:true}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV10 = CARDS_SV10;