// SV7 — Stellar Crown (175 cartas)
// Lançamento EN: 2024/09/13
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV7 = [
  {n:'001',name:'Venusaur ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:9.90,base:true},
  {n:'002',name:'Ledyba',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'003',name:'Ledian',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.25,base:true},
  {n:'004',name:'Celebi',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.10,base:true},
  {n:'005',name:'Lileep',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.09,base:true},
  {n:'006',name:'Cradily',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.20,base:true},
  {n:'007',name:'Carnivine',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'008',name:'Mow Rotom',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'009',name:'Grubbin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'010',name:'Gossifleur',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'011',name:'Eldegoss',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'012',name:'Applin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.13,base:true},
  {n:'013',name:'Dipplin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.13,base:true},
  {n:'014',name:'Hydrapple ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:6.00,base:true},
  {n:'015',name:'Nymble',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'016',name:'Lokix',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'017',name:'Toedscool',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'018',name:'Toedscruel',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.10,base:true},
  {n:'019',name:'Ponyta',type:'Fogo',color:'#F44336',rare:'Comum',price:0.15,base:true},
  {n:'020',name:'Rapidash',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.17,base:true},
  {n:'021',name:'Pansear',type:'Fogo',color:'#F44336',rare:'Comum',price:0.07,base:true},
  {n:'022',name:'Reshiram',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.10,base:true},
  {n:'023',name:'Salandit',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'024',name:'Salazzle',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.13,base:true},
  {n:'025',name:'Turtonator',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'026',name:'Scorbunny',type:'Fogo',color:'#F44336',rare:'Comum',price:0.09,base:true},
  {n:'027',name:'Raboot',type:'Fogo',color:'#F44336',rare:'Comum',price:0.17,base:true},
  {n:'028',name:'Cinderace ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:7.50,base:true},
  {n:'029',name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'030',name:'Blastoise ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:15.00,base:true},
  {n:'031',name:'Lapras',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.15,base:true},
  {n:'032',name:'Lapras ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:7.90,base:true},
  {n:'033',name:'Marill',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.18,base:true},
  {n:'034',name:'Azumarill',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.20,base:true},
  {n:'035',name:'Finneon',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'036',name:'Lumineon',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.10,base:true},
  {n:'037',name:'Tirtouga',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.15,base:true},
  {n:'038',name:'Carracosta',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.30,base:true},
  {n:'039',name:'Froakie',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'040',name:'Frogadier',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.13,base:true},
  {n:'041',name:'Greninja ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:6.00,base:true},
  {n:'042',name:'Crabominable',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.15,base:true},
  {n:'043',name:'Chewtle',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'044',name:'Drednaw',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.17,base:true},
  {n:'045',name:'Veluza',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.10,base:true},
  {n:'046',name:'Electabuzz',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.10,base:true},
  {n:'047',name:'Electivire',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.13,base:true},
  {n:'048',name:'Chinchou',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.13,base:true},
  {n:'049',name:'Lanturn',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.06,base:true},
  {n:'050',name:'Joltik',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'051',name:'Galvantula ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:4.50,base:true},
  {n:'052',name:'Charjabug',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.10,base:true},
  {n:'053',name:'Vikavolt',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.15,base:true},
  {n:'054',name:'Togedemaru',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.08,base:true},
  {n:'055',name:'Zeraora',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.25,base:true},
  {n:'056',name:'Pawmi',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'057',name:'Slowpoke',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:8.90,base:true},
  {n:'058',name:'Slowking',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.69,base:true},
  {n:'059',name:'Mewtwo',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.48,base:true},
  {n:'060',name:'Drifloon',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'061',name:'Drifblim',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.10,base:true},
  {n:'062',name:'Yamask',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'063',name:'Comfey',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'064',name:'Milcery',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'065',name:'Alcremie',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.45,base:true},
  {n:'066',name:'Fidough',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.09,base:true},
  {n:'067',name:'Dachsbun ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:3.90,base:true},
  {n:'068',name:'Flittle',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'069',name:'Espathra',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'070',name:'Greavard',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'071',name:'Iron Boulder',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.20,base:true},
  {n:'072',name:'Cubone',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'073',name:'Marowak',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.15,base:true},
  {n:'074',name:'Rhyhorn',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.09,base:true},
  {n:'075',name:'Rhydon',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.20,base:true},
  {n:'076',name:'Rhyperior',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.26,base:true},
  {n:'077',name:'Meditite',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'078',name:'Meditite',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.11,base:true},
  {n:'079',name:'Medicham',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.13,base:true},
  {n:'080',name:'Medicham ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:3.50,base:true},
  {n:'081',name:'Riolu',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'082',name:'Lucario ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:6.00,base:true},
  {n:'083',name:'Mienfoo',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'084',name:'Mienshao',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.10,base:true},
  {n:'085',name:'Pancham',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'086',name:'Diancie',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.14,base:true},
  {n:'087',name:'Crabrawler',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'088',name:'Falinks',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.20,base:true},
  {n:'089',name:'Garganacl ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:3.39,base:true},
  {n:'090',name:'Koraidon',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.10,base:true},
  {n:'091',name:'Gulpin',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.17,base:true},
  {n:'092',name:'Swalot',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'093',name:'Pangoro',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.09,base:true},
  {n:'094',name:'Impidimp',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.13,base:true},
  {n:'095',name:'Morgrem',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'096',name:'Grimmsnarl',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.30,base:true},
  {n:'097',name:'Bombirdier',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.14,base:true},
  {n:'098',name:'Jirachi',type:'Metal',color:'#78909C',rare:'Incomum',price:0.20,base:true},
  {n:'099',name:'Klink',type:'Metal',color:'#78909C',rare:'Comum',price:0.10,base:true},
  {n:'100',name:'Klang',type:'Metal',color:'#78909C',rare:'Comum',price:0.10,base:true},
  {n:'101',name:'Klinklang',type:'Metal',color:'#78909C',rare:'Rara',price:0.25,base:true},
  {n:'102',name:'Meltan',type:'Metal',color:'#78909C',rare:'Comum',price:0.20,base:true},
  {n:'103',name:'Meltan',type:'Metal',color:'#78909C',rare:'Comum',price:0.10,base:true},
  {n:'104',name:'Melmetal',type:'Metal',color:'#78909C',rare:'Rara',price:0.20,base:true},
  {n:'105',name:'Melmetal ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:4.89,base:true},
  {n:'106',name:'Duraludon',type:'Metal',color:'#78909C',rare:'Comum',price:0.08,base:true},
  {n:'107',name:'Archaludon',type:'Metal',color:'#78909C',rare:'Rara',price:0.20,base:true},
  {n:'108',name:'Varoom',type:'Metal',color:'#78909C',rare:'Comum',price:0.09,base:true},
  {n:'109',name:'Revavroom',type:'Metal',color:'#78909C',rare:'Incomum',price:0.18,base:true},
  {n:'110',name:'Orthworm ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:2.90,base:true},
  {n:'111',name:'Raging Bolt',type:'Dragão',color:'#3F51B5',rare:'Rara',price:0.29,base:true},
  {n:'112',name:'Tauros',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'113',name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'114',name:'Hoothoot',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.25,base:true},
  {n:'115',name:'Noctowl',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.27,base:true},
  {n:'116',name:'Glameow',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.14,base:true},
  {n:'117',name:'Purugly',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.13,base:true},
  {n:'118',name:'Fan Rotom',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'119',name:'Bouffalant',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.27,base:true},
  {n:'120',name:'Tornadus',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'121',name:'Fletchling',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'122',name:'Fletchinder',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.09,base:true},
  {n:'123',name:'Talonflame',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.08,base:true},
  {n:'124',name:'Wooloo',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'125',name:'Dubwool',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'126',name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.08,base:true},
  {n:'127',name:'Cyclizar',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.13,base:true},
  {n:'128',name:'Terapagos ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:4.78,base:true},
  {n:'129',name:'Antique Cover Fossil',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'130',name:'Antique Root Fossil',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.14,base:true},
  {n:'131',name:'Area Zero Underdepths',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.14,base:true},
  {n:'132',name:'Briar',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'133',name:'Crispin',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.80,base:true},
  {n:'134',name:'Deluxe Bomb',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:2.70,base:false},
  {n:'135',name:'Glass Trumpet',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'136',name:'Grand Tree',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:3.15,base:false},
  {n:'137',name:'Gravity Gemstone',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'138',name:'Kofu',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'139',name:'Lacey',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.13,base:true},
  {n:'140',name:'Occa Berry',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'141',name:'Payapa Berry',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.14,base:true},
  {n:'142',name:'Sparkling Crystal',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:2.40,base:false},
  {n:'143',name:'Bulbasaur',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:224.95,base:false,important:true},
  {n:'144',name:'Ledian',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:23.99,base:false},
  {n:'145',name:'Lileep',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:20.00,base:false,important:true},
  {n:'146',name:'Turtonator',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:14.50,base:false},
  {n:'147',name:'Raboot',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:24.90,base:false},
  {n:'148',name:'Squirtle',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:185.00,base:false,important:true},
  {n:'149',name:'Crabominable',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:9.00,base:false},
  {n:'150',name:'Joltik',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:19.00,base:false,important:true},
  {n:'151',name:'Zeraora',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:30.00,base:false,important:true},
  {n:'152',name:'Milcery',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:55.00,base:false,important:true},
  {n:'153',name:'Meditite',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:24.00,base:false,important:true},
  {n:'154',name:'Gulpin',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:19.00,base:false,important:true},
  {n:'155',name:'Archaludon',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:19.99,base:false},
  {n:'156',name:'Hydrapple ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:24.99,base:false},
  {n:'157',name:'Cinderace ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:14.71,base:false},
  {n:'158',name:'Lapras ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:14.90,base:false},
  {n:'159',name:'Galvantula ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:9.80,base:false},
  {n:'160',name:'Dachsbun ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:14.90,base:false},
  {n:'161',name:'Medicham ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:6.00,base:false},
  {n:'162',name:'Orthworm ex',type:'Metal',color:'#78909C',rare:'Ultra Rara',price:6.30,base:false},
  {n:'163',name:'Briar',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:17.00,base:false},
  {n:'164',name:'Crispin',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:69.90,base:false,important:true},
  {n:'165',name:'Kofu',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:6.00,base:false},
  {n:'166',name:'Lacey',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:9.99,base:false},
  {n:'167',name:'Hydrapple ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:148.90,base:false,important:true},
  {n:'168',name:'Galvantula ex',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada Especial',price:60.50,base:false,important:true},
  {n:'169',name:'Dachsbun ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:110.00,base:false,important:true},
  {n:'170',name:'Terapagos ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:85.00,base:false,important:true},
  {n:'171',name:'Briar',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:79.98,base:false,important:true},
  {n:'172',name:'Lacey',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:98.99,base:false,important:true},
  {n:'173',name:'Terapagos ex',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:30.00,base:false,important:true},
  {n:'174',name:'Area Zero Underdepths',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:54.90,base:false,important:true},
  {n:'175',name:'Bravery Charm',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:21.90,base:false}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV7 = CARDS_SV7;