// SV4 — Paradox Rift (266 cartas)
// Lançamento EN: 2023/11/03
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV4 = [
  {n:'001',dex:283,artist:"Yoriyuki Ikegami",name:'Surskit',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'002',dex:284,artist:"kantaro",name:'Masquerain',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.25,base:true},
  {n:'003',dex:478,artist:"5ban Graphics",name:'Froslass ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:4.50,base:true},
  {n:'004',dex:511,artist:"Jerky",name:'Pansage',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'005',dex:512,artist:"Kurata So",name:'Simisage',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.25,base:true},
  {n:'006',dex:557,artist:"Scav",name:'Dwebble',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'007',dex:558,artist:"Shin Nagasawa",name:'Crustle',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'008',dex:761,artist:"Kouki Saitou",name:'Bounsweet',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.13,base:true},
  {n:'009',dex:762,artist:"Kariya",name:'Steenee',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.21,base:true},
  {n:'010',dex:824,artist:"OKUBO",name:'Blipbug',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'011',dex:825,artist:"Haru Akasaka",name:'Dottler',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'012',dex:826,artist:"Oku",name:'Orbeetle',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'013',dex:919,artist:"Pani Kobayashi",name:'Nymble',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.13,base:true},
  {n:'014',dex:919,artist:"Kouki Saitou",name:'Nymble',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'015',dex:948,artist:"Tomokazu Komiya",name:'Toedscool',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'016',dex:948,artist:"Souichirou Gunjima",name:'Toedscool',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'017',dex:949,artist:"Toshinao Aoki",name:'Toedscruel',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'018',dex:1001,artist:"Kouki Saitou",name:'Wo-Chien',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.35,base:true},
  {n:'019',dex:240,artist:"Naoyo Kimura",name:'Magby',type:'Fogo',color:'#F44336',rare:'Comum',price:0.20,base:true},
  {n:'020',dex:513,artist:"LINNE",name:'Pansear',type:'Fogo',color:'#F44336',rare:'Comum',price:0.20,base:true},
  {n:'021',dex:514,artist:"Yuya Oka",name:'Simisear',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.20,base:true},
  {n:'022',dex:721,artist:"Nisota Niso",name:'Volcanion',type:'Fogo',color:'#F44336',rare:'Rara',price:0.35,base:true},
  {n:'023',dex:909,artist:"Gemi",name:'Fuecoco',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'024',dex:910,artist:"Pani Kobayashi",name:'Crocalor',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.13,base:true},
  {n:'025',dex:935,artist:"kantaro",name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.25,base:true},
  {n:'026',dex:935,artist:"Mizue",name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.21,base:true},
  {n:'027',dex:936,artist:"takuyoa",name:'Armarouge ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:4.90,base:true},
  {n:'028',dex:994,artist:"Kouki Saitou",name:'Iron Moth',type:'Fogo',color:'#F44336',rare:'Rara',price:0.35,base:true},
  {n:'029',dex:1004,artist:"Oswaldo KATO",name:'Chi-Yu',type:'Fogo',color:'#F44336',rare:'Rara',price:0.35,base:true},
  {n:'030',dex:116,artist:"HYOGONOSUKE",name:'Horsea',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.25,base:true},
  {n:'031',dex:117,artist:"otumami",name:'Seadra',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.24,base:true},
  {n:'032',dex:230,artist:"Tonji Matsuno",name:'Kingdra',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.34,base:true},
  {n:'033',dex:223,artist:"Midori Harada",name:'Remoraid',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'034',dex:224,artist:"Yuka Morii",name:'Octillery',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.25,base:true},
  {n:'035',dex:349,artist:"Tetsu Kayama",name:'Feebas',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'036',dex:350,artist:"Atsuya Uki",name:'Milotic',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.50,base:true},
  {n:'037',dex:361,artist:"satoma",name:'Snorunt',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.25,base:true},
  {n:'038',dex:445,artist:"5ban Graphics",name:'Garchomp ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:9.75,base:true},
  {n:'039',dex:458,artist:"miki kudo",name:'Mantyke',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'040',dex:484,artist:"Ryuta Fuse",name:'Palkia',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.20,base:true},
  {n:'041',dex:515,artist:"Natsumi Yoshida",name:'Panpour',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'042',dex:516,artist:"nagimiso",name:'Simipour',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.13,base:true},
  {n:'043',dex:582,artist:"miki kudo",name:'Vanillite',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'044',dex:583,artist:"Lee HyunJung",name:'Vanillish',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'045',dex:584,artist:"Nelnal",name:'Vanilluxe',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.10,base:true},
  {n:'046',dex:763,artist:"5ban Graphics",name:'Tsareena ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:6.90,base:true},
  {n:'047',dex:767,artist:"Shigenori Negishi",name:'Wimpod',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'048',dex:767,artist:"sowsow",name:'Wimpod',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'049',dex:768,artist:"nagimiso",name:'Golisopod',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.30,base:true},
  {n:'050',dex:768,artist:"N-DESIGN Inc.",name:'Golisopod ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:4.90,base:true},
  {n:'051',dex:960,artist:"Shibuzoh.",name:'Wiglett',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'052',dex:960,artist:"Tomokazu Komiya",name:'Wiglett',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.25,base:true},
  {n:'053',dex:961,artist:"Kouki Saitou",name:'Wugtrio',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.24,base:true},
  {n:'054',dex:976,artist:"Oswaldo KATO",name:'Veluza',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.21,base:true},
  {n:'055',dex:977,artist:"Kouki Saitou",name:'Dondozo',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.25,base:true},
  {n:'056',dex:991,artist:"Oswaldo KATO",name:'Iron Bundle',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.17,base:true},
  {n:'057',dex:1002,artist:"Anesaki Dynamic",name:'Chien-Pao',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.36,base:true},
  {n:'058',dex:150,artist:"aky CG Works",name:'Mewtwo ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:14.90,base:true},
  {n:'059',dex:239,artist:"aoki",name:'Elekid',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.21,base:true},
  {n:'060',dex:311,artist:"Sekio",name:'Plusle',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.23,base:true},
  {n:'061',dex:312,artist:"Narumi Sato",name:'Minun',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.25,base:true},
  {n:'062',dex:522,artist:"Shinji Kanda",name:'Blitzle',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.10,base:true},
  {n:'063',dex:523,artist:"GOSSAN",name:'Zebstrika',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.10,base:true},
  {n:'064',dex:595,artist:"Kedamahadaitai Yawarakai",name:'Joltik',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.21,base:true},
  {n:'065',dex:596,artist:"Taira Akitsu",name:'Galvantula',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.21,base:true},
  {n:'066',dex:644,artist:"Shiburingaru",name:'Zekrom',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.35,base:true},
  {n:'067',dex:741,artist:"Saya Tsuruta",name:'Oricorio',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.21,base:true},
  {n:'068',dex:785,artist:"hncl",name:'Tapu Koko ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:2.79,base:true},
  {n:'069',dex:848,artist:"Yuka Morii",name:'Toxel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.23,base:true},
  {n:'070',dex:992,artist:"PLANETA Mochizuki",name:'Iron Hands ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:4.00,base:true},
  {n:'071',dex:177,artist:"ryoma uratsuka",name:'Natu',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'072',dex:178,artist:"Tetsu Kayama",name:'Xatu',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.10,base:true},
  {n:'073',dex:381,artist:"chibi",name:'Latios',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.35,base:true},
  {n:'074',dex:386,artist:"Saya Tsuruta",name:'Deoxys',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.50,base:true},
  {n:'075',dex:562,artist:"Misa Tsutsui",name:'Yamask',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'076',dex:563,artist:"kawayoo",name:'Cofagrigus ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:2.90,base:true},
  {n:'077',dex:710,artist:"saino misaki",name:'Pumpkaboo',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'078',dex:711,artist:"nisimono",name:'Gourgeist',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.23,base:true},
  {n:'079',dex:955,artist:"Mizue",name:'Flittle',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'080',dex:955,artist:"kodama",name:'Flittle',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'081',dex:956,artist:"Teeziro",name:'Espathra',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.18,base:true},
  {n:'082',dex:957,artist:"Teeziro",name:'Tinkatink',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.21,base:true},
  {n:'083',dex:957,artist:"Oswaldo KATO",name:'Tinkatink',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.25,base:true},
  {n:'084',dex:958,artist:"Souichirou Gunjima",name:'Tinkatuff',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'085',dex:959,artist:"KEIICHIRO ITO",name:'Tinkaton',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.25,base:true},
  {n:'086',dex:985,artist:"Ryota Murayama",name:'Scream Tail',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.25,base:true},
  {n:'087',dex:999,artist:"Mizue",name:'Gimmighoul',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'088',dex:999,artist:"Kouki Saitou",name:'Gimmighoul',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'089',dex:1006,artist:"aky CG Works",name:'Iron Valiant ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:2.99,base:true},
  {n:'090',dex:95,artist:"Shiburingaru",name:'Onix',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.20,base:true},
  {n:'091',dex:207,artist:"HYOGONOSUKE",name:'Gligar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.13,base:true},
  {n:'092',dex:472,artist:"GOSSAN",name:'Gliscor',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.18,base:true},
  {n:'093',dex:383,artist:"Uta",name:'Groudon',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.35,base:true},
  {n:'094',dex:443,artist:"saino misaki",name:'Gible',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.21,base:true},
  {n:'095',dex:444,artist:"Nisota Niso",name:'Gabite',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.25,base:true},
  {n:'096',dex:619,artist:"Natsumi Yoshida",name:'Mienfoo',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.17,base:true},
  {n:'097',dex:620,artist:"Mousho",name:'Mienshao',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.24,base:true},
  {n:'098',dex:720,artist:"5ban Graphics",name:'Hoopa ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:4.90,base:true},
  {n:'099',dex:774,artist:"OKUBO",name:'Minior',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.24,base:true},
  {n:'100',dex:849,artist:"5ban Graphics",name:'Toxtricity ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:4.00,base:true},
  {n:'101',dex:932,artist:"Mizue",name:'Nacli',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'102',dex:932,artist:"Pani Kobayashi",name:'Nacli',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.21,base:true},
  {n:'103',dex:933,artist:"KEIICHIRO ITO",name:'Naclstack',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.21,base:true},
  {n:'104',dex:934,artist:"Souichirou Gunjima",name:'Garganacl',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.35,base:true},
  {n:'105',dex:950,artist:"Yuya Oka",name:'Klawf',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.24,base:true},
  {n:'106',dex:973,artist:"Anesaki Dynamic",name:'Flamigo',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.21,base:true},
  {n:'107',dex:988,artist:"Anesaki Dynamic",name:'Slither Wing',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.21,base:true},
  {n:'108',dex:989,artist:"PLANETA Mochizuki",name:'Sandy Shocks ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:2.99,base:true},
  {n:'109',dex:1003,artist:"AKIRA EGAWA",name:'Ting-Lu',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.25,base:true},
  {n:'110',dex:41,artist:"Sumiyoshi Kizuki",name:'Zubat',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.20,base:true},
  {n:'111',dex:42,artist:"Eri Yamaki",name:'Golbat',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.21,base:true},
  {n:'112',dex:169,artist:"Uta",name:'Crobat',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.25,base:true},
  {n:'113',dex:359,artist:"Shinji Kanda",name:'Absol',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.17,base:true},
  {n:'114',dex:509,artist:"0313",name:'Purrloin',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.20,base:true},
  {n:'115',dex:510,artist:"Yoshioka",name:'Liepard',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.20,base:true},
  {n:'116',dex:568,artist:"Miki Tanaka",name:'Trubbish',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'117',dex:569,artist:"Aya Kusube",name:'Garbodor',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  {n:'118',dex:717,artist:"kawayoo",name:'Yveltal',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.25,base:true},
  {n:'119',dex:827,artist:"Yuu Nishida",name:'Nickit',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'120',dex:828,artist:"SIE NANAHARA",name:'Thievul',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.35,base:true},
  {n:'121',dex:877,artist:"Cona Nitanda",name:'Morpeko',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.13,base:true},
  {n:'122',dex:920,artist:"Souichirou Gunjima",name:'Lokix',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.24,base:true},
  {n:'123',dex:986,artist:"Anesaki Dynamic",name:'Brute Bonnet',type:'Sombrio',color:'#607D8B',rare:'Rara',price:1.00,base:true},
  {n:'124',dex:1005,artist:"takuyoa",name:'Roaring Moon ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:5.00,base:true},
  {n:'125',dex:208,artist:"Po-Suzuki",name:'Steelix',type:'Metal',color:'#78909C',rare:'Rara',price:0.35,base:true},
  {n:'126',dex:385,artist:"Naoyo Kimura",name:'Jirachi',type:'Metal',color:'#78909C',rare:'Comum',price:0.25,base:true},
  {n:'127',dex:597,artist:"Miki Tanaka",name:'Ferroseed',type:'Metal',color:'#78909C',rare:'Comum',price:0.17,base:true},
  {n:'128',dex:598,artist:"SATOSHI NAKAI",name:'Ferrothorn',type:'Metal',color:'#78909C',rare:'Incomum',price:0.10,base:true},
  {n:'129',dex:632,artist:"Kyoko Umemoto",name:'Durant',type:'Metal',color:'#78909C',rare:'Incomum',price:0.20,base:true},
  {n:'130',dex:679,artist:"aoki",name:'Honedge',type:'Metal',color:'#78909C',rare:'Comum',price:0.10,base:true},
  {n:'131',dex:679,artist:"Nagomi Nijo",name:'Honedge',type:'Metal',color:'#78909C',rare:'Comum',price:0.20,base:true},
  {n:'132',dex:680,artist:"Bun Toujo",name:'Doublade',type:'Metal',color:'#78909C',rare:'Comum',price:0.20,base:true},
  {n:'133',dex:680,artist:"Shigenori Negishi",name:'Doublade',type:'Metal',color:'#78909C',rare:'Comum',price:0.21,base:true},
  {n:'134',dex:681,artist:"Jiro Sasumo",name:'Aegislash',type:'Metal',color:'#78909C',rare:'Rara',price:0.30,base:true},
  {n:'135',dex:681,artist:"toriyufu",name:'Aegislash ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:5.90,base:true},
  {n:'136',dex:888,artist:"Tonji Matsuno",name:'Zacian',type:'Metal',color:'#78909C',rare:'Rara',price:0.25,base:true},
  {n:'137',dex:911,artist:"5ban Graphics",name:'Skeledirge ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:7.19,base:true},
  {n:'138',dex:968,artist:"Pani Kobayashi",name:'Orthworm',type:'Metal',color:'#78909C',rare:'Incomum',price:0.21,base:true},
  {n:'139',dex:1000,artist:"takuyoa",name:'Gholdengo ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:4.90,base:true},
  {n:'140',dex:334,artist:"Saki Hayashiro",name:'Altaria ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:4.90,base:true},
  {n:'141',dex:978,artist:"Shibuzoh.",name:'Tatsugiri',type:'Dragão',color:'#3F51B5',rare:'Incomum',price:0.10,base:true},
  {n:'142',dex:137,artist:"Taiga Kayama",name:'Porygon',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'143',dex:233,artist:"kurumitsu",name:'Porygon2',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.21,base:true},
  {n:'144',dex:474,artist:"hatachu",name:'Porygon-Z',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.25,base:true},
  {n:'145',dex:190,artist:"aspara",name:'Aipom',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.17,base:true},
  {n:'146',dex:424,artist:"Hitoshi Ariga",name:'Ambipom',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.21,base:true},
  {n:'147',dex:241,artist:"sowsow",name:'Miltank',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.21,base:true},
  {n:'148',dex:293,artist:"sui",name:'Whismur',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'149',dex:294,artist:"Yukiko Baba",name:'Loudred',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.23,base:true},
  {n:'150',dex:295,artist:"LINNE",name:'Exploud',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.21,base:true},
  {n:'151',dex:327,artist:"Masakazu Fukuda",name:'Spinda',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'152',dex:333,artist:"HYOGONOSUKE",name:'Swablu',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'153',dex:924,artist:"Shibuzoh.",name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.25,base:true},
  {n:'154',dex:924,artist:"Akira Komayama",name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.30,base:true},
  {n:'155',dex:925,artist:"5ban Graphics",name:'Maushold ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:13.00,base:true},
  {n:'156',dex:962,artist:"PLANETA Mochizuki",name:'Bombirdier ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:4.90,base:true},
  {n:'157',dex:967,artist:"kawayoo",name:'Cyclizar',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'158',dex:993,artist:"Souichirou Gunjima",name:'Iron Jugulis',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.30,base:true},
  {n:'159',artist:"5ban Graphics",name:'Ancient Booster Energy Capsule',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.23,base:true},
  {n:'160',artist:"Toyste Beach",name:'Counter Catcher',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.98,base:true},
  {n:'161',artist:"AYUMI ODASHIMA",name:'Cursed Duster',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'162',artist:"Ayaka Yoshida",name:'Defiance Vest',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'163',artist:"AYUMI ODASHIMA",name:'Earthen Vessel',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'164',artist:"5ban Graphics",name:'Future Booster Energy Capsule',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.14,base:true},
  {n:'165',artist:"Akira Komayama",name:'Larry',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.13,base:true},
  {n:'166',artist:"Toyste Beach",name:'Luxurious Cape',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.30,base:true},
  {n:'167',artist:"kirisAki",name:'Mela',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'168',artist:"Hideki Ishikawa",name:'Norman',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'169',artist:"Cona Nitanda",name:'Parasol Lady',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'170',artist:"Megumi Mizutani",name:'Professor Sada\'s Vitality',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.13,base:true},
  {n:'171',artist:"hncl",name:'Professor Turo\'s Scenario',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.17,base:true},
  {n:'172',artist:"GIDORA",name:'Rika',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'173',artist:"Ryuta Fuse",name:'Roark',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'174',artist:"yuu",name:'Shauntal',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.18,base:true},
  {n:'175',artist:"AYUMI ODASHIMA",name:'Snorlax Doll',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'176',artist:"Studio Bora Inc.",name:'Technical Machine: Blindside',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'177',artist:"Studio Bora Inc.",name:'Technical Machine: Devolution',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'178',artist:"Studio Bora Inc.",name:'Technical Machine: Evolution',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'179',artist:"Studio Bora Inc.",name:'Technical Machine: Turbo Energize',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'180',artist:"inose yukie",name:'Techno Radar',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'181',artist:"Naoki Saito",name:'Tulip',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.30,base:true},
  {n:'182',name:'Medical Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'183',dex:558,artist:"OKUBO",name:'Crustle',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:19.90,base:false},
  {n:'184',dex:825,artist:"Tetsu Kayama",name:'Dottler',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:22.90,base:false},
  {n:'185',dex:949,artist:"KEIICHIRO ITO",name:'Toedscruel',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:22.50,base:false},
  {n:'186',dex:240,artist:"Mina Nakai",name:'Magby',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:97.90,base:false,important:true},
  {n:'187',dex:994,artist:"Takeshi Nakamura",name:'Iron Moth',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:44.99,base:false,important:true},
  {n:'188',dex:361,artist:"Narumi Sato",name:'Snorunt',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:28.50,base:false,important:true},
  {n:'189',dex:458,artist:"rika",name:'Mantyke',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:99.90,base:false,important:true},
  {n:'190',dex:583,artist:"Taiga Kayama",name:'Vanillish',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:43.00,base:false,important:true},
  {n:'191',dex:767,artist:"Oku",name:'Wimpod',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:19.00,base:false,important:true},
  {n:'192',dex:976,artist:"Shibuzoh.",name:'Veluza',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:30.00,base:false,important:true},
  {n:'193',dex:311,artist:"OKACHEKE",name:'Plusle',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:59.90,base:false,important:true},
  {n:'194',dex:312,artist:"OKACHEKE",name:'Minun',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:89.00,base:false,important:true},
  {n:'195',dex:522,artist:"matazo",name:'Blitzle',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:39.90,base:false,important:true},
  {n:'196',dex:595,artist:"Atsushi Furusawa",name:'Joltik',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:65.00,base:false,important:true},
  {n:'197',dex:956,artist:"AKIRA EGAWA",name:'Espathra',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:29.99,base:false},
  {n:'198',dex:999,artist:"Akira Komayama",name:'Gimmighoul',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:42.00,base:false,important:true},
  {n:'199',dex:383,artist:"Nurikabe",name:'Groudon',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:134.90,base:false,important:true},
  {n:'200',dex:620,artist:"Taira Akitsu",name:'Mienshao',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:35.00,base:false,important:true},
  {n:'201',dex:774,artist:"0313",name:'Minior',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:49.90,base:false,important:true},
  {n:'202',dex:934,artist:"kodama",name:'Garganacl',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:25.90,base:false},
  {n:'203',dex:988,artist:"Takeshi Nakamura",name:'Slither Wing',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:28.50,base:false},
  {n:'204',dex:569,artist:"Shinya Komatsu",name:'Garbodor',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:50.00,base:false,important:true},
  {n:'205',dex:717,artist:"Masako Tomii",name:'Yveltal',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:70.00,base:false,important:true},
  {n:'206',dex:877,artist:"Yuu Nishida",name:'Morpeko',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:110.00,base:false,important:true},
  {n:'207',dex:986,artist:"Tomokazu Komiya",name:'Brute Bonnet',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:67.00,base:false,important:true},
  {n:'208',dex:208,artist:"nisimono",name:'Steelix',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:67.92,base:false,important:true},
  {n:'209',dex:598,artist:"Kurata So",name:'Ferrothorn',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:32.00,base:false},
  {n:'210',dex:681,artist:"Takumi Wada",name:'Aegislash',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:40.90,base:false,important:true},
  {n:'211',dex:190,artist:"Yuka Morii",name:'Aipom',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:179.90,base:false,important:true},
  {n:'212',dex:294,artist:"NC Empire",name:'Loudred',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:49.90,base:false,important:true},
  {n:'213',dex:333,artist:"Jiro Sasumo",name:'Swablu',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:69.50,base:false,important:true},
  {n:'214',dex:474,artist:"GOSSAN",name:'Porygon-Z',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:70.00,base:false,important:true},
  {n:'215',dex:967,artist:"Mina Nakai",name:'Cyclizar',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:42.50,base:false},
  {n:'216',dex:993,artist:"GIDORA",name:'Iron Jugulis',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:37.85,base:false,important:true},
  {n:'217',dex:478,artist:"5ban Graphics",name:'Froslass ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:11.00,base:false},
  {n:'218',dex:936,artist:"takuyoa",name:'Armarouge ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:15.00,base:false},
  {n:'219',dex:445,artist:"5ban Graphics",name:'Garchomp ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:20.00,base:false},
  {n:'220',dex:763,artist:"5ban Graphics",name:'Tsareena ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:23.99,base:false},
  {n:'221',dex:768,artist:"N-DESIGN Inc.",name:'Golisopod ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:15.00,base:false},
  {n:'222',dex:785,artist:"PLANETA Igarashi",name:'Tapu Koko ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:19.50,base:false},
  {n:'223',dex:992,artist:"PLANETA Mochizuki",name:'Iron Hands ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:17.75,base:false},
  {n:'224',dex:563,artist:"Eske Yoshinob",name:'Cofagrigus ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:15.00,base:false},
  {n:'225',dex:1006,artist:"aky CG Works",name:'Iron Valiant ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:19.99,base:false},
  {n:'226',dex:720,artist:"5ban Graphics",name:'Hoopa ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:27.00,base:false},
  {n:'227',dex:849,artist:"5ban Graphics",name:'Toxtricity ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:19.50,base:false},
  {n:'228',dex:989,artist:"PLANETA Mochizuki",name:'Sandy Shocks ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:11.00,base:false},
  {n:'229',dex:1005,artist:"takuyoa",name:'Roaring Moon ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:15.00,base:false},
  {n:'230',dex:681,artist:"Satoshi Shirai",name:'Aegislash ex',type:'Metal',color:'#78909C',rare:'Ultra Rara',price:12.00,base:false},
  {n:'231',dex:1000,artist:"takuyoa",name:'Gholdengo ex',type:'Metal',color:'#78909C',rare:'Ultra Rara',price:29.90,base:false},
  {n:'232',dex:334,artist:"Saki Hayashiro",name:'Altaria ex',type:'Dragão',color:'#3F51B5',rare:'Ultra Rara',price:19.99,base:false},
  {n:'233',dex:925,artist:"5ban Graphics",name:'Maushold ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:77.00,base:false,important:true},
  {n:'234',dex:962,artist:"PLANETA Mochizuki",name:'Bombirdier ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:9.99,base:false},
  {n:'235',artist:"Akira Komayama",name:'Larry',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:9.00,base:false},
  {n:'236',artist:"kirisAki",name:'Mela',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:34.99,base:false},
  {n:'237',artist:"Hideki Ishikawa",name:'Norman',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:12.99,base:false},
  {n:'238',artist:"Cona Nitanda",name:'Parasol Lady',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:19.50,base:false},
  {n:'239',artist:"Megumi Mizutani",name:'Professor Sada\'s Vitality',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:9.90,base:false},
  {n:'240',artist:"hncl",name:'Professor Turo\'s Scenario',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:14.89,base:false},
  {n:'241',artist:"GIDORA",name:'Rika',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:29.90,base:false},
  {n:'242',artist:"Ryuta Fuse",name:'Roark',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:7.90,base:false},
  {n:'243',artist:"En Morikura",name:'Shauntal',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:20.00,base:false},
  {n:'244',artist:"Naoki Saito",name:'Tulip',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:30.00,base:false},
  {n:'245',dex:445,artist:"Oswaldo KATO",name:'Garchomp ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:150.00,base:false,important:true},
  {n:'246',dex:768,artist:"Oku",name:'Golisopod ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:139.90,base:false,important:true},
  {n:'247',dex:785,artist:"Jerky",name:'Tapu Koko ex',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada Especial',price:58.50,base:false,important:true},
  {n:'248',dex:992,artist:"Toshinao Aoki",name:'Iron Hands ex',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada Especial',price:67.50,base:false,important:true},
  {n:'249',dex:1006,artist:"kantaro",name:'Iron Valiant ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:119.90,base:false,important:true},
  {n:'250',dex:989,artist:"Toshinao Aoki",name:'Sandy Shocks ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:59.90,base:false,important:true},
  // Cartas 251-266 completadas em 15/jul/2026 (generate_set.js tinha pageSize=250 sem
  // paginação — perdia o final do set). Preços via api.pokemontcg.io, USD/BRL 5.8.
  {n:'251',dex:1005,artist:"Ryota Murayama",name:'Roaring Moon ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:153.00,base:false,important:true},
  {n:'252',dex:1000,artist:"Akira Komayama",name:'Gholdengo ex',type:'Metal',color:'#78909C',rare:'Rara Ilustrada Especial',price:150.00,base:false,important:true},
  {n:'253',dex:334,artist:"Jiro Sasumo",name:'Altaria ex',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada Especial',price:240.00,base:false,important:true},
  {n:'254',artist:"rika",name:'Mela',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:45.00,base:false},
  {n:'255',artist:"En Morikura",name:'Parasol Lady',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:129.00,base:false,important:true},
  {n:'256',artist:"Ryota Murayama",name:'Professor Sada\'s Vitality',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:29.99,base:false},
  {n:'257',artist:"Atsushi Furusawa",name:'Professor Turo\'s Scenario',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:44.90,base:false},
  {n:'258',artist:"kantaro",name:'Rika',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:74.95,base:false,important:true},
  {n:'259',artist:"AKIRA EGAWA",name:'Tulip',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:45.00,base:false},
  {n:'260',dex:445,artist:"5ban Graphics",name:'Garchomp ex',type:'Aquático',color:'#2196F3',rare:'Hiper Rara',price:54.00,base:false,important:true},
  {n:'261',dex:1006,artist:"aky CG Works",name:'Iron Valiant ex',type:'Psíquico',color:'#9C27B0',rare:'Hiper Rara',price:27.00,base:false},
  {n:'262',dex:1005,artist:"takuyoa",name:'Roaring Moon ex',type:'Sombrio',color:'#607D8B',rare:'Hiper Rara',price:29.90,base:false},
  {n:'263',artist:"Oswaldo KATO",name:'Beach Court',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:19.90,base:false},
  {n:'264',artist:"Toyste Beach",name:'Counter Catcher',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:19.90,base:false},
  {n:'265',artist:"Toyste Beach",name:'Luxurious Cape',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:24.89,base:false},
  {n:'266',name:'Reversal Energy',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:20.00,base:false}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV4 = CARDS_SV4;