// ME2.5(ASC) — Heróis Excelsos (Ascended Heroes) — 295 cartas
// Lançamento Japão: 30 jan 2026 | Série: Mega Evolution (companion set do ME05)
// Tema: 13 Pokémon Mega ex — Mega Audino ex, Mega Charizard Y ex, Mega Diancie ex,
//       Mega Dragonite ex, Mega Eelektross ex, Mega Emboar ex, Mega Feraligatr ex,
//       Mega Froslass ex, Mega Gardevoir ex, Mega Gengar ex, Mega Hawlucha ex,
//       Mega Lucario ex, Mega Meganium ex, Mega Scrafty ex
// Fonte: api.pokemontcg.io (295/295 cartas confirmadas ao vivo em 07/08/2026 — ver
// [[project_pokemon_tcg]]). Nomes mantidos em inglês (não traduzidos ainda).
// NOTA: `price` é estimativa por raridade (sem dados de mercado ainda) —
// ajustar com update_prices.py quando o set chegar ao mercado BR/internacional.
// Estrutura de raridades (impressão única = base:false, sem par N+RH):
//   Comum/Incomum/Rara = [N,RH] (2 versões) | Rara Dupla = [F] (1 versão, "ex" base)
//   A partir da carta 218 (acima do printedTotal=217): todas base:false, 1 versão.
//   Rara Ilustrada (218–250) → Ultra Rara (251–264) → Rara Mega Ataque (265–271,
//   alt-art dos 7 "Mega X ex" com efeito de ataque) → Rara Ilustrada Especial
//   (272–293) → Hiper Rara Mega (294–295, topo da coleção).
const CARDS_ME2PT5 = [
  // ── SET BASE 001–217 ─────────────────────────────────────
  {n:'001',dex:43,name:'Erika\'s Oddish',artist:'Yoriyuki Ikegami',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.05,base:true},
  {n:'002',dex:44,name:'Erika\'s Gloom',artist:'MARINA Chikazawa',type:'Grama',color:'#4CAF50',rare:'Incomum',price:0.13,base:true},
  {n:'003',dex:45,name:'Erika\'s Vileplume ex',artist:'5ban Graphics',type:'Grama',color:'#4CAF50',rare:'Rara Dupla',price:6.99,base:true},
  {n:'004',dex:69,name:'Erika\'s Bellsprout',artist:'sui',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.09,base:true},
  {n:'005',dex:70,name:'Erika\'s Weepinbell',artist:'LINNE',type:'Grama',color:'#4CAF50',rare:'Incomum',price:0.13,base:true},
  {n:'006',dex:71,name:'Erika\'s Victreebel',artist:'takashi shiraishi',type:'Grama',color:'#4CAF50',rare:'Rara',price:0.20,base:true},
  {n:'007',dex:114,name:'Erika\'s Tangela',artist:'GIDORA',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'008',dex:152,name:'Chikorita',artist:'Kariya',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'009',dex:153,name:'Bayleef',artist:'Tomomi Ozaki',type:'Grama',color:'#4CAF50',rare:'Incomum',price:0.14,base:true},
  {n:'010',dex:154,name:'Mega Meganium ex',artist:'5ban Graphics',type:'Grama',color:'#4CAF50',rare:'Rara Dupla',price:9.49,base:true},
  {n:'011',dex:265,name:'Wurmple',artist:'USGMEN',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'012',dex:266,name:'Silcoon',artist:'Eri Yamaki',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.14,base:true},
  {n:'013',dex:267,name:'Beautifly',artist:'Narumi Sato',type:'Grama',color:'#4CAF50',rare:'Incomum',price:0.14,base:true},
  {n:'014',dex:268,name:'Cascoon',artist:'Dsuke',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.13,base:true},
  {n:'015',dex:269,name:'Dustox',artist:'kamonabe',type:'Grama',color:'#4CAF50',rare:'Incomum',price:0.14,base:true},
  {n:'016',dex:406,name:'Budew',artist:'Yoriyuki Ikegami',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'017',dex:736,name:'Grubbin',artist:'Jerky',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.09,base:true},
  {n:'018',dex:917,name:'Team Rocket\'s Tarountula',artist:'Saboteri',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.12,base:true},
  {n:'019',dex:918,name:'Team Rocket\'s Spidops',artist:'Taiga Kasai',type:'Grama',color:'#4CAF50',rare:'Rara',price:0.20,base:true},
  {n:'020',dex:4,name:'Charmander',artist:'Orca',type:'Fogo',color:'#F44336',rare:'Comum',price:0.09,base:true},
  {n:'021',dex:5,name:'Charmeleon',artist:'Julie Hang',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.13,base:true},
  {n:'022',dex:6,name:'Mega Charizard Y ex',artist:'aky CG Works',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:20.90,base:true},
  {n:'023',dex:218,name:'Ethan\'s Slugma',artist:'Sanosuke Sakuma',type:'Fogo',color:'#F44336',rare:'Comum',price:0.09,base:true},
  {n:'024',dex:219,name:'Ethan\'s Magcargo',artist:'kodama',type:'Fogo',color:'#F44336',rare:'Rara',price:0.14,base:true},
  {n:'025',dex:244,name:'Entei',artist:'Kazumasa Yasukuni',type:'Fogo',color:'#F44336',rare:'Rara',price:0.20,base:true},
  {n:'026',dex:250,name:'Ethan\'s Ho-Oh ex',artist:'aky CG Works',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:7.00,base:true},
  {n:'027',dex:322,name:'Numel',artist:'Ounishi',type:'Fogo',color:'#F44336',rare:'Comum',price:0.09,base:true},
  {n:'028',dex:323,name:'Camerupt',artist:'Minahamu',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.14,base:true},
  {n:'029',dex:498,name:'Tepig',artist:'Uninori',type:'Fogo',color:'#F44336',rare:'Comum',price:0.09,base:true},
  {n:'030',dex:499,name:'Pignite',artist:'Aliya Chen',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.15,base:true},
  {n:'031',dex:500,name:'Mega Emboar ex',artist:'5ban Graphics',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:5.90,base:true},
  {n:'032',dex:554,name:'N\'s Darumaka',artist:'Gemi',type:'Fogo',color:'#F44336',rare:'Comum',price:0.12,base:true},
  {n:'033',dex:555,name:'N\'s Darmanitan',artist:'nagimiso',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.11,base:true},
  {n:'034',dex:757,name:'Salandit',artist:'Felicia Chen',type:'Fogo',color:'#F44336',rare:'Comum',price:0.14,base:true},
  {n:'035',dex:758,name:'Salazzle',artist:'Taiga Kasai',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.14,base:true},
  {n:'036',dex:813,name:'Scorbunny',artist:'Cona Nitanda',type:'Fogo',color:'#F44336',rare:'Comum',price:0.14,base:true},
  {n:'037',dex:814,name:'Raboot',artist:'aspara',type:'Fogo',color:'#F44336',rare:'Comum',price:0.09,base:true},
  {n:'038',dex:815,name:'Cinderace ex',artist:'5ban Graphics',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:4.00,base:true},
  {n:'039',dex:54,name:'Psyduck',artist:'Jiro Sasumo',type:'Agua',color:'#2196F3',rare:'Comum',price:0.15,base:true},
  {n:'040',dex:55,name:'Golduck',artist:'Jiro Sasumo',type:'Agua',color:'#2196F3',rare:'Incomum',price:0.15,base:true},
  {n:'041',dex:158,name:'Totodile',artist:'REND',type:'Agua',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'042',dex:159,name:'Croconaw',artist:'Felicia Chen',type:'Agua',color:'#2196F3',rare:'Incomum',price:0.10,base:true},
  {n:'043',dex:160,name:'Mega Feraligatr ex',artist:'5ban Graphics',type:'Agua',color:'#2196F3',rare:'Rara Dupla',price:8.60,base:true},
  {n:'044',dex:215,name:'Sneasel',artist:'Krgc',type:'Agua',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'045',dex:461,name:'Weavile',artist:'aspara',type:'Agua',color:'#2196F3',rare:'Incomum',price:0.13,base:true},
  {n:'046',dex:361,name:'Snorunt',artist:'Wintr Wandr',type:'Agua',color:'#2196F3',rare:'Comum',price:0.12,base:true},
  {n:'047',dex:478,name:'Mega Froslass ex',artist:'5ban Graphics',type:'Agua',color:'#2196F3',rare:'Rara Dupla',price:23.75,base:true},
  {n:'048',dex:378,name:'Regice ex',artist:'akagi',type:'Agua',color:'#2196F3',rare:'Rara Dupla',price:4.49,base:true},
  {n:'049',dex:582,name:'N\'s Vanillite',artist:'yuu',type:'Agua',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'050',dex:583,name:'N\'s Vanillish',artist:'kirisAki',type:'Agua',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'051',dex:584,name:'N\'s Vanilluxe',artist:'imoniii',type:'Agua',color:'#2196F3',rare:'Incomum',price:0.10,base:true},
  {n:'052',dex:872,name:'Snom',artist:'Izucch',type:'Agua',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'053',dex:873,name:'Frosmoth',artist:'cochi8i',type:'Agua',color:'#2196F3',rare:'Incomum',price:0.15,base:true},
  {n:'054',dex:896,name:'Glastrier',artist:'mashu',type:'Agua',color:'#2196F3',rare:'Incomum',price:0.14,base:true},
  {n:'055',dex:25,name:'Pikachu',artist:'kamonabe',type:'Eletrico',color:'#FFC107',rare:'Comum',price:0.15,base:true},
  {n:'056',dex:26,name:'Raichu',artist:'Iori Suzuki',type:'Eletrico',color:'#FFC107',rare:'Incomum',price:0.15,base:true},
  {n:'057',dex:25,name:'Pikachu ex',artist:'aky CG Works',type:'Eletrico',color:'#FFC107',rare:'Rara Dupla',price:29.50,base:true},
  {n:'058',dex:100,name:'Voltorb ex',artist:'5ban Graphics',type:'Eletrico',color:'#FFC107',rare:'Rara Dupla',price:4.20,base:true},
  {n:'059',dex:602,name:'Tynamo',artist:'Jerky',type:'Eletrico',color:'#FFC107',rare:'Comum',price:0.09,base:true},
  {n:'060',dex:603,name:'Eelektrik',artist:'Jerky',type:'Eletrico',color:'#FFC107',rare:'Incomum',price:0.11,base:true},
  {n:'061',dex:604,name:'Mega Eelektross ex',artist:'takuyoa',type:'Eletrico',color:'#FFC107',rare:'Rara Dupla',price:3.92,base:true},
  {n:'062',dex:618,name:'Stunfisk',artist:'Tetsu Kayama',type:'Eletrico',color:'#FFC107',rare:'Comum',price:0.12,base:true},
  {n:'063',dex:694,name:'Helioptile',artist:'Tika Matsuno',type:'Eletrico',color:'#FFC107',rare:'Comum',price:0.10,base:true},
  {n:'064',dex:695,name:'Heliolisk',artist:'svlt',type:'Eletrico',color:'#FFC107',rare:'Incomum',price:0.09,base:true},
  {n:'065',dex:737,name:'Charjabug',artist:'Misa Tsutsui',type:'Eletrico',color:'#FFC107',rare:'Comum',price:0.09,base:true},
  {n:'066',dex:738,name:'Vikavolt',artist:'Shiburingaru',type:'Eletrico',color:'#FFC107',rare:'Incomum',price:0.10,base:true},
  {n:'067',dex:785,name:'Tapu Koko',artist:'Anesaki Dynamic',type:'Eletrico',color:'#FFC107',rare:'Rara',price:0.19,base:true},
  {n:'068',dex:871,name:'Hop\'s Pincurchin ex',artist:'5ban Graphics',type:'Eletrico',color:'#FFC107',rare:'Rara Dupla',price:3.50,base:true},
  {n:'069',dex:938,name:'Iono\'s Tadbulb',artist:'kurumitsu',type:'Eletrico',color:'#FFC107',rare:'Comum',price:0.09,base:true},
  {n:'070',dex:939,name:'Iono\'s Bellibolt ex',artist:'5ban Graphics',type:'Eletrico',color:'#FFC107',rare:'Rara Dupla',price:3.59,base:true},
  {n:'071',dex:940,name:'Iono\'s Wattrel',artist:'Akira Komayama',type:'Eletrico',color:'#FFC107',rare:'Comum',price:0.13,base:true},
  {n:'072',dex:940,name:'Iono\'s Kilowattrel',artist:'chibi',type:'Eletrico',color:'#FFC107',rare:'Rara',price:0.19,base:true},
  {n:'073',dex:1008,name:'Miraidon ex',artist:'5ban Graphics',type:'Eletrico',color:'#FFC107',rare:'Rara Dupla',price:4.75,base:true},
  {n:'074',dex:35,name:'Clefairy',artist:'satoma',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'075',dex:36,name:'Clefable',artist:'satoma',type:'Psiquico',color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'076',dex:35,name:'Lillie\'s Clefairy ex',artist:'5ban Graphics',type:'Psiquico',color:'#9C27B0',rare:'Rara Dupla',price:27.50,base:true},
  {n:'077',dex:102,name:'Team Rocket\'s Exeggcute',artist:'Gapao',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'078',dex:103,name:'Team Rocket\'s Exeggutor',artist:'Ryuta Fuse',type:'Psiquico',color:'#9C27B0',rare:'Rara',price:0.20,base:true},
  {n:'079',dex:150,name:'Team Rocket\'s Mewtwo ex',artist:'aky CG Works',type:'Psiquico',color:'#9C27B0',rare:'Rara Dupla',price:7.90,base:true},
  {n:'080',dex:175,name:'Togepi',artist:'Yoko Hishida',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'081',dex:176,name:'Togetic',artist:'Teeziro',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'082',dex:468,name:'Togekiss',artist:'Narano',type:'Psiquico',color:'#9C27B0',rare:'Rara',price:0.20,base:true},
  {n:'083',dex:183,name:'Marill',artist:'Yoshimoto Yoshimon',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'084',dex:183,name:'Azumarill ex',artist:'5ban Graphics',type:'Psiquico',color:'#9C27B0',rare:'Rara Dupla',price:4.75,base:true},
  {n:'085',dex:200,name:'Misdreavus',artist:'Kazuhisa Uragami',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.12,base:true},
  {n:'086',dex:429,name:'Mismagius',artist:'nisimono',type:'Psiquico',color:'#9C27B0',rare:'Rara',price:0.20,base:true},
  {n:'087',dex:280,name:'Ralts',artist:'Terada Tera',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.08,base:true},
  {n:'088',dex:281,name:'Kirlia',artist:'satoma',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.08,base:true},
  {n:'089',dex:282,name:'Mega Gardevoir ex',artist:'takuyoa',type:'Psiquico',color:'#9C27B0',rare:'Rara Dupla',price:5.79,base:true},
  {n:'090',dex:353,name:'Shuppet',artist:'miki kudo',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.11,base:true},
  {n:'091',dex:354,name:'Banette',artist:'Anesaki Dynamic',type:'Psiquico',color:'#9C27B0',rare:'Incomum',price:0.12,base:true},
  {n:'092',dex:479,name:'Rotom',artist:'mingo',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'093',dex:684,name:'Swirlix',artist:'Saya Tsuruta',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'094',dex:685,name:'Slurpuff',artist:'Natsumi Yoshida',type:'Psiquico',color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'095',dex:708,name:'Hop\'s Phantump',artist:'tono',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'096',dex:709,name:'Hop\'s Trevenant',artist:'matazo',type:'Psiquico',color:'#9C27B0',rare:'Rara',price:0.19,base:true},
  {n:'097',dex:778,name:'Team Rocket\'s Mimikyu',artist:'DOM',type:'Psiquico',color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'098',dex:897,name:'Spectrier',artist:'Taiga Kasai',type:'Psiquico',color:'#9C27B0',rare:'Rara',price:0.20,base:true},
  {n:'099',dex:1015,name:'Munkidori',artist:'kodama',type:'Psiquico',color:'#9C27B0',rare:'Rara',price:0.89,base:true},
  {n:'100',dex:50,name:'Team Rocket\'s Diglett',artist:'Yuriko Akase',type:'Luta',color:'#FF6B35',rare:'Comum',price:0.12,base:true},
  {n:'101',dex:51,name:'Team Rocket\'s Dugtrio',artist:'KEIICHIRO ITO',type:'Luta',color:'#FF6B35',rare:'Incomum',price:0.14,base:true},
  {n:'102',dex:237,name:'Hitmontop',artist:'Kouki Saitou',type:'Luta',color:'#FF6B35',rare:'Comum',price:0.10,base:true},
  {n:'103',dex:307,name:'Meditite',artist:'Lee HyunJung',type:'Luta',color:'#FF6B35',rare:'Comum',price:0.15,base:true},
  {n:'104',dex:308,name:'Medicham',artist:'GIDORA',type:'Luta',color:'#FF6B35',rare:'Comum',price:0.10,base:true},
  {n:'105',dex:337,name:'Lunatone',artist:'Whisker',type:'Luta',color:'#FF6B35',rare:'Rara',price:0.30,base:true},
  {n:'106',dex:338,name:'Solrock',artist:'Whisker',type:'Luta',color:'#FF6B35',rare:'Incomum',price:0.10,base:true},
  {n:'107',dex:377,name:'Regirock ex',artist:'Nisota Niso',type:'Luta',color:'#FF6B35',rare:'Rara Dupla',price:3.00,base:true},
  {n:'108',dex:383,name:'Groudon',artist:'Kazumasa Yasukuni',type:'Luta',color:'#FF6B35',rare:'Rara',price:0.15,base:true},
  {n:'109',dex:443,name:'Cynthia\'s Gible',artist:'Tomomi Ozaki',type:'Luta',color:'#FF6B35',rare:'Comum',price:0.10,base:true},
  {n:'110',dex:444,name:'Cynthia\'s Gabite',artist:'Taira Akitsu',type:'Luta',color:'#FF6B35',rare:'Incomum',price:0.15,base:true},
  {n:'111',dex:445,name:'Cynthia\'s Garchomp ex',artist:'5ban Graphics',type:'Luta',color:'#FF6B35',rare:'Rara Dupla',price:9.00,base:true},
  {n:'112',dex:447,name:'Riolu',artist:'hncl',type:'Luta',color:'#FF6B35',rare:'Comum',price:0.10,base:true},
  {n:'113',dex:448,name:'Mega Lucario ex',artist:'5ban Graphics',type:'Luta',color:'#FF6B35',rare:'Rara Dupla',price:4.90,base:true},
  {n:'114',dex:618,name:'Stunfisk ex',artist:'5ban Graphics',type:'Luta',color:'#FF6B35',rare:'Rara Dupla',price:3.89,base:true},
  {n:'115',dex:674,name:'Pancham',artist:'Minato',type:'Luta',color:'#FF6B35',rare:'Comum',price:0.15,base:true},
  {n:'116',dex:701,name:'Mega Hawlucha ex',artist:'5ban Graphics',type:'Luta',color:'#FF6B35',rare:'Rara Dupla',price:4.00,base:true},
  {n:'117',dex:703,name:'Carbink',artist:'Eri Kamei',type:'Luta',color:'#FF6B35',rare:'Incomum',price:0.15,base:true},
  {n:'118',dex:837,name:'Rolycoly',artist:'Kurata So',type:'Luta',color:'#FF6B35',rare:'Comum',price:0.10,base:true},
  {n:'119',dex:838,name:'Carkol',artist:'Apios',type:'Luta',color:'#FF6B35',rare:'Comum',price:0.14,base:true},
  {n:'120',dex:839,name:'Coalossal',artist:'Nisota Niso',type:'Luta',color:'#FF6B35',rare:'Rara',price:0.20,base:true},
  {n:'121',dex:1007,name:'Koraidon ex',artist:'aky CG Works',type:'Luta',color:'#FF6B35',rare:'Rara Dupla',price:3.80,base:true},
  {n:'122',name:'Okidogi',artist:'Mitsuhiro Arita',type:'Luta',color:'#FF6B35',rare:'Rara',price:0.20,base:true},
  {n:'123',dex:92,name:'Gastly',artist:'Saboteri',type:'Trevas',color:'#212121',rare:'Comum',price:0.10,base:true},
  {n:'124',dex:93,name:'Haunter',artist:'Rianti Hidayat',type:'Trevas',color:'#212121',rare:'Incomum',price:0.10,base:true},
  {n:'125',dex:94,name:'Mega Gengar ex',artist:'5ban Graphics',type:'Trevas',color:'#212121',rare:'Rara Dupla',price:9.90,base:true},
  {n:'126',dex:198,name:'Team Rocket\'s Murkrow',artist:'Mugi Hamada',type:'Trevas',color:'#212121',rare:'Comum',price:0.15,base:true},
  {n:'127',dex:430,name:'Team Rocket\'s Honchkrow',artist:'hncl',type:'Trevas',color:'#212121',rare:'Rara',price:0.20,base:true},
  {n:'128',dex:261,name:'Poochyena',artist:'Miki Tanaka',type:'Trevas',color:'#212121',rare:'Comum',price:0.10,base:true},
  {n:'129',dex:262,name:'Mightyena',artist:'akagi',type:'Trevas',color:'#212121',rare:'Incomum',price:0.10,base:true},
  {n:'130',dex:263,name:'Galarian Zigzagoon',artist:'osare',type:'Trevas',color:'#212121',rare:'Comum',price:0.10,base:true},
  {n:'131',dex:264,name:'Galarian Linoone',artist:'Tomowaka',type:'Trevas',color:'#212121',rare:'Comum',price:0.10,base:true},
  {n:'132',dex:862,name:'Galarian Obstagoon',artist:'Dsuke',type:'Trevas',color:'#212121',rare:'Incomum',price:0.15,base:true},
  {n:'133',dex:442,name:'Cynthia\'s Spiritomb',artist:'satoma',type:'Trevas',color:'#212121',rare:'Incomum',price:0.15,base:true},
  {n:'134',dex:559,name:'Scraggy',artist:'Shimaris Yukichi',type:'Trevas',color:'#212121',rare:'Comum',price:0.14,base:true},
  {n:'135',dex:560,name:'Mega Scrafty ex',artist:'5ban Graphics',type:'Trevas',color:'#212121',rare:'Rara Dupla',price:4.50,base:true},
  {n:'136',dex:570,name:'N\'s Zorua',artist:'Jiro Sasumo',type:'Trevas',color:'#212121',rare:'Comum',price:0.10,base:true},
  {n:'137',dex:571,name:'N\'s Zoroark ex',artist:'takuyoa',type:'Trevas',color:'#212121',rare:'Rara Dupla',price:12.50,base:true},
  {n:'138',dex:629,name:'Vullaby',artist:'Nisota Niso',type:'Trevas',color:'#212121',rare:'Comum',price:0.10,base:true},
  {n:'139',dex:630,name:'Mandibuzz ex',artist:'Ultimateinudog',type:'Trevas',color:'#212121',rare:'Rara Dupla',price:4.49,base:true},
  {n:'140',dex:675,name:'Pangoro',artist:'takashi shiraishi',type:'Trevas',color:'#212121',rare:'Incomum',price:0.10,base:true},
  {n:'141',dex:720,name:'Hoopa',artist:'Anesaki Dynamic',type:'Trevas',color:'#212121',rare:'Rara',price:0.20,base:true},
  {n:'142',dex:1016,name:'Fezandipiti ex',artist:'takuyoa',type:'Trevas',color:'#212121',rare:'Rara Dupla',price:14.50,base:true},
  {n:'143',dex:1025,name:'Pecharunt',artist:'IKEDA Saki',type:'Trevas',color:'#212121',rare:'Rara',price:0.20,base:true},
  {n:'144',dex:303,name:'Mawile',artist:'CHORISO',type:'Metal',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  {n:'145',dex:379,name:'Registeel ex',artist:'toriyufu',type:'Metal',color:'#607D8B',rare:'Rara Dupla',price:3.90,base:true},
  {n:'146',dex:624,name:'Pawniard',artist:'Yuya Oka',type:'Metal',color:'#607D8B',rare:'Comum',price:0.09,base:true},
  {n:'147',dex:625,name:'Bisharp',artist:'Scav',type:'Metal',color:'#607D8B',rare:'Comum',price:0.14,base:true},
  {n:'148',dex:983,name:'Kingambit',artist:'Teeziro',type:'Metal',color:'#607D8B',rare:'Rara',price:0.14,base:true},
  {n:'149',dex:777,name:'Togedemaru ex',artist:'5ban Graphics',type:'Metal',color:'#607D8B',rare:'Rara Dupla',price:3.49,base:true},
  {n:'150',dex:147,name:'Dratini',artist:'HYOGONOSUKE',type:'Dragão',color:'#00BCD4',rare:'Comum',price:0.14,base:true},
  {n:'151',dex:148,name:'Dragonair',artist:'Gemi',type:'Dragão',color:'#00BCD4',rare:'Incomum',price:0.15,base:true},
  {n:'152',dex:149,name:'Mega Dragonite ex',artist:'aky CG Works',type:'Dragão',color:'#00BCD4',rare:'Rara Dupla',price:24.90,base:true},
  {n:'153',dex:384,name:'Rayquaza',artist:'nagimiso',type:'Dragão',color:'#00BCD4',rare:'Rara',price:0.20,base:true},
  {n:'154',dex:643,name:'N\'s Reshiram',artist:'rika',type:'Dragão',color:'#00BCD4',rare:'Rara',price:0.19,base:true},
  {n:'155',dex:644,name:'N\'s Zekrom',artist:'AKIRA EGAWA',type:'Dragão',color:'#00BCD4',rare:'Rara',price:0.36,base:true},
  {n:'156',dex:714,name:'Noibat',artist:'Eri Kamei',type:'Dragão',color:'#00BCD4',rare:'Comum',price:0.14,base:true},
  {n:'157',dex:715,name:'Noivern',artist:'Natsumi Miyanose',type:'Dragão',color:'#00BCD4',rare:'Incomum',price:0.11,base:true},
  {n:'158',dex:885,name:'Dreepy',artist:'Scav',type:'Dragão',color:'#00BCD4',rare:'Comum',price:0.11,base:true},
  {n:'159',dex:886,name:'Drakloak',artist:'cochi8i',type:'Dragão',color:'#00BCD4',rare:'Comum',price:0.10,base:true},
  {n:'160',dex:887,name:'Dragapult ex',artist:'5ban Graphics',type:'Dragão',color:'#00BCD4',rare:'Rara Dupla',price:4.49,base:true},
  {n:'161',dex:52,name:'Team Rocket\'s Meowth',artist:'Megumi Mizutani',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'162',dex:115,name:'Team Rocket\'s Kangaskhan ex',artist:'5ban Graphics',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:5.90,base:true},
  {n:'163',dex:206,name:'Larry\'s Dunsparce',artist:'0313',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'164',dex:206,name:'Larry\'s Dudunsparce ex',artist:'5ban Graphics',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:3.99,base:true},
  {n:'165',dex:300,name:'Skitty',artist:'Yoko Hishida',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.12,base:true},
  {n:'166',dex:301,name:'Delcatty',artist:'buchi',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.14,base:true},
  {n:'167',dex:335,name:'Zangoose ex',artist:'5ban Graphics',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:4.90,base:true},
  {n:'168',dex:396,name:'Larry\'s Starly',artist:'Natsumi Miyanose',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'169',dex:397,name:'Larry\'s Staravia',artist:'Fujimoto Gold',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'170',dex:398,name:'Larry\'s Staraptor',artist:'Po-Suzuki',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.25,base:true},
  {n:'171',dex:479,name:'Fan Rotom',artist:'Toshinao Aoki',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'172',dex:531,name:'Mega Audino ex',artist:'5ban Graphics',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:5.90,base:true},
  {n:'173',dex:627,name:'Larry\'s Rufflet',artist:'cochi8i',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'174',dex:628,name:'Larry\'s Braviary',artist:'Ryuta Fuse',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.13,base:true},
  {n:'175',dex:775,name:'Larry\'s Komala',artist:'ryoma uratsuka',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.07,base:true},
  {n:'176',dex:780,name:'Drampa',artist:'Scav',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'177',dex:845,name:'Hop\'s Cramorant',artist:'Saboteri',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.14,base:true},
  {n:'178',dex:1024,name:'Terapagos',artist:'GIDORA',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.15,base:true},
  {n:'179',dex:1024,name:'Terapagos ex',artist:'5ban Graphics',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:4.97,base:true},
  {n:'180',name:'Acerola\'s Mischief',artist:'Yuu Nishida',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  {n:'181',name:'Air Balloon',artist:'Studio Bora Inc.',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'182',name:'Anthea & Concordia',artist:'Sanosuke Sakuma',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.09,base:true},
  {n:'183',name:'Boss\'s Orders',artist:'akagi',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'184',name:'Buddy-Buddy Poffin',artist:'AYUMI ODASHIMA',type:'Treinador',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'185',name:'Canari',artist:'Naoki Saito',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  {n:'186',name:'Counter Gain',artist:'Toyste Beach',type:'Treinador',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'187',name:'Fighting Gong',artist:'Toyste Beach',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'188',name:'Forest of Vitality',artist:'AYUMI ODASHIMA',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.18,base:true},
  {n:'189',name:'Glass Trumpet',artist:'Toyste Beach',type:'Treinador',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'190',name:'Iris\'s Fighting Spirit',artist:'yuu',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  {n:'191',name:'Light Ball',artist:'Studio Bora Inc.',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  {n:'192',name:'Lillie\'s Determination',artist:'Atsushi Furusawa',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.24,base:true},
  {n:'193',name:'Mega Signal',artist:'inose yukie',type:'Treinador',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'194',name:'Mystery Garden',artist:'AYUMI ODASHIMA',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'195',name:'N\'s PP Up',artist:'Toyste Beach',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'196',name:'Night Stretcher',artist:'Toyste Beach',type:'Treinador',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'197',name:'Nighttime Mine',artist:'Takashi Yamaguchi',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  {n:'198',name:'Poké Pad',artist:'Studio Bora Inc.',type:'Treinador',color:'#607D8B',rare:'Comum',price:0.24,base:true},
  {n:'199',name:'Premium Power Pro',artist:'Toyste Beach',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.13,base:true},
  {n:'200',name:'Surfer',artist:'Hideki Ishikawa',type:'Treinador',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'201',name:'Team Rocket\'s Archer',artist:'Hideki Ishikawa',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'202',name:'Team Rocket\'s Ariana',artist:'hncl',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'203',name:'Team Rocket\'s Factory',artist:'imoniii',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'204',name:'Team Rocket\'s Giovanni',artist:'DOM',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'205',name:'Team Rocket\'s Great Ball',artist:'Toyste Beach',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'206',name:'Team Rocket\'s Hypnotizer',artist:'Toyste Beach',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'207',name:'Team Rocket\'s Petrel',artist:'GOSSAN',type:'Treinador',color:'#607D8B',rare:'Incomum',price:2.00,base:true},
  {n:'208',name:'Team Rocket\'s Proton',artist:'Naoki Saito',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'209',name:'Team Rocket\'s Transceiver',artist:'inose yukie',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'210',name:'Team Rocket\'s Watchtower',artist:'AYUMI ODASHIMA',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'211',name:'Thick Scale',artist:'Toyste Beach',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.13,base:true},
  {n:'212',name:'Tool Scrapper',artist:'Studio Bora Inc.',type:'Treinador',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'213',name:'Ultra Ball',artist:'Ayaka Yoshida',type:'Treinador',color:'#607D8B',rare:'Comum',price:0.08,base:true},
  {n:'214',name:'Urbain',artist:'Teeziro',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.12,base:true},
  {n:'215',name:'Waitress',artist:'Cona Nitanda',type:'Treinador',color:'#607D8B',rare:'Comum',price:0.05,base:true},
  {n:'216',name:'Prism Energy',type:'Energia',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'217',name:'Team Rocket\'s Energy',type:'Energia',color:'#212121',rare:'Incomum',price:0.20,base:true},
  // ── SECRETAS 218–295 (acima do número de regulação, impressão única) ─────
  {n:'218',dex:114,name:'Erika\'s Tangela',artist:'buchi',type:'Grama',color:'#4CAF50',rare:'Rara Ilustrada',price:97.00,base:false},
  {n:'219',dex:267,name:'Beautifly',artist:'Mori Yuu',type:'Grama',color:'#4CAF50',rare:'Rara Ilustrada',price:24.90,base:false},
  {n:'220',dex:269,name:'Dustox',artist:'IKEDA Saki',type:'Grama',color:'#4CAF50',rare:'Rara Ilustrada',price:17.78,base:false},
  {n:'221',dex:406,name:'Budew',artist:'Yoko Hishida',type:'Grama',color:'#4CAF50',rare:'Rara Ilustrada',price:26.00,base:false},
  {n:'222',dex:219,name:'Ethan\'s Magcargo',artist:'Hideki Ishikawa',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:32.00,base:false},
  {n:'223',dex:322,name:'Numel',artist:'Yoshimi Miyoshi',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:17.50,base:false},
  {n:'224',dex:758,name:'Salazzle',artist:'Dsuke',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:12.00,base:false},
  {n:'225',dex:813,name:'Scorbunny',artist:'Yuu Nishida',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:32.24,base:false},
  {n:'226',dex:54,name:'Psyduck',artist:'REND',type:'Agua',color:'#2196F3',rare:'Rara Ilustrada',price:220.00,base:false},
  {n:'227',dex:361,name:'Snorunt',artist:'Dsuke',type:'Agua',color:'#2196F3',rare:'Rara Ilustrada',price:27.99,base:false},
  {n:'228',dex:461,name:'Weavile',artist:'Uninori',type:'Agua',color:'#2196F3',rare:'Rara Ilustrada',price:29.00,base:false},
  {n:'229',dex:695,name:'Heliolisk',artist:'Takeshi Nakamura',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:9.99,base:false},
  {n:'230',dex:738,name:'Vikavolt',artist:'Tonji Matsuno',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:12.00,base:false},
  {n:'231',dex:940,name:'Iono\'s Wattrel',artist:'mingo',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:37.00,base:false},
  {n:'232',dex:183,name:'Marill',artist:'Rond',type:'Psiquico',color:'#9C27B0',rare:'Rara Ilustrada',price:40.00,base:false},
  {n:'233',dex:200,name:'Misdreavus',artist:'mashu',type:'Psiquico',color:'#9C27B0',rare:'Rara Ilustrada',price:20.00,base:false},
  {n:'234',dex:354,name:'Banette',artist:'YASHIRO Nanaco',type:'Psiquico',color:'#9C27B0',rare:'Rara Ilustrada',price:27.44,base:false},
  {n:'235',dex:468,name:'Togekiss',artist:'satoma',type:'Psiquico',color:'#9C27B0',rare:'Rara Ilustrada',price:27.90,base:false},
  {n:'236',dex:685,name:'Slurpuff',artist:'Yoshimoto Yoshimon',type:'Psiquico',color:'#9C27B0',rare:'Rara Ilustrada',price:19.90,base:false},
  {n:'237',dex:709,name:'Hop\'s Trevenant',artist:'Tomowaka',type:'Psiquico',color:'#9C27B0',rare:'Rara Ilustrada',price:22.90,base:false},
  {n:'238',dex:778,name:'Team Rocket\'s Mimikyu',artist:'GOSSAN',type:'Psiquico',color:'#9C27B0',rare:'Rara Ilustrada',price:64.00,base:false},
  {n:'239',dex:51,name:'Team Rocket\'s Dugtrio',artist:'Whisker',type:'Luta',color:'#FF6B35',rare:'Rara Ilustrada',price:34.50,base:false},
  {n:'240',dex:237,name:'Hitmontop',artist:'osare',type:'Luta',color:'#FF6B35',rare:'Rara Ilustrada',price:19.98,base:false},
  {n:'241',dex:308,name:'Medicham',artist:'KEIICHIRO ITO',type:'Luta',color:'#FF6B35',rare:'Rara Ilustrada',price:14.00,base:false},
  {n:'242',dex:703,name:'Carbink',artist:'sui',type:'Luta',color:'#FF6B35',rare:'Rara Ilustrada',price:17.49,base:false},
  {n:'243',dex:262,name:'Mightyena',artist:'Yano Keiji',type:'Trevas',color:'#212121',rare:'Rara Ilustrada',price:21.90,base:false},
  {n:'244',dex:442,name:'Cynthia\'s Spiritomb',artist:'hncl',type:'Trevas',color:'#212121',rare:'Rara Ilustrada',price:38.90,base:false},
  {n:'245',dex:862,name:'Galarian Obstagoon',artist:'Krgc',type:'Trevas',color:'#212121',rare:'Rara Ilustrada',price:16.66,base:false},
  {n:'246',dex:303,name:'Mawile',artist:'sowsow',type:'Metal',color:'#607D8B',rare:'Rara Ilustrada',price:19.90,base:false},
  {n:'247',dex:885,name:'Dreepy',artist:'Jerky',type:'Dragão',color:'#00BCD4',rare:'Rara Ilustrada',price:36.90,base:false},
  {n:'248',dex:886,name:'Drakloak',artist:'Jerky',type:'Dragão',color:'#00BCD4',rare:'Rara Ilustrada',price:41.50,base:false},
  {n:'249',dex:398,name:'Larry\'s Staraptor',artist:'kantaro',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:16.90,base:false},
  {n:'250',dex:479,name:'Fan Rotom',artist:'Yukihiro Tada',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:17.90,base:false},
  {n:'251',dex:906,name:'Sprigatito ex',artist:'5ban Graphics',type:'Grama',color:'#4CAF50',rare:'Ultra Rara',price:14.50,base:false},
  {n:'252',dex:618,name:'Stunfisk ex',artist:'5ban Graphics',type:'Luta',color:'#FF6B35',rare:'Ultra Rara',price:3.90,base:false},
  {n:'253',dex:531,name:'Mega Audino ex',artist:'5ban Graphics',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8.00,base:false},
  {n:'254',name:'Anthea & Concordia',artist:'Sanosuke Sakuma',type:'Treinador',color:'#607D8B',rare:'Ultra Rara',price:8.00,base:false},
  {n:'255',name:'Black Belt\'s Training',artist:'GOSSAN',type:'Treinador',color:'#607D8B',rare:'Ultra Rara',price:9.00,base:false},
  {n:'256',name:'Boss\'s Orders',artist:'akagi',type:'Treinador',color:'#607D8B',rare:'Ultra Rara',price:54.89,base:false},
  {n:'257',name:'Canari',artist:'Naoki Saito',type:'Treinador',color:'#607D8B',rare:'Ultra Rara',price:18.00,base:false},
  {n:'258',name:'Cheren',artist:'REND',type:'Treinador',color:'#607D8B',rare:'Ultra Rara',price:4.50,base:false},
  {n:'259',name:'Counter Gain',artist:'Toyste Beach',type:'Treinador',color:'#607D8B',rare:'Ultra Rara',price:3.75,base:false},
  {n:'260',name:'Glass Trumpet',artist:'Toyste Beach',type:'Treinador',color:'#607D8B',rare:'Ultra Rara',price:4.99,base:false},
  {n:'261',name:'Jamming Tower',artist:'AYUMI ODASHIMA',type:'Treinador',color:'#607D8B',rare:'Ultra Rara',price:4.00,base:false},
  {n:'262',name:'N\'s PP Up',artist:'Toyste Beach',type:'Treinador',color:'#607D8B',rare:'Ultra Rara',price:9.00,base:false},
  {n:'263',name:'Team Rocket\'s Transceiver',artist:'inose yukie',type:'Treinador',color:'#607D8B',rare:'Ultra Rara',price:10.00,base:false},
  {n:'264',name:'Ultra Ball',artist:'Studio Bora Inc.',type:'Treinador',color:'#607D8B',rare:'Ultra Rara',price:52.90,base:false},
  {n:'265',dex:478,name:'Mega Froslass ex',artist:'Saboteri',type:'Agua',color:'#2196F3',rare:'Rara Mega Ataque',price:58.00,base:false},
  {n:'266',dex:604,name:'Mega Eelektross ex',artist:'DOM',type:'Eletrico',color:'#FFC107',rare:'Rara Mega Ataque',price:19.00,base:false},
  {n:'267',dex:719,name:'Mega Diancie ex',artist:'DOM',type:'Psiquico',color:'#9C27B0',rare:'Rara Mega Ataque',price:29.90,base:false},
  {n:'268',dex:701,name:'Mega Hawlucha ex',artist:'Taiga Kasai',type:'Luta',color:'#FF6B35',rare:'Rara Mega Ataque',price:28.90,base:false},
  {n:'269',dex:94,name:'Mega Gengar ex',artist:'Taiga Kasai',type:'Trevas',color:'#212121',rare:'Rara Mega Ataque',price:206.78,base:false},
  {n:'270',dex:560,name:'Mega Scrafty ex',artist:'Taiga Kasai',type:'Trevas',color:'#212121',rare:'Rara Mega Ataque',price:24.90,base:false},
  {n:'271',dex:149,name:'Mega Dragonite ex',artist:'DOM',type:'Dragão',color:'#00BCD4',rare:'Rara Mega Ataque',price:120.00,base:false},
  {n:'272',dex:154,name:'Mega Meganium ex',artist:'Tika Matsuno',type:'Grama',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:377.90,base:false},
  {n:'273',dex:500,name:'Mega Emboar ex',artist:'nagimiso',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:235.00,base:false},
  {n:'274',dex:160,name:'Mega Feraligatr ex',artist:'Souichirou Gunjima',type:'Agua',color:'#2196F3',rare:'Rara Ilustrada Especial',price:350.00,base:false},
  {n:'275',dex:478,name:'Mega Froslass ex',artist:'Teeziro',type:'Agua',color:'#2196F3',rare:'Rara Ilustrada Especial',price:398.99,base:false},
  {n:'276',dex:25,name:'Pikachu ex',artist:'booota',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada Especial',price:3349.90,base:false},
  {n:'277',dex:25,name:'Pikachu ex',artist:'James Turner',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada Especial',price:1190.00,base:false},
  {n:'278',dex:604,name:'Mega Eelektross ex',artist:'akagi',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada Especial',price:138.90,base:false},
  {n:'279',dex:939,name:'Iono\'s Bellibolt ex',artist:'Akira Komayama',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada Especial',price:234.00,base:false},
  {n:'280',dex:35,name:'Lillie\'s Clefairy ex',artist:'Naoki Saito',type:'Psiquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:619.90,base:false},
  {n:'281',dex:150,name:'Team Rocket\'s Mewtwo ex',artist:'Mitsuhiro Arita',type:'Psiquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:920.00,base:false},
  {n:'282',dex:719,name:'Mega Diancie ex',artist:'Narano',type:'Psiquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:220.00,base:false},
  {n:'283',dex:701,name:'Mega Hawlucha ex',artist:'AKIRA EGAWA',type:'Luta',color:'#FF6B35',rare:'Rara Ilustrada Especial',price:229.07,base:false},
  {n:'284',dex:94,name:'Mega Gengar ex',artist:'danciao',type:'Trevas',color:'#212121',rare:'Rara Ilustrada Especial',price:2099.00,base:false},
  {n:'285',dex:560,name:'Mega Scrafty ex',artist:'nagimiso',type:'Trevas',color:'#212121',rare:'Rara Ilustrada Especial',price:220.00,base:false},
  {n:'286',dex:571,name:'N\'s Zoroark ex',artist:'Raita Kazama',type:'Trevas',color:'#212121',rare:'Rara Ilustrada Especial',price:549.90,base:false},
  {n:'287',dex:861,name:'Marnie\'s Grimmsnarl ex',artist:'Ligton',type:'Trevas',color:'#212121',rare:'Rara Ilustrada Especial',price:269.90,base:false},
  {n:'288',dex:1016,name:'Fezandipiti ex',artist:'SIE NANAHARA',type:'Trevas',color:'#212121',rare:'Rara Ilustrada Especial',price:269.90,base:false},
  {n:'289',dex:376,name:'Steven\'s Metagross ex',artist:'chibi',type:'Metal',color:'#607D8B',rare:'Rara Ilustrada Especial',price:284.99,base:false},
  {n:'290',dex:149,name:'Mega Dragonite ex',artist:'DOM',type:'Dragão',color:'#00BCD4',rare:'Rara Ilustrada Especial',price:1484.78,base:false},
  {n:'291',name:'Canari',artist:'kantaro',type:'Treinador',color:'#607D8B',rare:'Rara Ilustrada Especial',price:174.90,base:false},
  {n:'292',name:'Iris\'s Fighting Spirit',artist:'Kuroimori',type:'Treinador',color:'#607D8B',rare:'Rara Ilustrada Especial',price:120.00,base:false},
  {n:'293',name:'Surfer',artist:'OKUBO',type:'Treinador',color:'#607D8B',rare:'Rara Ilustrada Especial',price:138.90,base:false},
  {n:'294',dex:6,name:'Mega Charizard Y ex',artist:'aky CG Works',type:'Fogo',color:'#F44336',rare:'Hiper Rara Mega',price:1339.00,base:false},
  {n:'295',dex:149,name:'Mega Dragonite ex',artist:'aky CG Works',type:'Dragão',color:'#00BCD4',rare:'Hiper Rara Mega',price:750.00,base:false},
];
