// CEL30 — Celebração de 30 Anos do Pokémon Estampas Ilustradas (30th Celebration) — 199 cartas
// Lancamento Japao/Global: 16 set 2026
// Tema: comemorativo dos 30 anos do TCG — 128 base (com subset especial de
//       30 Pikachus ilustrados e as 12 "ex"), 30 secretas (129-158), 3 RGB
//       (Mew, fora da contagem oficial), 30 reimpressões da Coleção Clássica
//       (numeração ORIGINAL de cada set de origem, ex: 4/102 = Charizard da
//       Base Set) e 8 Energias Básicas.
// CORRIGIDO 30/09/2026: name/type/rare/artist de 191 das 199 cartas
// conferidos carta a carta contra limitlesstcg.com/cards/30C (fonte oficial
// de banco de dados competitivo, texto+raridade+ilustrador por carta) — a
// primeira versão deste arquivo tinha varios tipos elementares errados
// (chutados por conhecimento de especie sem fonte, ex: Exeggcute virou
// Grama em vez de Psiquico, Marill/Azumarill sao Psiquico e nao Agua,
// Nidoran/Nidorina sao Trevas e nao Grama, Chandelure e Gengar ex sao
// Trevas/Psiquico trocados, Seismitoad e Luta e nao Agua, Crobat G e
// Psiquico e nao Trevas, Genesect-EX da Colecao Classica e Grama e nao
// Metal). Raridade tambem foi refinada pra bater com o vocabulario real
// (Common/Rare/Double Rare/Art Rare/Special Art Rare/Ultra Rare/Secret
// Rare -> Comum/Rara/Rara Dupla/Rara Ilustrada/Ilustr. Esp. Rara/Rara
// Ultra/Rara Secreta). As 30 Pikachu ilustradas (023-052) nao tem raridade
// listada na fonte (icone sem texto acessivel) — mantido 'Rara Ilustrada'
// por aproximacao. As 8 Energias Basicas (MEE 009-016) nao aparecem no
// checklist do limitlesstcg — nao foi possivel confirmar/corrigir essas 8,
// mantido o que veio do deckcerto.com (nomes/precos) sem artist/verificacao.
// Precos em BRL continuam do deckcerto.com (preserva o preço já ajustado
// pro mercado nacional); dex por conhecimento de espécie (não disponível em
// nenhuma das duas fontes).
const CARDS_CEL30 = [
  // ── SET BASE 001–128 ─────────────────────────────────────
  {n:'001',dex:102,artist:'Nelnal',name:'Exeggcute',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.89,base:true},
  {n:'002',dex:103,artist:'Oswaldo KATO',name:'Exeggutor de Alola',type:'Grama',color:'#4CAF50',rare:'Comum',price:1.5,base:true},
  {n:'003',dex:313,artist:'Yoriyuki Ikegami',name:'Volbeat',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.95,base:true},
  {n:'004',dex:314,artist:'Shibuzoh.',name:'Illumise',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.85,base:true},
  {n:'005',dex:357,artist:'Minahamu',name:'Tropius',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.69,base:true},
  {n:'006',dex:420,artist:'Kurata So',name:'Cherubi',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.65,base:true},
  {n:'007',dex:421,artist:'takashi shiraishi',name:'Cherrim',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.79,base:true},
  {n:'008',dex:666,artist:'Jerky',name:'Vivillon',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.85,base:true},
  {n:'009',dex:37,artist:'miki kudo',name:'Vulpix',type:'Fogo',color:'#F44336',rare:'Comum',price:0.85,base:true},
  {n:'010',dex:38,artist:'kodama',name:'Ninetales',type:'Fogo',color:'#F44336',rare:'Comum',price:1,base:true},
  {n:'011',dex:146,artist:'HYOGONOSUKE',name:'Moltres',type:'Fogo',color:'#F44336',rare:'Comum',price:1.5,base:true},
  {n:'012',dex:250,artist:'Anesaki Dynamic',name:'Ho-Oh',type:'Fogo',color:'#F44336',rare:'Rara',price:1.5,base:true},
  {n:'013',dex:494,artist:'Jiro Sasumo',name:'Victini',type:'Fogo',color:'#F44336',rare:'Comum',price:1.01,base:true},
  {n:'014',dex:643,artist:'Uta',name:'Reshiram',type:'Fogo',color:'#F44336',rare:'Rara',price:0.9,base:true},
  {n:'015',dex:909,artist:'5ban Graphics',name:'Fuecoco ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:4.29,base:true},
  {n:'016',dex:79,artist:'Uninori',name:'Slowpoke',type:'Agua',color:'#2196F3',rare:'Comum',price:0.95,base:true},
  {n:'017',dex:131,artist:'Masa',name:'Lapras',type:'Agua',color:'#2196F3',rare:'Comum',price:1.35,base:true},
  {n:'018',dex:144,artist:'HYOGONOSUKE',name:'Articuno',type:'Agua',color:'#2196F3',rare:'Comum',price:1.5,base:true},
  {n:'019',dex:382,artist:'Tonji Matsuno',name:'Kyogre',type:'Agua',color:'#2196F3',rare:'Rara',price:0.94,base:true},
  {n:'020',dex:484,artist:'kawayoo',name:'Palkia',type:'Agua',color:'#2196F3',rare:'Rara',price:1.45,base:true},
  {n:'021',dex:658,artist:'5ban Graphics',name:'Greninja ex',type:'Agua',color:'#2196F3',rare:'Rara Dupla',price:8.49,base:true},
  {n:'022',dex:746,artist:'Narano',name:'Wishiwashi',type:'Agua',color:'#2196F3',rare:'Comum',price:0.9,base:true},
  {n:'023',dex:25,artist:'Ken Sugimori',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:8.5,base:true},
  {n:'024',dex:25,artist:'danciao',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:7,base:true},
  {n:'025',dex:25,artist:'satoma',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:6.79,base:true},
  {n:'026',dex:25,artist:'Takeshi Nakamura',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:7.5,base:true},
  {n:'027',dex:25,artist:'Asako Ito',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:11,base:true},
  {n:'028',dex:25,artist:'sowsow',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:12.8,base:true},
  {n:'029',dex:25,artist:'James Turner',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:9,base:true},
  {n:'030',dex:25,artist:'DOM',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:7.5,base:true},
  {n:'031',dex:25,artist:'Atsushi Furusawa',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:8,base:true},
  {n:'032',dex:25,artist:'Tomokazu Komiya',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:17.9,base:true},
  {n:'033',dex:25,artist:'Narumi Sato',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:7.5,base:true},
  {n:'034',dex:25,artist:'USGMEN',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:8.9,base:true},
  {n:'035',dex:25,artist:'Susumu Maeya',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:9,base:true},
  {n:'036',dex:25,artist:'OKACHEKE',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:11.9,base:true},
  {n:'037',dex:25,artist:'Yuu Nishida',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:6.5,base:true},
  {n:'038',dex:25,artist:'Tetsu Kayama',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:8.5,base:true},
  {n:'039',dex:25,artist:'Teeziro',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:10.44,base:true},
  {n:'040',dex:25,artist:'Shinji Kanda',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:13.5,base:true},
  {n:'041',dex:25,artist:'Rianti Hidayat',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:7.5,base:true},
  {n:'042',dex:25,artist:'Akira Komayama',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:8.88,base:true},
  {n:'043',dex:25,artist:'OOYAMA',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:9,base:true},
  {n:'044',dex:25,artist:'akagi',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:9,base:true},
  {n:'045',dex:25,artist:'Naoyo Kimura',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:7.5,base:true},
  {n:'046',dex:25,artist:'svlt',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:7.9,base:true},
  {n:'047',dex:25,artist:'Atsuko Nishida',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:8,base:true},
  {n:'048',dex:25,artist:'KIYOTAKA OSHIYAMA',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:8,base:true},
  {n:'049',dex:25,artist:'Nurikabe',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:8.44,base:true},
  {n:'050',dex:25,artist:'Shimaris Yukichi',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:9,base:true},
  {n:'051',dex:25,artist:'nagimiso',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:9,base:true},
  {n:'052',dex:25,artist:'Kazuki Minami',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:7.9,base:true},
  {n:'053',dex:25,artist:'5ban Graphics',name:'Pikachu ex',type:'Eletrico',color:'#FFC107',rare:'Rara Dupla',price:15,base:true},
  {n:'054',dex:25,artist:'takuyoa',name:'Pikachu ex',type:'Eletrico',color:'#FFC107',rare:'Rara Dupla',price:18,base:true},
  {n:'055',dex:145,artist:'HYOGONOSUKE',name:'Zapdos',type:'Eletrico',color:'#FFC107',rare:'Comum',price:1.45,base:true},
  {n:'056',dex:644,artist:'akagi',name:'Zekrom',type:'Eletrico',color:'#FFC107',rare:'Rara',price:0.9,base:true},
  {n:'057',dex:807,artist:'Bun Toujo',name:'Zeraora',type:'Eletrico',color:'#FFC107',rare:'Comum',price:0.95,base:true},
  {n:'058',dex:848,artist:'Shimaris Yukichi',name:'Toxel',type:'Eletrico',color:'#FFC107',rare:'Comum',price:0.89,base:true},
  {n:'059',dex:849,artist:'Haru Akasaka',name:'Toxtricity',type:'Eletrico',color:'#FFC107',rare:'Comum',price:0.97,base:true},
  {n:'060',dex:849,artist:'Yuriko Akase',name:'Toxtricity',type:'Eletrico',color:'#FFC107',rare:'Comum',price:0.95,base:true},
  {n:'061',dex:877,artist:'Naoki Saito',name:'Morpeko',type:'Eletrico',color:'#FFC107',rare:'Comum',price:0.9,base:true},
  {n:'062',dex:1008,artist:'Kazumasa Yasukuni',name:'Miraidon',type:'Eletrico',color:'#FFC107',rare:'Rara',price:0.9,base:true},
  {n:'063',dex:150,artist:'nagimiso',name:'Mewtwo',type:'Psiquico',color:'#9C27B0',rare:'Rara',price:2,base:true},
  {n:'064',dex:150,artist:'5ban Graphics',name:'Mewtwo ex',type:'Psiquico',color:'#9C27B0',rare:'Rara Dupla',price:7,base:true},
  {n:'065',dex:151,artist:'danciao',name:'Mew',type:'Psiquico',color:'#9C27B0',rare:'Rara',price:2,base:true},
  {n:'066',dex:151,artist:'aky CG Works',name:'Mew ex',type:'Psiquico',color:'#9C27B0',rare:'Rara Dupla',price:63,base:true},
  {n:'067',dex:183,artist:'Saya Tsuruta',name:'Marill',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.95,base:true},
  {n:'068',dex:184,artist:'Kagemaru Himeno',name:'Azumarill',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.93,base:true},
  {n:'069',dex:196,artist:'aspara',name:'Espeon',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:2,base:true},
  {n:'070',dex:196,artist:'5ban Graphics',name:'Espeon ex',type:'Psiquico',color:'#9C27B0',rare:'Rara Dupla',price:10.99,base:true},
  {n:'071',dex:700,artist:'5ban Graphics',name:'Sylveon ex',type:'Psiquico',color:'#9C27B0',rare:'Rara Dupla',price:8.9,base:true},
  {n:'072',dex:201,artist:'mingo',name:'Unown',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:1.45,base:true},
  {n:'073',dex:425,artist:'Shinya Komatsu',name:'Drifloon',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.8,base:true},
  {n:'074',dex:488,artist:'KEIICHIRO ITO',name:'Cresselia',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.72,base:true},
  {n:'075',dex:609,artist:'Yoshioka',name:'Chandelure',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.95,base:true},
  {n:'076',dex:716,artist:'kodama',name:'Xerneas',type:'Psiquico',color:'#9C27B0',rare:'Rara',price:0.95,base:true},
  {n:'077',dex:764,artist:'sui',name:'Comfey',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.7,base:true},
  {n:'078',dex:789,artist:'Mina Nakai',name:'Cosmog',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.95,base:true},
  {n:'079',dex:790,artist:'Masako Tomii',name:'Cosmoem',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.83,base:true},
  {n:'080',dex:792,artist:'Bun Toujo',name:'Lunala',type:'Psiquico',color:'#9C27B0',rare:'Rara',price:0.95,base:true},
  {n:'081',dex:999,artist:'Fujimoto Gold',name:'Gimmighoul',type:'Psiquico',color:'#9C27B0',rare:'Comum',price:0.93,base:true},
  {n:'082',dex:383,artist:'Takumi Wada',name:'Groudon',type:'Luta',color:'#FF6B35',rare:'Rara',price:0.95,base:true},
  {n:'083',dex:448,artist:'Hideki Ishikawa',name:'Lucario',type:'Luta',color:'#FF6B35',rare:'Comum',price:1.49,base:true},
  {n:'084',dex:537,artist:'Kurata So',name:'Seismitoad',type:'Luta',color:'#FF6B35',rare:'Comum',price:0.9,base:true},
  {n:'085',dex:745,artist:'matazo',name:'Lycanroc',type:'Luta',color:'#FF6B35',rare:'Comum',price:0.94,base:true},
  {n:'086',dex:1007,artist:'Mitsuhiro Arita',name:'Koraidon',type:'Luta',color:'#FF6B35',rare:'Rara',price:0.95,base:true},
  {n:'087',dex:29,artist:'Taira Akitsu',name:'Nidoran Fêmea',type:'Trevas',color:'#212121',rare:'Comum',price:0.9,base:true},
  {n:'088',dex:30,artist:'Miki Tanaka',name:'Nidorina',type:'Trevas',color:'#212121',rare:'Comum',price:0.8,base:true},
  {n:'089',dex:52,artist:'Natsumi Yoshida',name:'Meowth de Alola',type:'Trevas',color:'#212121',rare:'Comum',price:0.8,base:true},
  {n:'090',dex:94,artist:'5ban Graphics',name:'Gengar ex',type:'Trevas',color:'#212121',rare:'Rara Dupla',price:29.9,base:true},
  {n:'091',dex:197,artist:'Iori Suzuki',name:'Umbreon',type:'Trevas',color:'#212121',rare:'Comum',price:2.5,base:true},
  {n:'092',dex:197,artist:'Keisuke Azuma',name:'Umbreon ex',type:'Trevas',color:'#212121',rare:'Rara Dupla',price:13.9,base:true},
  {n:'093',dex:198,artist:'Kouki Saitou',name:'Murkrow',type:'Trevas',color:'#212121',rare:'Comum',price:0.9,base:true},
  {n:'094',dex:559,artist:'Souichirou Gunjima',name:'Scraggy',type:'Trevas',color:'#212121',rare:'Comum',price:0.74,base:true},
  {n:'095',dex:570,artist:'Atsuya Uki',name:'Zorua',type:'Trevas',color:'#212121',rare:'Comum',price:0.95,base:true},
  {n:'096',dex:571,artist:'Shiburingaru',name:'Zoroark',type:'Trevas',color:'#212121',rare:'Comum',price:0.95,base:true},
  {n:'097',dex:633,artist:'Gapao',name:'Deino',type:'Trevas',color:'#212121',rare:'Comum',price:0.65,base:true},
  {n:'098',dex:634,artist:'IKEDA Saki',name:'Zweilous',type:'Trevas',color:'#212121',rare:'Comum',price:0.85,base:true},
  {n:'099',dex:635,artist:'Ryuta Fuse',name:'Hydreigon',type:'Trevas',color:'#212121',rare:'Comum',price:0.97,base:true},
  {n:'100',dex:717,artist:'hncl',name:'Yveltal',type:'Trevas',color:'#212121',rare:'Rara',price:0.98,base:true},
  {n:'101',dex:52,artist:'Mékayu',name:'Meowth de Galar',type:'Metal',color:'#607D8B',rare:'Comum',price:0.99,base:true},
  {n:'102',dex:385,artist:'5ban Graphics',name:'Jirachi ex',type:'Metal',color:'#607D8B',rare:'Rara Dupla',price:4,base:true},
  {n:'103',dex:483,artist:'toriyufu',name:'Dialga',type:'Metal',color:'#607D8B',rare:'Rara',price:0.96,base:true},
  {n:'104',dex:598,artist:'Po-Suzuki',name:'Ferrothorn',type:'Metal',color:'#607D8B',rare:'Comum',price:0.85,base:true},
  {n:'105',dex:791,artist:'Nurikabe',name:'Solgaleo',type:'Metal',color:'#607D8B',rare:'Rara',price:0.95,base:true},
  {n:'106',dex:888,artist:'AKIRA EGAWA',name:'Zacian',type:'Metal',color:'#607D8B',rare:'Rara',price:0.95,base:true},
  {n:'107',dex:889,artist:'Tsuyoshi Nagano',name:'Zamazenta',type:'Metal',color:'#607D8B',rare:'Rara',price:0.9,base:true},
  {n:'108',dex:1000,artist:'Sanosuke Sakuma',name:'Gholdengo',type:'Metal',color:'#607D8B',rare:'Comum',price:0.95,base:true},
  {n:'109',dex:373,artist:'5ban Graphics',name:'Salamence ex',type:'Dragao',color:'#673AB7',rare:'Rara Dupla',price:4.88,base:true},
  {n:'110',dex:782,artist:'miki kudo',name:'Jangmo-o',type:'Dragao',color:'#673AB7',rare:'Comum',price:0.95,base:true},
  {n:'111',dex:783,artist:'Jiro Sasumo',name:'Hakamo-o',type:'Dragao',color:'#673AB7',rare:'Comum',price:0.5,base:true},
  {n:'112',dex:784,artist:'MARINA Chikazawa',name:'Kommo-o',type:'Dragao',color:'#673AB7',rare:'Comum',price:0.93,base:true},
  {n:'113',dex:52,artist:'MINAMINAMI Take',name:'Meowth',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.97,base:true},
  {n:'114',dex:115,artist:'Pani Kobayashi',name:'Kangaskhan',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.95,base:true},
  {n:'115',dex:132,artist:'Toshinao Aoki',name:'Ditto',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:2.5,base:true},
  {n:'116',dex:133,artist:'Wintr Wandr',name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.98,base:true},
  {n:'117',dex:133,artist:'En Morikura',name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:2.9,base:true},
  {n:'118',dex:133,artist:'Hitoshi Ariga',name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:2,base:true},
  {n:'119',dex:143,artist:'Aya Kusube',name:'Snorlax',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1,base:true},
  {n:'120',dex:174,artist:'Kanami Ogata',name:'Igglybuff',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.9,base:true},
  {n:'121',dex:249,artist:'Kazuki Minami',name:'Lugia',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:1.95,base:true},
  {n:'122',dex:570,artist:'Megumi Mizutani',name:'Zorua de Hisui',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.95,base:true},
  {n:'123',dex:571,artist:'Kamome Shirahama',name:'Zoroark de Hisui',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.9,base:true},
  {n:'124',dex:774,artist:'ryoma uratsuka',name:'Minior',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.9,base:true},
  {n:'125',dex:925,artist:'Kariya',name:'Maushold',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.46,base:true},
  {n:'126',artist:'Yuka Morii',name:'Poké Tablet',type:'Treinador',color:'#607D8B',rare:'Comum',price:7,base:true},
  {n:'127',artist:'Yuka Morii',name:'Substituição',type:'Treinador',color:'#607D8B',rare:'Comum',price:1.48,base:true},
  {n:'128',artist:'Yuka Morii',name:'Ultra Bola',type:'Treinador',color:'#607D8B',rare:'Comum',price:5.99,base:true},
  // ── SECRETAS 129–158 (acima do numero de regulacao, todas impressao unica) ──
  {n:'129',dex:103,artist:'AYUMI ODASHIMA',name:'Exeggutor de Alola',type:'Grama',color:'#4CAF50',rare:'Rara Ilustrada',price:33.5,base:false},
  {n:'130',dex:146,artist:'mashu',name:'Moltres',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:58.99,base:false},
  {n:'131',dex:131,artist:'Amelicart',name:'Lapras',type:'Agua',color:'#2196F3',rare:'Rara Ilustrada',price:72,base:false},
  {n:'132',dex:144,artist:'mashu',name:'Articuno',type:'Agua',color:'#2196F3',rare:'Rara Ilustrada',price:69.9,base:false},
  {n:'133',dex:145,artist:'mashu',name:'Zapdos',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:60,base:false},
  {n:'134',dex:849,artist:'Kazumasa Yasukuni',name:'Toxtricity',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:29.89,base:false},
  {n:'135',dex:877,artist:'Yoshimi Miyoshi',name:'Morpeko',type:'Eletrico',color:'#FFC107',rare:'Rara Ilustrada',price:42.89,base:false},
  {n:'136',dex:425,artist:'Whisker',name:'Drifloon',type:'Psiquico',color:'#9C27B0',rare:'Rara Ilustrada',price:27.9,base:false},
  {n:'137',dex:609,artist:'YASHIRO Nanaco',name:'Chandelure',type:'Psiquico',color:'#9C27B0',rare:'Rara Ilustrada',price:23.9,base:false},
  {n:'138',dex:745,artist:'Raita Kazama',name:'Lycanroc',type:'Luta',color:'#FF6B35',rare:'Rara Ilustrada',price:21,base:false},
  {n:'139',dex:52,artist:'OKUBO',name:'Meowth de Alola',type:'Trevas',color:'#212121',rare:'Rara Ilustrada',price:58.7,base:false},
  {n:'140',dex:559,artist:'GOSSAN',name:'Scraggy',type:'Trevas',color:'#212121',rare:'Rara Ilustrada',price:16.7,base:false},
  {n:'141',dex:52,artist:'OKUBO',name:'Meowth de Galar',type:'Metal',color:'#607D8B',rare:'Rara Ilustrada',price:67.9,base:false},
  {n:'142',dex:1000,artist:'toriyufu',name:'Gholdengo',type:'Metal',color:'#607D8B',rare:'Rara Ilustrada',price:21.84,base:false},
  {n:'143',dex:784,artist:'Gemi',name:'Kommo-o',type:'Dragao',color:'#673AB7',rare:'Rara Ilustrada',price:16.9,base:false},
  {n:'144',dex:52,artist:'OKUBO',name:'Meowth',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:85.26,base:false},
  {n:'145',dex:570,artist:'0313',name:'Zorua de Hisui',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:48.02,base:false},
  {n:'146',dex:925,artist:'osare',name:'Maushold',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:109.9,base:false},
  {n:'147',dex:909,artist:'Atsushi Furusawa',name:'Fuecoco ex',type:'Fogo',color:'#F44336',rare:'Ilustr. Esp. Rara',price:132,base:false},
  {n:'148',dex:658,artist:'GIDORA',name:'Greninja ex',type:'Agua',color:'#2196F3',rare:'Ilustr. Esp. Rara',price:176.3,base:false},
  {n:'149',dex:25,artist:'kantaro',name:'Pikachu ex',type:'Eletrico',color:'#FFC107',rare:'Ilustr. Esp. Rara',price:557.62,base:false},
  {n:'150',dex:25,artist:'kantaro',name:'Pikachu ex',type:'Eletrico',color:'#FFC107',rare:'Ilustr. Esp. Rara',price:605,base:false},
  {n:'151',dex:150,artist:'Yano Keiji',name:'Mewtwo ex',type:'Psiquico',color:'#9C27B0',rare:'Ilustr. Esp. Rara',price:489.02,base:false},
  {n:'152',dex:151,artist:'Kuroimori',name:'Mew ex',type:'Psiquico',color:'#9C27B0',rare:'Ilustr. Esp. Rara',price:606.62,base:false},
  {n:'153',dex:700,artist:'You Iribi',name:'Sylveon ex',type:'Psiquico',color:'#9C27B0',rare:'Ilustr. Esp. Rara',price:391.02,base:false},
  {n:'154',dex:94,artist:'CHORISO',name:'Gengar ex',type:'Trevas',color:'#212121',rare:'Ilustr. Esp. Rara',price:620,base:false},
  {n:'155',dex:385,artist:'AKIRA EGAWA',name:'Jirachi ex',type:'Metal',color:'#607D8B',rare:'Ilustr. Esp. Rara',price:306,base:false},
  {n:'156',dex:373,artist:'Ryota Murayama',name:'Salamence ex',type:'Dragao',color:'#673AB7',rare:'Ilustr. Esp. Rara',price:112.7,base:false},
  {n:'157',dex:150,artist:'YOSHIROTTEN',name:'Mewtwo ex',type:'Psiquico',color:'#9C27B0',rare:'Rara Ultra',price:489.02,base:false},
  {n:'158',dex:151,artist:'YOSHIROTTEN',name:'Mew ex',type:'Psiquico',color:'#9C27B0',rare:'Rara Ultra',price:568.4,base:false},
  // ── CARTAS RGB — Mew (fora da contagem oficial de 199, bonus ultra-raro) ──
  {n:'R/RGB',dex:151,artist:'YOSHIROTTEN',name:'Mew',type:'Psiquico',color:'#9C27B0',rare:'Rara Secreta',price:16000,base:false},
  {n:'G/RGB',dex:151,artist:'YOSHIROTTEN',name:'Mew',type:'Psiquico',color:'#9C27B0',rare:'Rara Secreta',price:0,base:false},
  {n:'B/RGB',dex:151,artist:'YOSHIROTTEN',name:'Mew',type:'Psiquico',color:'#9C27B0',rare:'Rara Secreta',price:20000,base:false},
  // ── COLEÇÃO CLÁSSICA (30 reimpressões — numeração do set de ORIGEM) ──
  {n:'4/102',dex:6,artist:'Mitsuhiro Arita',name:'Charizard',type:'Fogo',color:'#F44336',rare:'Coleção Clássica',price:1220,base:false},
  {n:'5/109',dex:301,artist:'Atsuko Nishida',name:'Delcatty',type:'Incolor',color:'#9E9E9E',rare:'Coleção Clássica',price:49.9,base:false},
  {n:'11/113',dex:376,artist:'Masakazu Fukuda',name:'Metagross δ',type:'Eletrico',color:'#FFC107',rare:'Coleção Clássica',price:78,base:false},
  {n:'11/101',dex:649,artist:'Eske Yoshinob',name:'Genesect-EX',type:'Grama',color:'#4CAF50',rare:'Coleção Clássica',price:67.66,base:false},
  {n:'18/132',artist:'Ken Sugimori',name:'Misty',type:'Treinador',color:'#607D8B',rare:'Coleção Clássica',price:88.89,base:false},
  {n:'19/109',dex:248,artist:'Nakaoka',name:'Tyranitar Sombrio',type:'Trevas',color:'#212121',rare:'Coleção Clássica',price:104,base:false},
  {n:'25/111',dex:215,artist:'Ken Sugimori',name:'Sneasel',type:'Trevas',color:'#212121',rare:'Coleção Clássica',price:48,base:false},
  {n:'33/181',dex:25,artist:'Mitsuhiro Arita',name:'Pikachu e Zekrom-GX',type:'Eletrico',color:'#FFC107',rare:'Coleção Clássica',price:315,base:false},
  {n:'41/122',dex:658,artist:'5ban Graphics',name:'Greninja BREAK',type:'Agua',color:'#2196F3',rare:'Coleção Clássica',price:60,base:false},
  {n:'43/146',dex:480,artist:'Ken Sugimori',name:'Uxie',type:'Psiquico',color:'#9C27B0',rare:'Coleção Clássica',price:45,base:false},
  {n:'47/127',dex:169,artist:'Makoto Imai',name:'Crobat G',type:'Psiquico',color:'#9C27B0',rare:'Coleção Clássica',price:55,base:false},
  {n:'050/185',dex:243,artist:'Hideki Ishikawa',name:'Raikou',type:'Eletrico',color:'#FFC107',rare:'Coleção Clássica',price:45,base:false},
  {n:'57/111',dex:794,artist:'5ban Graphics',name:'Buzzwole-GX',type:'Luta',color:'#FF6B35',rare:'Coleção Clássica',price:44,base:false},
  {n:'58/102',dex:25,artist:'Mitsuhiro Arita',name:'Pikachu',type:'Eletrico',color:'#FFC107',rare:'Coleção Clássica',price:139.9,base:false},
  {n:'69/132',dex:39,artist:'Ken Sugimori',name:'Jigglypuff da Érica',type:'Incolor',color:'#9E9E9E',rare:'Coleção Clássica',price:87.5,base:false},
  {n:'85/124',dex:384,artist:'Eske Yoshinob',name:'Rayquaza-EX',type:'Dragao',color:'#673AB7',rare:'Coleção Clássica',price:144,base:false},
  {n:'89/149',dex:791,artist:'PLANETA',name:'Solgaleo-GX',type:'Metal',color:'#607D8B',rare:'Coleção Clássica',price:71.92,base:false},
  {n:'94/102',dex:94,artist:'Takashi Yamaguchi',name:'Gengar',type:'Psiquico',color:'#9C27B0',rare:'Coleção Clássica',price:370,base:false},
  {n:'99/102',dex:491,artist:'Shinji Higuchi',name:'Darkrai & Cresselia LEGEND',type:'Trevas',color:'#212121',rare:'Coleção Clássica',price:159.92,base:false},
  {n:'100/102',dex:488,artist:'Shinji Higuchi',name:'Darkrai & Cresselia LEGEND',type:'Trevas',color:'#212121',rare:'Coleção Clássica',price:135,base:false},
  {n:'101/101',artist:'Ken Sugimori',name:'N',type:'Treinador',color:'#607D8B',rare:'Coleção Clássica',price:146.99,base:false},
  {n:'106/106',dex:484,artist:'Ryo Ueda',name:'Palkia LV.X',type:'Agua',color:'#2196F3',rare:'Coleção Clássica',price:178.32,base:false},
  {n:'106/160',dex:282,artist:'5ban Graphics',name:'M Gardevoir-EX',type:'Psiquico',color:'#9C27B0',rare:'Coleção Clássica',price:115,base:false},
  {n:'106/105',dex:251,artist:'Hironobu Yoshida',name:'Celebi Luminescente',type:'Grama',color:'#4CAF50',rare:'Coleção Clássica',price:222.9,base:false},
  {n:'108/115',dex:212,artist:'Mitsuhiro Arita',name:'Scizor ex',type:'Metal',color:'#607D8B',rare:'Coleção Clássica',price:85,base:false},
  {n:'114/264',dex:151,artist:'5ban Graphics',name:'Mew-VMAX',type:'Psiquico',color:'#9C27B0',rare:'Coleção Clássica',price:104.9,base:false},
  {n:'123/172',dex:493,artist:'5ban Graphics',name:'Arceus VSTAR',type:'Incolor',color:'#9E9E9E',rare:'Coleção Clássica',price:365,base:false},
  {n:'138/202',dex:888,artist:'5ban Graphics',name:'Zacian-V',type:'Metal',color:'#607D8B',rare:'Coleção Clássica',price:98.32,base:false},
  {n:'149/147',dex:249,artist:'Naoyo Kimura',name:'Lugia',type:'Incolor',color:'#9E9E9E',rare:'Coleção Clássica',price:832.49,base:false},
  {n:'203/193',dex:129,artist:'Shinji Kanda',name:'Magikarp',type:'Agua',color:'#2196F3',rare:'Coleção Clássica',price:500,base:false},
  // ── ENERGIAS BÁSICAS (8 cartas bonus, sem preco de mercado ainda) ──
  {n:'MEE 009',name:'Energia de Planta Básica',type:'Energia',color:'#4CAF50',rare:'Comum',price:0,base:false},
  {n:'MEE 010',name:'Energia de Fogo Básica',type:'Energia',color:'#F44336',rare:'Comum',price:0,base:false},
  {n:'MEE 011',name:'Energia de Água Básica',type:'Energia',color:'#2196F3',rare:'Comum',price:0,base:false},
  {n:'MEE 012',name:'Energia de Raio Básica',type:'Energia',color:'#FFC107',rare:'Comum',price:0,base:false},
  {n:'MEE 013',name:'Energia Psíquica Básica',type:'Energia',color:'#9C27B0',rare:'Comum',price:0,base:false},
  {n:'MEE 014',name:'Energia de Luta Básica',type:'Energia',color:'#FF6B35',rare:'Comum',price:0,base:false},
  {n:'MEE 015',name:'Energia de Escuridão Básica',type:'Energia',color:'#212121',rare:'Comum',price:0,base:false},
  {n:'MEE 016',name:'Energia de Metal Básica',type:'Energia',color:'#607D8B',rare:'Comum',price:0,base:false},
];
