// ME2.5(ASC) — Heróis Excelsos (Ascended Heroes) — 295 cartas (RECONSTRUÍDO 01/10/2026)
// Lançamento Internacional: 30 jan 2026 | Série: Mega Evolution (companion set do ME05)
// Tema: 13 Pokémon Mega ex — Mega Audino ex, Mega Charizard Y ex, Mega Diancie ex,
//       Mega Dragonite ex, Mega Eelektross ex, Mega Emboar ex, Mega Feraligatr ex,
//       Mega Froslass ex, Mega Gardevoir ex, Mega Gengar ex, Mega Hawlucha ex,
//       Mega Lucario ex, Mega Meganium ex, Mega Scrafty ex
// HISTÓRICO: a versão anterior vinha da api.pokemontcg.io com os nomes em
// INGLÊS gravados no campo `name` (ex: "Erika's Oddish") — nunca traduzidos
// pro português, apesar de ser o campo usado como padrão PT/BRL em toda a
// UI. Também usava imagem fixa em inglês (scrydex) independente do idioma
// escolhido no fichário.
// RECONSTRUÇÃO (01/10/2026, pedido do Eduardo): fonte trocada pra
// api.tcgdex.net, que cataloga este set (slug "me02.5") com dados
// COMPLETOS e estruturados em português (nome com gramática correta — "X
// da Érica"/"X da Equipe Rocket" em vez do possessivo em inglês — tipo,
// raridade, Pokédex, ilustrador) e em inglês, mais o preço ao vivo
// (cardmarket EUR + tcgplayer USD, já tem fetchLivePrices() cuidando disso
// — ver TCGDX em app.js). 295/295 cartas conferidas contra o JSON da API,
// sem gaps.
// ARTE: imgMe2pt5(n,lang) agora busca direto do tcgdex
// (assets.tcgdex.net/{pt|en}/me/me02.5/{n}/high.png) — PT mostra arte com
// texto em português de verdade, EN mostra a arte americana. Resolve o
// "fichário em português com foto em inglês" relatado pelo Eduardo.
// ESTRUTURA FÍSICA (confirmada via tcgdex variants_detailed + cruzada contra
// ninthpocket.com/sets/ascended-heroes e binderforge.com, que batem
// exatamente): diferente de qualquer outro set ME/SV já catalogado aqui,
// Ascended Heroes tem DOIS reverse holo distintos pra cada carta Pokémon
// Comum/Incomum/Rara (140 cartas, campo implícito via category==='Pokémon'
// + rare + base) — "Reverse Holo Energia" e "Reverse Holo [padrão de bola/
// Equipe Rocket]" — em vez do N+RH simples de sempre (ver novo branch em
// getSlots() no app.js, slot extra código 'RH2'). Treinador/Energia
// (38 cartas) continuam só com 1 reverse holo padrão (N+RH, sem mudança).
// Rara Dupla (ex, 39 cartas) e todas as 78 secretas (218-295, Ilustração
// Rara em diante) continuam impressão única (1 slot), sem reverse — isso já
// funcionava certo antes (base:false / r.includes('Dupla')).
// JAPONÊS/CHINÊS: ainda NÃO existem neste arquivo. Ascended Heroes é uma
// COMPILAÇÃO internacional de 5 lançamentos japoneses diferentes (Mega
// Brave/M1L, Mega Symphonia/M1S, Inferno X/M2, Mega Dream ex/M2a, e parte
// do Start Deck 100 Battle Collection/MC — confirmado via
// pokemon.com/us/pokemon-news + limitlesstcg.com/cards/ASC, que lista o
// "JP. PRINTS" de cada carta individualmente) — não um set japonês único
// como os outros ME/SV. Chinês simplificado nem existe ainda pra era
// Megaevolução (tcgdex só cobre zh-cn até a série SV). Decisão (pedido do
// Eduardo): fechar só PT+EN agora, JP/CN ficam pendentes.
const CARDS_ME2PT5 = [
  // ── SET BASE 001–217 ────────────────────────────────
  {n:"001",dex:43,artist:"Yoriyuki Ikegami",name:"Oddish da Érica",nameEn:"Erika's Oddish",type:"Grama",color:"#4CAF50",rare:"Comum",price:0.1,base:true},
  {n:"002",dex:44,artist:"MARINA Chikazawa",name:"Gloom da Érica",nameEn:"Erika's Gloom",type:"Grama",color:"#4CAF50",rare:"Incomum",price:0.13,base:true},
  {n:"003",dex:45,artist:"5ban Graphics",name:"Vileplume ex da Érica",nameEn:"Erika's Vileplume ex",type:"Grama",color:"#4CAF50",rare:"Rara Dupla",price:5,base:true},
  {n:"004",dex:69,artist:"sui",name:"Bellsprout da Érica",nameEn:"Erika's Bellsprout",type:"Grama",color:"#4CAF50",rare:"Comum",price:0.05,base:true},
  {n:"005",dex:70,artist:"LINNE",name:"Weepinbell da Érica",nameEn:"Erika's Weepinbell",type:"Grama",color:"#4CAF50",rare:"Incomum",price:0.1,base:true},
  {n:"006",dex:71,artist:"takashi shiraishi",name:"Victreebel da Érica",nameEn:"Erika's Victreebel",type:"Grama",color:"#4CAF50",rare:"Rara",price:0.2,base:true},
  {n:"007",dex:114,artist:"GIDORA",name:"Tangela da Érica",nameEn:"Erika's Tangela",type:"Grama",color:"#4CAF50",rare:"Comum",price:0.05,base:true},
  {n:"008",dex:152,artist:"Kariya",name:"Chikorita",type:"Grama",color:"#4CAF50",rare:"Comum",price:0.15,base:true},
  {n:"009",dex:153,artist:"Tomomi Ozaki",name:"Bayleef",type:"Grama",color:"#4CAF50",rare:"Incomum",price:0.1,base:true},
  {n:"010",dex:154,artist:"5ban Graphics",name:"Mega Meganium ex",type:"Grama",color:"#4CAF50",rare:"Rara Dupla",price:4.99,base:true},
  {n:"011",dex:265,artist:"USGMEN",name:"Wurmple",type:"Grama",color:"#4CAF50",rare:"Comum",price:0.05,base:true},
  {n:"012",dex:266,artist:"Eri Yamaki",name:"Silcoon",type:"Grama",color:"#4CAF50",rare:"Comum",price:0.1,base:true},
  {n:"013",dex:267,artist:"Narumi Sato",name:"Beautifly",type:"Grama",color:"#4CAF50",rare:"Incomum",price:0.15,base:true},
  {n:"014",dex:268,artist:"Dsuke",name:"Cascoon",type:"Grama",color:"#4CAF50",rare:"Comum",price:0.13,base:true},
  {n:"015",dex:269,artist:"kamonabe",name:"Dustox",type:"Grama",color:"#4CAF50",rare:"Incomum",price:0.14,base:true},
  {n:"016",dex:406,artist:"Yoriyuki Ikegami",name:"Budew",type:"Grama",color:"#4CAF50",rare:"Comum",price:0.05,base:true},
  {n:"017",dex:736,artist:"Jerky",name:"Grubbin",type:"Grama",color:"#4CAF50",rare:"Comum",price:0.05,base:true},
  {n:"018",dex:917,artist:"Saboteri",name:"Tarountula da Equipe Rocket",nameEn:"Team Rocket's Tarountula",type:"Grama",color:"#4CAF50",rare:"Comum",price:0.1,base:true},
  {n:"019",dex:918,artist:"Taiga Kasai",name:"Spidops da Equipe Rocket",nameEn:"Team Rocket's Spidops",type:"Grama",color:"#4CAF50",rare:"Rara",price:0.2,base:true},
  {n:"020",dex:4,artist:"Orca",name:"Charmander",type:"Fogo",color:"#F44336",rare:"Comum",price:0.1,base:true},
  {n:"021",dex:5,artist:"Julie Hang",name:"Charmeleon",type:"Fogo",color:"#F44336",rare:"Incomum",price:0.13,base:true},
  {n:"022",dex:6,artist:"aky CG Works",name:"Mega Charizard Y ex",type:"Fogo",color:"#F44336",rare:"Rara Dupla",price:35.9,base:true},
  {n:"023",dex:218,artist:"Sanosuke Sakuma",name:"Slugma do Ethan",nameEn:"Ethan's Slugma",type:"Fogo",color:"#F44336",rare:"Comum",price:0.05,base:true},
  {n:"024",dex:219,artist:"kodama",name:"Magcargo do Ethan",nameEn:"Ethan's Magcargo",type:"Fogo",color:"#F44336",rare:"Rara",price:0.14,base:true},
  {n:"025",dex:244,artist:"Kazumasa Yasukuni",name:"Entei",type:"Fogo",color:"#F44336",rare:"Rara",price:0.4,base:true},
  {n:"026",dex:250,artist:"aky CG Works",name:"Ho-Oh ex do Ethan",nameEn:"Ethan's Ho-Oh ex",type:"Fogo",color:"#F44336",rare:"Rara Dupla",price:9.75,base:true},
  {n:"027",dex:322,artist:"Ounishi",name:"Numel",type:"Fogo",color:"#F44336",rare:"Comum",price:0.15,base:true},
  {n:"028",dex:323,artist:"Minahamu",name:"Camerupt",type:"Fogo",color:"#F44336",rare:"Incomum",price:0.1,base:true},
  {n:"029",dex:498,artist:"Uninori",name:"Tepig",type:"Fogo",color:"#F44336",rare:"Comum",price:0.1,base:true},
  {n:"030",dex:499,artist:"Aliya Chen",name:"Pignite",type:"Fogo",color:"#F44336",rare:"Incomum",price:0.1,base:true},
  {n:"031",dex:500,artist:"5ban Graphics",name:"Mega Emboar ex",type:"Fogo",color:"#F44336",rare:"Rara Dupla",price:3.96,base:true},
  {n:"032",dex:554,artist:"Gemi",name:"Darumaka do N",nameEn:"N's Darumaka",type:"Fogo",color:"#F44336",rare:"Comum",price:0.12,base:true},
  {n:"033",dex:555,artist:"nagimiso",name:"Darmanitan do N",nameEn:"N's Darmanitan",type:"Fogo",color:"#F44336",rare:"Incomum",price:0.05,base:true},
  {n:"034",dex:757,artist:"Felicia Chen",name:"Salandit",type:"Fogo",color:"#F44336",rare:"Comum",price:0.05,base:true},
  {n:"035",dex:758,artist:"Taiga Kasai",name:"Salazzle",type:"Fogo",color:"#F44336",rare:"Incomum",price:0.1,base:true},
  {n:"036",dex:813,artist:"Cona Nitanda",name:"Scorbunny",type:"Fogo",color:"#F44336",rare:"Comum",price:0.14,base:true},
  {n:"037",dex:814,artist:"aspara",name:"Raboot",type:"Fogo",color:"#F44336",rare:"Comum",price:0.1,base:true},
  {n:"038",dex:815,artist:"5ban Graphics",name:"Cinderace ex",type:"Fogo",color:"#F44336",rare:"Rara Dupla",price:4.9,base:true},
  {n:"039",dex:54,artist:"Jiro Sasumo",name:"Psyduck",type:"Agua",color:"#2196F3",rare:"Comum",price:0.05,base:true},
  {n:"040",dex:55,artist:"Jiro Sasumo",name:"Golduck",type:"Agua",color:"#2196F3",rare:"Incomum",price:0.18,base:true},
  {n:"041",dex:158,artist:"REND",name:"Totodile",type:"Agua",color:"#2196F3",rare:"Comum",price:0.05,base:true},
  {n:"042",dex:159,artist:"Felicia Chen",name:"Croconaw",type:"Agua",color:"#2196F3",rare:"Incomum",price:0.05,base:true},
  {n:"043",dex:160,artist:"5ban Graphics",name:"Mega Feraligatr ex",type:"Agua",color:"#2196F3",rare:"Rara Dupla",price:4.99,base:true},
  {n:"044",dex:215,artist:"Krgc",name:"Sneasel",type:"Agua",color:"#2196F3",rare:"Comum",price:0.15,base:true},
  {n:"045",dex:461,artist:"aspara",name:"Weavile",type:"Agua",color:"#2196F3",rare:"Incomum",price:0.15,base:true},
  {n:"046",dex:361,artist:"Wintr Wandr",name:"Snorunt",type:"Agua",color:"#2196F3",rare:"Comum",price:0.1,base:true},
  {n:"047",dex:478,artist:"5ban Graphics",name:"Mega Froslass ex",type:"Agua",color:"#2196F3",rare:"Rara Dupla",price:27.9,base:true},
  {n:"048",dex:378,artist:"akagi",name:"Regice ex",type:"Agua",color:"#2196F3",rare:"Rara Dupla",price:4,base:true},
  {n:"049",dex:582,artist:"yuu",name:"Vanillite do N",nameEn:"N's Vanillite",type:"Agua",color:"#2196F3",rare:"Comum",price:0.05,base:true},
  {n:"050",dex:583,artist:"kirisAki",name:"Vanillish do N",nameEn:"N's Vanillish",type:"Agua",color:"#2196F3",rare:"Comum",price:0.1,base:true},
  {n:"051",dex:584,artist:"imoniii",name:"Vanilluxe do N",nameEn:"N's Vanilluxe",type:"Agua",color:"#2196F3",rare:"Incomum",price:0.05,base:true},
  {n:"052",dex:872,artist:"Izucch",name:"Snom",type:"Agua",color:"#2196F3",rare:"Comum",price:0.05,base:true},
  {n:"053",dex:873,artist:"cochi8i",name:"Frosmoth",type:"Agua",color:"#2196F3",rare:"Incomum",price:0.15,base:true},
  {n:"054",dex:896,artist:"mashu",name:"Glastrier",type:"Agua",color:"#2196F3",rare:"Incomum",price:0.14,base:true},
  {n:"055",dex:25,artist:"kamonabe",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Comum",price:0.15,base:true},
  {n:"056",dex:26,artist:"Iori Suzuki",name:"Raichu",type:"Eletrico",color:"#FFC107",rare:"Incomum",price:0.15,base:true},
  {n:"057",dex:25,artist:"aky CG Works",name:"Pikachu ex",type:"Eletrico",color:"#FFC107",rare:"Rara Dupla",price:29.9,base:true},
  {n:"058",dex:100,artist:"5ban Graphics",name:"Voltorb ex",type:"Eletrico",color:"#FFC107",rare:"Rara Dupla",price:3.5,base:true},
  {n:"059",dex:602,artist:"Jerky",name:"Tynamo",type:"Eletrico",color:"#FFC107",rare:"Comum",price:0.05,base:true},
  {n:"060",dex:603,artist:"Jerky",name:"Eelektrik",type:"Eletrico",color:"#FFC107",rare:"Incomum",price:0.05,base:true},
  {n:"061",dex:604,artist:"takuyoa",name:"Mega Eelektross ex",type:"Eletrico",color:"#FFC107",rare:"Rara Dupla",price:4,base:true},
  {n:"062",dex:618,artist:"Tetsu Kayama",name:"Stunfisk",type:"Eletrico",color:"#FFC107",rare:"Comum",price:0.12,base:true},
  {n:"063",dex:694,artist:"Tika Matsuno",name:"Helioptile",type:"Eletrico",color:"#FFC107",rare:"Comum",price:0.1,base:true},
  {n:"064",dex:695,artist:"svlt",name:"Heliolisk",type:"Eletrico",color:"#FFC107",rare:"Incomum",price:0.1,base:true},
  {n:"065",dex:737,artist:"Misa Tsutsui",name:"Charjabug",type:"Eletrico",color:"#FFC107",rare:"Comum",price:0.14,base:true},
  {n:"066",dex:738,artist:"Shiburingaru",name:"Vikavolt",type:"Eletrico",color:"#FFC107",rare:"Incomum",price:0.1,base:true},
  {n:"067",dex:785,artist:"Anesaki Dynamic",name:"Tapu Koko",type:"Eletrico",color:"#FFC107",rare:"Rara",price:0.19,base:true},
  {n:"068",dex:871,artist:"5ban Graphics",name:"Pincurchin ex do Lupo",nameEn:"Hop's Pincurchin ex",type:"Eletrico",color:"#FFC107",rare:"Rara Dupla",price:2.5,base:true},
  {n:"069",dex:938,artist:"kurumitsu",name:"Tadbulb da Kissera",nameEn:"Iono's Tadbulb",type:"Eletrico",color:"#FFC107",rare:"Comum",price:0.1,base:true},
  {n:"070",dex:939,artist:"5ban Graphics",name:"Bellibolt ex da Kissera",nameEn:"Iono's Bellibolt ex",type:"Eletrico",color:"#FFC107",rare:"Rara Dupla",price:3.8,base:true},
  {n:"071",dex:940,artist:"Akira Komayama",name:"Wattrel da Kissera",nameEn:"Iono's Wattrel",type:"Eletrico",color:"#FFC107",rare:"Comum",price:0.1,base:true},
  {n:"072",dex:941,artist:"chibi",name:"Kilowattrel da Kissera",nameEn:"Iono's Kilowattrel",type:"Eletrico",color:"#FFC107",rare:"Rara",price:0.19,base:true},
  {n:"073",dex:1008,artist:"5ban Graphics",name:"Miraidon ex",type:"Eletrico",color:"#FFC107",rare:"Rara Dupla",price:4,base:true},
  {n:"074",dex:35,artist:"satoma",name:"Clefairy",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0.15,base:true},
  {n:"075",dex:36,artist:"satoma",name:"Clefable",type:"Psiquico",color:"#9C27B0",rare:"Incomum",price:0.1,base:true},
  {n:"076",dex:35,artist:"5ban Graphics",name:"Clefairy ex da Lílian",nameEn:"Lillie's Clefairy ex",type:"Psiquico",color:"#9C27B0",rare:"Rara Dupla",price:24.99,base:true},
  {n:"077",dex:102,artist:"Gapao",name:"Exeggcute da Equipe Rocket",nameEn:"Team Rocket's Exeggcute",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0.1,base:true},
  {n:"078",dex:103,artist:"Ryuta Fuse",name:"Exeggutor da Equipe Rocket",nameEn:"Team Rocket's Exeggutor",type:"Psiquico",color:"#9C27B0",rare:"Rara",price:0.2,base:true},
  {n:"079",dex:150,artist:"aky CG Works",name:"Mewtwo ex da Equipe Rocket",nameEn:"Team Rocket's Mewtwo ex",type:"Psiquico",color:"#9C27B0",rare:"Rara Dupla",price:9,base:true},
  {n:"080",dex:175,artist:"Yoko Hishida",name:"Togepi",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0.05,base:true},
  {n:"081",dex:176,artist:"Teeziro",name:"Togetic",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0.15,base:true},
  {n:"082",dex:468,artist:"Narano",name:"Togekiss",type:"Psiquico",color:"#9C27B0",rare:"Rara",price:0.2,base:true},
  {n:"083",dex:183,artist:"Yoshimoto Yoshimon",name:"Marill",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0.05,base:true},
  {n:"084",dex:184,artist:"5ban Graphics",name:"Azumarill ex",type:"Psiquico",color:"#9C27B0",rare:"Rara Dupla",price:5,base:true},
  {n:"085",dex:200,artist:"Kazuhisa Uragami",name:"Misdreavus",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0.1,base:true},
  {n:"086",dex:429,artist:"nisimono",name:"Mismagius",type:"Psiquico",color:"#9C27B0",rare:"Rara",price:0.15,base:true},
  {n:"087",dex:280,artist:"Terada Tera",name:"Ralts",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0.08,base:true},
  {n:"088",dex:281,artist:"satoma",name:"Kirlia",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0.08,base:true},
  {n:"089",dex:282,artist:"takuyoa",name:"Mega Gardevoir ex",type:"Psiquico",color:"#9C27B0",rare:"Rara Dupla",price:4.88,base:true},
  {n:"090",dex:353,artist:"miki kudo",name:"Shuppet",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0.1,base:true},
  {n:"091",dex:354,artist:"Anesaki Dynamic",name:"Banette",type:"Psiquico",color:"#9C27B0",rare:"Incomum",price:0.1,base:true},
  {n:"092",dex:479,artist:"mingo",name:"Rotom",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0.1,base:true},
  {n:"093",dex:684,artist:"Saya Tsuruta",name:"Swirlix",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0.15,base:true},
  {n:"094",dex:685,artist:"Natsumi Yoshida",name:"Slurpuff",type:"Psiquico",color:"#9C27B0",rare:"Incomum",price:0.15,base:true},
  {n:"095",dex:708,artist:"tono",name:"Phantump do Lupo",nameEn:"Hop's Phantump",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0.1,base:true},
  {n:"096",dex:709,artist:"matazo",name:"Trevenant do Lupo",nameEn:"Hop's Trevenant",type:"Psiquico",color:"#9C27B0",rare:"Rara",price:0.19,base:true},
  {n:"097",dex:778,artist:"DOM",name:"Mimikyu da Equipe Rocket",nameEn:"Team Rocket's Mimikyu",type:"Psiquico",color:"#9C27B0",rare:"Incomum",price:0.15,base:true},
  {n:"098",dex:897,artist:"Taiga Kasai",name:"Spectrier",type:"Psiquico",color:"#9C27B0",rare:"Rara",price:0.2,base:true},
  {n:"099",dex:1015,artist:"kodama",name:"Munkidori",type:"Psiquico",color:"#9C27B0",rare:"Rara",price:0.6,base:true},
  {n:"100",dex:50,artist:"Yuriko Akase",name:"Diglett da Equipe Rocket",nameEn:"Team Rocket's Diglett",type:"Luta",color:"#FF6B35",rare:"Comum",price:0.12,base:true},
  {n:"101",dex:51,artist:"KEIICHIRO ITO",name:"Dugtrio da Equipe Rocket",nameEn:"Team Rocket's Dugtrio",type:"Luta",color:"#FF6B35",rare:"Incomum",price:0.14,base:true},
  {n:"102",dex:237,artist:"Kouki Saitou",name:"Hitmontop",type:"Luta",color:"#FF6B35",rare:"Comum",price:0.1,base:true},
  {n:"103",dex:307,artist:"Lee HyunJung",name:"Meditite",type:"Luta",color:"#FF6B35",rare:"Comum",price:0.15,base:true},
  {n:"104",dex:308,artist:"GIDORA",name:"Medicham",type:"Luta",color:"#FF6B35",rare:"Comum",price:0.15,base:true},
  {n:"105",dex:337,artist:"Whisker",name:"Lunatone",type:"Luta",color:"#FF6B35",rare:"Rara",price:0.29,base:true},
  {n:"106",dex:338,artist:"Whisker",name:"Solrock",type:"Luta",color:"#FF6B35",rare:"Incomum",price:0.1,base:true},
  {n:"107",dex:377,artist:"Nisota Niso",name:"Regirock ex",type:"Luta",color:"#FF6B35",rare:"Rara Dupla",price:4.2,base:true},
  {n:"108",dex:383,artist:"Kazumasa Yasukuni",name:"Groudon",type:"Luta",color:"#FF6B35",rare:"Rara",price:0.15,base:true},
  {n:"109",dex:443,artist:"Tomomi Ozaki",name:"Gible da Cíntia",nameEn:"Cynthia's Gible",type:"Luta",color:"#FF6B35",rare:"Comum",price:0.1,base:true},
  {n:"110",dex:444,artist:"Taira Akitsu",name:"Gabite da Cíntia",nameEn:"Cynthia's Gabite",type:"Luta",color:"#FF6B35",rare:"Incomum",price:0.15,base:true},
  {n:"111",dex:445,artist:"5ban Graphics",name:"Garchomp ex da Cíntia",nameEn:"Cynthia's Garchomp ex",type:"Luta",color:"#FF6B35",rare:"Rara Dupla",price:8.91,base:true},
  {n:"112",dex:447,artist:"hncl",name:"Riolu",type:"Luta",color:"#FF6B35",rare:"Comum",price:0.1,base:true},
  {n:"113",dex:448,artist:"5ban Graphics",name:"Mega Lucario ex",type:"Luta",color:"#FF6B35",rare:"Rara Dupla",price:4.9,base:true},
  {n:"114",dex:618,artist:"5ban Graphics",name:"Stunfisk ex",type:"Luta",color:"#FF6B35",rare:"Rara Dupla",price:3,base:true},
  {n:"115",dex:674,artist:"Minato",name:"Pancham",type:"Luta",color:"#FF6B35",rare:"Comum",price:0.05,base:true},
  {n:"116",dex:701,artist:"5ban Graphics",name:"Mega Hawlucha ex",type:"Luta",color:"#FF6B35",rare:"Rara Dupla",price:4.5,base:true},
  {n:"117",dex:703,artist:"Eri Kamei",name:"Carbink",type:"Luta",color:"#FF6B35",rare:"Incomum",price:0.15,base:true},
  {n:"118",dex:837,artist:"Kurata So",name:"Rolycoly",type:"Luta",color:"#FF6B35",rare:"Comum",price:0.1,base:true},
  {n:"119",dex:838,artist:"Apios",name:"Carkol",type:"Luta",color:"#FF6B35",rare:"Comum",price:0.15,base:true},
  {n:"120",dex:839,artist:"Nisota Niso",name:"Coalossal",type:"Luta",color:"#FF6B35",rare:"Rara",price:0.24,base:true},
  {n:"121",dex:1007,artist:"aky CG Works",name:"Koraidon ex",type:"Luta",color:"#FF6B35",rare:"Rara Dupla",price:4.69,base:true},
  {n:"122",dex:1014,artist:"Mitsuhiro Arita",name:"Okidogi",type:"Luta",color:"#FF6B35",rare:"Rara",price:0.2,base:true},
  {n:"123",dex:92,artist:"Saboteri",name:"Gastly",type:"Trevas",color:"#212121",rare:"Comum",price:0.1,base:true},
  {n:"124",dex:93,artist:"Rianti Hidayat",name:"Haunter",type:"Trevas",color:"#212121",rare:"Incomum",price:0.1,base:true},
  {n:"125",dex:94,artist:"5ban Graphics",name:"Mega Gengar ex",type:"Trevas",color:"#212121",rare:"Rara Dupla",price:10.9,base:true},
  {n:"126",dex:198,artist:"Mugi Hamada",name:"Murkrow da Equipe Rocket",nameEn:"Team Rocket's Murkrow",type:"Trevas",color:"#212121",rare:"Comum",price:0.1,base:true},
  {n:"127",dex:430,artist:"hncl",name:"Honchkrow da Equipe Rocket",nameEn:"Team Rocket's Honchkrow",type:"Trevas",color:"#212121",rare:"Rara",price:0.15,base:true},
  {n:"128",dex:261,artist:"Miki Tanaka",name:"Poochyena",type:"Trevas",color:"#212121",rare:"Comum",price:0.05,base:true},
  {n:"129",dex:262,artist:"akagi",name:"Mightyena",type:"Trevas",color:"#212121",rare:"Incomum",price:0.1,base:true},
  {n:"130",dex:263,artist:"osare",name:"Zigzagoon de Galar",nameEn:"Galarian Zigzagoon",type:"Trevas",color:"#212121",rare:"Comum",price:0.1,base:true},
  {n:"131",dex:264,artist:"Tomowaka",name:"Linoone de Galar",nameEn:"Galarian Linoone",type:"Trevas",color:"#212121",rare:"Comum",price:0.05,base:true},
  {n:"132",dex:862,artist:"Dsuke",name:"Obstagoon de Galar",nameEn:"Galarian Obstagoon",type:"Trevas",color:"#212121",rare:"Incomum",price:0.1,base:true},
  {n:"133",dex:442,artist:"satoma",name:"Spiritomb da Cíntia",nameEn:"Cynthia's Spiritomb",type:"Trevas",color:"#212121",rare:"Incomum",price:0.15,base:true},
  {n:"134",dex:559,artist:"Shimaris Yukichi",name:"Scraggy",type:"Trevas",color:"#212121",rare:"Comum",price:0.1,base:true},
  {n:"135",dex:560,artist:"5ban Graphics",name:"Mega Scrafty ex",type:"Trevas",color:"#212121",rare:"Rara Dupla",price:4.5,base:true},
  {n:"136",dex:570,artist:"Jiro Sasumo",name:"Zorua do N",nameEn:"N's Zorua",type:"Trevas",color:"#212121",rare:"Comum",price:0.1,base:true},
  {n:"137",dex:571,artist:"takuyoa",name:"Zoroark ex do N",nameEn:"N's Zoroark ex",type:"Trevas",color:"#212121",rare:"Rara Dupla",price:15.9,base:true},
  {n:"138",dex:629,artist:"Nisota Niso",name:"Vullaby",type:"Trevas",color:"#212121",rare:"Comum",price:0.05,base:true},
  {n:"139",dex:630,artist:"Ultimateinudog",name:"Mandibuzz ex",type:"Trevas",color:"#212121",rare:"Rara Dupla",price:3.8,base:true},
  {n:"140",dex:675,artist:"takashi shiraishi",name:"Pangoro",type:"Trevas",color:"#212121",rare:"Incomum",price:0.1,base:true},
  {n:"141",dex:720,artist:"Anesaki Dynamic",name:"Hoopa",type:"Trevas",color:"#212121",rare:"Rara",price:0.1,base:true},
  {n:"142",dex:1016,artist:"takuyoa",name:"Fezandipiti ex",type:"Trevas",color:"#212121",rare:"Rara Dupla",price:17.5,base:true},
  {n:"143",dex:1025,artist:"IKEDA Saki",name:"Pecharunt",type:"Trevas",color:"#212121",rare:"Rara",price:0.15,base:true},
  {n:"144",dex:303,artist:"CHORISO",name:"Mawile",type:"Metal",color:"#607D8B",rare:"Incomum",price:0.1,base:true},
  {n:"145",dex:379,artist:"toriyufu",name:"Registeel ex",type:"Metal",color:"#607D8B",rare:"Rara Dupla",price:3.4,base:true},
  {n:"146",dex:624,artist:"Yuya Oka",name:"Pawniard",type:"Metal",color:"#607D8B",rare:"Comum",price:0.05,base:true},
  {n:"147",dex:625,artist:"Scav",name:"Bisharp",type:"Metal",color:"#607D8B",rare:"Comum",price:0.1,base:true},
  {n:"148",dex:983,artist:"Teeziro",name:"Kingambit",type:"Metal",color:"#607D8B",rare:"Rara",price:0.1,base:true},
  {n:"149",dex:777,artist:"5ban Graphics",name:"Togedemaru ex",type:"Metal",color:"#607D8B",rare:"Rara Dupla",price:3.49,base:true},
  {n:"150",dex:147,artist:"HYOGONOSUKE",name:"Dratini",type:"Dragao",color:"#673AB7",rare:"Comum",price:0.14,base:true},
  {n:"151",dex:148,artist:"Gemi",name:"Dragonair",type:"Dragao",color:"#673AB7",rare:"Incomum",price:0.15,base:true},
  {n:"152",dex:149,artist:"aky CG Works",name:"Mega Dragonite ex",type:"Dragao",color:"#673AB7",rare:"Rara Dupla",price:25.48,base:true},
  {n:"153",dex:384,artist:"nagimiso",name:"Rayquaza",type:"Dragao",color:"#673AB7",rare:"Rara",price:0.2,base:true},
  {n:"154",dex:643,artist:"rika",name:"Reshiram do N",nameEn:"N's Reshiram",type:"Dragao",color:"#673AB7",rare:"Rara",price:0.2,base:true},
  {n:"155",dex:644,artist:"AKIRA EGAWA",name:"Zekrom do N",nameEn:"N's Zekrom",type:"Dragao",color:"#673AB7",rare:"Rara",price:0.2,base:true},
  {n:"156",dex:714,artist:"Eri Kamei",name:"Noibat",type:"Dragao",color:"#673AB7",rare:"Comum",price:0.1,base:true},
  {n:"157",dex:715,artist:"Natsumi Miyanose",name:"Noivern",type:"Dragao",color:"#673AB7",rare:"Incomum",price:0.1,base:true},
  {n:"158",dex:885,artist:"Scav",name:"Dreepy",type:"Dragao",color:"#673AB7",rare:"Comum",price:0.1,base:true},
  {n:"159",dex:886,artist:"cochi8i",name:"Drakloak",type:"Dragao",color:"#673AB7",rare:"Comum",price:0.15,base:true},
  {n:"160",dex:887,artist:"5ban Graphics",name:"Dragapult ex",type:"Dragao",color:"#673AB7",rare:"Rara Dupla",price:3.43,base:true},
  {n:"161",dex:52,artist:"Megumi Mizutani",name:"Meowth da Equipe Rocket",nameEn:"Team Rocket's Meowth",type:"Incolor",color:"#9E9E9E",rare:"Comum",price:0.15,base:true},
  {n:"162",dex:115,artist:"5ban Graphics",name:"Kangaskhan ex da Equipe Rocket",nameEn:"Team Rocket's Kangaskhan ex",type:"Incolor",color:"#9E9E9E",rare:"Rara Dupla",price:5.9,base:true},
  {n:"163",dex:206,artist:"0313",name:"Dunsparce do Lauro",nameEn:"Larry's Dunsparce",type:"Incolor",color:"#9E9E9E",rare:"Comum",price:0.15,base:true},
  {n:"164",dex:982,artist:"5ban Graphics",name:"Dudunsparce ex do Lauro",nameEn:"Larry's Dudunsparce ex",type:"Incolor",color:"#9E9E9E",rare:"Rara Dupla",price:2.9,base:true},
  {n:"165",dex:300,artist:"Yoko Hishida",name:"Skitty",type:"Incolor",color:"#9E9E9E",rare:"Comum",price:0.1,base:true},
  {n:"166",dex:301,artist:"buchi",name:"Delcatty",type:"Incolor",color:"#9E9E9E",rare:"Incomum",price:0.1,base:true},
  {n:"167",dex:335,artist:"5ban Graphics",name:"Zangoose ex",type:"Incolor",color:"#9E9E9E",rare:"Rara Dupla",price:4,base:true},
  {n:"168",dex:396,artist:"Natsumi Miyanose",name:"Starly do Lauro",nameEn:"Larry's Starly",type:"Incolor",color:"#9E9E9E",rare:"Comum",price:0.15,base:true},
  {n:"169",dex:397,artist:"Fujimoto Gold",name:"Staravia do Lauro",nameEn:"Larry's Staravia",type:"Incolor",color:"#9E9E9E",rare:"Incomum",price:0.1,base:true},
  {n:"170",dex:398,artist:"Po-Suzuki",name:"Staraptor do Lauro",nameEn:"Larry's Staraptor",type:"Incolor",color:"#9E9E9E",rare:"Rara",price:0.25,base:true},
  {n:"171",dex:479,artist:"Toshinao Aoki",name:"Rotom Ventilador",nameEn:"Fan Rotom",type:"Incolor",color:"#9E9E9E",rare:"Comum",price:0.15,base:true},
  {n:"172",dex:531,artist:"5ban Graphics",name:"Mega Audino ex",type:"Incolor",color:"#9E9E9E",rare:"Rara Dupla",price:7,base:true},
  {n:"173",dex:627,artist:"cochi8i",name:"Rufflet do Lauro",nameEn:"Larry's Rufflet",type:"Incolor",color:"#9E9E9E",rare:"Comum",price:0.1,base:true},
  {n:"174",dex:628,artist:"Ryuta Fuse",name:"Braviary do Lauro",nameEn:"Larry's Braviary",type:"Incolor",color:"#9E9E9E",rare:"Incomum",price:0.1,base:true},
  {n:"175",dex:775,artist:"ryoma uratsuka",name:"Komala do Lauro",nameEn:"Larry's Komala",type:"Incolor",color:"#9E9E9E",rare:"Comum",price:0.05,base:true},
  {n:"176",dex:780,artist:"Scav",name:"Drampa",type:"Incolor",color:"#9E9E9E",rare:"Incomum",price:0.15,base:true},
  {n:"177",dex:845,artist:"Saboteri",name:"Cramorant do Lupo",nameEn:"Hop's Cramorant",type:"Incolor",color:"#9E9E9E",rare:"Incomum",price:0.15,base:true},
  {n:"178",dex:1024,artist:"GIDORA",name:"Terapagos",type:"Incolor",color:"#9E9E9E",rare:"Rara",price:0.15,base:true},
  {n:"179",dex:1024,artist:"5ban Graphics",name:"Terapagos ex",type:"Incolor",color:"#9E9E9E",rare:"Rara Dupla",price:5,base:true},
  {n:"180",artist:"Yuu Nishida",name:"Traquinagem da Acerola",nameEn:"Acerola's Mischief",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.1,base:true},
  {n:"181",artist:"Studio Bora Inc.",name:"Balão de Ar",nameEn:"Air Balloon",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.2,base:true},
  {n:"182",artist:"Sanosuke Sakuma",name:"Amor e Paz",nameEn:"Anthea & Concordia",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.09,base:true},
  {n:"183",artist:"akagi",name:"Ordem da Chefia",nameEn:"Boss's Orders",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.2,base:true},
  {n:"184",artist:"AYUMI ODASHIMA",name:"Poffin de Colega",nameEn:"Buddy-Buddy Poffin",type:"Treinador",color:"#607D8B",rare:"Comum",category:"Treinador",price:0.1,base:true},
  {n:"185",artist:"Naoki Saito",name:"Canari",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.1,base:true},
  {n:"186",artist:"Toyste Beach",name:"Contra-ataque de Alcance",nameEn:"Counter Gain",type:"Treinador",color:"#607D8B",rare:"Comum",category:"Treinador",price:0.15,base:true},
  {n:"187",artist:"Toyste Beach",name:"Gongo de Luta",nameEn:"Fighting Gong",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.15,base:true},
  {n:"188",artist:"AYUMI ODASHIMA",name:"Floresta da Vitalidade",nameEn:"Forest of Vitality",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.18,base:true},
  {n:"189",artist:"Toyste Beach",name:"Trompete de Vidro",nameEn:"Glass Trumpet",type:"Treinador",color:"#607D8B",rare:"Comum",category:"Treinador",price:0.15,base:true},
  {n:"190",artist:"yuu",name:"Espírito de Luta da Iris",nameEn:"Iris's Fighting Spirit",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.1,base:true},
  {n:"191",artist:"Studio Bora Inc.",name:"Esfera de Luz",nameEn:"Light Ball",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.1,base:true},
  {n:"192",artist:"Atsushi Furusawa",name:"Determinação da Lílian",nameEn:"Lillie's Determination",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.2,base:true},
  {n:"193",artist:"inose yukie",name:"Megassinal",nameEn:"Mega Signal",type:"Treinador",color:"#607D8B",rare:"Comum",category:"Treinador",price:0.1,base:true},
  {n:"194",artist:"AYUMI ODASHIMA",name:"Jardim Misterioso",nameEn:"Mystery Garden",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.19,base:true},
  {n:"195",artist:"Toyste Beach",name:"PP Up do N",nameEn:"N's PP Up",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.15,base:true},
  {n:"196",artist:"Toyste Beach",name:"Maca Noturna",nameEn:"Night Stretcher",type:"Treinador",color:"#607D8B",rare:"Comum",category:"Treinador",price:0.15,base:true},
  {n:"197",artist:"Takashi Yamaguchi",name:"Mina Noturna",nameEn:"Nighttime Mine",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.15,base:true},
  {n:"198",artist:"Studio Bora Inc.",name:"Poké Tablet",nameEn:"Poké Pad",type:"Treinador",color:"#607D8B",rare:"Comum",category:"Treinador",price:0.5,base:true},
  {n:"199",artist:"Toyste Beach",name:"Suplemento Premium Pro",nameEn:"Premium Power Pro",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.15,base:true},
  {n:"200",artist:"Hideki Ishikawa",name:"Surfista",nameEn:"Surfer",type:"Treinador",color:"#607D8B",rare:"Comum",category:"Treinador",price:0.1,base:true},
  {n:"201",artist:"Hideki Ishikawa",name:"Apollo da Equipe Rocket",nameEn:"Team Rocket's Archer",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.19,base:true},
  {n:"202",artist:"hncl",name:"Athena da Equipe Rocket",nameEn:"Team Rocket's Ariana",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.15,base:true},
  {n:"203",artist:"imoniii",name:"Fábrica da Equipe Rocket",nameEn:"Team Rocket's Factory",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.14,base:true},
  {n:"204",artist:"DOM",name:"Giovanni da Equipe Rocket",nameEn:"Team Rocket's Giovanni",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.2,base:true},
  {n:"205",artist:"Toyste Beach",name:"Grande Bola da Equipe Rocket",nameEn:"Team Rocket's Great Ball",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.1,base:true},
  {n:"206",artist:"Toyste Beach",name:"Hipnotizador da Equipe Rocket",nameEn:"Team Rocket's Hypnotizer",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.15,base:true},
  {n:"207",artist:"GOSSAN",name:"Petrel da Equipe Rocket",nameEn:"Team Rocket's Petrel",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.5,base:true},
  {n:"208",artist:"Naoki Saito",name:"Próton da Equipe Rocket",nameEn:"Team Rocket's Proton",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.15,base:true},
  {n:"209",artist:"inose yukie",name:"Transmissor da Equipe Rocket",nameEn:"Team Rocket's Transceiver",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.2,base:true},
  {n:"210",artist:"AYUMI ODASHIMA",name:"Torre de Vigia da Equipe Rocket",nameEn:"Team Rocket's Watchtower",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.25,base:true},
  {n:"211",artist:"Toyste Beach",name:"Escama Espessa",nameEn:"Thick Scale",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.13,base:true},
  {n:"212",artist:"Studio Bora Inc.",name:"Sucateador de Ferramentas",nameEn:"Tool Scrapper",type:"Treinador",color:"#607D8B",rare:"Comum",category:"Treinador",price:0.14,base:true},
  {n:"213",artist:"Ayaka Yoshida",name:"Ultra Bola",nameEn:"Ultra Ball",type:"Treinador",color:"#607D8B",rare:"Comum",category:"Treinador",price:0.08,base:true},
  {n:"214",artist:"Teeziro",name:"Urbano",nameEn:"Urbain",type:"Treinador",color:"#607D8B",rare:"Incomum",category:"Treinador",price:0.12,base:true},
  {n:"215",artist:"Cona Nitanda",name:"Garçonete",nameEn:"Waitress",type:"Treinador",color:"#607D8B",rare:"Comum",category:"Treinador",price:0.05,base:true},
  {n:"216",name:"Energia de Prisma",nameEn:"Prism Energy",type:"Energia",color:"#607D8B",rare:"Incomum",category:"Energia",price:0.15,base:true},
  {n:"217",name:"Energia da Equipe Rocket",nameEn:"Team Rocket's Energy",type:"Energia",color:"#607D8B",rare:"Incomum",category:"Energia",price:0.2,base:true},
  // ── SECRETAS 218–295 (acima do número de regulação, impressão única) ──
  {n:"218",dex:114,artist:"buchi",name:"Tangela da Érica",nameEn:"Erika's Tangela",type:"Grama",color:"#4CAF50",rare:"Ilustração Rara",price:84.9,base:false},
  {n:"219",dex:267,artist:"Mori Yuu",name:"Beautifly",type:"Grama",color:"#4CAF50",rare:"Ilustração Rara",price:23.9,base:false},
  {n:"220",dex:269,artist:"IKEDA Saki",name:"Dustox",type:"Grama",color:"#4CAF50",rare:"Ilustração Rara",price:12.9,base:false},
  {n:"221",dex:406,artist:"Yoko Hishida",name:"Budew",type:"Grama",color:"#4CAF50",rare:"Ilustração Rara",price:28.9,base:false},
  {n:"222",dex:219,artist:"Hideki Ishikawa",name:"Magcargo do Ethan",nameEn:"Ethan's Magcargo",type:"Fogo",color:"#F44336",rare:"Ilustração Rara",price:28.9,base:false},
  {n:"223",dex:322,artist:"Yoshimi Miyoshi",name:"Numel",type:"Fogo",color:"#F44336",rare:"Ilustração Rara",price:16.9,base:false},
  {n:"224",dex:758,artist:"Dsuke",name:"Salazzle",type:"Fogo",color:"#F44336",rare:"Ilustração Rara",price:12.9,base:false},
  {n:"225",dex:813,artist:"Yuu Nishida",name:"Scorbunny",type:"Fogo",color:"#F44336",rare:"Ilustração Rara",price:37,base:false},
  {n:"226",dex:54,artist:"REND",name:"Psyduck",type:"Agua",color:"#2196F3",rare:"Ilustração Rara",price:207,base:false},
  {n:"227",dex:361,artist:"June",name:"Snorunt",type:"Agua",color:"#2196F3",rare:"Ilustração Rara",price:27.9,base:false},
  {n:"228",dex:461,artist:"Uninori",name:"Weavile",type:"Agua",color:"#2196F3",rare:"Ilustração Rara",price:29.9,base:false},
  {n:"229",dex:695,artist:"Takeshi Nakamura",name:"Heliolisk",type:"Eletrico",color:"#FFC107",rare:"Ilustração Rara",price:13,base:false},
  {n:"230",dex:738,artist:"Tonji Matsuno",name:"Vikavolt",type:"Eletrico",color:"#FFC107",rare:"Ilustração Rara",price:10,base:false},
  {n:"231",dex:940,artist:"mingo",name:"Wattrel da Kissera",nameEn:"Iono's Wattrel",type:"Eletrico",color:"#FFC107",rare:"Ilustração Rara",price:39.9,base:false},
  {n:"232",dex:183,artist:"Rond",name:"Marill",type:"Psiquico",color:"#9C27B0",rare:"Ilustração Rara",price:47.9,base:false},
  {n:"233",dex:200,artist:"mashu",name:"Misdreavus",type:"Psiquico",color:"#9C27B0",rare:"Ilustração Rara",price:20.9,base:false},
  {n:"234",dex:354,artist:"YASHIRO Nanaco",name:"Banette",type:"Psiquico",color:"#9C27B0",rare:"Ilustração Rara",price:36.9,base:false},
  {n:"235",dex:468,artist:"satoma",name:"Togekiss",type:"Psiquico",color:"#9C27B0",rare:"Ilustração Rara",price:24,base:false},
  {n:"236",dex:685,artist:"Yoshimoto Yoshimon",name:"Slurpuff",type:"Psiquico",color:"#9C27B0",rare:"Ilustração Rara",price:17.9,base:false},
  {n:"237",dex:709,artist:"Tomowaka",name:"Trevenant do Lupo",nameEn:"Hop's Trevenant",type:"Psiquico",color:"#9C27B0",rare:"Ilustração Rara",price:22.9,base:false},
  {n:"238",dex:778,artist:"GOSSAN",name:"Mimikyu da Equipe Rocket",nameEn:"Team Rocket's Mimikyu",type:"Psiquico",color:"#9C27B0",rare:"Ilustração Rara",price:63.9,base:false},
  {n:"239",dex:51,artist:"Whisker",name:"Dugtrio da Equipe Rocket",nameEn:"Team Rocket's Dugtrio",type:"Luta",color:"#FF6B35",rare:"Ilustração Rara",price:37.89,base:false},
  {n:"240",dex:237,artist:"osare",name:"Hitmontop",type:"Luta",color:"#FF6B35",rare:"Ilustração Rara",price:23,base:false},
  {n:"241",dex:308,artist:"KEIICHIRO ITO",name:"Medicham",type:"Luta",color:"#FF6B35",rare:"Ilustração Rara",price:18.81,base:false},
  {n:"242",dex:703,artist:"sui",name:"Carbink",type:"Luta",color:"#FF6B35",rare:"Ilustração Rara",price:22.9,base:false},
  {n:"243",dex:262,artist:"Yano Keiji",name:"Mightyena",type:"Trevas",color:"#212121",rare:"Ilustração Rara",price:19.5,base:false},
  {n:"244",dex:442,artist:"hncl",name:"Spiritomb da Cíntia",nameEn:"Cynthia's Spiritomb",type:"Trevas",color:"#212121",rare:"Ilustração Rara",price:39,base:false},
  {n:"245",dex:862,artist:"Krgc",name:"Obstagoon de Galar",nameEn:"Galarian Obstagoon",type:"Trevas",color:"#212121",rare:"Ilustração Rara",price:21.6,base:false},
  {n:"246",dex:303,artist:"sowsow",name:"Mawile",type:"Metal",color:"#607D8B",rare:"Ilustração Rara",price:19.9,base:false},
  {n:"247",dex:885,artist:"Jerky",name:"Dreepy",type:"Dragao",color:"#673AB7",rare:"Ilustração Rara",price:29.9,base:false},
  {n:"248",dex:886,artist:"Jerky",name:"Drakloak",type:"Dragao",color:"#673AB7",rare:"Ilustração Rara",price:37.9,base:false},
  {n:"249",dex:398,artist:"kantaro",name:"Staraptor do Lauro",nameEn:"Larry's Staraptor",type:"Incolor",color:"#9E9E9E",rare:"Ilustração Rara",price:19.2,base:false},
  {n:"250",dex:479,artist:"Yukihiro Tada",name:"Rotom Ventilador",nameEn:"Fan Rotom",type:"Incolor",color:"#9E9E9E",rare:"Ilustração Rara",price:17.99,base:false},
  {n:"251",dex:906,artist:"5ban Graphics",name:"Sprigatito ex",type:"Grama",color:"#4CAF50",rare:"Ultra Rara",price:13.5,base:false},
  {n:"252",dex:618,artist:"5ban Graphics",name:"Stunfisk ex",type:"Luta",color:"#FF6B35",rare:"Ultra Rara",price:4,base:false},
  {n:"253",dex:531,artist:"5ban Graphics",name:"Mega Audino ex",type:"Incolor",color:"#9E9E9E",rare:"Ultra Rara",price:8,base:false},
  {n:"254",artist:"Sanosuke Sakuma",name:"Amor e Paz",nameEn:"Anthea & Concordia",type:"Treinador",color:"#607D8B",rare:"Ultra Rara",category:"Treinador",price:7.65,base:false},
  {n:"255",artist:"GOSSAN",name:"Treino de Faixa Preta",nameEn:"Black Belt's Training",type:"Treinador",color:"#607D8B",rare:"Ultra Rara",category:"Treinador",price:8.9,base:false},
  {n:"256",artist:"akagi",name:"Ordem da Chefia",nameEn:"Boss's Orders",type:"Treinador",color:"#607D8B",rare:"Ultra Rara",category:"Treinador",price:58.8,base:false},
  {n:"257",artist:"Naoki Saito",name:"Canari",type:"Treinador",color:"#607D8B",rare:"Ultra Rara",category:"Treinador",price:17.99,base:false},
  {n:"258",artist:"REND",name:"Cheren",type:"Treinador",color:"#607D8B",rare:"Ultra Rara",category:"Treinador",price:6.84,base:false},
  {n:"259",artist:"Toyste Beach",name:"Contra-ataque de Alcance",nameEn:"Counter Gain",type:"Treinador",color:"#607D8B",rare:"Ultra Rara",category:"Treinador",price:4.8,base:false},
  {n:"260",artist:"Toyste Beach",name:"Trompete de Vidro",nameEn:"Glass Trumpet",type:"Treinador",color:"#607D8B",rare:"Ultra Rara",category:"Treinador",price:4.8,base:false},
  {n:"261",artist:"AYUMI ODASHIMA",name:"Torre de Interferência",nameEn:"Jamming Tower",type:"Treinador",color:"#607D8B",rare:"Ultra Rara",category:"Treinador",price:6.9,base:false},
  {n:"262",artist:"Toyste Beach",name:"PP Up do N",nameEn:"N's PP Up",type:"Treinador",color:"#607D8B",rare:"Ultra Rara",category:"Treinador",price:7.5,base:false},
  {n:"263",artist:"inose yukie",name:"Transmissor da Equipe Rocket",nameEn:"Team Rocket's Transceiver",type:"Treinador",color:"#607D8B",rare:"Ultra Rara",category:"Treinador",price:9.9,base:false},
  {n:"264",artist:"Studio Bora Inc.",name:"Ultra Bola",nameEn:"Ultra Ball",type:"Treinador",color:"#607D8B",rare:"Ultra Rara",category:"Treinador",price:52,base:false},
  {n:"265",dex:478,artist:"Saboteri",name:"Mega Froslass ex",type:"Agua",color:"#2196F3",rare:"Ultra Rara",price:59.99,base:false},
  {n:"266",dex:604,artist:"DOM",name:"Mega Eelektross ex",type:"Eletrico",color:"#FFC107",rare:"Ultra Rara",price:22.28,base:false},
  {n:"267",dex:719,artist:"DOM",name:"Mega Diancie ex",type:"Psiquico",color:"#9C27B0",rare:"Ultra Rara",price:35,base:false},
  {n:"268",dex:701,artist:"Taiga Kasai",name:"Mega Hawlucha ex",type:"Luta",color:"#FF6B35",rare:"Ultra Rara",price:32,base:false},
  {n:"269",dex:94,artist:"Taiga Kasai",name:"Mega Gengar ex",type:"Trevas",color:"#212121",rare:"Ultra Rara",price:199.9,base:false},
  {n:"270",dex:560,artist:"Taiga Kasai",name:"Mega Scrafty ex",type:"Trevas",color:"#212121",rare:"Ultra Rara",price:26.99,base:false},
  {n:"271",dex:149,artist:"DOM",name:"Mega Dragonite ex",type:"Dragao",color:"#673AB7",rare:"Ultra Rara",price:104.99,base:false},
  {n:"272",dex:154,artist:"Tika Matsuno",name:"Mega Meganium ex",type:"Grama",color:"#4CAF50",rare:"Ilustração Rara Especial",price:399.9,base:false},
  {n:"273",dex:500,artist:"nagimiso",name:"Mega Emboar ex",type:"Fogo",color:"#F44336",rare:"Ilustração Rara Especial",price:244.99,base:false},
  {n:"274",dex:160,artist:"Souichirou Gunjima",name:"Mega Feraligatr ex",type:"Agua",color:"#2196F3",rare:"Ilustração Rara Especial",price:389,base:false},
  {n:"275",dex:478,artist:"Teeziro",name:"Mega Froslass ex",type:"Agua",color:"#2196F3",rare:"Ilustração Rara Especial",price:380,base:false},
  {n:"276",dex:25,artist:"booota",name:"Pikachu ex",type:"Eletrico",color:"#FFC107",rare:"Ilustração Rara Especial",price:3279.99,base:false},
  {n:"277",dex:25,artist:"James Turner",name:"Pikachu ex",type:"Eletrico",color:"#FFC107",rare:"Ilustração Rara Especial",price:1499,base:false},
  {n:"278",dex:604,artist:"akagi",name:"Mega Eelektross ex",type:"Eletrico",color:"#FFC107",rare:"Ilustração Rara Especial",price:99,base:false},
  {n:"279",dex:939,artist:"Akira Komayama",name:"Bellibolt ex da Kissera",nameEn:"Iono's Bellibolt ex",type:"Eletrico",color:"#FFC107",rare:"Ilustração Rara Especial",price:239.9,base:false},
  {n:"280",dex:35,artist:"Naoki Saito",name:"Clefairy ex da Lílian",nameEn:"Lillie's Clefairy ex",type:"Psiquico",color:"#9C27B0",rare:"Ilustração Rara Especial",price:595,base:false},
  {n:"281",dex:150,artist:"Mitsuhiro Arita",name:"Mewtwo ex da Equipe Rocket",nameEn:"Team Rocket's Mewtwo ex",type:"Psiquico",color:"#9C27B0",rare:"Ilustração Rara Especial",price:935,base:false},
  {n:"282",dex:719,artist:"Narano",name:"Mega Diancie ex",type:"Psiquico",color:"#9C27B0",rare:"Ilustração Rara Especial",price:239.9,base:false},
  {n:"283",dex:701,artist:"AKIRA EGAWA",name:"Mega Hawlucha ex",type:"Luta",color:"#FF6B35",rare:"Ilustração Rara Especial",price:218.99,base:false},
  {n:"284",dex:94,artist:"danciao",name:"Mega Gengar ex",type:"Trevas",color:"#212121",rare:"Ilustração Rara Especial",price:2100,base:false},
  {n:"285",dex:560,artist:"nagimiso",name:"Mega Scrafty ex",type:"Trevas",color:"#212121",rare:"Ilustração Rara Especial",price:230,base:false},
  {n:"286",dex:571,artist:"Raita Kazama",name:"Zoroark ex do N",nameEn:"N's Zoroark ex",type:"Trevas",color:"#212121",rare:"Ilustração Rara Especial",price:599,base:false},
  {n:"287",dex:861,artist:"Ligton",name:"Grimmsnarl ex da Marine",nameEn:"Marnie's Grimmsnarl ex",type:"Trevas",color:"#212121",rare:"Ilustração Rara Especial",price:239.9,base:false},
  {n:"288",dex:1016,artist:"SIE NANAHARA",name:"Fezandipiti ex",type:"Trevas",color:"#212121",rare:"Ilustração Rara Especial",price:269.9,base:false},
  {n:"289",dex:376,artist:"chibi",name:"Metagross ex do Steven",nameEn:"Steven's Metagross ex",type:"Metal",color:"#607D8B",rare:"Ilustração Rara Especial",price:300,base:false},
  {n:"290",dex:149,artist:"DOM",name:"Mega Dragonite ex",type:"Dragao",color:"#673AB7",rare:"Ilustração Rara Especial",price:1650,base:false},
  {n:"291",artist:"kantaro",name:"Canari",type:"Treinador",color:"#607D8B",rare:"Ilustração Rara Especial",category:"Treinador",price:175,base:false},
  {n:"292",artist:"Kuroimori",name:"Espírito de Luta da Iris",nameEn:"Iris's Fighting Spirit",type:"Treinador",color:"#607D8B",rare:"Ilustração Rara Especial",category:"Treinador",price:150,base:false},
  {n:"293",artist:"OKUBO",name:"Surfista",nameEn:"Surfer",type:"Treinador",color:"#607D8B",rare:"Ilustração Rara Especial",category:"Treinador",price:145,base:false},
  {n:"294",dex:6,artist:"aky CG Works",name:"Mega Charizard Y ex",type:"Fogo",color:"#F44336",rare:"Mega Hiper Raro",price:1279.9,base:false},
  {n:"295",dex:149,artist:"aky CG Works",name:"Mega Dragonite ex",type:"Dragao",color:"#673AB7",rare:"Mega Hiper Raro",price:710.08,base:false},
];
