// SV2 — Paldea Evolved (279 cartas)
// Lançamento EN: 2023/06/09
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV2 = [
  {n:'001',name:'Hoppip',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.16,base:true},
  {n:'002',name:'Skiploom',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'003',name:'Jumpluff',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.45,base:true},
  {n:'004',name:'Pineco',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'005',name:'Forretress ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:4.90,base:true},
  {n:'006',name:'Heracross',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.25,base:true},
  {n:'007',name:'Tropius',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'008',name:'Combee',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.16,base:true},
  {n:'009',name:'Vespiquen',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'010',name:'Snover',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.13,base:true},
  {n:'011',name:'Abomasnow',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.25,base:true},
  {n:'012',name:'Sprigatito',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'013',name:'Sprigatito',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'014',name:'Floragato',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.19,base:true},
  {n:'015',name:'Meowscarada ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.90,base:true},
  {n:'016',name:'Tarountula',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.13,base:true},
  {n:'017',name:'Tarountula',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'018',name:'Spidops',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.19,base:true},
  {n:'019',name:'Nymble',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'020',name:'Nymble',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.16,base:true},
  {n:'021',name:'Lokix',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.19,base:true},
  {n:'022',name:'Bramblin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.13,base:true},
  {n:'023',name:'Bramblin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'024',name:'Brambleghast',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'025',name:'Rellor',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'026',name:'Rellor',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'027',name:'Wo-Chien ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:5.99,base:true},
  {n:'028',name:'Paldean Tauros',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.18,base:true},
  {n:'029',name:'Fletchinder',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.15,base:true},
  {n:'030',name:'Talonflame',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.17,base:true},
  {n:'031',name:'Litleo',type:'Fogo',color:'#F44336',rare:'Comum',price:0.13,base:true},
  {n:'032',name:'Pyroar',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.20,base:true},
  {n:'033',name:'Oricorio',type:'Fogo',color:'#F44336',rare:'Rara',price:0.19,base:true},
  {n:'034',name:'Fuecoco',type:'Fogo',color:'#F44336',rare:'Comum',price:0.21,base:true},
  {n:'035',name:'Fuecoco',type:'Fogo',color:'#F44336',rare:'Comum',price:0.23,base:true},
  {n:'036',name:'Crocalor',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.23,base:true},
  {n:'037',name:'Skeledirge ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:4.90,base:true},
  {n:'038',name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.20,base:true},
  {n:'039',name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.17,base:true},
  {n:'040',name:'Chi-Yu ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:4.00,base:true},
  {n:'041',name:'Paldean Tauros',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.23,base:true},
  {n:'042',name:'Magikarp',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'043',name:'Gyarados',type:'Aquático',color:'#2196F3',rare:'Rara',price:1.00,base:true},
  {n:'044',name:'Marill',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.15,base:true},
  {n:'045',name:'Azumarill',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.15,base:true},
  {n:'046',name:'Delibird',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'047',name:'Luvdisc',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'048',name:'Eiscue',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.15,base:true},
  {n:'049',name:'Quaxly',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'050',name:'Quaxly',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.17,base:true},
  {n:'051',name:'Quaxwell',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.20,base:true},
  {n:'052',name:'Quaquaval ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:4.75,base:true},
  {n:'053',name:'Cetoddle',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.17,base:true},
  {n:'054',name:'Cetoddle',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'055',name:'Cetitan',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.20,base:true},
  {n:'056',name:'Veluza',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.20,base:true},
  {n:'057',name:'Frigibax',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.17,base:true},
  {n:'058',name:'Frigibax',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.17,base:true},
  {n:'059',name:'Arctibax',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.21,base:true},
  {n:'060',name:'Baxcalibur',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.40,base:true},
  {n:'061',name:'Chien-Pao ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:5.85,base:true},
  {n:'062',name:'Pikachu',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.90,base:true},
  {n:'063',name:'Pikachu ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:18.00,base:true},
  {n:'064',name:'Raichu',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.45,base:true},
  {n:'065',name:'Magnemite',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.20,base:true},
  {n:'066',name:'Voltorb',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'067',name:'Electrode',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.20,base:true},
  {n:'068',name:'Shinx',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.19,base:true},
  {n:'069',name:'Shinx',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.20,base:true},
  {n:'070',name:'Luxio',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.21,base:true},
  {n:'071',name:'Luxray',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.32,base:true},
  {n:'072',name:'Pincurchin',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.20,base:true},
  {n:'073',name:'Pincurchin',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.13,base:true},
  {n:'074',name:'Pawmi',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.19,base:true},
  {n:'075',name:'Pawmo',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.19,base:true},
  {n:'076',name:'Pawmot',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.35,base:true},
  {n:'077',name:'Tadbulb',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.13,base:true},
  {n:'078',name:'Tadbulb',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.10,base:true},
  {n:'079',name:'Bellibolt ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:4.20,base:true},
  {n:'080',name:'Wattrel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.35,base:true},
  {n:'081',name:'Wattrel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.20,base:true},
  {n:'082',name:'Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.17,base:true},
  {n:'083',name:'Jigglypuff',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.25,base:true},
  {n:'084',name:'Wigglytuff',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.50,base:true},
  {n:'085',name:'Slowpoke',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.23,base:true},
  {n:'086',name:'Slowking ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:5.10,base:true},
  {n:'087',name:'Misdreavus',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'088',name:'Mismagius',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.23,base:true},
  {n:'089',name:'Spiritomb',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.25,base:true},
  {n:'090',name:'Gothita',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.17,base:true},
  {n:'091',name:'Gothorita',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.17,base:true},
  {n:'092',name:'Gothitelle',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.25,base:true},
  {n:'093',name:'Dedenne ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:8.00,base:true},
  {n:'094',name:'Oranguru',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.19,base:true},
  {n:'095',name:'Sandygast',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'096',name:'Palossand',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.20,base:true},
  {n:'097',name:'Mimikyu',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.26,base:true},
  {n:'098',name:'Ceruledge',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.47,base:true},
  {n:'099',name:'Rabsca',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.21,base:true},
  {n:'100',name:'Tinkatink',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.17,base:true},
  {n:'101',name:'Tinkatink',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'102',name:'Tinkatink',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'103',name:'Tinkatuff',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.21,base:true},
  {n:'104',name:'Tinkatuff',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.40,base:true},
  {n:'105',name:'Tinkaton',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.45,base:true},
  {n:'106',name:'Mankey',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.16,base:true},
  {n:'107',name:'Primeape',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'108',name:'Paldean Tauros',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.25,base:true},
  {n:'109',name:'Sudowoodo',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'110',name:'Larvitar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.19,base:true},
  {n:'111',name:'Pupitar',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'112',name:'Makuhita',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'113',name:'Hariyama',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.34,base:true},
  {n:'114',name:'Croagunk',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.09,base:true},
  {n:'115',name:'Toxicroak',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.15,base:true},
  {n:'116',name:'Rockruff',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'117',name:'Lycanroc ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:8.50,base:true},
  {n:'118',name:'Passimian',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.17,base:true},
  {n:'119',name:'Falinks',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.09,base:true},
  {n:'120',name:'Nacli',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'121',name:'Nacli',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'122',name:'Naclstack',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'123',name:'Garganacl',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.09,base:true},
  {n:'124',name:'Glimmet',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.20,base:true},
  {n:'125',name:'Glimmet',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'126',name:'Glimmora',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.49,base:true},
  {n:'127',name:'Ting-Lu ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:3.00,base:true},
  {n:'128',name:'Paldean Wooper',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.23,base:true},
  {n:'129',name:'Paldean Wooper',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.25,base:true},
  {n:'130',name:'Paldean Clodsire ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:4.59,base:true},
  {n:'131',name:'Murkrow',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'132',name:'Honchkrow',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'133',name:'Sneasel',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.17,base:true},
  {n:'134',name:'Weavile',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.30,base:true},
  {n:'135',name:'Tyranitar',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.50,base:true},
  {n:'136',name:'Sableye',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.35,base:true},
  {n:'137',name:'Seviper',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.12,base:true},
  {n:'138',name:'Deino',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'139',name:'Zweilous',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'140',name:'Hydreigon',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.80,base:true},
  {n:'141',name:'Maschiff',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'142',name:'Maschiff',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.20,base:true},
  {n:'143',name:'Mabosstiff',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.17,base:true},
  {n:'144',name:'Shroodle',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.16,base:true},
  {n:'145',name:'Shroodle',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'146',name:'Grafaiai',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'147',name:'Bombirdier',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'148',name:'Corviknight',type:'Metal',color:'#78909C',rare:'Incomum',price:0.20,base:true},
  {n:'149',name:'Cufant',type:'Metal',color:'#78909C',rare:'Comum',price:0.19,base:true},
  {n:'150',name:'Copperajah ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:4.98,base:true},
  {n:'151',name:'Orthworm',type:'Metal',color:'#78909C',rare:'Rara',price:0.30,base:true},
  {n:'152',name:'Noibat',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.09,base:true},
  {n:'153',name:'Noivern ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:4.90,base:true},
  {n:'154',name:'Girafarig',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'155',name:'Farigiraf',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.17,base:true},
  {n:'156',name:'Dunsparce',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.32,base:true},
  {n:'157',name:'Dudunsparce',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'158',name:'Wingull',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.13,base:true},
  {n:'159',name:'Pelipper',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'160',name:'Slakoth',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'161',name:'Vigoroth',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'162',name:'Slaking',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.35,base:true},
  {n:'163',name:'Fletchling',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.09,base:true},
  {n:'164',name:'Rookidee',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'165',name:'Corvisquire',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'166',name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'167',name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.50,base:true},
  {n:'168',name:'Maushold',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.40,base:true},
  {n:'169',name:'Squawkabilly ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:4.20,base:true},
  {n:'170',name:'Flamigo',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'171',name:'Artazon',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'172',name:'Boss\'s Orders (Ghetsis)',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.30,base:true},
  {n:'173',name:'Bravery Charm',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.50,base:true},
  {n:'174',name:'Calamitous Snowy Mountain',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.50,base:true},
  {n:'175',name:'Calamitous Wasteland',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.35,base:true},
  {n:'176',name:'Choice Belt',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'177',name:'Clavell',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'178',name:'Delivery Drone',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'179',name:'Dendra',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'180',name:'Falkner',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.23,base:true},
  {n:'181',name:'Fighting Au Lait',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.19,base:true},
  {n:'182',name:'Giacomo',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.18,base:true},
  {n:'183',name:'Great Ball',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'184',name:'Grusha',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'185',name:'Iono',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.17,base:true},
  {n:'186',name:'Practice Studio',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'187',name:'Saguaro',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'188',name:'Super Rod',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'189',name:'Superior Energy Retrieval',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.30,base:true},
  {n:'190',name:'Jet Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.49,base:true},
  {n:'191',name:'Luminous Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.50,base:true},
  {n:'192',name:'Reversal Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.27,base:true},
  {n:'193',name:'Therapeutic Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.29,base:true},
  {n:'194',name:'Heracross',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:51.00,base:false,important:true},
  {n:'195',name:'Tropius',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:59.90,base:false,important:true},
  {n:'196',name:'Sprigatito',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:175.00,base:false,important:true},
  {n:'197',name:'Floragato',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:103.90,base:false,important:true},
  {n:'198',name:'Bramblin',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:50.00,base:false,important:true},
  {n:'199',name:'Fletchinder',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:77.90,base:false,important:true},
  {n:'200',name:'Pyroar',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:23.75,base:false,important:true},
  {n:'201',name:'Fuecoco',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:250.00,base:false,important:true},
  {n:'202',name:'Crocalor',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:41.80,base:false,important:true},
  {n:'203',name:'Magikarp',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:449.99,base:false,important:true},
  {n:'204',name:'Marill',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:89.00,base:false,important:true},
  {n:'205',name:'Eiscue',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:39.99,base:false,important:true},
  {n:'206',name:'Quaxly',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:139.99,base:false,important:true},
  {n:'207',name:'Quaxwell',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:26.99,base:false,important:true},
  {n:'208',name:'Frigibax',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:39.99,base:false,important:true},
  {n:'209',name:'Arctibax',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:67.40,base:false,important:true},
  {n:'210',name:'Baxcalibur',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:59.00,base:false,important:true},
  {n:'211',name:'Raichu',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:259.00,base:false,important:true},
  {n:'212',name:'Mismagius',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:209.90,base:false,important:true},
  {n:'213',name:'Gothorita',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:49.90,base:false,important:true},
  {n:'214',name:'Sandygast',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:24.90,base:false,important:true},
  {n:'215',name:'Rabsca',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:21.99,base:false},
  {n:'216',name:'Tinkatink',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:89.90,base:false,important:true},
  {n:'217',name:'Tinkatuff',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:69.90,base:false,important:true},
  {n:'218',name:'Paldean Tauros',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:40.00,base:false,important:true},
  {n:'219',name:'Sudowoodo',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:40.00,base:false,important:true},
  {n:'220',name:'Nacli',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:29.90,base:false},
  {n:'221',name:'Paldean Wooper',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:46.90,base:false,important:true},
  {n:'222',name:'Tyranitar',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:99.50,base:false,important:true},
  {n:'223',name:'Grafaiai',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:45.00,base:false,important:true},
  {n:'224',name:'Orthworm',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:47.50,base:false},
  {n:'225',name:'Rookidee',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:40.00,base:false,important:true},
  {n:'226',name:'Maushold',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:89.00,base:false,important:true},
  {n:'227',name:'Flamigo',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:44.90,base:false,important:true},
  {n:'228',name:'Farigiraf',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:68.00,base:false,important:true},
  {n:'229',name:'Dudunsparce',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:24.90,base:false,important:true},
  {n:'230',name:'Forretress ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:9.90,base:false},
  {n:'231',name:'Meowscarada ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:21.25,base:false},
  {n:'232',name:'Wo-Chien ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:12.00,base:false},
  {n:'233',name:'Skeledirge ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:9.90,base:false},
  {n:'234',name:'Chi-Yu ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:15.90,base:false},
  {n:'235',name:'Quaquaval ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:12.00,base:false},
  {n:'236',name:'Chien-Pao ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:17.50,base:false},
  {n:'237',name:'Bellibolt ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:15.21,base:false},
  {n:'238',name:'Slowking ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:28.00,base:false},
  {n:'239',name:'Dedenne ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:105.00,base:false,important:true},
  {n:'240',name:'Tinkaton ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:33.89,base:false,important:true},
  {n:'241',name:'Lycanroc ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:17.00,base:false},
  {n:'242',name:'Annihilape ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:25.00,base:false},
  {n:'243',name:'Ting-Lu ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:7.75,base:false},
  {n:'244',name:'Paldean Clodsire ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:11.70,base:false},
  {n:'245',name:'Copperajah ex',type:'Metal',color:'#78909C',rare:'Ultra Rara',price:7.00,base:false},
  {n:'246',name:'Noivern ex',type:'Dragão',color:'#3F51B5',rare:'Ultra Rara',price:9.00,base:false},
  {n:'247',name:'Squawkabilly ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:9.41,base:false},
  {n:'248',name:'Boss\'s Orders (Ghetsis)',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:80.00,base:false,important:true},
  {n:'249',name:'Clavell',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8.00,base:false},
  {n:'250',name:'Dendra',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:19.90,base:false},
  // Cartas 251-279 completadas em 15/jul/2026 (generate_set.js tinha pageSize=250 sem
  // paginação — perdia o final do set, incluindo várias Special Illustration Rare).
  // Preços via api.pokemontcg.io, USD/BRL 5.8.
  {n:'251',name:'Falkner',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:9.90,base:false},
  {n:'252',name:'Giacomo',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:13.50,base:false},
  {n:'253',name:'Grusha',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:19.90,base:false},
  {n:'254',name:'Iono',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:52.90,base:false,important:true},
  {n:'255',name:'Saguaro',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8.00,base:false},
  {n:'256',name:'Meowscarada ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:129.90,base:false,important:true},
  {n:'257',name:'Wo-Chien ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:49.90,base:false,important:true},
  {n:'258',name:'Skeledirge ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:67.50,base:false,important:true},
  {n:'259',name:'Chi-Yu ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:144.50,base:false,important:true},
  {n:'260',name:'Quaquaval ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:44.90,base:false,important:true},
  {n:'261',name:'Chien-Pao ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:89.90,base:false,important:true},
  {n:'262',name:'Tinkaton ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:140.65,base:false,important:true},
  {n:'263',name:'Ting-Lu ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:35.00,base:false,important:true},
  {n:'264',name:'Squawkabilly ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:49.50,base:false,important:true},
  {n:'265',name:'Boss\'s Orders (Ghetsis)',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:169.90,base:false,important:true},
  {n:'266',name:'Dendra',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:39.00,base:false,important:true},
  {n:'267',name:'Giacomo',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:29.50,base:false},
  {n:'268',name:'Grusha',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:150.00,base:false,important:true},
  {n:'269',name:'Iono',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:250.00,base:false,important:true},
  {n:'270',name:'Saguaro',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:98.99,base:false,important:true},
  {n:'271',name:'Meowscarada ex',type:'Planta',color:'#4CAF50',rare:'Hiper Rara',price:29.99,base:false,important:true},
  {n:'272',name:'Skeledirge ex',type:'Fogo',color:'#F44336',rare:'Hiper Rara',price:34.90,base:false},
  {n:'273',name:'Quaquaval ex',type:'Aquático',color:'#2196F3',rare:'Hiper Rara',price:54.90,base:false},
  {n:'274',name:'Chien-Pao ex',type:'Aquático',color:'#2196F3',rare:'Hiper Rara',price:39.90,base:false},
  {n:'275',name:'Ting-Lu ex',type:'Lutador',color:'#FF9800',rare:'Hiper Rara',price:15.00,base:false},
  {n:'276',name:'Super Rod',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:35.00,base:false},
  {n:'277',name:'Superior Energy Retrieval',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:29.00,base:false},
  {n:'278',name:'Basic Grass Energy',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:39.90,base:false,important:true},
  {n:'279',name:'Basic Water Energy',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:89.90,base:false,important:true}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV2 = CARDS_SV2;