// SVP — Scarlet & Violet Promos (218 cartas cadastradas)
// Fonte: pokemontcg.io API (set.id:svp) + limitlesstcg.com/cards/SVP pra preencher gaps/cauda mais recente.
// Numeracao oficial tem buracos reais (190-192, 213-215 nao existem) — nao e erro de cadastro.
// ATENCAO: nomes em ingles, seguindo o mesmo padrao dos cards_sv*.js (nao traduzido).
// PRECOS ESTIMADOS por categoria (comum/ex/promo-personagem) — ainda NAO pesquisados
// individualmente na Liga/TCGplayer. Ajustar quando houver referencia real de mercado,
// mesmo padrao de aviso usado em cards_me06.js. Ver [[project_pokemon_tcg]].
const CARDS_SVP = [
  {n:'001',dex:906,artist:"Yuu Nishida",name:'Sprigatito',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'002',dex:909,artist:"Ryuta Fuse",name:'Fuecoco',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'003',dex:912,artist:"Narumi Sato",name:'Quaxly',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'004',dex:778,artist:"PLANETA Yamashita",name:'Mimikyu ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'005',dex:914,artist:"kodama",name:'Quaquaval',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'006',dex:922,artist:"GIDORA",name:'Pawmot',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'007',dex:701,artist:"Yuya Oka",name:'Hawlucha',type:'Lutador',color:'#FF9800',rare:'Promo',price:2.00,base:false},
  {n:'008',dex:966,artist:"DOM",name:'Revavroom',type:'Metal',color:'#78909C',rare:'Promo',price:2.00,base:false},
  {n:'009',dex:918,artist:"Anesaki Dynamic",name:'Spidops',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'010',dex:956,artist:"Sanosuke Sakuma",name:'Espathra',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'011',dex:59,artist:"Ryuta Fuse",name:'Arcanine',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'012',dex:977,artist:"Shin Nagasawa",name:'Dondozo',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'013',dex:1008,artist:"Akira Komayama",name:'Miraidon',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'014',dex:1007,artist:"Mina Nakai",name:'Koraidon',type:'Lutador',color:'#FF9800',rare:'Promo',price:2.00,base:false},
  {n:'015',dex:180,artist:"0313",name:'Flaaffy',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'016',dex:181,artist:"PLANETA Tsuji",name:'Ampharos ex',type:'Raio',color:'#FFEB3B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'017',dex:448,artist:"5ban Graphics",name:'Lucario ex',type:'Lutador',color:'#FF9800',rare:'Promo',price:18.00,base:false,important:true},
  {n:'018',dex:967,artist:"5ban Graphics",name:'Cyclizar ex',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:18.00,base:false,important:true},
  {n:'019',dex:998,artist:"Oswaldo KATO",name:'Baxcalibur',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'020',dex:959,artist:"Anesaki Dynamic",name:'Tinkaton',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'021',dex:198,artist:"Shiburingaru",name:'Murkrow',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'022',dex:279,artist:"Nisota Niso",name:'Pelipper',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'023',dex:928,artist:"Misa Tsutsui",name:'Smoliv',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'024',dex:58,artist:"Uta",name:'Growlithe',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'025',dex:957,artist:"Kouki Saitou",name:'Tinkatink',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'026',dex:965,artist:"Mina Nakai",name:'Varoom',type:'Metal',color:'#78909C',rare:'Promo',price:2.00,base:false},
  {n:'027',dex:25,artist:"Atsushi Furusawa",name:'Pikachu',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'028',dex:1008,artist:"5ban Graphics",name:'Miraidon ex',type:'Raio',color:'#FFEB3B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'029',dex:1007,artist:"aky CG Works",name:'Koraidon ex',type:'Lutador',color:'#FF9800',rare:'Promo',price:18.00,base:false,important:true},
  {n:'030',dex:1002,artist:"aky CG Works",name:'Chien-Pao ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'031',dex:959,artist:"takuyoa",name:'Tinkaton ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'032',dex:979,artist:"PLANETA Hiiragi",name:'Annihilape ex',type:'Lutador',color:'#FF9800',rare:'Promo',price:18.00,base:false,important:true},
  {n:'033',dex:908,artist:"5ban Graphics",name:'Meowscarada ex',type:'Planta',color:'#4CAF50',rare:'Promo',price:18.00,base:false,important:true},
  {n:'034',dex:911,artist:"5ban Graphics",name:'Skeledirge ex',type:'Fogo',color:'#F44336',rare:'Promo',price:18.00,base:false,important:true},
  {n:'035',dex:914,artist:"5ban Graphics",name:'Quaquaval ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'036',dex:964,artist:"nagimiso",name:'Palafin',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'037',dex:173,artist:"Mina Nakai",name:'Cleffa',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'038',dex:468,artist:"OKACHEKE",name:'Togekiss',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'039',dex:303,artist:"Souichirou Gunjima",name:'Mawile',type:'Metal',color:'#78909C',rare:'Promo',price:2.00,base:false},
  {n:'040',dex:921,artist:"Ryuta Fuse",name:'Pawmi',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'041',dex:194,artist:"kirisAki",name:'Paldean Wooper',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'042',dex:972,artist:"Pani Kobayashi",name:'Houndstone',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'043',dex:133,artist:"saino misaki",name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'044',dex:4,artist:"MINAMINAMI Take",name:'Charmander',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'045',artist:"Naoki Saito",name:'Paradise Resort',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:4.00,base:false},
  {n:'046',dex:1,artist:"OKACHEKE",name:'Bulbasaur',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'047',dex:4,artist:"NC Empire",name:'Charmander',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'048',dex:7,artist:"Gemi",name:'Squirtle',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'049',dex:145,artist:"takuyoa",name:'Zapdos ex',type:'Raio',color:'#FFEB3B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'050',dex:65,artist:"Mitsuhiro Arita",name:'Alakazam ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'051',dex:143,artist:"GOSSAN",name:'Snorlax',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'052',dex:150,artist:"Bun Toujo",name:'Mewtwo',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'053',dex:151,artist:"Natsumi Yoshida",name:'Mew ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'054',dex:658,artist:"takuyoa",name:'Greninja ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'055',dex:115,artist:"N-DESIGN Inc.",name:'Kangaskhan ex',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:18.00,base:false,important:true},
  {n:'056',dex:6,artist:"takuyoa",name:'Charizard ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'057',dex:1004,artist:"Dsuke",name:'Chi-Yu',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'058',dex:991,artist:"Lee HyunJung",name:'Iron Bundle',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'059',dex:178,artist:"GOSSAN",name:'Xatu',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'060',dex:681,artist:"Takeshi Nakamura",name:'Aegislash',type:'Metal',color:'#78909C',rare:'Promo',price:2.00,base:false},
  {n:'061',dex:204,artist:"Nobuhiro Imagawa",name:'Pineco',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'062',dex:854,artist:"kurumitsu",name:'Sinistea',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'063',dex:975,artist:"GOSSAN",name:'Cetitan',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'064',dex:997,artist:"Teeziro",name:'Arctibax',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'065',dex:985,artist:"GIDORA",name:'Scream Tail',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'066',dex:991,artist:"Teeziro",name:'Iron Bundle',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'067',dex:1005,artist:"takuyoa",name:'Roaring Moon ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'068',dex:1006,artist:"aky CG Works",name:'Iron Valiant ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'069',dex:926,artist:"sowsow",name:'Fidough',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'070',dex:971,artist:"Nisota Niso",name:'Greavard',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'071',dex:942,artist:"Kagemaru Himeno",name:'Maschiff',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'072',dex:984,artist:"5ban Graphics",name:'Great Tusk ex',type:'Lutador',color:'#FF9800',rare:'Promo',price:18.00,base:false,important:true},
  {n:'073',dex:990,artist:"5ban Graphics",name:'Iron Treads ex',type:'Metal',color:'#78909C',rare:'Promo',price:18.00,base:false,important:true},
  {n:'074',dex:6,artist:"5ban Graphics",name:'Charizard ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'075',dex:778,artist:"Mitsuhiro Arita",name:'Mimikyu',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'076',dex:906,artist:"kurumitsu",name:'Sprigatito',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'077',dex:907,artist:"GIDORA",name:'Floragato',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'078',dex:908,artist:"5ban Graphics",name:'Meowscarada ex',type:'Planta',color:'#4CAF50',rare:'Promo',price:18.00,base:false,important:true},
  {n:'079',dex:909,artist:"OKACHEKE",name:'Fuecoco',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'080',dex:910,artist:"Hideki Ishikawa",name:'Crocalor',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'081',dex:911,artist:"5ban Graphics",name:'Skeledirge ex',type:'Fogo',color:'#F44336',rare:'Promo',price:18.00,base:false,important:true},
  {n:'082',dex:912,artist:"GIDORA",name:'Quaxly',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'083',dex:913,artist:"Atsushi Furusawa",name:'Quaxwell',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'084',dex:914,artist:"5ban Graphics",name:'Quaquaval ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'085',dex:25,artist:"Naoyo Kimura",name:'Pikachu with Grey Felt Hat',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'086',dex:943,artist:"PLANETA Mochizuki",name:'Mabosstiff ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'087',dex:906,artist:"takuyoa",name:'Sprigatito ex',type:'Planta',color:'#4CAF50',rare:'Promo',price:18.00,base:false,important:true},
  {n:'088',dex:25,artist:"saino misaki",name:'Pikachu',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'089',dex:160,artist:"Kurata So",name:'Feraligatr',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'090',dex:375,artist:"Uta",name:'Metang',type:'Metal',color:'#78909C',rare:'Promo',price:2.00,base:false},
  {n:'091',dex:1007,artist:"Anesaki Dynamic",name:'Koraidon',type:'Dragão',color:'#3F51B5',rare:'Promo',price:2.00,base:false},
  {n:'092',dex:1008,artist:"akagi",name:'Miraidon',type:'Dragão',color:'#3F51B5',rare:'Promo',price:2.00,base:false},
  {n:'093',dex:318,artist:"Tonji Matsuno",name:'Carvanha',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'094',dex:939,artist:"Mizue",name:'Bellibolt',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'095',dex:173,artist:"Tika Matsuno",name:'Cleffa',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'096',dex:967,artist:"Hasuno",name:'Cyclizar',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'097',dex:987,artist:"Takumi Wada",name:'Flutter Mane',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'098',dex:995,artist:"Tonji Matsuno",name:'Iron Thorns',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'099',dex:944,artist:"Hitoshi Ariga",name:'Shroodle',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'100',dex:945,artist:"aky CG Works",name:'Grafaiai ex',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:18.00,base:false,important:true},
  {n:'101',dex:25,artist:"Jiro Sasumo",name:'Pikachu',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'102',dex:43,artist:"Miranda Branley",name:'Oddish',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'103',dex:229,artist:"PLANETA Tsuji",name:'Houndoom ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'104',dex:809,artist:"PLANETA Igarashi",name:'Melmetal ex',type:'Metal',color:'#78909C',rare:'Promo',price:18.00,base:false,important:true},
  {n:'105',dex:936,artist:"PLANETA Tsuji",name:'Armarouge ex',type:'Fogo',color:'#F44336',rare:'Promo',price:18.00,base:false,important:true},
  {n:'106',dex:25,artist:"takuyoa",name:'Pikachu ex',type:'Raio',color:'#FFEB3B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'107',dex:179,artist:"Orca",name:'Mareep',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'108',dex:180,artist:"Akira Komayama",name:'Flaaffy',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'109',dex:181,artist:"GIDORA",name:'Ampharos',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'110',dex:491,artist:"5ban Graphics",name:'Darkrai ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'111',dex:624,artist:"matazo",name:'Pawniard',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'112',dex:625,artist:"AKIRA EGAWA",name:'Bisharp',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'113',dex:983,artist:"nagimiso",name:'Kingambit',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'114',artist:"Susumu Maeya",name:'Picnicker',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:3.00,base:false},
  {n:'115',dex:811,artist:"Uninori",name:'Thwackey',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'116',dex:392,artist:"Kazumasa Yasukuni",name:'Infernape',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'117',dex:478,artist:"mingo",name:'Froslass',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'118',dex:978,artist:"Shimaris Yukichi",name:'Tatsugiri',type:'Dragão',color:'#3F51B5',rare:'Promo',price:2.00,base:false},
  {n:'119',dex:848,artist:"Natsumi Yoshida",name:'Toxel',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'120',dex:247,artist:"Shiburingaru",name:'Pupitar',type:'Lutador',color:'#FF9800',rare:'Promo',price:2.00,base:false},
  {n:'121',dex:966,artist:"Nisota Niso",name:'Revavroom',type:'Metal',color:'#78909C',rare:'Promo',price:2.00,base:false},
  {n:'122',dex:143,artist:"Po-Suzuki",name:'Snorlax',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'123',dex:1017,artist:"kodama",name:'Teal Mask Ogerpon',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'124',artist:"yuu",name:'Iono',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:8.00,base:false,important:true},
  {n:'125',dex:936,artist:"5ban Graphics",name:'Armarouge ex',type:'Fogo',color:'#F44336',rare:'Promo',price:18.00,base:false,important:true},
  {n:'126',dex:964,artist:"PLANETA Mochizuki",name:'Palafin ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'127',dex:1009,artist:"takuyoa",name:'Walking Wake ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'128',dex:1010,artist:"5ban Graphics",name:'Iron Leaves ex',type:'Planta',color:'#4CAF50',rare:'Promo',price:18.00,base:false,important:true},
  {n:'129',dex:1025,artist:"nagimiso",name:'Pecharunt',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'130',dex:983,artist:"Oku",name:'Kingambit',type:'Metal',color:'#78909C',rare:'Promo',price:2.00,base:false},
  {n:'131',dex:230,artist:"akagi",name:'Kingdra ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'132',dex:658,artist:"SIE NANAHARA",name:'Greninja ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'133',dex:166,artist:"Natsumi Yoshida",name:'Ledian',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'134',dex:740,artist:"KEIICHIRO ITO",name:'Crabominable',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'135',dex:426,artist:"Keisin",name:'Drifblim',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'136',dex:626,artist:"Tonji Matsuno",name:'Bouffalant',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'137',dex:116,artist:"MAHOU",name:'Horsea',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'138',dex:233,artist:"GOSSAN",name:'Porygon2',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'139',dex:380,artist:"hncl",name:'Latias',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'140',dex:959,artist:"DOM",name:'Tinkaton',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'141',dex:164,artist:"Tetsu Kayama",name:'Noctowl',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'142',dex:494,artist:"Saki Hayashiro",name:'Victini ex',type:'Fogo',color:'#F44336',rare:'Promo',price:18.00,base:false,important:true},
  {n:'143',dex:1008,artist:"5ban Graphics",name:'Miraidon ex',type:'Raio',color:'#FFEB3B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'144',artist:"PLANETA Mochizuki",name:'Gouging Fire ex',type:'Fogo',color:'#F44336',rare:'Promo',price:18.00,base:false,important:true},
  {n:'145',artist:"PLANETA Mochizuki",name:'Raging Bolt ex',type:'Dragão',color:'#3F51B5',rare:'Promo',price:18.00,base:false,important:true},
  {n:'146',artist:"5ban Graphics",name:'Iron Crown ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'147',artist:"5ban Graphics",name:'Iron Boulder ex',type:'Lutador',color:'#FF9800',rare:'Promo',price:18.00,base:false,important:true},
  {n:'148',dex:1008,artist:"hncl",name:'Miraidon',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'149',artist:"Souichirou Gunjima",name:'Pecharunt',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'150',artist:"Naoki Saito",name:'Paradise Resort',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:4.00,base:false},
  {n:'151',name:'Gouging Fire',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'152',dex:1002,name:'Chien-Pao',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'153',dex:82,name:'Magneton',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'154',dex:876,name:'Indeedee',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'155',dex:194,name:'Wooper',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'156',dex:195,name:'Quagsire',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'157',dex:145,name:'Zapdos',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'158',dex:417,name:'Pachirisu',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'159',dex:82,name:'Magneton',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'160',dex:931,name:'Squawkabilly ex',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:18.00,base:false,important:true},
  {n:'161',dex:6,name:'Charizard ex',type:'Fogo',color:'#F44336',rare:'Promo',price:18.00,base:false,important:true},
  {n:'162',dex:972,name:'Houndstone ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'163',dex:815,name:'Cinderace ex',type:'Fogo',color:'#F44336',rare:'Promo',price:18.00,base:false,important:true},
  {n:'164',dex:131,name:'Lapras ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'165',dex:1024,name:'Terapagos ex',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:18.00,base:false,important:true},
  {n:'166',dex:1017,artist:"5ban Graphics",name:'Teal Mask Ogerpon ex',type:'Planta',color:'#4CAF50',rare:'Promo',price:18.00,base:false,important:true},
  {n:'167',dex:136,artist:"SIE NANAHARA",name:'Flareon',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'168',dex:134,artist:"Taira Akitsu",name:'Vaporeon',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'169',dex:135,artist:"Nisota Niso",name:'Jolteon',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'170',dex:470,artist:"Iori Suzuki",name:'Leafeon',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'171',dex:471,artist:"Keisin",name:'Glaceon',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'172',dex:700,artist:"Susumu Maeya",name:'Sylveon',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'173',dex:133,artist:"Makura Tami",name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'174',dex:133,artist:"Natsuko Shoji été",name:'Eevee ex',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:18.00,base:false,important:true},
  {n:'175',name:'Espeon ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'176',name:'Umbreon ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'177',dex:901,artist:"aky CG Works",name:'Bloodmoon Ursaluna ex',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:18.00,base:false,important:true},
  {n:'178',dex:382,artist:"takuyoa",name:'Kyogre ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'179',dex:716,artist:"PLANETA Igarashi",name:'Xerneas ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'180',dex:483,artist:"PLANETA Tsuji",name:'Dialga ex',type:'Metal',color:'#78909C',rare:'Promo',price:18.00,base:false,important:true},
  {n:'181',dex:555,artist:"Takeshi Nakamura",name:'N\'s Darmanitan',type:'Fogo',color:'#F44336',rare:'Promo',price:14.00,base:false,important:true},
  {n:'182',dex:941,artist:"DOM",name:'Iono\'s Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Promo',price:14.00,base:false,important:true},
  {n:'183',dex:743,artist:"tono",name:'Lillie\'s Ribombee',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:14.00,base:false,important:true},
  {n:'184',dex:143,artist:"OKACHEKE",name:'Hop\'s Snorlax',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:14.00,base:false,important:true},
  {n:'185',dex:193,artist:"Dsuke",name:'Yanma',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'186',dex:559,artist:"OKUBO",name:'Scraggy',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'187',dex:469,artist:"Dsuke",name:'Yanmega',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'188',dex:560,artist:"OKUBO",name:'Scrafty',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'189',dex:570,artist:"Megumi Mizutani",name:'N\'s Zorua',type:'Sombrio',color:'#607D8B',rare:'Promo',price:14.00,base:false,important:true},
  {n:'193',dex:888,artist:"PLANETA Mochizuki",name:'Hop\'s Zacian ex',type:'Metal',color:'#78909C',rare:'Promo',price:38.00,base:false,important:true},
  {n:'194',dex:939,artist:"PLANETA Mochizuki",name:'Iono\'s Bellibolt ex',type:'Raio',color:'#FFEB3B',rare:'Promo',price:38.00,base:false,important:true},
  {n:'195',dex:35,artist:"PLANETA Tsuji",name:'Lillie\'s Clefairy ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:38.00,base:false,important:true},
  {n:'196',dex:6,artist:"5ban Graphics",name:'Charizard ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'197',dex:1007,artist:"PLANETA Tsuji",name:'Koraidon ex',type:'Lutador',color:'#FF9800',rare:'Promo',price:18.00,base:false,important:true},
  {n:'198',dex:888,artist:"PLANETA Mochizuki",name:'Zacian ex',type:'Metal',color:'#78909C',rare:'Promo',price:18.00,base:false,important:true},
  {n:'199',dex:893,artist:"Uninori",name:'Zarude',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'200',dex:133,artist:"Kariya",name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'201',dex:523,artist:"Krgc",name:'Zebstrika',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'202',dex:115,artist:"Uta",name:'Kangaskhan',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'203',dex:202,artist:"Saboteri",name:'Team Rocket\'s Wobbuffet',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:14.00,base:false,important:true},
  {n:'204',name:'Cynthia\'s Garchomp ex',type:'Lutador',color:'#FF9800',rare:'Promo',price:38.00,base:false,important:true},
  {n:'205',name:'Team Rocket\'s Mewtwo ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:38.00,base:false,important:true},
  {n:'206',dex:877,artist:"Susumu Maeya",name:'Marnie\'s Morpeko',type:'Sombrio',color:'#607D8B',rare:'Promo',price:14.00,base:false,important:true},
  {n:'207',dex:374,artist:"hncl",name:'Steven\'s Beldum',type:'Metal',color:'#78909C',rare:'Promo',price:14.00,base:false,important:true},
  {n:'208',name:'Victini',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'209',name:'Thundurus',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'210',name:'Tornadus',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'211',name:'Gothitelle',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'212',name:'Reuniclus',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'216',name:'Team Rocket\'s Mewtwo ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:38.00,base:false,important:true},
  {n:'217',name:'Team Rocket\'s Nidoking ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:38.00,base:false,important:true},
  {n:'218',name:'Team Rocket\'s Persian ex',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:38.00,base:false,important:true},
  {n:'219',name:'Black Belt\'s Training',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:3.00,base:false},
  {n:'220',name:'Black Belt\'s Training',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:3.00,base:false},
  {n:'221',name:'Professor\'s Research',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:1.50,base:false},
  {n:'222',name:'Professor\'s Research',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:1.50,base:false},
  {n:'223',name:'Professor\'s Research',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:1.50,base:false},
  {n:'224',name:'Paradise Resort',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:4.00,base:false},
];
