// SV6PT5 — Shrouded Fable (99 cartas)
// Lançamento EN: 2024/08/02
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV6PT5 = [
  {n:'001',name:'Joltik',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'002',name:'Galvantula',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.21,base:true},
  {n:'003',name:'Rowlet',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'004',name:'Dartrix',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'005',name:'Decidueye',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.15,base:true},
  {n:'006',name:'Tapu Bulu',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.50,base:true},
  {n:'007',name:'Houndour',type:'Fogo',color:'#F44336',rare:'Comum',price:0.15,base:true},
  {n:'008',name:'Houndoom',type:'Fogo',color:'#F44336',rare:'Comum',price:0.20,base:true},
  {n:'009',name:'Iron Moth',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.20,base:true},
  {n:'010',name:'Horsea',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.11,base:true},
  {n:'011',name:'Seadra',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.15,base:true},
  {n:'012',name:'Kingdra ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:4.00,base:true},
  {n:'013',name:'Sneasel',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.15,base:true},
  {n:'014',name:'Weavile',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.20,base:true},
  {n:'015',name:'Revavroom ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:2.99,base:true},
  {n:'016',name:'Drowzee',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'017',name:'Hypno',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'018',name:'Duskull',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.30,base:true},
  {n:'019',name:'Dusclops',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.26,base:true},
  {n:'020',name:'Dusknoir',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:2.50,base:true},
  {n:'021',name:'Cresselia',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.35,base:true},
  {n:'022',name:'Sylveon',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.30,base:true},
  {n:'023',name:'Croagunk',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'024',name:'Toxicroak',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.13,base:true},
  {n:'025',name:'Bloodmoon Ursaluna',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.35,base:true},
  {n:'026',name:'Slither Wing',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.10,base:true},
  {n:'027',name:'Zubat',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.11,base:true},
  {n:'028',name:'Golbat',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.20,base:true},
  {n:'029',name:'Crobat',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'030',name:'Absol',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.12,base:true},
  {n:'031',name:'Zorua',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.20,base:true},
  {n:'032',name:'Zoroark',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.45,base:true},
  {n:'033',name:'Inkay',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.11,base:true},
  {n:'034',name:'Malamar',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.18,base:true},
  {n:'035',name:'Yveltal',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'036',name:'Okidogi ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:4.90,base:true},
  {n:'037',name:'Munkidori ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:3.90,base:true},
  {n:'038',name:'Fezandipiti ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:12.99,base:true},
  {n:'039',name:'Pecharunt ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:34.90,base:true},
  {n:'040',name:'Genesect',type:'Metal',color:'#78909C',rare:'Incomum',price:0.20,base:true},
  {n:'041',name:'Cufant',type:'Metal',color:'#78909C',rare:'Comum',price:0.11,base:true},
  {n:'042',name:'Copperajah',type:'Metal',color:'#78909C',rare:'Rara',price:0.30,base:true},
  {n:'043',name:'Varoom',type:'Metal',color:'#78909C',rare:'Comum',price:0.09,base:true},
  {n:'044',name:'Axew',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.20,base:true},
  {n:'045',name:'Fraxure',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.20,base:true},
  {n:'046',name:'Haxorus',type:'Dragão',color:'#3F51B5',rare:'Rara',price:0.35,base:true},
  {n:'047',name:'Kyurem',type:'Dragão',color:'#3F51B5',rare:'Incomum',price:0.35,base:true},
  {n:'048',name:'Meowth',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'049',name:'Persian',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'050',name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'051',name:'Furfrou',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.11,base:true},
  {n:'052',name:'Stufful',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.18,base:true},
  {n:'053',name:'Bewear',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'054',name:'Academy at Night',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.40,base:true},
  {n:'055',name:'Binding Mochi',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.12,base:true},
  {n:'056',name:'Cassiopeia',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.17,base:true},
  {n:'057',name:'Colress\'s Tenacity',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.18,base:true},
  {n:'058',name:'Dangerous Laser',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:4.50,base:false},
  {n:'059',name:'Janine\'s Secret Art',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.18,base:true},
  {n:'060',name:'Neutralization Zone',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:14.00,base:false},
  {n:'061',name:'Night Stretcher',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.90,base:true},
  {n:'062',name:'Poké Vital A',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:7.50,base:false},
  {n:'063',name:'Powerglass',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'064',name:'Xerosic\'s Machinations',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.99,base:true},
  {n:'065',name:'Tapu Bulu',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:34.90,base:false,important:true},
  {n:'066',name:'Houndoom',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:67.00,base:false,important:true},
  {n:'067',name:'Horsea',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:139.99,base:false,important:true},
  {n:'068',name:'Duskull',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:120.00,base:false,important:true},
  {n:'069',name:'Dusclops',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:128.90,base:false,important:true},
  {n:'070',name:'Dusknoir',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:79.90,base:false,important:true},
  {n:'071',name:'Cresselia',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:55.00,base:false,important:true},
  {n:'072',name:'Munkidori',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:199.00,base:false,important:true},
  {n:'073',name:'Fezandipiti',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:39.50,base:false,important:true},
  {n:'074',name:'Okidogi',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:67.15,base:false,important:true},
  {n:'075',name:'Zorua',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:49.99,base:false,important:true},
  {n:'076',name:'Cufant',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:29.90,base:false,important:true},
  {n:'077',name:'Fraxure',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada',price:44.90,base:false,important:true},
  {n:'078',name:'Persian',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:99.50,base:false,important:true},
  {n:'079',name:'Bewear',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:29.50,base:false,important:true},
  {n:'080',name:'Kingdra ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:14.90,base:false},
  {n:'081',name:'Revavroom ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:6.90,base:false},
  {n:'082',name:'Okidogi ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:14.90,base:false},
  {n:'083',name:'Munkidori ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:8.85,base:false},
  {n:'084',name:'Fezandipiti ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:89.89,base:false,important:true},
  {n:'085',name:'Pecharunt ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:60.00,base:false},
  {n:'086',name:'Cassiopeia',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:22.00,base:false},
  {n:'087',name:'Colress\'s Tenacity',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:15.00,base:false},
  {n:'088',name:'Janine\'s Secret Art',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:43.00,base:false},
  {n:'089',name:'Xerosic\'s Machinations',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:68.00,base:false,important:true},
  {n:'090',name:'Okidogi ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:79.90,base:false,important:true},
  {n:'091',name:'Munkidori ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:49.90,base:false,important:true},
  {n:'092',name:'Fezandipiti ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:270.00,base:false,important:true},
  {n:'093',name:'Pecharunt ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:115.00,base:false,important:true},
  {n:'094',name:'Cassiopeia',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:144.90,base:false,important:true},
  {n:'095',name:'Pecharunt ex',type:'Sombrio',color:'#607D8B',rare:'Hiper Rara',price:99.90,base:false,important:true},
  {n:'096',name:'Earthen Vessel',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:109.95,base:false,important:true},
  {n:'097',name:'Powerglass',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:82.90,base:false,important:true},
  {n:'098',name:'Basic Darkness Energy',type:'Sombrio',color:'#607D8B',rare:'Hiper Rara',price:309.90,base:false,important:true},
  {n:'099',name:'Basic Metal Energy',type:'Metal',color:'#78909C',rare:'Hiper Rara',price:184.99,base:false,important:true}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV6PT5 = CARDS_SV6PT5;