// SV2 — Paldea Evolved (279 cartas)
// Lançamento EN: 2023/06/09
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV2 = [
  {n:'001',dex:187,artist:"Yukiko Baba",name:'Hoppip',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.16,base:true},
  {n:'002',dex:188,artist:"Yoriyuki Ikegami",name:'Skiploom',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.25,base:true},
  {n:'003',dex:189,artist:"Naoyo Kimura",name:'Jumpluff',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.45,base:true},
  {n:'004',dex:204,artist:"Kouki Saitou",name:'Pineco',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.16,base:true},
  {n:'005',dex:205,artist:"5ban Graphics",name:'Forretress ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:2.90,base:true},
  {n:'006',dex:214,artist:"GOSSAN",name:'Heracross',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.25,base:true},
  {n:'007',dex:357,artist:"Taira Akitsu",name:'Tropius',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.18,base:true},
  {n:'008',dex:415,artist:"Yoriyuki Ikegami",name:'Combee',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'009',dex:416,artist:"Megumi Higuchi",name:'Vespiquen',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'010',dex:459,artist:"Taira Akitsu",name:'Snover',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.13,base:true},
  {n:'011',dex:460,artist:"Ryuta Fuse",name:'Abomasnow',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.25,base:true},
  {n:'012',dex:906,artist:"Megumi Mizutani",name:'Sprigatito',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'013',dex:906,artist:"Naoyo Kimura",name:'Sprigatito',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.37,base:true},
  {n:'014',dex:907,artist:"nagimiso",name:'Floragato',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'015',dex:908,artist:"5ban Graphics",name:'Meowscarada ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.90,base:true},
  {n:'016',dex:917,artist:"Kyoko Umemoto",name:'Tarountula',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'017',dex:917,artist:"Mina Nakai",name:'Tarountula',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'018',dex:918,artist:"Oswaldo KATO",name:'Spidops',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.19,base:true},
  {n:'019',dex:919,artist:"Shin Nagasawa",name:'Nymble',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'020',dex:919,artist:"Sekio",name:'Nymble',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.16,base:true},
  {n:'021',dex:920,artist:"Anesaki Dynamic",name:'Lokix',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.19,base:true},
  {n:'022',dex:946,artist:"Pani Kobayashi",name:'Bramblin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.13,base:true},
  {n:'023',dex:946,artist:"Miki Tanaka",name:'Bramblin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'024',dex:947,artist:"KEIICHIRO ITO",name:'Brambleghast',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'025',dex:953,artist:"Kouki Saitou",name:'Rellor',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'026',dex:953,artist:"Anesaki Dynamic",name:'Rellor',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'027',dex:1001,artist:"5ban Graphics",name:'Wo-Chien ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:1.90,base:true},
  {n:'028',dex:128,artist:"AKIRA EGAWA",name:'Paldean Tauros',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.18,base:true},
  {n:'029',dex:662,artist:"kurumitsu",name:'Fletchinder',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.15,base:true},
  {n:'030',dex:663,artist:"Nisota Niso",name:'Talonflame',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.17,base:true},
  {n:'031',dex:667,artist:"Yuu Nishida",name:'Litleo',type:'Fogo',color:'#F44336',rare:'Comum',price:0.13,base:true},
  {n:'032',dex:668,artist:"Uta",name:'Pyroar',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.20,base:true},
  {n:'033',dex:741,artist:"Haru Akasaka",name:'Oricorio',type:'Fogo',color:'#F44336',rare:'Rara',price:0.19,base:true},
  {n:'034',dex:909,artist:"Kagemaru Himeno",name:'Fuecoco',type:'Fogo',color:'#F44336',rare:'Comum',price:0.25,base:true},
  {n:'035',dex:909,artist:"ryoma uratsuka",name:'Fuecoco',type:'Fogo',color:'#F44336',rare:'Comum',price:0.25,base:true},
  {n:'036',dex:910,artist:"Hitoshi Ariga",name:'Crocalor',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.23,base:true},
  {n:'037',dex:911,artist:"5ban Graphics",name:'Skeledirge ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:3.75,base:true},
  {n:'038',dex:935,artist:"takuyoa",name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.20,base:true},
  {n:'039',dex:935,artist:"KEIICHIRO ITO",name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.17,base:true},
  {n:'040',dex:1004,artist:"5ban Graphics",name:'Chi-Yu ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:3.50,base:true},
  {n:'041',dex:128,artist:"Oswaldo KATO",name:'Paldean Tauros',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.23,base:true},
  {n:'042',dex:129,artist:"HYOGONOSUKE",name:'Magikarp',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'043',dex:130,artist:"Yuya Oka",name:'Gyarados',type:'Aquático',color:'#2196F3',rare:'Rara',price:1.00,base:true},
  {n:'044',dex:183,artist:"saino misaki",name:'Marill',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'045',dex:184,artist:"En Morikura",name:'Azumarill',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.15,base:true},
  {n:'046',dex:225,artist:"miki kudo",name:'Delibird',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'047',dex:370,artist:"ryoma uratsuka",name:'Luvdisc',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'048',dex:875,artist:"kawayoo",name:'Eiscue',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.15,base:true},
  {n:'049',dex:912,artist:"sui",name:'Quaxly',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'050',dex:912,artist:"Naoki Saito",name:'Quaxly',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.25,base:true},
  {n:'051',dex:913,artist:"Souichirou Gunjima",name:'Quaxwell',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.20,base:true},
  {n:'052',dex:914,artist:"5ban Graphics",name:'Quaquaval ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:4.75,base:true},
  {n:'053',dex:974,artist:"Sekio",name:'Cetoddle',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.17,base:true},
  {n:'054',dex:974,artist:"Saya Tsuruta",name:'Cetoddle',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'055',dex:975,artist:"Pani Kobayashi",name:'Cetitan',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.20,base:true},
  {n:'056',dex:976,artist:"Anesaki Dynamic",name:'Veluza',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.20,base:true},
  {n:'057',dex:996,artist:"Akira Komayama",name:'Frigibax',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.17,base:true},
  {n:'058',dex:996,artist:"AKIRA EGAWA",name:'Frigibax',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.17,base:true},
  {n:'059',dex:997,artist:"Kouki Saitou",name:'Arctibax',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.25,base:true},
  {n:'060',dex:998,artist:"Shin Nagasawa",name:'Baxcalibur',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.40,base:true},
  {n:'061',dex:1002,artist:"aky CG Works",name:'Chien-Pao ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:5.00,base:true},
  {n:'062',dex:25,artist:"OKACHEKE",name:'Pikachu',type:'Raio',color:'#FFEB3B',rare:'Comum',price:1.00,base:true},
  {n:'063',dex:25,artist:"N-DESIGN Inc.",name:'Pikachu ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:27.00,base:true},
  {n:'064',dex:26,artist:"Teeziro",name:'Raichu',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.45,base:true},
  {n:'065',dex:81,artist:"ryoma uratsuka",name:'Magnemite',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.20,base:true},
  {n:'066',dex:100,artist:"sui",name:'Voltorb',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'067',dex:101,artist:"Scav",name:'Electrode',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.20,base:true},
  {n:'068',dex:403,artist:"kurumitsu",name:'Shinx',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.19,base:true},
  {n:'069',dex:403,artist:"Oswaldo KATO",name:'Shinx',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.20,base:true},
  {n:'070',dex:404,artist:"Narumi Sato",name:'Luxio',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.23,base:true},
  {n:'071',dex:405,artist:"aoki",name:'Luxray',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.30,base:true},
  {n:'072',dex:871,artist:"Yuka Morii",name:'Pincurchin',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.21,base:true},
  {n:'073',dex:871,artist:"miki kudo",name:'Pincurchin',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.13,base:true},
  {n:'074',dex:921,artist:"sowsow",name:'Pawmi',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.19,base:true},
  {n:'075',dex:922,artist:"Hitoshi Ariga",name:'Pawmo',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.19,base:true},
  {n:'076',dex:922,artist:"kodama",name:'Pawmot',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.35,base:true},
  {n:'077',dex:938,artist:"Pani Kobayashi",name:'Tadbulb',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.13,base:true},
  {n:'078',dex:938,artist:"Tika Matsuno",name:'Tadbulb',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.10,base:true},
  {n:'079',dex:939,artist:"PLANETA Yamashita",name:'Bellibolt ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:4.20,base:true},
  {n:'080',dex:940,artist:"Shibuzoh.",name:'Wattrel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.35,base:true},
  {n:'081',dex:940,artist:"sowsow",name:'Wattrel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.20,base:true},
  {n:'082',dex:941,artist:"Pani Kobayashi",name:'Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.17,base:true},
  {n:'083',dex:39,artist:"Yuu Nishida",name:'Jigglypuff',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.25,base:true},
  {n:'084',dex:40,artist:"Hitoshi Ariga",name:'Wigglytuff',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.80,base:true},
  {n:'085',dex:79,artist:"sowsow",name:'Slowpoke',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.25,base:true},
  {n:'086',dex:199,artist:"5ban Graphics",name:'Slowking ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:5.10,base:true},
  {n:'087',dex:200,artist:"Megumi Higuchi",name:'Misdreavus',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'088',dex:429,artist:"Atsushi Furusawa",name:'Mismagius',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.23,base:true},
  {n:'089',dex:442,artist:"Aya Kusube",name:'Spiritomb',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.25,base:true},
  {n:'090',dex:574,artist:"0313",name:'Gothita',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.17,base:true},
  {n:'091',dex:575,artist:"Aya Kusube",name:'Gothorita',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.17,base:true},
  {n:'092',dex:576,artist:"Shiburingaru",name:'Gothitelle',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.25,base:true},
  {n:'093',dex:702,artist:"aky CG Works",name:'Dedenne ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:4.90,base:true},
  {n:'094',dex:765,artist:"Toshinao Aoki",name:'Oranguru',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.19,base:true},
  {n:'095',dex:769,artist:"Shin Nagasawa",name:'Sandygast',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'096',dex:770,artist:"HYOGONOSUKE",name:'Palossand',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.25,base:true},
  {n:'097',dex:778,artist:"Kagemaru Himeno",name:'Mimikyu',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.49,base:true},
  {n:'098',dex:937,artist:"Ryota Murayama",name:'Ceruledge',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.25,base:true},
  {n:'099',dex:954,artist:"Oswaldo KATO",name:'Rabsca',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.21,base:true},
  {n:'100',dex:957,artist:"Mizue",name:'Tinkatink',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.17,base:true},
  {n:'101',dex:957,artist:"Shibuzoh.",name:'Tinkatink',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'102',dex:957,artist:"Pani Kobayashi",name:'Tinkatink',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'103',dex:958,artist:"Akira Komayama",name:'Tinkatuff',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.21,base:true},
  {n:'104',dex:958,artist:"sowsow",name:'Tinkatuff',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.40,base:true},
  {n:'105',dex:959,artist:"Kouki Saitou",name:'Tinkaton',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.45,base:true},
  {n:'106',dex:56,artist:"kurumitsu",name:'Mankey',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.16,base:true},
  {n:'107',dex:57,artist:"Shin Nagasawa",name:'Primeape',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.23,base:true},
  {n:'108',dex:128,artist:"Shin Nagasawa",name:'Paldean Tauros',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.25,base:true},
  {n:'109',dex:185,artist:"Jerky",name:'Sudowoodo',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'110',dex:246,artist:"Haru Akasaka",name:'Larvitar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.19,base:true},
  {n:'111',dex:247,artist:"Shigenori Negishi",name:'Pupitar',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'112',dex:296,artist:"Kurata So",name:'Makuhita',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'113',dex:297,artist:"Hasuno",name:'Hariyama',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.34,base:true},
  {n:'114',dex:453,artist:"kawayoo",name:'Croagunk',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.09,base:true},
  {n:'115',dex:454,artist:"Yuya Oka",name:'Toxicroak',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.15,base:true},
  {n:'116',dex:744,artist:"0313",name:'Rockruff',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'117',dex:745,artist:"kawayoo",name:'Lycanroc ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:5.90,base:true},
  {n:'118',dex:766,artist:"Jerky",name:'Passimian',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.17,base:true},
  {n:'119',dex:870,artist:"kurumitsu",name:'Falinks',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.09,base:true},
  {n:'120',dex:932,artist:"yuu",name:'Nacli',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'121',dex:932,artist:"Shin Nagasawa",name:'Nacli',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'122',dex:933,artist:"GIDORA",name:'Naclstack',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'123',dex:934,artist:"Anesaki Dynamic",name:'Garganacl',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.09,base:true},
  {n:'124',dex:969,artist:"Mizue",name:'Glimmet',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.20,base:true},
  {n:'125',dex:969,artist:"Sekio",name:'Glimmet',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.20,base:true},
  {n:'126',dex:970,artist:"Shin Nagasawa",name:'Glimmora',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.49,base:true},
  {n:'127',dex:1003,artist:"5ban Graphics",name:'Ting-Lu ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:4.00,base:true},
  {n:'128',dex:194,artist:"Kouki Saitou",name:'Paldean Wooper',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.23,base:true},
  {n:'129',dex:194,artist:"Saya Tsuruta",name:'Paldean Wooper',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.25,base:true},
  {n:'130',dex:980,artist:"PLANETA Mochizuki",name:'Paldean Clodsire ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:5.00,base:true},
  {n:'131',dex:198,artist:"Teeziro",name:'Murkrow',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'132',dex:430,artist:"Nisota Niso",name:'Honchkrow',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'133',dex:215,artist:"Kagemaru Himeno",name:'Sneasel',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.17,base:true},
  {n:'134',dex:461,artist:"saino misaki",name:'Weavile',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.30,base:true},
  {n:'135',dex:248,artist:"hncl",name:'Tyranitar',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.68,base:true},
  {n:'136',dex:302,artist:"Nagomi Nijo",name:'Sableye',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.35,base:true},
  {n:'137',dex:336,artist:"Nisota Niso",name:'Seviper',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.12,base:true},
  {n:'138',dex:633,artist:"Narumi Sato",name:'Deino',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'139',dex:634,artist:"nagimiso",name:'Zweilous',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.23,base:true},
  {n:'140',dex:635,artist:"Teeziro",name:'Hydreigon',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.80,base:true},
  {n:'141',dex:942,artist:"DOM",name:'Maschiff',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'142',dex:942,artist:"Shibuzoh.",name:'Maschiff',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.20,base:true},
  {n:'143',dex:943,artist:"Souichirou Gunjima",name:'Mabosstiff',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.17,base:true},
  {n:'144',dex:944,artist:"Akira Komayama",name:'Shroodle',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.16,base:true},
  {n:'145',dex:944,artist:"Anesaki Dynamic",name:'Shroodle',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'146',dex:945,artist:"Souichirou Gunjima",name:'Grafaiai',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'147',dex:962,artist:"Sekio",name:'Bombirdier',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'148',dex:823,artist:"Scav",name:'Corviknight',type:'Metal',color:'#78909C',rare:'Incomum',price:0.20,base:true},
  {n:'149',dex:878,artist:"Oswaldo KATO",name:'Cufant',type:'Metal',color:'#78909C',rare:'Comum',price:0.19,base:true},
  {n:'150',dex:879,artist:"Uta",name:'Copperajah ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:4.90,base:true},
  {n:'151',dex:968,artist:"Hitoshi Ariga",name:'Orthworm',type:'Metal',color:'#78909C',rare:'Rara',price:0.30,base:true},
  {n:'152',dex:714,artist:"chibi",name:'Noibat',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.09,base:true},
  {n:'153',dex:715,artist:"Nisota Niso",name:'Noivern ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:4.90,base:true},
  {n:'154',dex:203,artist:"kirisAki",name:'Girafarig',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'155',dex:981,artist:"Kouki Saitou",name:'Farigiraf',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.17,base:true},
  {n:'156',dex:206,artist:"Nagomi Nijo",name:'Dunsparce',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.45,base:true},
  {n:'157',dex:982,artist:"Mina Nakai",name:'Dudunsparce',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'158',dex:278,artist:"Kouki Saitou",name:'Wingull',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.13,base:true},
  {n:'159',dex:279,artist:"Shinya Komatsu",name:'Pelipper',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'160',dex:287,artist:"Shigenori Negishi",name:'Slakoth',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'161',dex:288,artist:"GIDORA",name:'Vigoroth',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'162',dex:289,artist:"Yuya Oka",name:'Slaking',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.35,base:true},
  {n:'163',dex:661,artist:"sui",name:'Fletchling',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.09,base:true},
  {n:'164',dex:821,artist:"Naoki Saito",name:'Rookidee',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'165',dex:822,artist:"sui",name:'Corvisquire',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'166',dex:924,artist:"Oswaldo KATO",name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.25,base:true},
  {n:'167',dex:924,artist:"Sekio",name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.25,base:true},
  {n:'168',dex:925,artist:"Saya Tsuruta",name:'Maushold',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.45,base:true},
  {n:'169',dex:931,artist:"PLANETA Mochizuki",name:'Squawkabilly ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:4.00,base:true},
  {n:'170',dex:973,artist:"nagimiso",name:'Flamigo',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'171',artist:"Oswaldo KATO",name:'Artazon',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'172',artist:"NC Empire",name:'Boss\'s Orders (Ghetsis)',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.20,base:true},
  {n:'173',artist:"Toyste Beach",name:'Bravery Charm',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.50,base:true},
  {n:'174',artist:"AYUMI ODASHIMA",name:'Calamitous Snowy Mountain',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.50,base:true},
  {n:'175',artist:"AYUMI ODASHIMA",name:'Calamitous Wasteland',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.19,base:true},
  {n:'176',artist:"Studio Bora Inc.",name:'Choice Belt',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'177',artist:"Hitoshi Ariga",name:'Clavell',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.19,base:true},
  {n:'178',artist:"inose yukie",name:'Delivery Drone',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.19,base:true},
  {n:'179',artist:"yuu",name:'Dendra',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'180',artist:"Ryuta Fuse",name:'Falkner',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.19,base:true},
  {n:'181',artist:"Ayaka Yoshida",name:'Fighting Au Lait',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.19,base:true},
  {n:'182',artist:"Akira Komayama",name:'Giacomo',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.18,base:true},
  {n:'183',artist:"Studio Bora Inc.",name:'Great Ball',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'184',artist:"GIDORA",name:'Grusha',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'185',artist:"Sanosuke Sakuma",name:'Iono',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.17,base:true},
  {n:'186',artist:"AYUMI ODASHIMA",name:'Practice Studio',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'187',artist:"nagimiso",name:'Saguaro',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'188',artist:"Toyste Beach",name:'Super Rod',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.19,base:true},
  {n:'189',artist:"Studio Bora Inc.",name:'Superior Energy Retrieval',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.50,base:true},
  {n:'190',name:'Jet Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.50,base:true},
  {n:'191',name:'Luminous Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.50,base:true},
  {n:'192',name:'Reversal Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.30,base:true},
  {n:'193',name:'Therapeutic Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.30,base:true},
  {n:'194',dex:214,artist:"Kurata So",name:'Heracross',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:60.00,base:false,important:true},
  {n:'195',dex:357,artist:"Jerky",name:'Tropius',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:59.90,base:false,important:true},
  {n:'196',dex:906,artist:"Kouki Saitou",name:'Sprigatito',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:175.00,base:false,important:true},
  {n:'197',dex:907,artist:"Kouki Saitou",name:'Floragato',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:84.90,base:false,important:true},
  {n:'198',dex:946,artist:"sowsow",name:'Bramblin',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:46.99,base:false,important:true},
  {n:'199',dex:662,artist:"Atsushi Furusawa",name:'Fletchinder',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:120.00,base:false,important:true},
  {n:'200',dex:668,artist:"Po-Suzuki",name:'Pyroar',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:34.00,base:false,important:true},
  {n:'201',dex:909,artist:"kantaro",name:'Fuecoco',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:199.90,base:false,important:true},
  {n:'202',dex:910,artist:"kantaro",name:'Crocalor',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:41.80,base:false,important:true},
  {n:'203',dex:129,artist:"Shinji Kanda",name:'Magikarp',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:939.00,base:false,important:true},
  {n:'204',dex:183,artist:"Atsuya Uki",name:'Marill',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:89.00,base:false,important:true},
  {n:'205',dex:875,artist:"Nelnal",name:'Eiscue',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:37.99,base:false,important:true},
  {n:'206',dex:912,artist:"Souichirou Gunjima",name:'Quaxly',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:130.00,base:false,important:true},
  {n:'207',dex:913,artist:"Souichirou Gunjima",name:'Quaxwell',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:79.90,base:false,important:true},
  {n:'208',dex:996,artist:"Tomokazu Komiya",name:'Frigibax',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:39.99,base:false,important:true},
  {n:'209',dex:997,artist:"Tomokazu Komiya",name:'Arctibax',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:67.40,base:false,important:true},
  {n:'210',dex:998,artist:"Tomokazu Komiya",name:'Baxcalibur',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:49.90,base:false,important:true},
  {n:'211',dex:26,artist:"Toshinao Aoki",name:'Raichu',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:269.90,base:false,important:true},
  {n:'212',dex:429,artist:"aoki",name:'Mismagius',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:209.90,base:false,important:true},
  {n:'213',dex:575,artist:"SIE NANAHARA",name:'Gothorita',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:79.90,base:false,important:true},
  {n:'214',dex:769,artist:"Teeziro",name:'Sandygast',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:34.90,base:false,important:true},
  {n:'215',dex:954,artist:"nagimiso",name:'Rabsca',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:21.99,base:false},
  {n:'216',dex:957,artist:"Tika Matsuno",name:'Tinkatink',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:89.90,base:false,important:true},
  {n:'217',dex:958,artist:"Tika Matsuno",name:'Tinkatuff',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:59.50,base:false,important:true},
  {n:'218',dex:128,artist:"Anesaki Dynamic",name:'Paldean Tauros',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:50.00,base:false,important:true},
  {n:'219',dex:185,artist:"Narumi Sato",name:'Sudowoodo',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:55.00,base:false,important:true},
  {n:'220',dex:932,artist:"Ryota Murayama",name:'Nacli',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:29.90,base:false},
  {n:'221',dex:194,artist:"Miki Tanaka",name:'Paldean Wooper',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:40.00,base:false,important:true},
  {n:'222',dex:248,artist:"Nurikabe",name:'Tyranitar',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:99.50,base:false,important:true},
  {n:'223',dex:945,artist:"Oswaldo KATO",name:'Grafaiai',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:45.00,base:false,important:true},
  {n:'224',dex:968,artist:"OKACHEKE",name:'Orthworm',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:47.50,base:false},
  {n:'225',dex:821,artist:"GOSSAN",name:'Rookidee',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:24.99,base:false,important:true},
  {n:'226',dex:925,artist:"Mizue",name:'Maushold',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:200.00,base:false,important:true},
  {n:'227',dex:973,artist:"Shibuzoh.",name:'Flamigo',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:44.90,base:false,important:true},
  {n:'228',dex:981,artist:"Mina Nakai",name:'Farigiraf',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:79.90,base:false,important:true},
  {n:'229',dex:982,artist:"Saya Tsuruta",name:'Dudunsparce',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:24.90,base:false,important:true},
  {n:'230',dex:205,artist:"5ban Graphics",name:'Forretress ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:6.75,base:false},
  {n:'231',dex:908,artist:"5ban Graphics",name:'Meowscarada ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:19.90,base:false},
  {n:'232',dex:1001,artist:"5ban Graphics",name:'Wo-Chien ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:11.75,base:false},
  {n:'233',dex:911,artist:"5ban Graphics",name:'Skeledirge ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:9.90,base:false},
  {n:'234',dex:1004,artist:"PLANETA Yamashita",name:'Chi-Yu ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:15.90,base:false},
  {n:'235',dex:914,artist:"5ban Graphics",name:'Quaquaval ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:14.95,base:false},
  {n:'236',dex:1002,artist:"aky CG Works",name:'Chien-Pao ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:17.50,base:false},
  {n:'237',dex:939,artist:"PLANETA Yamashita",name:'Bellibolt ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:16.90,base:false},
  {n:'238',dex:199,artist:"5ban Graphics",name:'Slowking ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:28.00,base:false},
  {n:'239',dex:702,artist:"aky CG Works",name:'Dedenne ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:89.50,base:false,important:true},
  {n:'240',dex:959,artist:"takuyoa",name:'Tinkaton ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:33.89,base:false,important:true},
  {n:'241',dex:745,artist:"Ayaka Yoshida",name:'Lycanroc ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:17.99,base:false},
  {n:'242',dex:979,artist:"PLANETA Hiiragi",name:'Annihilape ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:19.50,base:false},
  {n:'243',dex:1003,artist:"5ban Graphics",name:'Ting-Lu ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:7.75,base:false},
  {n:'244',dex:980,artist:"PLANETA Mochizuki",name:'Paldean Clodsire ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:11.70,base:false},
  {n:'245',dex:879,artist:"Eske Yoshinob",name:'Copperajah ex',type:'Metal',color:'#78909C',rare:'Ultra Rara',price:7.00,base:false},
  {n:'246',dex:715,artist:"Eske Yoshinob",name:'Noivern ex',type:'Dragão',color:'#3F51B5',rare:'Ultra Rara',price:8.55,base:false},
  {n:'247',dex:931,artist:"PLANETA Mochizuki",name:'Squawkabilly ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8.75,base:false},
  {n:'248',artist:"Hideki Ishikawa",name:'Boss\'s Orders (Ghetsis)',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:99.90,base:false,important:true},
  {n:'249',artist:"Sanosuke Sakuma",name:'Clavell',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8.00,base:false},
  {n:'250',artist:"yuu",name:'Dendra',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:21.00,base:false},
  // Cartas 251-279 completadas em 15/jul/2026 (generate_set.js tinha pageSize=250 sem
  // paginação — perdia o final do set, incluindo várias Special Illustration Rare).
  // Preços via api.pokemontcg.io, USD/BRL 5.8.
  {n:'251',artist:"Ryuta Fuse",name:'Falkner',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:9.90,base:false},
  {n:'252',artist:"kantaro",name:'Giacomo',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8.90,base:false},
  {n:'253',artist:"GIDORA",name:'Grusha',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:15.00,base:false},
  {n:'254',artist:"Sanosuke Sakuma",name:'Iono',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:50.00,base:false,important:true},
  {n:'255',artist:"nagimiso",name:'Saguaro',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8.00,base:false},
  {n:'256',dex:908,artist:"Kouki Saitou",name:'Meowscarada ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:129.90,base:false,important:true},
  {n:'257',dex:1001,artist:"takuyoa",name:'Wo-Chien ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:57.00,base:false,important:true},
  {n:'258',dex:911,artist:"kantaro",name:'Skeledirge ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:71.25,base:false,important:true},
  {n:'259',dex:1004,artist:"AKIRA EGAWA",name:'Chi-Yu ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:99.75,base:false,important:true},
  {n:'260',dex:914,artist:"Souichirou Gunjima",name:'Quaquaval ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:47.00,base:false,important:true},
  {n:'261',dex:1002,artist:"kodama",name:'Chien-Pao ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:89.50,base:false,important:true},
  {n:'262',dex:959,artist:"Tika Matsuno",name:'Tinkaton ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:148.05,base:false,important:true},
  {n:'263',dex:1003,artist:"KEIICHIRO ITO",name:'Ting-Lu ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:35.00,base:false,important:true},
  {n:'264',dex:931,artist:"Amelicart",name:'Squawkabilly ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:49.50,base:false,important:true},
  {n:'265',artist:"hncl",name:'Boss\'s Orders (Ghetsis)',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:149.90,base:false,important:true},
  {n:'266',artist:"GIDORA",name:'Dendra',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:47.41,base:false,important:true},
  {n:'267',artist:"KIYOTAKA OSHIYAMA",name:'Giacomo',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:29.50,base:false},
  {n:'268',artist:"DOM",name:'Grusha',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:168.00,base:false,important:true},
  {n:'269',artist:"kirisAki",name:'Iono',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:250.00,base:false,important:true},
  {n:'270',artist:"Sanosuke Sakuma",name:'Saguaro',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:64.90,base:false,important:true},
  {n:'271',dex:908,artist:"5ban Graphics",name:'Meowscarada ex',type:'Planta',color:'#4CAF50',rare:'Hiper Rara',price:29.99,base:false,important:true},
  {n:'272',dex:911,artist:"5ban Graphics",name:'Skeledirge ex',type:'Fogo',color:'#F44336',rare:'Hiper Rara',price:34.90,base:false},
  {n:'273',dex:914,artist:"5ban Graphics",name:'Quaquaval ex',type:'Aquático',color:'#2196F3',rare:'Hiper Rara',price:49.99,base:false},
  {n:'274',dex:1002,artist:"aky CG Works",name:'Chien-Pao ex',type:'Aquático',color:'#2196F3',rare:'Hiper Rara',price:39.90,base:false},
  {n:'275',dex:1003,artist:"5ban Graphics",name:'Ting-Lu ex',type:'Lutador',color:'#FF9800',rare:'Hiper Rara',price:15.00,base:false},
  {n:'276',artist:"Toyste Beach",name:'Super Rod',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:31.99,base:false},
  {n:'277',artist:"Studio Bora Inc.",name:'Superior Energy Retrieval',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:29.00,base:false},
  {n:'278',name:'Basic Grass Energy',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:39.90,base:false,important:true},
  {n:'279',name:'Basic Water Energy',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:89.90,base:false,important:true}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV2 = CARDS_SV2;