// ME03 — Ordem Perfeita (Perfect Order) — 120 cartas
// Lancamento EN: 27 mar 2026 | PT-BR: previsto abr/mai 2026
// Tema: Mega Zygarde ex, Mega Clefable ex, Mega Starmie ex
const CARDS_ME03 = [
  // ── BASE 001–070 ─────────────────────────────────────────
  {n:'001',name:'Caterpie',       type:'Grama',  color:'#4CAF50',rare:'Comum',      price:.40,base:true},
  {n:'002',name:'Metapod',        type:'Grama',  color:'#4CAF50',rare:'Comum',      price:.40,base:true},
  {n:'003',name:'Butterfree',     type:'Grama',  color:'#4CAF50',rare:'Incomum',    price:.55,base:true},
  {n:'004',name:'Tangela',        type:'Grama',  color:'#4CAF50',rare:'Comum',      price:.40,base:true},
  {n:'005',name:'Tangrowth',      type:'Grama',  color:'#4CAF50',rare:'Incomum',    price:.60,base:true},
  {n:'006',name:'Carnivine',      type:'Grama',  color:'#4CAF50',rare:'Comum',      price:.45,base:true},
  {n:'007',name:'Lickitung',      type:'Incolor',color:'#9E9E9E',rare:'Comum',      price:.40,base:true},
  {n:'008',name:'Lickilicky',     type:'Incolor',color:'#9E9E9E',rare:'Incomum',    price:.55,base:true},
  {n:'009',name:'Wooper',         type:'Agua',   color:'#2196F3',rare:'Comum',      price:.40,base:true},
  {n:'010',name:'Quagsire',       type:'Agua',   color:'#2196F3',rare:'Incomum',    price:.60,base:true},
  {n:'011',name:'Slowpoke',       type:'Agua',   color:'#2196F3',rare:'Comum',      price:.40,base:true},
  {n:'012',name:'Slowbro',        type:'Agua',   color:'#2196F3',rare:'Incomum',    price:.55,base:true},
  {n:'013',name:'Slowking',       type:'Agua',   color:'#2196F3',rare:'Incomum',    price:.60,base:true},
  {n:'014',name:'Staryu',         type:'Agua',   color:'#2196F3',rare:'Comum',      price:.40,base:true},
  {n:'015',name:'Starmie',        type:'Agua',   color:'#2196F3',rare:'Incomum',    price:.70,base:true},
  {n:'016',name:'Magikarp',       type:'Agua',   color:'#2196F3',rare:'Comum',      price:.45,base:true},
  {n:'017',name:'Gyarados',       type:'Agua',   color:'#2196F3',rare:'Incomum',    price:.80,base:true},
  {n:'018',name:'Phanpy',         type:'Luta',   color:'#FF6B35',rare:'Comum',      price:.40,base:true},
  {n:'019',name:'Donphan',        type:'Luta',   color:'#FF6B35',rare:'Incomum',    price:.60,base:true},
  {n:'020',name:'Goomy',          type:'Dragao', color:'#673AB7',rare:'Comum',      price:.45,base:true},
  {n:'021',name:'Sliggoo',        type:'Dragao', color:'#673AB7',rare:'Incomum',    price:.60,base:true},
  {n:'022',name:'Goodra',         type:'Dragao', color:'#673AB7',rare:'Incomum',    price:.80,base:true},
  {n:'023',name:'Zygarde 10%',    type:'Dragao', color:'#673AB7',rare:'Comum',      price:.50,base:true},
  {n:'024',name:'Zygarde 50%',    type:'Dragao', color:'#673AB7',rare:'Incomum',    price:.70,base:true},
  {n:'025',name:'Clefairy',       type:'Fada',   color:'#E91E9E',rare:'Comum',      price:.45,base:true},
  {n:'026',name:'Clefable',       type:'Fada',   color:'#E91E9E',rare:'Incomum',    price:.70,base:true},
  {n:'027',name:'Snubbull',       type:'Fada',   color:'#E91E9E',rare:'Comum',      price:.40,base:true},
  {n:'028',name:'Granbull',       type:'Fada',   color:'#E91E9E',rare:'Incomum',    price:.55,base:true},
  {n:'029',name:'Togekiss',       type:'Fada',   color:'#E91E9E',rare:'Incomum',    price:.80,base:true},
  {n:'030',name:'Meowth',         type:'Incolor',color:'#9E9E9E',rare:'Comum',      price:.55,base:true},
  {n:'031',name:'Persian',        type:'Incolor',color:'#9E9E9E',rare:'Incomum',    price:.65,base:true},
  {n:'032',name:'Meowth (Galar)', type:'Aco',    color:'#607D8B',rare:'Comum',      price:.50,base:true},
  {n:'033',name:'Perrserker',     type:'Aco',    color:'#607D8B',rare:'Incomum',    price:.65,base:true},
  {n:'034',name:'Jigglypuff',     type:'Fada',   color:'#E91E9E',rare:'Comum',      price:.45,base:true},
  {n:'035',name:'Wigglytuff',     type:'Fada',   color:'#E91E9E',rare:'Incomum',    price:.60,base:true},
  {n:'036',name:'Dedenne',        type:'Fada',   color:'#E91E9E',rare:'Comum',      price:.45,base:true},
  {n:'037',name:'Alcremie',       type:'Fada',   color:'#E91E9E',rare:'Incomum',    price:.65,base:true},
  {n:'038',name:'Beldum',         type:'Aco',    color:'#607D8B',rare:'Comum',      price:.40,base:true},
  {n:'039',name:'Metang',         type:'Aco',    color:'#607D8B',rare:'Incomum',    price:.55,base:true},
  {n:'040',name:'Metagross',      type:'Aco',    color:'#607D8B',rare:'Incomum',    price:.75,base:true},
  {n:'041',name:'Registeel',      type:'Aco',    color:'#607D8B',rare:'Incomum',    price:.80,base:true},
  {n:'042',name:'Melmetal',       type:'Aco',    color:'#607D8B',rare:'Incomum',    price:.75,base:true},
  {n:'043',name:'Magnemite',      type:'Eletrico',color:'#FFC107',rare:'Comum',     price:.40,base:true},
  {n:'044',name:'Magneton',       type:'Eletrico',color:'#FFC107',rare:'Incomum',   price:.55,base:true},
  {n:'045',name:'Magnezone',      type:'Eletrico',color:'#FFC107',rare:'Incomum',   price:.70,base:true},
  {n:'046',name:'Marill',         type:'Agua',   color:'#2196F3',rare:'Comum',      price:.40,base:true},
  {n:'047',name:'Azumarill',      type:'Agua',   color:'#2196F3',rare:'Incomum',    price:.60,base:true},
  {n:'048',name:'Phantump',       type:'Grama',  color:'#4CAF50',rare:'Comum',      price:.40,base:true},
  {n:'049',name:'Trevenant',      type:'Grama',  color:'#4CAF50',rare:'Incomum',    price:.65,base:true},
  {n:'050',name:'Xerneas',        type:'Fada',   color:'#E91E9E',rare:'Incomum',    price:.90,base:true},
  // ── RARAS 051–070 ──────────────────────────────────────
  {n:'051',name:'Mega Starmie ex', type:'Agua',  color:'#2196F3',rare:'Rara',       price:2.50,base:true},
  {n:'052',name:'Mega Clefable ex',type:'Fada',  color:'#E91E9E',rare:'Rara',       price:2.80,base:true},
  {n:'053',name:'Mega Zygarde ex', type:'Dragao',color:'#673AB7',rare:'Rara',       price:3.00,base:true},
  {n:'054',name:'Meowth ex',       type:'Incolor',color:'#9E9E9E',rare:'Rara',      price:2.20,base:true},
  {n:'055',name:'Togekiss ex',     type:'Fada',  color:'#E91E9E',rare:'Rara',       price:2.00,base:true},
  {n:'056',name:'Goodra ex',       type:'Dragao',color:'#673AB7',rare:'Rara',       price:2.00,base:true},
  {n:'057',name:'Gyarados ex',     type:'Agua',  color:'#2196F3',rare:'Rara',       price:2.50,base:true},
  {n:'058',name:'Metagross ex',    type:'Aco',   color:'#607D8B',rare:'Rara',       price:2.20,base:true},
  {n:'059',name:'Registeel ex',    type:'Aco',   color:'#607D8B',rare:'Rara',       price:1.80,base:true},
  {n:'060',name:'Magnezone ex',    type:'Eletrico',color:'#FFC107',rare:'Rara',     price:2.00,base:true},
  // ── DUPLAS RARAS 061–070 ────────────────────────────────
  {n:'061',name:'Mega Starmie ex', type:'Agua',  color:'#2196F3',rare:'Rara Dupla', price:12.00,base:true},
  {n:'062',name:'Mega Clefable ex',type:'Fada',  color:'#E91E9E',rare:'Rara Dupla', price:14.00,base:true},
  {n:'063',name:'Mega Zygarde ex', type:'Dragao',color:'#673AB7',rare:'Rara Dupla', price:18.00,base:true},
  {n:'064',name:'Meowth ex',       type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:10.00,base:true},
  {n:'065',name:'Togekiss ex',     type:'Fada',  color:'#E91E9E',rare:'Rara Dupla', price:9.00,base:true},
  {n:'066',name:'Goodra ex',       type:'Dragao',color:'#673AB7',rare:'Rara Dupla', price:8.00,base:true},
  {n:'067',name:'Gyarados ex',     type:'Agua',  color:'#2196F3',rare:'Rara Dupla', price:11.00,base:true},
  {n:'068',name:'Metagross ex',    type:'Aco',   color:'#607D8B',rare:'Rara Dupla', price:9.50,base:true},
  {n:'069',name:'Registeel ex',    type:'Aco',   color:'#607D8B',rare:'Rara Dupla', price:8.00,base:true},
  {n:'070',name:'Magnezone ex',    type:'Eletrico',color:'#FFC107',rare:'Rara Dupla',price:8.50,base:true},
  // ── ILUSTRACOES RARAS 071–080 ───────────────────────────
  {n:'071',name:'Mega Starmie ex', type:'Agua',  color:'#2196F3',rare:'Ilustr. Rara',price:30.00,base:true},
  {n:'072',name:'Mega Clefable ex',type:'Fada',  color:'#E91E9E',rare:'Ilustr. Rara',price:35.00,base:true},
  {n:'073',name:'Mega Zygarde ex', type:'Dragao',color:'#673AB7',rare:'Ilustr. Rara',price:42.00,base:true},
  {n:'074',name:'Meowth ex',       type:'Incolor',color:'#9E9E9E',rare:'Ilustr. Rara',price:28.00,base:true},
  {n:'075',name:'Togekiss ex',     type:'Fada',  color:'#E91E9E',rare:'Ilustr. Rara',price:25.00,base:true},
  {n:'076',name:'Goodra ex',       type:'Dragao',color:'#673AB7',rare:'Ilustr. Rara',price:22.00,base:true},
  {n:'077',name:'Gyarados ex',     type:'Agua',  color:'#2196F3',rare:'Ilustr. Rara',price:32.00,base:true},
  {n:'078',name:'Metagross ex',    type:'Aco',   color:'#607D8B',rare:'Ilustr. Rara',price:24.00,base:true},
  {n:'079',name:'Zygarde 100%',    type:'Dragao',color:'#673AB7',rare:'Ilustr. Rara',price:28.00,base:true},
  {n:'080',name:'Meowth (Galar) ex',type:'Aco', color:'#607D8B',rare:'Ilustr. Rara',price:22.00,base:true},
  // ── RARAS ULTRA 081–098 ─────────────────────────────────
  {n:'081',name:'Mega Starmie ex', type:'Agua',  color:'#2196F3',rare:'Rara Ultra', price:28.00,base:true},
  {n:'082',name:'Mega Clefable ex',type:'Fada',  color:'#E91E9E',rare:'Rara Ultra', price:32.00,base:true},
  {n:'083',name:'Mega Zygarde ex', type:'Dragao',color:'#673AB7',rare:'Rara Ultra', price:45.00,base:true},
  {n:'084',name:'Meowth ex',       type:'Incolor',color:'#9E9E9E',rare:'Rara Ultra',price:25.00,base:true},
  {n:'085',name:'Togekiss ex',     type:'Fada',  color:'#E91E9E',rare:'Rara Ultra', price:24.00,base:true},
  {n:'086',name:'Zygarde 100% ex', type:'Dragao',color:'#673AB7',rare:'Rara Ultra', price:35.00,base:true},
  {n:'087',name:'Goodra ex',       type:'Dragao',color:'#673AB7',rare:'Rara Ultra', price:22.00,base:true},
  {n:'088',name:'Gyarados ex',     type:'Agua',  color:'#2196F3',rare:'Rara Ultra', price:30.00,base:true},
  {n:'089',name:'Metagross ex',    type:'Aco',   color:'#607D8B',rare:'Rara Ultra', price:24.00,base:true},
  {n:'090',name:'Registeel ex',    type:'Aco',   color:'#607D8B',rare:'Rara Ultra', price:20.00,base:true},
  {n:'091',name:'Magnezone ex',    type:'Eletrico',color:'#FFC107',rare:'Rara Ultra',price:22.00,base:true},
  {n:'092',name:'Starmie ex (Full Art)',type:'Agua',color:'#2196F3',rare:'Rara Ultra',price:50.00,base:true},
  {n:'093',name:'Clefable ex (Full Art)',type:'Fada',color:'#E91E9E',rare:'Rara Ultra',price:55.00,base:true},
  {n:'094',name:'Zygarde ex (Full Art)',type:'Dragao',color:'#673AB7',rare:'Rara Ultra',price:70.00,base:true},
  {n:'095',name:'Meowth ex (Full Art)',type:'Incolor',color:'#9E9E9E',rare:'Rara Ultra',price:42.00,base:true},
  {n:'096',name:'Gyarados ex (Full Art)',type:'Agua',color:'#2196F3',rare:'Rara Ultra',price:48.00,base:true},
  {n:'097',name:'Energia Fada Esp.',type:'Incolor',color:'#9E9E9E',rare:'Rara Ultra',price:18.00,base:true},
  {n:'098',name:'Energia Dragao Esp.',type:'Incolor',color:'#9E9E9E',rare:'Rara Ultra',price:18.00,base:true},
  // ── ILUSTR. ESPECIAL RARA 099–105 ──────────────────────
  {n:'099',name:'Mega Starmie ex', type:'Agua',  color:'#2196F3',rare:'Ilustr. Esp. Rara',price:180.00,base:true},
  {n:'100',name:'Mega Clefable ex',type:'Fada',  color:'#E91E9E',rare:'Ilustr. Esp. Rara',price:220.00,base:true},
  {n:'101',name:'Mega Zygarde ex', type:'Dragao',color:'#673AB7',rare:'Ilustr. Esp. Rara',price:320.00,base:true},
  {n:'102',name:'Meowth ex',       type:'Incolor',color:'#9E9E9E',rare:'Ilustr. Esp. Rara',price:160.00,base:true},
  {n:'103',name:'Gyarados ex',     type:'Agua',  color:'#2196F3',rare:'Ilustr. Esp. Rara',price:190.00,base:true},
  {n:'104',name:'Zygarde 100% ex', type:'Dragao',color:'#673AB7',rare:'Ilustr. Esp. Rara',price:280.00,base:true},
  {n:'105',name:'Togekiss ex',     type:'Fada',  color:'#E91E9E',rare:'Ilustr. Esp. Rara',price:150.00,base:true},
  // ── MEGA ATTACK RARE (Gold) 106 ─────────────────────────
  {n:'106',name:'Mega Zygarde ex Gold',type:'Dragao',color:'#673AB7',rare:'Mega Attack Rare',price:980.00,base:true},
  // ── TREINADORES 107–120 ─────────────────────────────────
  {n:'107',name:'Ordem dos Seis Aneis',type:'Treinador',color:'#607D8B',rare:'Incomum',price:.70,base:true},
  {n:'108',name:'Laboratorio de Zygarde',type:'Treinador',color:'#607D8B',rare:'Incomum',price:.80,base:true},
  {n:'109',name:'Pesquisadora da Liga',type:'Treinador',color:'#607D8B',rare:'Incomum',price:.60,base:true},
  {n:'110',name:'Bolas Ultra',type:'Treinador',color:'#607D8B',rare:'Incomum',price:.55,base:true},
  {n:'111',name:'Laboratorio de Pesquisa',type:'Treinador',color:'#607D8B',rare:'Incomum',price:.60,base:true},
  {n:'112',name:'Troca de Energia',type:'Treinador',color:'#607D8B',rare:'Incomum',price:.70,base:true},
  {n:'113',name:'Viajante do Tempo',type:'Treinador',color:'#607D8B',rare:'Incomum',price:.65,base:true},
  {n:'114',name:'Captura de Acordo',type:'Treinador',color:'#607D8B',rare:'Comum',price:.40,base:true},
  {n:'115',name:'Energia Agua',type:'Energia',color:'#2196F3',rare:'Comum',price:.20,base:true},
  {n:'116',name:'Energia Fada',type:'Energia',color:'#E91E9E',rare:'Comum',price:.25,base:true},
  {n:'117',name:'Energia Dragao',type:'Energia',color:'#673AB7',rare:'Comum',price:.25,base:true},
  {n:'118',name:'Energia Aco',type:'Energia',color:'#607D8B',rare:'Comum',price:.20,base:true},
  {n:'119',name:'Energia Eletrico',type:'Energia',color:'#FFC107',rare:'Comum',price:.20,base:true},
  {n:'120',name:'Energia Incolor',type:'Energia',color:'#9E9E9E',rare:'Comum',price:.15,base:true},
];
