// ME03 — Ordem Perfeita (Perfect Order) — 124 cartas
// Lancamento EN: 27 mar 2026 | PT-BR: previsto abr/mai 2026
// Tema: Mega Zygarde ex, Mega Starmie ex, Mega Clefable ex, Mega Skarmory ex
// Precos: TCGPlayer market price (jun/2026) — valores em USD
const CARDS_ME03 = [
  // ── COMUNS / INCOMUNS / RARAS 001–088 ────────────────────────
  {n:'001',name:'Spinarak',          type:'Grama',    color:'#4CAF50',rare:'Comum',      price:0.10, base:true},
  {n:'002',name:'Ariados',           type:'Grama',    color:'#4CAF50',rare:'Comum',      price:0.06, base:true},
  {n:'003',name:'Shaymin',           type:'Grama',    color:'#4CAF50',rare:'Incomum',    price:0.04, base:true},
  {n:'004',name:'Snivy',             type:'Grama',    color:'#4CAF50',rare:'Comum',      price:0.10, base:true},
  {n:'005',name:'Servine',           type:'Grama',    color:'#4CAF50',rare:'Comum',      price:0.13, base:true},
  {n:'006',name:'Serperior',         type:'Grama',    color:'#4CAF50',rare:'Rara',       price:0.17, base:true},
  {n:'007',name:'Scatterbug',        type:'Grama',    color:'#4CAF50',rare:'Comum',      price:0.17, base:true},
  {n:'008',name:'Spewpa',            type:'Grama',    color:'#4CAF50',rare:'Comum',      price:0.14, base:true},
  {n:'009',name:'Vivillon',          type:'Grama',    color:'#4CAF50',rare:'Incomum',    price:0.15, base:true},
  {n:'010',name:'Rowlet',            type:'Grama',    color:'#4CAF50',rare:'Comum',      price:0.20, base:true},
  {n:'011',name:'Dartrix',           type:'Grama',    color:'#4CAF50',rare:'Comum',      price:0.12, base:true},
  {n:'012',name:'Decidueye ex',      type:'Grama',    color:'#4CAF50',rare:'Rara Dupla', price:0.45, base:true},
  {n:'013',name:'Fletchinder',       type:'Fogo',     color:'#F44336',rare:'Comum',      price:0.10, base:true},
  {n:'014',name:'Talonflame',        type:'Fogo',     color:'#F44336',rare:'Incomum',    price:0.12, base:true},
  {n:'015',name:'Salandit',          type:'Fogo',     color:'#F44336',rare:'Comum',      price:0.12, base:true},
  {n:'016',name:'Salazzle ex',       type:'Fogo',     color:'#F44336',rare:'Rara Dupla', price:0.43, base:true},
  {n:'017',name:'Turtonator',        type:'Fogo',     color:'#F44336',rare:'Incomum',    price:0.08, base:true},
  {n:'018',name:'Seel',              type:'Aquático', color:'#2196F3',rare:'Comum',      price:0.11, base:true},
  {n:'019',name:'Dewgong',           type:'Aquático', color:'#2196F3',rare:'Rara',       price:0.17, base:true},
  {n:'020',name:'Staryu',            type:'Aquático', color:'#2196F3',rare:'Comum',      price:0.17, base:true},
  {n:'021',name:'Mega Starmie ex',   type:'Aquático', color:'#2196F3',rare:'Rara Dupla', price:0.61, base:true,important:true},
  {n:'022',name:'Lapras ex',         type:'Aquático', color:'#2196F3',rare:'Rara Dupla', price:0.51, base:true},
  {n:'023',name:'Amaura',            type:'Aquático', color:'#2196F3',rare:'Comum',      price:0.16, base:true},
  {n:'024',name:'Aurorus',           type:'Aquático', color:'#2196F3',rare:'Rara',       price:0.14, base:true},
  {n:'025',name:'Volcanion',         type:'Fogo',     color:'#F44336',rare:'Incomum',    price:0.07, base:true},
  {n:'026',name:'Shinx',             type:'Raio',     color:'#FFEB3B',rare:'Comum',      price:0.10, base:true},
  {n:'027',name:'Luxio',             type:'Raio',     color:'#FFEB3B',rare:'Incomum',    price:0.10, base:true},
  {n:'028',name:'Luxray',            type:'Raio',     color:'#FFEB3B',rare:'Rara',       price:0.24, base:true},
  {n:'029',name:'Dedenne',           type:'Raio',     color:'#FFEB3B',rare:'Comum',      price:0.17, base:true},
  {n:'030',name:'Clefairy',          type:'Psíquico', color:'#9C27B0',rare:'Comum',      price:0.12, base:true},
  {n:'031',name:'Mega Clefable ex',  type:'Psíquico', color:'#9C27B0',rare:'Rara Dupla', price:0.57, base:true,important:true},
  {n:'032',name:'Mawile',            type:'Metal',    color:'#9E9E9E',rare:'Comum',      price:0.13, base:true},
  {n:'033',name:'Espurr',            type:'Psíquico', color:'#9C27B0',rare:'Comum',      price:0.13, base:true},
  {n:'034',name:'Meowstic',          type:'Psíquico', color:'#9C27B0',rare:'Incomum',    price:0.09, base:true},
  {n:'035',name:'Spritzee',          type:'Psíquico', color:'#9C27B0',rare:'Comum',      price:0.21, base:true},
  {n:'036',name:'Aromatisse',        type:'Psíquico', color:'#9C27B0',rare:'Incomum',    price:0.13, base:true},
  {n:'037',name:'Nosepass',          type:'Metal',    color:'#9E9E9E',rare:'Comum',      price:0.08, base:true},
  {n:'038',name:'Probopass',         type:'Metal',    color:'#9E9E9E',rare:'Comum',      price:0.10, base:true},
  {n:'039',name:'Hippopotas',        type:'Lutador',  color:'#FF9800',rare:'Comum',      price:0.06, base:true},
  {n:'040',name:'Hippowdon',         type:'Lutador',  color:'#FF9800',rare:'Incomum',    price:0.06, base:true},
  {n:'041',name:'Landorus',          type:'Lutador',  color:'#FF9800',rare:'Rara',       price:0.12, base:true},
  {n:'042',name:'Binacle',           type:'Lutador',  color:'#FF9800',rare:'Comum',      price:0.20, base:true},
  {n:'043',name:'Barbaracle',        type:'Lutador',  color:'#FF9800',rare:'Incomum',    price:0.17, base:true},
  {n:'044',name:'Tyrunt',            type:'Lutador',  color:'#FF9800',rare:'Comum',      price:0.15, base:true},
  {n:'045',name:'Tyrantrum',         type:'Lutador',  color:'#FF9800',rare:'Rara',       price:0.15, base:true},
  {n:'046',name:'Hawlucha',          type:'Lutador',  color:'#FF9800',rare:'Comum',      price:0.06, base:true},
  {n:'047',name:'Mega Zygarde ex',   type:'Lutador',  color:'#FF9800',rare:'Rara Dupla', price:0.40, base:true,important:true},
  {n:'048',name:'Gastly',            type:'Psíquico', color:'#9C27B0',rare:'Comum',      price:0.15, base:true},
  {n:'049',name:'Haunter',           type:'Psíquico', color:'#9C27B0',rare:'Comum',      price:0.20, base:true},
  {n:'050',name:'Gengar',            type:'Psíquico', color:'#9C27B0',rare:'Rara',       price:0.67, base:true},
  {n:'051',name:'Skorupi',           type:'Escuridão',color:'#607D8B',rare:'Comum',      price:0.10, base:true},
  {n:'052',name:'Drapion',           type:'Escuridão',color:'#607D8B',rare:'Incomum',    price:0.14, base:true},
  {n:'053',name:'Yveltal ex',        type:'Escuridão',color:'#607D8B',rare:'Rara Dupla', price:0.56, base:true},
  {n:'054',name:'Chien-Pao',         type:'Aquático', color:'#2196F3',rare:'Rara',       price:0.18, base:true},
  {n:'055',name:'Mega Skarmory ex',  type:'Metal',    color:'#9E9E9E',rare:'Rara Dupla', price:0.51, base:true,important:true},
  {n:'056',name:'Honedge',           type:'Metal',    color:'#9E9E9E',rare:'Comum',      price:0.12, base:true},
  {n:'057',name:'Doublade',          type:'Metal',    color:'#9E9E9E',rare:'Comum',      price:0.11, base:true},
  {n:'058',name:'Aegislash',         type:'Metal',    color:'#9E9E9E',rare:'Incomum',    price:0.11, base:true},
  {n:'059',name:'Klefki',            type:'Metal',    color:'#9E9E9E',rare:'Comum',      price:0.11, base:true},
  {n:'060',name:'Rattata',           type:'Incolor',  color:'#78909C',rare:'Comum',      price:0.11, base:true},
  {n:'061',name:'Raticate',          type:'Incolor',  color:'#78909C',rare:'Incomum',    price:0.09, base:true},
  {n:'062',name:'Meowth ex',         type:'Incolor',  color:'#78909C',rare:'Rara Dupla', price:2.29,base:true,important:true},
  {n:'063',name:'Snorlax',           type:'Incolor',  color:'#78909C',rare:'Comum',      price:0.13, base:true},
  {n:'064',name:'Bunnelby',          type:'Incolor',  color:'#78909C',rare:'Comum',      price:0.06, base:true},
  {n:'065',name:'Diggersby',         type:'Incolor',  color:'#78909C',rare:'Incomum',    price:0.05, base:true},
  {n:'066',name:'Fletchling',        type:'Incolor',  color:'#78909C',rare:'Comum',      price:0.08, base:true},
  {n:'067',name:'Furfrou',           type:'Incolor',  color:'#78909C',rare:'Comum',      price:0.10, base:true},
  {n:'068',name:'Fossil Maxilar',    type:'Item',     color:'#5C6BC0',rare:'Comum',      price:0.14, base:true},
  {n:'069',name:'Fossil Vela',       type:'Item',     color:'#5C6BC0',rare:'Comum',      price:0.14, base:true},
  {n:'070',name:'Memória Essencial', type:'Item',     color:'#5C6BC0',rare:'Incomum',    price:0.11, base:true},
  {n:'071',name:'Martelo Esmagador', type:'Item',     color:'#5C6BC0',rare:'Comum',      price:0.18, base:true},
  {n:'072',name:'Busca de Energia',  type:'Item',     color:'#5C6BC0',rare:'Comum',      price:0.16, base:true},
  {n:'073',name:'Repelente de Energia',type:'Item',   color:'#5C6BC0',rare:'Incomum',    price:0.07, base:true},
  {n:'074',name:'Pa Escavadora',     type:'Item',     color:'#5C6BC0',rare:'Comum',      price:0.12, base:true},
  {n:'075',name:'Jacinthe',          type:'Suporte',  color:'#E91E63',rare:'Incomum',    price:0.13, base:true},
  {n:'076',name:'Juiz',              type:'Suporte',  color:'#E91E63',rare:'Incomum',    price:0.21, base:true},
  {n:'077',name:'Cidade Lumiose',    type:'Estadio',  color:'#795548',rare:'Incomum',    price:0.07, base:true},
  {n:'078',name:'Galete Lumiose',    type:'Item',     color:'#5C6BC0',rare:'Incomum',    price:0.09, base:true},
  {n:'079',name:'Naveen',            type:'Suporte',  color:'#E91E63',rare:'Incomum',    price:0.07, base:true},
  {n:'080',name:'Poke Bola',         type:'Item',     color:'#5C6BC0',rare:'Comum',      price:0.14, base:true},
  {n:'081',name:'Poke Pad',          type:'Item',     color:'#5C6BC0',rare:'Incomum',    price:0.37, base:true},
  {n:'082',name:'Capturador Pokemon',type:'Item',     color:'#5C6BC0',rare:'Comum',      price:0.19, base:true},
  {n:'083',name:'Pocao',             type:'Item',     color:'#5C6BC0',rare:'Comum',      price:0.11, base:true},
  {n:'084',name:'Estimulo da Rosa',  type:'Suporte',  color:'#E91E63',rare:'Incomum',    price:0.16, base:true},
  {n:'085',name:'Tarragon',          type:'Suporte',  color:'#E91E63',rare:'Incomum',    price:0.14, base:true},
  {n:'086',name:'Energia Grama Crescente',type:'Grama',color:'#4CAF50',rare:'Rara',      price:0.26, base:true},
  {n:'087',name:'Energia Lutador Rochosa',type:'Lutador',color:'#FF9800',rare:'Rara',    price:0.22, base:true},
  {n:'088',name:'Energia Psiquica Telepatica',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.32,base:true},
  // ── ILUSTRACOES RARAS 089–099 ─────────────────────────────────
  {n:'089',name:'Spewpa',            type:'Grama',    color:'#4CAF50',rare:'Ilustr. Rara',price:1.88, base:false},
  {n:'090',name:'Rowlet',            type:'Grama',    color:'#4CAF50',rare:'Ilustr. Rara',price:5.67, base:false},
  {n:'091',name:'Talonflame',        type:'Fogo',     color:'#F44336',rare:'Ilustr. Rara',price:2.60, base:false},
  {n:'092',name:'Aurorus',           type:'Aquático', color:'#2196F3',rare:'Ilustr. Rara',price:3.90, base:false},
  {n:'093',name:'Dedenne',           type:'Raio',     color:'#FFEB3B',rare:'Ilustr. Rara',price:5.85, base:false},
  {n:'094',name:'Clefairy',          type:'Psíquico', color:'#9C27B0',rare:'Ilustr. Rara',price:24.50,base:false,important:true},
  {n:'095',name:'Espurr',            type:'Psíquico', color:'#9C27B0',rare:'Ilustr. Rara',price:5.47, base:false},
  {n:'096',name:'Probopass',         type:'Metal',    color:'#9E9E9E',rare:'Ilustr. Rara',price:1.08,  base:false},
  {n:'097',name:'Drapion',           type:'Escuridão',color:'#607D8B',rare:'Ilustr. Rara',price:1.26, base:false},
  {n:'098',name:'Doublade',          type:'Metal',    color:'#9E9E9E',rare:'Ilustr. Rara',price:2.38, base:false},
  {n:'099',name:'Raticate',          type:'Incolor',  color:'#78909C',rare:'Ilustr. Rara',price:2.95, base:false},
  // ── RARAS ULTRA 100–117 ───────────────────────────────────────
  {n:'100',name:'Decidueye ex',      type:'Grama',    color:'#4CAF50',rare:'Rara Ultra', price:2.00, base:false},
  {n:'101',name:'Salazzle ex',       type:'Fogo',     color:'#F44336',rare:'Rara Ultra', price:1.86, base:false},
  {n:'102',name:'Mega Starmie ex',   type:'Aquático', color:'#2196F3',rare:'Rara Ultra', price:7.90, base:false},
  {n:'103',name:'Mega Clefable ex',  type:'Psíquico', color:'#9C27B0',rare:'Rara Ultra', price:6.58, base:false},
  {n:'104',name:'Mega Zygarde ex',   type:'Lutador',  color:'#FF9800',rare:'Rara Ultra', price:8.30, base:false},
  {n:'105',name:'Yveltal ex',        type:'Escuridão',color:'#607D8B',rare:'Rara Ultra', price:5.69, base:false},
  {n:'106',name:'Mega Skarmory ex',  type:'Metal',    color:'#9E9E9E',rare:'Rara Ultra', price:4.78, base:false},
  {n:'107',name:'Meowth ex',         type:'Incolor',  color:'#78909C',rare:'Rara Ultra', price:15.41,base:false,important:true},
  {n:'108',name:'Reciclador de Energia',type:'Item',  color:'#5C6BC0',rare:'Rara Ultra', price:2.40, base:false},
  {n:'109',name:'Floresta da Vitalidade',type:'Estadio',color:'#795548',rare:'Rara Ultra',price:5.96,base:false},
  {n:'110',name:'Jacinthe',          type:'Suporte',  color:'#E91E63',rare:'Rara Ultra', price:3.85, base:false},
  {n:'111',name:'Cidade Lumiose',    type:'Estadio',  color:'#795548',rare:'Rara Ultra', price:1.91, base:false},
  {n:'112',name:'Naveen',            type:'Suporte',  color:'#E91E63',rare:'Rara Ultra', price:2.31, base:false},
  {n:'113',name:'Poke Pad',          type:'Item',     color:'#5C6BC0',rare:'Rara Ultra', price:12.41,base:false,important:true},
  {n:'114',name:'Estimulo da Rosa',  type:'Suporte',  color:'#E91E63',rare:'Rara Ultra', price:5.64, base:false},
  {n:'115',name:'Cinzas Sagradas',   type:'Item',     color:'#5C6BC0',rare:'Rara Ultra', price:2.33, base:false},
  {n:'116',name:'Tarragon',          type:'Suporte',  color:'#E91E63',rare:'Rara Ultra', price:2.46, base:false},
  {n:'117',name:'Curativo Maravilhoso',type:'Item',   color:'#5C6BC0',rare:'Rara Ultra', price:2.92, base:false},
  // ── ILUSTR. ESPECIAL RARA 118–123 ────────────────────────────
  {n:'118',name:'Mega Starmie ex',   type:'Aquático', color:'#2196F3',rare:'Ilustr. Esp. Rara',price:61.38, base:false},
  {n:'119',name:'Mega Clefable ex',  type:'Psíquico', color:'#9C27B0',rare:'Ilustr. Esp. Rara',price:65.06, base:false},
  {n:'120',name:'Mega Zygarde ex',   type:'Lutador',  color:'#FF9800',rare:'Ilustr. Esp. Rara',price:68.61, base:false},
  {n:'121',name:'Meowth ex',         type:'Incolor',  color:'#78909C',rare:'Ilustr. Esp. Rara',price:171.04,base:false,important:true},
  {n:'122',name:'Jacinthe',          type:'Suporte',  color:'#E91E63',rare:'Ilustr. Esp. Rara',price:26.46, base:false},
  {n:'123',name:'Estimulo da Rosa',  type:'Suporte',  color:'#E91E63',rare:'Ilustr. Esp. Rara',price:66.95, base:false},
  // ── MEGA HYPER RARE 124 ──────────────────────────────────────
  {n:'124',name:'Mega Zygarde ex Gold',type:'Lutador', color:'#FF9800',rare:'Mega Attack Rare',price:155.09,base:false,important:true},
];
