// SV5 — Temporal Forces (218 cartas)
// Lançamento EN: 2024/03/22
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV5 = [
  {n:'001',name:'Scyther',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.35,base:true},
  {n:'002',name:'Pineco',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.3,base:true},
  {n:'003',name:'Seedot',type:'Planta',color:'#4CAF50',rare:'Comum',price:1.1,base:true},
  {n:'004',name:'Nuzleaf',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.7,base:true},
  {n:'005',name:'Shiftry',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.41,base:true},
  {n:'006',name:'Shroomish',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.35,base:true},
  {n:'007',name:'Breloom',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.3,base:true},
  {n:'008',name:'Roselia',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.3,base:true},
  {n:'009',name:'Roserade',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.3,base:true},
  {n:'010',name:'Turtwig',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.99,base:true},
  {n:'011',name:'Grotle',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.75,base:true},
  {n:'012',name:'Torterra ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.83,base:true},
  {n:'013',name:'Shaymin',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.93,base:true},
  {n:'014',name:'Cottonee',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.3,base:true},
  {n:'015',name:'Whimsicott',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.35,base:true},
  {n:'016',name:'Deerling',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.41,base:true},
  {n:'017',name:'Sawsbuck',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.87,base:true},
  {n:'018',name:'Grubbin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.3,base:true},
  {n:'019',name:'Dhelmise',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.41,base:true},
  {n:'020',name:'Bramblin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.75,base:true},
  {n:'021',name:'Brambleghast',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.64,base:true},
  {n:'022',name:'Scovillain ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:4.23,base:true},
  {n:'023',name:'Rellor',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.75,base:true},
  {n:'024',name:'Rabsca',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.99,base:true},
  {n:'025',name:'Iron Leaves ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:4.35,base:true},
  {n:'026',name:'Ponyta',type:'Fogo',color:'#F44336',rare:'Comum',price:1.16,base:true},
  {n:'027',name:'Rapidash',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.64,base:true},
  {n:'028',name:'Slugma',type:'Fogo',color:'#F44336',rare:'Comum',price:0.52,base:true},
  {n:'029',name:'Magcargo',type:'Fogo',color:'#F44336',rare:'Rara',price:0.35,base:true},
  {n:'030',name:'Victini',type:'Fogo',color:'#F44336',rare:'Comum',price:0.99,base:true},
  {n:'031',name:'Heatmor',type:'Fogo',color:'#F44336',rare:'Comum',price:0.35,base:true},
  {n:'032',name:'Litten',type:'Fogo',color:'#F44336',rare:'Comum',price:0.7,base:true},
  {n:'033',name:'Torracat',type:'Fogo',color:'#F44336',rare:'Comum',price:1.39,base:true},
  {n:'034',name:'Incineroar ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:4.18,base:true},
  {n:'035',name:'Turtonator',type:'Fogo',color:'#F44336',rare:'Comum',price:0.46,base:true},
  {n:'036',name:'Sizzlipede',type:'Fogo',color:'#F44336',rare:'Comum',price:0.41,base:true},
  {n:'037',name:'Centiskorch',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.35,base:true},
  {n:'038',name:'Gouging Fire ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:3.89,base:true},
  {n:'039',name:'Totodile',type:'Aquático',color:'#2196F3',rare:'Comum',price:1.45,base:true},
  {n:'040',name:'Croconaw',type:'Aquático',color:'#2196F3',rare:'Comum',price:1.57,base:true},
  {n:'041',name:'Feraligatr',type:'Aquático',color:'#2196F3',rare:'Rara',price:1.8,base:true},
  {n:'042',name:'Carvanha',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.35,base:true},
  {n:'043',name:'Sharpedo',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.87,base:true},
  {n:'044',name:'Keldeo',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.81,base:true},
  {n:'045',name:'Snom',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.93,base:true},
  {n:'046',name:'Frosmoth',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.64,base:true},
  {n:'047',name:'Wiglett',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.52,base:true},
  {n:'048',name:'Finizen',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.46,base:true},
  {n:'049',name:'Palafin',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.35,base:true},
  {n:'050',name:'Walking Wake ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:3.83,base:true},
  {n:'051',name:'Pikachu',type:'Raio',color:'#FFEB3B',rare:'Comum',price:1.51,base:true},
  {n:'052',name:'Raichu',type:'Raio',color:'#FFEB3B',rare:'Comum',price:1.33,base:true},
  {n:'053',name:'Electabuzz',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.52,base:true},
  {n:'054',name:'Electivire',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.52,base:true},
  {n:'055',name:'Charjabug',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.46,base:true},
  {n:'056',name:'Vikavolt',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.64,base:true},
  {n:'057',name:'Zeraora',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.35,base:true},
  {n:'058',name:'Yamper',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.93,base:true},
  {n:'059',name:'Boltund',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.41,base:true},
  {n:'060',name:'Wugtrio ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:3.71,base:true},
  {n:'061',name:'Iron Hands',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.64,base:true},
  {n:'062',name:'Iron Thorns',type:'Raio',color:'#FFEB3B',rare:'Rara',price:1.22,base:true},
  {n:'063',name:'Mr. Mime',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.99,base:true},
  {n:'064',name:'Marill',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.75,base:true},
  {n:'065',name:'Azumarill',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.58,base:true},
  {n:'066',name:'Girafarig',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.52,base:true},
  {n:'067',name:'Latias',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.58,base:true},
  {n:'068',name:'Bronzor',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.46,base:true},
  {n:'069',name:'Bronzong',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.75,base:true},
  {n:'070',name:'Solosis',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.46,base:true},
  {n:'071',name:'Duosion',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.81,base:true},
  {n:'072',name:'Reuniclus',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.46,base:true},
  {n:'073',name:'Elgyem',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.41,base:true},
  {n:'074',name:'Beheeyem',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.46,base:true},
  {n:'075',name:'Cutiefly',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.3,base:true},
  {n:'076',name:'Ribombee',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.7,base:true},
  {n:'077',name:'Scream Tail',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.41,base:true},
  {n:'078',name:'Flutter Mane',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:1.16,base:true},
  {n:'079',name:'Iron Valiant',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.64,base:true},
  {n:'080',name:'Iron Valiant',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.46,base:true},
  {n:'081',name:'Iron Crown ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:3.89,base:true},
  {n:'082',name:'Meditite',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.41,base:true},
  {n:'083',name:'Medicham',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.41,base:true},
  {n:'084',name:'Relicanth',type:'Lutador',color:'#FF9800',rare:'Rara',price:1.68,base:true},
  {n:'085',name:'Drilbur',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.64,base:true},
  {n:'086',name:'Excadrill',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.41,base:true},
  {n:'087',name:'Golett',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.52,base:true},
  {n:'088',name:'Golurk',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.3,base:true},
  {n:'089',name:'Rockruff',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.35,base:true},
  {n:'090',name:'Lycanroc',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.87,base:true},
  {n:'091',name:'Mudbray',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.41,base:true},
  {n:'092',name:'Mudsdale',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.41,base:true},
  {n:'093',name:'Rolycoly',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.35,base:true},
  {n:'094',name:'Carkol',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.52,base:true},
  {n:'095',name:'Coalossal',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.46,base:true},
  {n:'096',name:'Great Tusk',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.35,base:true},
  {n:'097',name:'Great Tusk',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.35,base:true},
  {n:'098',name:'Sandy Shocks',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.87,base:true},
  {n:'099',name:'Iron Boulder ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:3.54,base:true},
  {n:'100',name:'Ekans',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.46,base:true},
  {n:'101',name:'Arbok',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.87,base:true},
  {n:'102',name:'Gastly',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.52,base:true},
  {n:'103',name:'Haunter',type:'Sombrio',color:'#607D8B',rare:'Comum',price:1.22,base:true},
  {n:'104',name:'Gengar ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:38.11,base:true},
  {n:'105',name:'Poochyena',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.58,base:true},
  {n:'106',name:'Mightyena',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.46,base:true},
  {n:'107',name:'Sableye',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.87,base:true},
  {n:'108',name:'Farigiraf ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:3.54,base:true},
  {n:'109',name:'Roaring Moon',type:'Sombrio',color:'#607D8B',rare:'Rara',price:1.1,base:true},
  {n:'110',name:'Forretress',type:'Metal',color:'#78909C',rare:'Incomum',price:0.41,base:true},
  {n:'111',name:'Scizor ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:4.87,base:true},
  {n:'112',name:'Mawile',type:'Metal',color:'#78909C',rare:'Comum',price:0.81,base:true},
  {n:'113',name:'Beldum',type:'Metal',color:'#78909C',rare:'Comum',price:0.81,base:true},
  {n:'114',name:'Metang',type:'Metal',color:'#78909C',rare:'Comum',price:1.39,base:true},
  {n:'115',name:'Metagross',type:'Metal',color:'#78909C',rare:'Incomum',price:0.64,base:true},
  {n:'116',name:'Meltan',type:'Metal',color:'#78909C',rare:'Comum',price:0.58,base:true},
  {n:'117',name:'Melmetal',type:'Metal',color:'#78909C',rare:'Rara',price:0.81,base:true},
  {n:'118',name:'Iron Treads',type:'Metal',color:'#78909C',rare:'Incomum',price:0.35,base:true},
  {n:'119',name:'Koraidon',type:'Dragão',color:'#3F51B5',rare:'Rara',price:0.81,base:true},
  {n:'120',name:'Koraidon ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:4.23,base:true},
  {n:'121',name:'Miraidon',type:'Dragão',color:'#3F51B5',rare:'Rara',price:1.22,base:true},
  {n:'122',name:'Miraidon ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:3.65,base:true},
  {n:'123',name:'Raging Bolt ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:8.35,base:true},
  {n:'124',name:'Lickitung',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.35,base:true},
  {n:'125',name:'Lickilicky',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.99,base:true},
  {n:'126',name:'Hoothoot',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.04,base:true},
  {n:'127',name:'Noctowl',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.7,base:true},
  {n:'128',name:'Dunsparce',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.87,base:true},
  {n:'129',name:'Dudunsparce',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:4.47,base:true},
  {n:'130',name:'Skitty',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.7,base:true},
  {n:'131',name:'Delcatty',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.99,base:true},
  {n:'132',name:'Chatot',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.3,base:true},
  {n:'133',name:'Pidove',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.64,base:true},
  {n:'134',name:'Tranquill',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.35,base:true},
  {n:'135',name:'Unfezant',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.3,base:true},
  {n:'136',name:'Minccino',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.16,base:true},
  {n:'137',name:'Cinccino',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.99,base:true},
  {n:'138',name:'Drampa',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:1.04,base:true},
  {n:'139',name:'Iron Jugulis',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.41,base:true},
  {n:'140',name:'Ancient Booster Energy Capsule',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.99,base:true},
  {n:'141',name:'Awakening Drum',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:2.15,base:false},
  {n:'142',name:'Bianca\'s Devotion',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.7,base:true},
  {n:'143',name:'Boxed Order',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.41,base:true},
  {n:'144',name:'Buddy-Buddy Poffin',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.1,base:true},
  {n:'145',name:'Ciphermaniac\'s Codebreaking',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.93,base:true},
  {n:'146',name:'Eri',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.99,base:true},
  {n:'147',name:'Explorer\'s Guidance',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.04,base:true},
  {n:'148',name:'Full Metal Lab',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.75,base:true},
  {n:'149',name:'Future Booster Energy Capsule',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.75,base:true},
  {n:'150',name:'Hand Trimmer',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.99,base:true},
  {n:'151',name:'Heavy Baton',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.75,base:true},
  {n:'152',name:'Hero\'s Cape',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:126.21,base:false,important:true},
  {n:'153',name:'Master Ball',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:9.92,base:false},
  {n:'154',name:'Maximum Belt',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:4.93,base:false},
  {n:'155',name:'Morty\'s Conviction',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.87,base:true},
  {n:'156',name:'Perilous Jungle',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.22,base:true},
  {n:'157',name:'Prime Catcher',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:4.58,base:false},
  {n:'158',name:'Reboot Pod',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:1.91,base:false},
  {n:'159',name:'Rescue Board',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.99,base:true},
  {n:'160',name:'Salvatore',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.04,base:true},
  {n:'161',name:'Mist Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:12.76,base:true},
  {n:'162',name:'Neo Upper Energy',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:115.65,base:false,important:true},
  {n:'163',name:'Shiftry',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:72.5,base:false,important:true},
  {n:'164',name:'Grotle',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:87.35,base:false,important:true},
  {n:'165',name:'Deerling',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:265,base:false,important:true},
  {n:'166',name:'Sawsbuck',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:341.27,base:false,important:true},
  {n:'167',name:'Litten',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:241.98,base:false,important:true},
  {n:'168',name:'Snom',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:103.41,base:false,important:true},
  {n:'169',name:'Charjabug',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:52.08,base:false,important:true},
  {n:'170',name:'Bronzor',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:51.91,base:false,important:true},
  {n:'171',name:'Reuniclus',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:125.11,base:false,important:true},
  {n:'172',name:'Cutiefly',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:53.42,base:false,important:true},
  {n:'173',name:'Relicanth',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:64.03,base:false,important:true},
  {n:'174',name:'Excadrill',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:65.08,base:false,important:true},
  {n:'175',name:'Mudsdale',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:57.59,base:false,important:true},
  {n:'176',name:'Arbok',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:191.11,base:false,important:true},
  {n:'177',name:'Gastly',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:621.24,base:false,important:true},
  {n:'178',name:'Metagross',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:232.81,base:false,important:true},
  {n:'179',name:'Meltan',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:38.45,base:false},
  {n:'180',name:'Lickitung',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:182.58,base:false,important:true},
  {n:'181',name:'Chatot',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:80.16,base:false,important:true},
  {n:'182',name:'Minccino',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:168.43,base:false,important:true},
  {n:'183',name:'Cinccino',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:265.7,base:false,important:true},
  {n:'184',name:'Drampa',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:197.14,base:false,important:true},
  {n:'185',name:'Torterra ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:23.32,base:false},
  {n:'186',name:'Iron Leaves ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:12.18,base:false},
  {n:'187',name:'Incineroar ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:15.14,base:false},
  {n:'188',name:'Gouging Fire ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:16.24,base:false},
  {n:'189',name:'Walking Wake ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:12.01,base:false},
  {n:'190',name:'Wugtrio ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:8.82,base:false},
  {n:'191',name:'Iron Crown ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:10.67,base:false},
  {n:'192',name:'Iron Boulder ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:7.37,base:false},
  {n:'193',name:'Gengar ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:403.62,base:false,important:true},
  {n:'194',name:'Farigiraf ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:12.93,base:false},
  {n:'195',name:'Scizor ex',type:'Metal',color:'#78909C',rare:'Ultra Rara',price:18.91,base:false},
  {n:'196',name:'Raging Bolt ex',type:'Dragão',color:'#3F51B5',rare:'Ultra Rara',price:26.45,base:false},
  {n:'197',name:'Bianca\'s Devotion',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:15.54,base:false},
  {n:'198',name:'Ciphermaniac\'s Codebreaking',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:49.76,base:false},
  {n:'199',name:'Eri',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:15.08,base:false},
  {n:'200',name:'Explorer\'s Guidance',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:11.72,base:false},
  {n:'201',name:'Morty\'s Conviction',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:25.29,base:false},
  {n:'202',name:'Salvatore',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:27.03,base:false},
  {n:'203',name:'Iron Leaves ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:240.35,base:false,important:true},
  {n:'204',name:'Gouging Fire ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:349.97,base:false,important:true},
  {n:'205',name:'Walking Wake ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:356.7,base:false,important:true},
  {n:'206',name:'Iron Crown ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:345.39,base:false,important:true},
  {n:'207',name:'Iron Boulder ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:169.36,base:false,important:true},
  {n:'208',name:'Raging Bolt ex',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada Especial',price:417.6,base:false,important:true},
  {n:'209',name:'Bianca\'s Devotion',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:172.55,base:false,important:true},
  {n:'210',name:'Eri',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:98.6,base:false,important:true},
  {n:'211',name:'Morty\'s Conviction',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:444.57,base:false,important:true},
  {n:'212',name:'Salvatore',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:117.51,base:false,important:true},
  {n:'213',name:'Iron Leaves ex',type:'Planta',color:'#4CAF50',rare:'Hiper Rara',price:52.84,base:false,important:true},
  {n:'214',name:'Gouging Fire ex',type:'Fogo',color:'#F44336',rare:'Hiper Rara',price:92.57,base:false,important:true},
  {n:'215',name:'Walking Wake ex',type:'Aquático',color:'#2196F3',rare:'Hiper Rara',price:73.08,base:false,important:true},
  {n:'216',name:'Iron Crown ex',type:'Psíquico',color:'#9C27B0',rare:'Hiper Rara',price:53.71,base:false,important:true},
  {n:'217',name:'Iron Boulder ex',type:'Lutador',color:'#FF9800',rare:'Hiper Rara',price:51.79,base:false,important:true},
  {n:'218',name:'Raging Bolt ex',type:'Dragão',color:'#3F51B5',rare:'Hiper Rara',price:83.4,base:false,important:true}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV5 = CARDS_SV5;