// SVP — Scarlet & Violet Promos (218 cartas cadastradas)
// Fonte: pokemontcg.io API (set.id:svp) + limitlesstcg.com/cards/SVP pra preencher gaps/cauda mais recente.
// Numeracao oficial tem buracos reais (190-192, 213-215 nao existem) — nao e erro de cadastro.
// ATENCAO: nomes em ingles, seguindo o mesmo padrao dos cards_sv*.js (nao traduzido).
// PRECOS ESTIMADOS por categoria (comum/ex/promo-personagem) — ainda NAO pesquisados
// individualmente na Liga/TCGplayer. Ajustar quando houver referencia real de mercado,
// mesmo padrao de aviso usado em cards_me06.js. Ver [[project_pokemon_tcg]].
const CARDS_SVP = [
  {n:'001',name:'Sprigatito',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'002',name:'Fuecoco',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'003',name:'Quaxly',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'004',name:'Mimikyu ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'005',name:'Quaquaval',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'006',name:'Pawmot',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'007',name:'Hawlucha',type:'Lutador',color:'#FF9800',rare:'Promo',price:2.00,base:false},
  {n:'008',name:'Revavroom',type:'Metal',color:'#78909C',rare:'Promo',price:2.00,base:false},
  {n:'009',name:'Spidops',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'010',name:'Espathra',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'011',name:'Arcanine',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'012',name:'Dondozo',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'013',name:'Miraidon',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'014',name:'Koraidon',type:'Lutador',color:'#FF9800',rare:'Promo',price:2.00,base:false},
  {n:'015',name:'Flaaffy',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'016',name:'Ampharos ex',type:'Raio',color:'#FFEB3B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'017',name:'Lucario ex',type:'Lutador',color:'#FF9800',rare:'Promo',price:18.00,base:false,important:true},
  {n:'018',name:'Cyclizar ex',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:18.00,base:false,important:true},
  {n:'019',name:'Baxcalibur',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'020',name:'Tinkaton',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'021',name:'Murkrow',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'022',name:'Pelipper',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'023',name:'Smoliv',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'024',name:'Growlithe',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'025',name:'Tinkatink',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'026',name:'Varoom',type:'Metal',color:'#78909C',rare:'Promo',price:2.00,base:false},
  {n:'027',name:'Pikachu',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'028',name:'Miraidon ex',type:'Raio',color:'#FFEB3B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'029',name:'Koraidon ex',type:'Lutador',color:'#FF9800',rare:'Promo',price:18.00,base:false,important:true},
  {n:'030',name:'Chien-Pao ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'031',name:'Tinkaton ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'032',name:'Annihilape ex',type:'Lutador',color:'#FF9800',rare:'Promo',price:18.00,base:false,important:true},
  {n:'033',name:'Meowscarada ex',type:'Planta',color:'#4CAF50',rare:'Promo',price:18.00,base:false,important:true},
  {n:'034',name:'Skeledirge ex',type:'Fogo',color:'#F44336',rare:'Promo',price:18.00,base:false,important:true},
  {n:'035',name:'Quaquaval ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'036',name:'Palafin',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'037',name:'Cleffa',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'038',name:'Togekiss',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'039',name:'Mawile',type:'Metal',color:'#78909C',rare:'Promo',price:2.00,base:false},
  {n:'040',name:'Pawmi',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'041',name:'Paldean Wooper',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'042',name:'Houndstone',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'043',name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'044',name:'Charmander',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'045',name:'Paradise Resort',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:4.00,base:false},
  {n:'046',name:'Bulbasaur',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'047',name:'Charmander',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'048',name:'Squirtle',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'049',name:'Zapdos ex',type:'Raio',color:'#FFEB3B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'050',name:'Alakazam ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'051',name:'Snorlax',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'052',name:'Mewtwo',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'053',name:'Mew ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'054',name:'Greninja ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'055',name:'Kangaskhan ex',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:18.00,base:false,important:true},
  {n:'056',name:'Charizard ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'057',name:'Chi-Yu',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'058',name:'Iron Bundle',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'059',name:'Xatu',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'060',name:'Aegislash',type:'Metal',color:'#78909C',rare:'Promo',price:2.00,base:false},
  {n:'061',name:'Pineco',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'062',name:'Sinistea',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'063',name:'Cetitan',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'064',name:'Arctibax',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'065',name:'Scream Tail',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'066',name:'Iron Bundle',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'067',name:'Roaring Moon ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'068',name:'Iron Valiant ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'069',name:'Fidough',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'070',name:'Greavard',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'071',name:'Maschiff',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'072',name:'Great Tusk ex',type:'Lutador',color:'#FF9800',rare:'Promo',price:18.00,base:false,important:true},
  {n:'073',name:'Iron Treads ex',type:'Metal',color:'#78909C',rare:'Promo',price:18.00,base:false,important:true},
  {n:'074',name:'Charizard ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'075',name:'Mimikyu',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'076',name:'Sprigatito',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'077',name:'Floragato',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'078',name:'Meowscarada ex',type:'Planta',color:'#4CAF50',rare:'Promo',price:18.00,base:false,important:true},
  {n:'079',name:'Fuecoco',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'080',name:'Crocalor',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'081',name:'Skeledirge ex',type:'Fogo',color:'#F44336',rare:'Promo',price:18.00,base:false,important:true},
  {n:'082',name:'Quaxly',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'083',name:'Quaxwell',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'084',name:'Quaquaval ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'085',name:'Pikachu with Grey Felt Hat',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'086',name:'Mabosstiff ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'087',name:'Sprigatito ex',type:'Planta',color:'#4CAF50',rare:'Promo',price:18.00,base:false,important:true},
  {n:'088',name:'Pikachu',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'089',name:'Feraligatr',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'090',name:'Metang',type:'Metal',color:'#78909C',rare:'Promo',price:2.00,base:false},
  {n:'091',name:'Koraidon',type:'Dragão',color:'#3F51B5',rare:'Promo',price:2.00,base:false},
  {n:'092',name:'Miraidon',type:'Dragão',color:'#3F51B5',rare:'Promo',price:2.00,base:false},
  {n:'093',name:'Carvanha',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'094',name:'Bellibolt',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'095',name:'Cleffa',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'096',name:'Cyclizar',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'097',name:'Flutter Mane',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'098',name:'Iron Thorns',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'099',name:'Shroodle',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'100',name:'Grafaiai ex',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:18.00,base:false,important:true},
  {n:'101',name:'Pikachu',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'102',name:'Oddish',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'103',name:'Houndoom ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'104',name:'Melmetal ex',type:'Metal',color:'#78909C',rare:'Promo',price:18.00,base:false,important:true},
  {n:'105',name:'Armarouge ex',type:'Fogo',color:'#F44336',rare:'Promo',price:18.00,base:false,important:true},
  {n:'106',name:'Pikachu ex',type:'Raio',color:'#FFEB3B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'107',name:'Mareep',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'108',name:'Flaaffy',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'109',name:'Ampharos',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'110',name:'Darkrai ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'111',name:'Pawniard',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'112',name:'Bisharp',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'113',name:'Kingambit',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'114',name:'Picnicker',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:3.00,base:false},
  {n:'115',name:'Thwackey',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'116',name:'Infernape',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'117',name:'Froslass',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'118',name:'Tatsugiri',type:'Dragão',color:'#3F51B5',rare:'Promo',price:2.00,base:false},
  {n:'119',name:'Toxel',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'120',name:'Pupitar',type:'Lutador',color:'#FF9800',rare:'Promo',price:2.00,base:false},
  {n:'121',name:'Revavroom',type:'Metal',color:'#78909C',rare:'Promo',price:2.00,base:false},
  {n:'122',name:'Snorlax',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'123',name:'Teal Mask Ogerpon',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'124',name:'Iono',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:8.00,base:false,important:true},
  {n:'125',name:'Armarouge ex',type:'Fogo',color:'#F44336',rare:'Promo',price:18.00,base:false,important:true},
  {n:'126',name:'Palafin ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'127',name:'Walking Wake ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'128',name:'Iron Leaves ex',type:'Planta',color:'#4CAF50',rare:'Promo',price:18.00,base:false,important:true},
  {n:'129',name:'Pecharunt',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'130',name:'Kingambit',type:'Metal',color:'#78909C',rare:'Promo',price:2.00,base:false},
  {n:'131',name:'Kingdra ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'132',name:'Greninja ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'133',name:'Ledian',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'134',name:'Crabominable',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'135',name:'Drifblim',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'136',name:'Bouffalant',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'137',name:'Horsea',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'138',name:'Porygon2',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'139',name:'Latias',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'140',name:'Tinkaton',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'141',name:'Noctowl',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'142',name:'Victini ex',type:'Fogo',color:'#F44336',rare:'Promo',price:18.00,base:false,important:true},
  {n:'143',name:'Miraidon ex',type:'Raio',color:'#FFEB3B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'144',name:'Gouging Fire ex',type:'Fogo',color:'#F44336',rare:'Promo',price:18.00,base:false,important:true},
  {n:'145',name:'Raging Bolt ex',type:'Dragão',color:'#3F51B5',rare:'Promo',price:18.00,base:false,important:true},
  {n:'146',name:'Iron Crown ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'147',name:'Iron Boulder ex',type:'Lutador',color:'#FF9800',rare:'Promo',price:18.00,base:false,important:true},
  {n:'148',name:'Miraidon',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'149',name:'Pecharunt',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'150',name:'Paradise Resort',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:4.00,base:false},
  {n:'151',name:'Gouging Fire',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'152',name:'Chien-Pao',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'153',name:'Magneton',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'154',name:'Indeedee',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'155',name:'Wooper',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'156',name:'Quagsire',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'157',name:'Zapdos',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'158',name:'Pachirisu',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'159',name:'Magneton',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'160',name:'Squawkabilly ex',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:18.00,base:false,important:true},
  {n:'161',name:'Charizard ex',type:'Fogo',color:'#F44336',rare:'Promo',price:18.00,base:false,important:true},
  {n:'162',name:'Houndstone ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'163',name:'Cinderace ex',type:'Fogo',color:'#F44336',rare:'Promo',price:18.00,base:false,important:true},
  {n:'164',name:'Lapras ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'165',name:'Terapagos ex',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:18.00,base:false,important:true},
  {n:'166',name:'Teal Mask Ogerpon ex',type:'Planta',color:'#4CAF50',rare:'Promo',price:18.00,base:false,important:true},
  {n:'167',name:'Flareon',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'168',name:'Vaporeon',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'169',name:'Jolteon',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'170',name:'Leafeon',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'171',name:'Glaceon',type:'Aquático',color:'#2196F3',rare:'Promo',price:2.00,base:false},
  {n:'172',name:'Sylveon',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'173',name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'174',name:'Eevee ex',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:18.00,base:false,important:true},
  {n:'175',name:'Espeon ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'176',name:'Umbreon ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'177',name:'Bloodmoon Ursaluna ex',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:18.00,base:false,important:true},
  {n:'178',name:'Kyogre ex',type:'Aquático',color:'#2196F3',rare:'Promo',price:18.00,base:false,important:true},
  {n:'179',name:'Xerneas ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:18.00,base:false,important:true},
  {n:'180',name:'Dialga ex',type:'Metal',color:'#78909C',rare:'Promo',price:18.00,base:false,important:true},
  {n:'181',name:'N\'s Darmanitan',type:'Fogo',color:'#F44336',rare:'Promo',price:14.00,base:false,important:true},
  {n:'182',name:'Iono\'s Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Promo',price:14.00,base:false,important:true},
  {n:'183',name:'Lillie\'s Ribombee',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:14.00,base:false,important:true},
  {n:'184',name:'Hop\'s Snorlax',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:14.00,base:false,important:true},
  {n:'185',name:'Yanma',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'186',name:'Scraggy',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'187',name:'Yanmega',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'188',name:'Scrafty',type:'Sombrio',color:'#607D8B',rare:'Promo',price:2.00,base:false},
  {n:'189',name:'N\'s Zorua',type:'Sombrio',color:'#607D8B',rare:'Promo',price:14.00,base:false,important:true},
  {n:'193',name:'Hop\'s Zacian ex',type:'Metal',color:'#78909C',rare:'Promo',price:38.00,base:false,important:true},
  {n:'194',name:'Iono\'s Bellibolt ex',type:'Raio',color:'#FFEB3B',rare:'Promo',price:38.00,base:false,important:true},
  {n:'195',name:'Lillie\'s Clefairy ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:38.00,base:false,important:true},
  {n:'196',name:'Charizard ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:18.00,base:false,important:true},
  {n:'197',name:'Koraidon ex',type:'Lutador',color:'#FF9800',rare:'Promo',price:18.00,base:false,important:true},
  {n:'198',name:'Zacian ex',type:'Metal',color:'#78909C',rare:'Promo',price:18.00,base:false,important:true},
  {n:'199',name:'Zarude',type:'Planta',color:'#4CAF50',rare:'Promo',price:2.00,base:false},
  {n:'200',name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'201',name:'Zebstrika',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'202',name:'Kangaskhan',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'203',name:'Team Rocket\'s Wobbuffet',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:14.00,base:false,important:true},
  {n:'204',name:'Cynthia\'s Garchomp ex',type:'Lutador',color:'#FF9800',rare:'Promo',price:38.00,base:false,important:true},
  {n:'205',name:'Team Rocket\'s Mewtwo ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:38.00,base:false,important:true},
  {n:'206',name:'Marnie\'s Morpeko',type:'Sombrio',color:'#607D8B',rare:'Promo',price:14.00,base:false,important:true},
  {n:'207',name:'Steven\'s Beldum',type:'Metal',color:'#78909C',rare:'Promo',price:14.00,base:false,important:true},
  {n:'208',name:'Victini',type:'Fogo',color:'#F44336',rare:'Promo',price:2.00,base:false},
  {n:'209',name:'Thundurus',type:'Raio',color:'#FFEB3B',rare:'Promo',price:2.00,base:false},
  {n:'210',name:'Tornadus',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:2.00,base:false},
  {n:'211',name:'Gothitelle',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'212',name:'Reuniclus',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:2.00,base:false},
  {n:'216',name:'Team Rocket\'s Mewtwo ex',type:'Psíquico',color:'#9C27B0',rare:'Promo',price:38.00,base:false,important:true},
  {n:'217',name:'Team Rocket\'s Nidoking ex',type:'Sombrio',color:'#607D8B',rare:'Promo',price:38.00,base:false,important:true},
  {n:'218',name:'Team Rocket\'s Persian ex',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:38.00,base:false,important:true},
  {n:'219',name:'Black Belt\'s Training',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:3.00,base:false},
  {n:'220',name:'Black Belt\'s Training',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:3.00,base:false},
  {n:'221',name:'Professor\'s Research',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:1.50,base:false},
  {n:'222',name:'Professor\'s Research',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:1.50,base:false},
  {n:'223',name:'Professor\'s Research',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:1.50,base:false},
  {n:'224',name:'Paradise Resort',type:'Incolor',color:'#9E9E9E',rare:'Promo',price:4.00,base:false},
];
