// SV6 — Twilight Masquerade (226 cartas)
// Lançamento EN: 2024/05/24
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV6 = [
  {n:'001',dex:114,artist:"Yoriyuki Ikegami",name:'Tangela',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.16,base:true},
  {n:'002',dex:465,artist:"LINNE",name:'Tangrowth',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'003',dex:127,artist:"HYOGONOSUKE",name:'Pinsir',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.19,base:true},
  {n:'004',dex:167,artist:"Saya Tsuruta",name:'Spinarak',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'005',dex:168,artist:"Anesaki Dynamic",name:'Ariados',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.23,base:true},
  {n:'006',dex:191,artist:"Naoyo Kimura",name:'Sunkern',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.09,base:true},
  {n:'007',dex:192,artist:"Ounishi",name:'Sunflora',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.23,base:true},
  {n:'008',dex:214,artist:"Toshinao Aoki",name:'Heracross',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'009',dex:313,artist:"Orca",name:'Volbeat',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.19,base:true},
  {n:'010',dex:314,artist:"Orca",name:'Illumise',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'011',dex:470,artist:"Kuroimori",name:'Leafeon',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.30,base:true},
  {n:'012',dex:708,artist:"Katsunori Sato",name:'Phantump',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'013',dex:709,artist:"Oswaldo KATO",name:'Trevenant',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.19,base:true},
  {n:'014',dex:810,artist:"Tomomi Ozaki",name:'Grookey',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.39,base:true},
  {n:'015',dex:811,artist:"GOSSAN",name:'Thwackey',type:'Planta',color:'#4CAF50',rare:'Comum',price:11.89,base:true},
  {n:'016',dex:812,artist:"toriyufu",name:'Rillaboom',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.24,base:true},
  {n:'017',dex:840,artist:"OKUBO",name:'Applin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'018',artist:"Saboteri",name:'Dipplin',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.15,base:true},
  {n:'019',dex:1010,artist:"Mitsuhiro Arita",name:'Iron Leaves',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.45,base:true},
  {n:'020',artist:"MINAMINAMI Take",name:'Poltchageist',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.19,base:true},
  {n:'021',artist:"Souichirou Gunjima",name:'Poltchageist',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.19,base:true},
  {n:'022',artist:"Kouki Saitou",name:'Sinistcha',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.25,base:true},
  {n:'023',artist:"aky CG Works",name:'Sinistcha ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.50,base:true},
  {n:'024',artist:"Sanosuke Sakuma",name:'Teal Mask Ogerpon',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.09,base:true},
  {n:'025',artist:"5ban Graphics",name:'Teal Mask Ogerpon ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:20.00,base:true},
  {n:'026',dex:37,artist:"sowsow",name:'Vulpix',type:'Fogo',color:'#F44336',rare:'Comum',price:0.15,base:true},
  {n:'027',dex:38,artist:"KEIICHIRO ITO",name:'Ninetales',type:'Fogo',color:'#F44336',rare:'Comum',price:0.22,base:true},
  {n:'028',dex:218,artist:"Gapao",name:'Slugma',type:'Fogo',color:'#F44336',rare:'Comum',price:0.19,base:true},
  {n:'029',dex:219,artist:"PLANETA Mochizuki",name:'Magcargo ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:1.81,base:true},
  {n:'030',dex:324,artist:"Teeziro",name:'Torkoal',type:'Fogo',color:'#F44336',rare:'Comum',price:0.19,base:true},
  {n:'031',dex:390,artist:"Jerky",name:'Chimchar',type:'Fogo',color:'#F44336',rare:'Comum',price:0.15,base:true},
  {n:'032',dex:391,artist:"Scav",name:'Monferno',type:'Fogo',color:'#F44336',rare:'Comum',price:0.20,base:true},
  {n:'033',dex:392,artist:"Takumi Wada",name:'Infernape',type:'Fogo',color:'#F44336',rare:'Rara',price:0.40,base:true},
  {n:'034',dex:554,artist:"osare",name:'Darumaka',type:'Fogo',color:'#F44336',rare:'Comum',price:0.13,base:true},
  {n:'035',dex:555,artist:"OKUBO",name:'Darmanitan',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.20,base:true},
  {n:'036',dex:607,artist:"Saya Tsuruta",name:'Litwick',type:'Fogo',color:'#F44336',rare:'Comum',price:0.09,base:true},
  {n:'037',dex:608,artist:"Rond",name:'Lampent',type:'Fogo',color:'#F44336',rare:'Comum',price:0.19,base:true},
  {n:'038',dex:609,artist:"saino misaki",name:'Chandelure',type:'Fogo',color:'#F44336',rare:'Rara',price:1.00,base:true},
  {n:'039',dex:1004,artist:"Oku",name:'Chi-Yu',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.25,base:true},
  {n:'040',artist:"5ban Graphics",name:'Hearthflame Mask Ogerpon ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:4.09,base:true},
  {n:'041',dex:60,artist:"Kedamahadaitai Yawarakai",name:'Poliwag',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.19,base:true},
  {n:'042',dex:61,artist:"OKACHEKE",name:'Poliwhirl',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.24,base:true},
  {n:'043',dex:62,artist:"Nisota Niso",name:'Poliwrath',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.30,base:true},
  {n:'044',dex:118,artist:"saino misaki",name:'Goldeen',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.19,base:true},
  {n:'045',dex:119,artist:"Gemi",name:'Seaking',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.16,base:true},
  {n:'046',dex:124,artist:"Gapao",name:'Jynx',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.16,base:true},
  {n:'047',dex:341,artist:"Kouki Saitou",name:'Corphish',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.19,base:true},
  {n:'048',dex:342,artist:"Kurata So",name:'Crawdaunt',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.22,base:true},
  {n:'049',dex:349,artist:"Scav",name:'Feebas',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.15,base:true},
  {n:'050',dex:350,artist:"Taira Akitsu",name:'Milotic',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.20,base:true},
  {n:'051',dex:361,artist:"Mékayu",name:'Snorunt',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'052',dex:362,artist:"Oku",name:'Glalie',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.21,base:true},
  {n:'053',dex:478,artist:"Makura Tami",name:'Froslass',type:'Aquático',color:'#2196F3',rare:'Rara',price:2.90,base:true},
  {n:'054',dex:471,artist:"rika",name:'Glaceon',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.40,base:true},
  {n:'055',dex:489,artist:"aspara",name:'Phione',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.16,base:true},
  {n:'056',dex:656,artist:"Yuka Morii",name:'Froakie',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.24,base:true},
  {n:'057',dex:657,artist:"Hitoshi Ariga",name:'Frogadier',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.25,base:true},
  {n:'058',dex:845,artist:"OKACHEKE",name:'Cramorant',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.19,base:true},
  {n:'059',dex:963,artist:"Narumi Sato",name:'Finizen',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'060',dex:964,artist:"Ligton",name:'Palafin',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.17,base:true},
  {n:'061',dex:964,artist:"PLANETA Mochizuki",name:'Palafin ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:5.00,base:true},
  {n:'062',dex:991,artist:"nagimiso",name:'Iron Bundle',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.17,base:true},
  {n:'063',dex:1009,artist:"kawayoo",name:'Walking Wake',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.30,base:true},
  {n:'064',artist:"5ban Graphics",name:'Wellspring Mask Ogerpon ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:7.00,base:true},
  {n:'065',dex:145,artist:"GOSSAN",name:'Zapdos',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.42,base:true},
  {n:'066',dex:403,artist:"Yuu Nishida",name:'Shinx',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.19,base:true},
  {n:'067',dex:404,artist:"Takumi Wada",name:'Luxio',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.19,base:true},
  {n:'068',dex:405,artist:"PLANETA Yamashita",name:'Luxray ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:5.90,base:true},
  {n:'069',dex:587,artist:"Shimaris Yukichi",name:'Emolga',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.13,base:true},
  {n:'070',dex:694,artist:"Taiga Kayama",name:'Helioptile',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.10,base:true},
  {n:'071',dex:695,artist:"Atsuya Uki",name:'Heliolisk',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.13,base:true},
  {n:'072',dex:877,artist:"kodama",name:'Morpeko',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.19,base:true},
  {n:'073',dex:938,artist:"nisimono",name:'Tadbulb',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'074',dex:939,artist:"Mina Nakai",name:'Bellibolt',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.20,base:true},
  {n:'075',dex:940,artist:"Teeziro",name:'Wattrel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'076',dex:941,artist:"Anesaki Dynamic",name:'Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.09,base:true},
  {n:'077',dex:995,artist:"PLANETA Mochizuki",name:'Iron Thorns ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:4.90,base:true},
  {n:'078',dex:35,artist:"Sanosuke Sakuma",name:'Clefairy',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.24,base:true},
  {n:'079',dex:36,artist:"satoma",name:'Clefable',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.23,base:true},
  {n:'080',dex:63,artist:"Kariya",name:'Abra',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.35,base:true},
  {n:'081',dex:64,artist:"Uninori",name:'Kadabra',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.33,base:true},
  {n:'082',dex:65,artist:"Masako Tomii",name:'Alakazam',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.99,base:true},
  {n:'083',dex:203,artist:"Shinji Kanda",name:'Girafarig',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.16,base:true},
  {n:'084',dex:981,artist:"Dsuke",name:'Farigiraf',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.19,base:true},
  {n:'085',dex:358,artist:"Mousho",name:'Chimecho',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.19,base:true},
  {n:'086',dex:669,artist:"Yukiko Baba",name:'Flabébé',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'087',dex:670,artist:"mingo",name:'Floette',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.25,base:true},
  {n:'088',dex:671,artist:"Ligton",name:'Florges',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.13,base:true},
  {n:'089',dex:684,artist:"Akira Komayama",name:'Swirlix',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.19,base:true},
  {n:'090',dex:685,artist:"mingo",name:'Slurpuff',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.20,base:true},
  {n:'091',dex:769,artist:"Asako Ito",name:'Sandygast',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.16,base:true},
  {n:'092',dex:770,artist:"Uta",name:'Palossand',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'093',dex:905,artist:"DOM",name:'Enamorus',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.46,base:true},
  {n:'094',dex:985,artist:"akagi",name:'Scream Tail ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:3.00,base:true},
  {n:'095',artist:"kodama",name:'Munkidori',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:1.90,base:true},
  {n:'096',artist:"Kouki Saitou",name:'Fezandipiti',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.30,base:true},
  {n:'097',dex:27,artist:"Tetsu Kayama",name:'Sandshrew',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.19,base:true},
  {n:'098',dex:28,artist:"Nisota Niso",name:'Sandslash',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.18,base:true},
  {n:'099',dex:58,artist:"Whisker",name:'Hisuian Growlithe',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.22,base:true},
  {n:'100',dex:59,artist:"SIE NANAHARA",name:'Hisuian Arcanine',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.40,base:true},
  {n:'101',dex:299,artist:"AKIRA EGAWA",name:'Nosepass',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.19,base:true},
  {n:'102',dex:476,artist:"OKUBO",name:'Probopass',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'103',dex:532,artist:"Kouki Saitou",name:'Timburr',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.09,base:true},
  {n:'104',dex:533,artist:"Aya Kusube",name:'Gurdurr',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.22,base:true},
  {n:'105',dex:534,artist:"Takeshi Nakamura",name:'Conkeldurr',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.25,base:true},
  {n:'106',dex:658,artist:"5ban Graphics",name:'Greninja ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:29.90,base:true},
  {n:'107',dex:701,artist:"Shigenori Negishi",name:'Hawlucha',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.09,base:true},
  {n:'108',dex:969,artist:"Miki Tanaka",name:'Glimmet',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.14,base:true},
  {n:'109',dex:970,artist:"Kazumasa Yasukuni",name:'Glimmora',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'110',dex:1003,artist:"Anesaki Dynamic",name:'Ting-Lu',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.45,base:true},
  {n:'111',artist:"Souichirou Gunjima",name:'Okidogi',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.17,base:true},
  {n:'112',artist:"5ban Graphics",name:'Cornerstone Mask Ogerpon ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:7.00,base:true},
  {n:'113',dex:261,artist:"Shibuzoh.",name:'Poochyena',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.16,base:true},
  {n:'114',dex:262,artist:"kawayoo",name:'Mightyena',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'115',dex:543,artist:"Tomokazu Komiya",name:'Venipede',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'116',dex:544,artist:"Krgc",name:'Whirlipede',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.19,base:true},
  {n:'117',dex:545,artist:"Shiburingaru",name:'Scolipede',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.19,base:true},
  {n:'118',dex:986,artist:"danciao",name:'Brute Bonnet',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:1.25,base:true},
  {n:'119',dex:227,artist:"toi8",name:'Skarmory',type:'Metal',color:'#78909C',rare:'Comum',price:0.19,base:true},
  {n:'120',dex:304,artist:"Gapao",name:'Aron',type:'Metal',color:'#78909C',rare:'Comum',price:0.19,base:true},
  {n:'121',dex:305,artist:"takashi shiraishi",name:'Lairon',type:'Metal',color:'#78909C',rare:'Comum',price:0.24,base:true},
  {n:'122',dex:306,artist:"Dsuke",name:'Aggron',type:'Metal',color:'#78909C',rare:'Incomum',price:0.24,base:true},
  {n:'123',dex:485,artist:"AKIRA EGAWA",name:'Heatran',type:'Metal',color:'#78909C',rare:'Rara',price:0.55,base:true},
  {n:'124',dex:965,artist:"Shigenori Negishi",name:'Varoom',type:'Metal',color:'#78909C',rare:'Comum',price:0.09,base:true},
  {n:'125',dex:966,artist:"Hasuno",name:'Revavroom',type:'Metal',color:'#78909C',rare:'Incomum',price:0.20,base:true},
  {n:'126',dex:840,artist:"Teeziro",name:'Applin',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.13,base:true},
  {n:'127',artist:"OKACHEKE",name:'Dipplin',type:'Dragão',color:'#3F51B5',rare:'Incomum',price:0.13,base:true},
  {n:'128',dex:885,artist:"Scav",name:'Dreepy',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.15,base:true},
  {n:'129',dex:886,artist:"cochi8i",name:'Drakloak',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.10,base:true},
  {n:'130',dex:887,artist:"5ban Graphics",name:'Dragapult ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:3.20,base:true},
  {n:'131',dex:978,artist:"Jerky",name:'Tatsugiri',type:'Dragão',color:'#3F51B5',rare:'Incomum',price:0.14,base:true},
  {n:'132',dex:83,artist:"miki kudo",name:'Farfetch\'d',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.24,base:true},
  {n:'133',dex:113,artist:"HYOGONOSUKE",name:'Chansey',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.24,base:true},
  {n:'134',dex:242,artist:"Iwamoto05",name:'Blissey ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:4.99,base:true},
  {n:'135',dex:133,artist:"satoma",name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'136',dex:143,artist:"Souichirou Gunjima",name:'Snorlax',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.30,base:true},
  {n:'137',dex:190,artist:"Mugi Hamada",name:'Aipom',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.19,base:true},
  {n:'138',dex:424,artist:"KEIICHIRO ITO",name:'Ambipom',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'139',dex:580,artist:"Shibuzoh.",name:'Ducklett',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.13,base:true},
  {n:'140',dex:581,artist:"Susumu Maeya",name:'Swanna',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'141',dex:901,artist:"aky CG Works",name:'Bloodmoon Ursaluna ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:4.80,base:true},
  {n:'142',artist:"AYUMI ODASHIMA",name:'Accompanying Flute',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'143',artist:"AYUMI ODASHIMA",name:'Bug Catching Set',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'144',artist:"Akira Komayama",name:'Caretaker',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.16,base:true},
  {n:'145',artist:"kantaro",name:'Carmine',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'146',artist:"MARINA Chikazawa",name:'Community Center',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'147',artist:"Hideki Ishikawa",name:'Cook',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.19,base:true},
  {n:'148',artist:"Eske Yoshinob",name:'Enhanced Hammer',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'149',artist:"MARINA Chikazawa",name:'Festival Grounds',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'150',artist:"Toyste Beach",name:'Handheld Fan',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:10.90,base:true},
  {n:'151',artist:"GOSSAN",name:'Hassel',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.30,base:true},
  {n:'152',artist:"Toyste Beach",name:'Hyper Aroma',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:2.50,base:false},
  {n:'153',artist:"AYUMI ODASHIMA",name:'Jamming Tower',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.45,base:true},
  {n:'154',artist:"GIDORA",name:'Kieran',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'155',artist:"Atsushi Furusawa",name:'Lana\'s Aid',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.30,base:true},
  {n:'156',artist:"Studio Bora Inc.",name:'Love Ball',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'157',artist:"hncl",name:'Lucian',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'158',artist:"Studio Bora Inc.",name:'Lucky Helmet',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:10.00,base:true},
  {n:'159',artist:"5ban Graphics",name:'Ogre\'s Mask',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'160',artist:"Naoki Saito",name:'Perrin',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.16,base:true},
  {n:'161',artist:"hncl",name:'Raifort',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.17,base:true},
  {n:'162',artist:"Toyste Beach",name:'Scoop Up Cyclone',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:5.00,base:false},
  {n:'163',artist:"Toyste Beach",name:'Secret Box',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:47.50,base:false},
  {n:'164',artist:"inose yukie",name:'Survival Brace',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:4.80,base:false},
  {n:'165',artist:"Toyste Beach",name:'Unfair Stamp',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:48.00,base:false,important:true},
  {n:'166',name:'Boomerang Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.49,base:true},
  {n:'167',name:'Legacy Energy',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:59.90,base:false},
  {n:'168',dex:127,artist:"Yukihiro Tada",name:'Pinsir',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:45.90,base:false,important:true},
  {n:'169',dex:192,artist:"Shinya Komatsu",name:'Sunflora',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:37.98,base:false,important:true},
  {n:'170',artist:"Akira Komayama",name:'Dipplin',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:69.90,base:false,important:true},
  {n:'171',artist:"Saboteri",name:'Poltchageist',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:23.00,base:false},
  {n:'172',dex:324,artist:"Masa",name:'Torkoal',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:29.50,base:false},
  {n:'173',dex:392,artist:"Krgc",name:'Infernape',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:49.90,base:false,important:true},
  {n:'174',dex:478,artist:"matazo",name:'Froslass',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:73.90,base:false},
  {n:'175',dex:489,artist:"takashi shiraishi",name:'Phione',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:26.90,base:false,important:true},
  {n:'176',dex:845,artist:"Fujimoto Gold",name:'Cramorant',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:27.90,base:false},
  {n:'177',dex:695,artist:"Tonji Matsuno",name:'Heliolisk',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:17.00,base:false},
  {n:'178',dex:940,artist:"Mitsuhiro Arita",name:'Wattrel',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:29.90,base:false},
  {n:'179',dex:358,artist:"REND",name:'Chimecho',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:15.00,base:false},
  {n:'180',dex:905,artist:"GOTO minori",name:'Enamorus',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:63.99,base:false},
  {n:'181',dex:58,artist:"GIDORA",name:'Hisuian Growlithe',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:149.99,base:false,important:true},
  {n:'182',dex:476,artist:"Kariya",name:'Probopass',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:19.90,base:false},
  {n:'183',dex:532,artist:"Yuriko Akase",name:'Timburr',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:26.89,base:false},
  {n:'184',dex:305,artist:"Dsuke",name:'Lairon',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:47.41,base:false},
  {n:'185',dex:840,artist:"Katsunori Sato",name:'Applin',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada',price:84.14,base:false,important:true},
  {n:'186',dex:978,artist:"osare",name:'Tatsugiri',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada',price:49.99,base:false,important:true},
  {n:'187',dex:113,artist:"Toshinao Aoki",name:'Chansey',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:168.00,base:false,important:true},
  {n:'188',dex:133,artist:"Narumi Sato",name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:219.90,base:false,important:true},
  {n:'189',artist:"aky CG Works",name:'Sinistcha ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:5.00,base:false},
  {n:'190',artist:"5ban Graphics",name:'Teal Mask Ogerpon ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:48.40,base:false},
  {n:'191',dex:219,artist:"PLANETA Yamashita",name:'Magcargo ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:9.50,base:false},
  {n:'192',artist:"5ban Graphics",name:'Hearthflame Mask Ogerpon ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:9.75,base:false},
  {n:'193',dex:964,artist:"PLANETA Mochizuki",name:'Palafin ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:12.95,base:false},
  {n:'194',artist:"5ban Graphics",name:'Wellspring Mask Ogerpon ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:28.88,base:false},
  {n:'195',dex:405,artist:"PLANETA Yamashita",name:'Luxray ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:8.90,base:false},
  {n:'196',dex:995,artist:"PLANETA Mochizuki",name:'Iron Thorns ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:34.80,base:false},
  {n:'197',dex:985,artist:"PLANETA Hiiragi",name:'Scream Tail ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:11.90,base:false},
  {n:'198',dex:658,artist:"5ban Graphics",name:'Greninja ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:115.00,base:false,important:true},
  {n:'199',artist:"5ban Graphics",name:'Cornerstone Mask Ogerpon ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:18.00,base:false},
  {n:'200',dex:887,artist:"5ban Graphics",name:'Dragapult ex',type:'Dragão',color:'#3F51B5',rare:'Ultra Rara',price:99.00,base:false,important:true},
  {n:'201',dex:242,artist:"PLANETA Tsuji",name:'Blissey ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:16.00,base:false},
  {n:'202',dex:901,artist:"aky CG Works",name:'Bloodmoon Ursaluna ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:17.90,base:false},
  {n:'203',artist:"Akira Komayama",name:'Caretaker',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:6.50,base:false},
  {n:'204',artist:"kantaro",name:'Carmine',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:44.90,base:false},
  {n:'205',artist:"GOSSAN",name:'Hassel',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:34.90,base:false},
  {n:'206',artist:"GIDORA",name:'Kieran',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:19.99,base:false},
  {n:'207',artist:"Atsushi Furusawa",name:'Lana\'s Aid',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:60.00,base:false},
  {n:'208',artist:"hncl",name:'Lucian',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:18.00,base:false},
  {n:'209',artist:"Naoki Saito",name:'Perrin',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:29.90,base:false},
  {n:'210',artist:"Saboteri",name:'Sinistcha ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:60.00,base:false,important:true},
  {n:'211',artist:"Yano Keiji",name:'Teal Mask Ogerpon ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:119.90,base:false,important:true},
  {n:'212',artist:"Yano Keiji",name:'Hearthflame Mask Ogerpon ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:49.90,base:false,important:true},
  {n:'213',artist:"Yano Keiji",name:'Wellspring Mask Ogerpon ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:88.00,base:false,important:true},
  {n:'214',dex:658,artist:"akagi",name:'Greninja ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:619.90,base:false,important:true},
  {n:'215',artist:"Yano Keiji",name:'Cornerstone Mask Ogerpon ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:89.00,base:false,important:true},
  {n:'216',dex:901,artist:"MINAMINAMI Take",name:'Bloodmoon Ursaluna ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:149.90,base:false,important:true},
  {n:'217',artist:"En Morikura",name:'Carmine',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:199.99,base:false,important:true},
  {n:'218',artist:"Teeziro",name:'Kieran',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:108.00,base:false,important:true},
  {n:'219',artist:"Toshinao Aoki",name:'Lana\'s Aid',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:269.99,base:false,important:true},
  {n:'220',artist:"GIDORA",name:'Perrin',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:650.00,base:false,important:true},
  {n:'221',artist:"5ban Graphics",name:'Teal Mask Ogerpon ex',type:'Planta',color:'#4CAF50',rare:'Hiper Rara',price:54.90,base:false,important:true},
  {n:'222',dex:901,artist:"aky CG Works",name:'Bloodmoon Ursaluna ex',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:69.00,base:false,important:true},
  {n:'223',artist:"AYUMI ODASHIMA",name:'Buddy-Buddy Poffin',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:74.90,base:false,important:true},
  {n:'224',artist:"Eske Yoshinob",name:'Enhanced Hammer',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:39.75,base:false},
  {n:'225',artist:"Toyste Beach",name:'Rescue Board',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:23.89,base:false},
  {n:'226',name:'Luminous Energy',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:44.99,base:false}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV6 = CARDS_SV6;