// SV10 — Destined Rivals (244 cartas)
// Lançamento EN: 2025/05/30
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV10 = [
  {n:'001',name:'Ethan\'s Pinsir',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.15,base:true},
  {n:'002',name:'Yanma',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'003',name:'Yanmega ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:4.20,base:true},
  {n:'004',name:'Pineco',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'005',name:'Shroomish',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'006',name:'Breloom',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'007',name:'Cynthia\'s Roselia',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'008',name:'Cynthia\'s Roserade',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.25,base:true},
  {n:'009',name:'Mow Rotom',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'010',name:'Shaymin',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.85,base:true},
  {n:'011',name:'Dwebble',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.18,base:true},
  {n:'012',name:'Crustle',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.68,base:true},
  {n:'013',name:'Fomantis',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'014',name:'Lurantis',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.12,base:true},
  {n:'015',name:'Team Rocket\'s Blipbug',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'016',name:'Applin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.12,base:true},
  {n:'017',name:'Dipplin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'018',name:'Hydrapple',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.20,base:true},
  {n:'019',name:'Team Rocket\'s Tarountula',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'020',name:'Team Rocket\'s Spidops',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.44,base:true},
  {n:'021',name:'Smoliv',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'022',name:'Dolliv',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.19,base:true},
  {n:'023',name:'Arboliva ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:6.00,base:true},
  {n:'024',name:'Rellor',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'025',name:'Rabsca ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:2.99,base:true},
  {n:'026',name:'Teal Mask Ogerpon',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.10,base:true},
  {n:'027',name:'Growlithe',type:'Fogo',color:'#F44336',rare:'Comum',price:0.15,base:true},
  {n:'028',name:'Arcanine',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.19,base:true},
  {n:'029',name:'Ponyta',type:'Fogo',color:'#F44336',rare:'Comum',price:0.20,base:true},
  {n:'030',name:'Rapidash',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.14,base:true},
  {n:'031',name:'Team Rocket\'s Moltres ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:4.49,base:true},
  {n:'032',name:'Ethan\'s Cyndaquil',type:'Fogo',color:'#F44336',rare:'Comum',price:0.19,base:true},
  {n:'033',name:'Ethan\'s Quilava',type:'Fogo',color:'#F44336',rare:'Comum',price:0.25,base:true},
  {n:'034',name:'Ethan\'s Typhlosion',type:'Fogo',color:'#F44336',rare:'Rara',price:1.00,base:true},
  {n:'035',name:'Ethan\'s Slugma',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'036',name:'Ethan\'s Magcargo',type:'Fogo',color:'#F44336',rare:'Rara',price:0.21,base:true},
  {n:'037',name:'Team Rocket\'s Houndour',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'038',name:'Team Rocket\'s Houndoom',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.17,base:true},
  {n:'039',name:'Ethan\'s Ho-Oh ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:4.40,base:true},
  {n:'040',name:'Torchic',type:'Fogo',color:'#F44336',rare:'Comum',price:0.14,base:true},
  {n:'041',name:'Combusken',type:'Fogo',color:'#F44336',rare:'Comum',price:0.15,base:true},
  {n:'042',name:'Blaziken',type:'Fogo',color:'#F44336',rare:'Rara',price:0.25,base:true},
  {n:'043',name:'Heat Rotom',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'044',name:'Hearthflame Mask Ogerpon',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.13,base:true},
  {n:'045',name:'Misty\'s Psyduck',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.20,base:true},
  {n:'046',name:'Misty\'s Staryu',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'047',name:'Misty\'s Starmie',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.17,base:true},
  {n:'048',name:'Misty\'s Magikarp',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'049',name:'Misty\'s Gyarados',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.29,base:true},
  {n:'050',name:'Misty\'s Lapras',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.12,base:true},
  {n:'051',name:'Team Rocket\'s Articuno',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.75,base:true},
  {n:'052',name:'Cynthia\'s Feebas',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'053',name:'Cynthia\'s Milotic',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.13,base:true},
  {n:'054',name:'Clamperl',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.15,base:true},
  {n:'055',name:'Huntail',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.14,base:true},
  {n:'056',name:'Gorebyss',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.19,base:true},
  {n:'057',name:'Buizel',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.15,base:true},
  {n:'058',name:'Floatzel',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.10,base:true},
  {n:'059',name:'Snover',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'060',name:'Abomasnow',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.10,base:true},
  {n:'061',name:'Wash Rotom',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'062',name:'Arrokuda',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.18,base:true},
  {n:'063',name:'Barraskewda',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.10,base:true},
  {n:'064',name:'Cetoddle',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'065',name:'Cetitan ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:2.99,base:true},
  {n:'066',name:'Dondozo ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:3.00,base:true},
  {n:'067',name:'Wellspring Mask Ogerpon',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.13,base:true},
  {n:'068',name:'Electabuzz',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.10,base:true},
  {n:'069',name:'Electivire ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:2.50,base:true},
  {n:'070',name:'Team Rocket\'s Zapdos',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.29,base:true},
  {n:'071',name:'Ethan\'s Pichu',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.18,base:true},
  {n:'072',name:'Team Rocket\'s Mareep',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.11,base:true},
  {n:'073',name:'Team Rocket\'s Flaaffy',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'074',name:'Team Rocket\'s Ampharos',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.15,base:true},
  {n:'075',name:'Electrike',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.11,base:true},
  {n:'076',name:'Manectric',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.11,base:true},
  {n:'077',name:'Rotom',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'078',name:'Zeraora',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.23,base:true},
  {n:'079',name:'Team Rocket\'s Drowzee',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'080',name:'Team Rocket\'s Hypno',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.18,base:true},
  {n:'081',name:'Team Rocket\'s Mewtwo ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:4.35,base:true},
  {n:'082',name:'Team Rocket\'s Wobbuffet',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.20,base:true},
  {n:'083',name:'Steven\'s Baltoy',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'084',name:'Steven\'s Claydol',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.14,base:true},
  {n:'085',name:'Team Rocket\'s Chingling',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'086',name:'Steven\'s Carbink',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.16,base:true},
  {n:'087',name:'Team Rocket\'s Mimikyu',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'088',name:'Team Rocket\'s Dottler',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'089',name:'Team Rocket\'s Orbeetle',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.16,base:true},
  {n:'090',name:'Mankey',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.13,base:true},
  {n:'091',name:'Primeape',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'092',name:'Annihilape',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.21,base:true},
  {n:'093',name:'Ethan\'s Sudowoodo',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.07,base:true},
  {n:'094',name:'Team Rocket\'s Larvitar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'095',name:'Team Rocket\'s Pupitar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.14,base:true},
  {n:'096',name:'Team Rocket\'s Tyranitar',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.20,base:true},
  {n:'097',name:'Nosepass',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.14,base:true},
  {n:'098',name:'Probopass',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.13,base:true},
  {n:'099',name:'Meditite',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.16,base:true},
  {n:'100',name:'Medicham',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.16,base:true},
  {n:'101',name:'Regirock ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:2.99,base:true},
  {n:'102',name:'Cynthia\'s Gible',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'103',name:'Cynthia\'s Gabite',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.25,base:true},
  {n:'104',name:'Cynthia\'s Garchomp ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:8.50,base:true},
  {n:'105',name:'Hippopotas',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'106',name:'Hippowdon',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.12,base:true},
  {n:'107',name:'Mudbray',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.12,base:true},
  {n:'108',name:'Mudsdale',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.12,base:true},
  {n:'109',name:'Arven\'s Toedscool',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.09,base:true},
  {n:'110',name:'Arven\'s Toedscruel',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.14,base:true},
  {n:'111',name:'Cornerstone Mask Ogerpon',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.17,base:true},
  {n:'112',name:'Team Rocket\'s Ekans',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'113',name:'Team Rocket\'s Arbok',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'114',name:'Team Rocket\'s Nidoran♀',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'115',name:'Team Rocket\'s Nidorina',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.11,base:true},
  {n:'116',name:'Team Rocket\'s Nidoqueen',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'117',name:'Team Rocket\'s Nidoran♂',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'118',name:'Team Rocket\'s Nidorino',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.23,base:true},
  {n:'119',name:'Team Rocket\'s Nidoking ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:4.00,base:true},
  {n:'120',name:'Team Rocket\'s Zubat',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'121',name:'Team Rocket\'s Golbat',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'122',name:'Team Rocket\'s Crobat ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:3.00,base:true},
  {n:'123',name:'Team Rocket\'s Grimer',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.08,base:true},
  {n:'124',name:'Team Rocket\'s Muk',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'125',name:'Team Rocket\'s Koffing',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'126',name:'Team Rocket\'s Weezing',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  {n:'127',name:'Team Rocket\'s Murkrow',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  {n:'128',name:'Team Rocket\'s Sneasel',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.23,base:true},
  {n:'129',name:'Cynthia\'s Spiritomb',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'130',name:'Marnie\'s Purrloin',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.14,base:true},
  {n:'131',name:'Marnie\'s Liepard',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'132',name:'Marnie\'s Scraggy',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'133',name:'Marnie\'s Scrafty',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'134',name:'Marnie\'s Impidimp',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'135',name:'Marnie\'s Morgrem',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  {n:'136',name:'Marnie\'s Grimmsnarl ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:5.00,base:true},
  {n:'137',name:'Marnie\'s Morpeko',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'138',name:'Arven\'s Maschiff',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'139',name:'Arven\'s Mabosstiff ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:3.00,base:true},
  {n:'140',name:'Forretress',type:'Metal',color:'#78909C',rare:'Incomum',price:0.09,base:true},
  {n:'141',name:'Skarmory',type:'Metal',color:'#78909C',rare:'Comum',price:0.13,base:true},
  {n:'142',name:'Steven\'s Skarmory',type:'Metal',color:'#78909C',rare:'Comum',price:0.17,base:true},
  {n:'143',name:'Steven\'s Beldum',type:'Metal',color:'#78909C',rare:'Comum',price:0.12,base:true},
  {n:'144',name:'Steven\'s Metang',type:'Metal',color:'#78909C',rare:'Incomum',price:0.15,base:true},
  {n:'145',name:'Steven\'s Metagross ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:4.50,base:true},
  {n:'146',name:'Zamazenta',type:'Metal',color:'#78909C',rare:'Rara',price:0.20,base:true},
  {n:'147',name:'Team Rocket\'s Rattata',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'148',name:'Team Rocket\'s Raticate',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.14,base:true},
  {n:'149',name:'Team Rocket\'s Meowth',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.09,base:true},
  {n:'150',name:'Team Rocket\'s Persian ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:2.99,base:true},
  {n:'151',name:'Kangaskhan',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'152',name:'Tauros',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.18,base:true},
  {n:'153',name:'Team Rocket\'s Porygon',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.12,base:true},
  {n:'154',name:'Team Rocket\'s Porygon2',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.34,base:true},
  {n:'155',name:'Team Rocket\'s Porygon-Z',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.24,base:true},
  {n:'156',name:'Taillow',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.18,base:true},
  {n:'157',name:'Swellow',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'158',name:'Arven\'s Skwovet',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'159',name:'Arven\'s Greedent',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.15,base:true},
  {n:'160',name:'Squawkabilly',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.14,base:true},
  {n:'161',name:'Arven\'s Sandwich',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'162',name:'Cynthia\'s Power Weight',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.23,base:true},
  {n:'163',name:'Emcee\'s Hype',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'164',name:'Energy Recycler',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.16,base:true},
  {n:'165',name:'Ethan\'s Adventure',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'166',name:'Granite Cave',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'167',name:'Judge',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'168',name:'Sacred Ash',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.19,base:true},
  {n:'169',name:'Spikemuth Gym',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.19,base:true},
  {n:'170',name:'Team Rocket\'s Archer',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'171',name:'Team Rocket\'s Ariana',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'172',name:'Team Rocket\'s Bother-Bot',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.13,base:true},
  {n:'173',name:'Team Rocket\'s Factory',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'174',name:'Team Rocket\'s Giovanni',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.30,base:true},
  {n:'175',name:'Team Rocket\'s Great Ball',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.14,base:true},
  {n:'176',name:'Team Rocket\'s Petrel',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:2.25,base:true},
  {n:'177',name:'Team Rocket\'s Proton',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'178',name:'Team Rocket\'s Transceiver',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.30,base:true},
  {n:'179',name:'Team Rocket\'s Venture Bomb',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.14,base:true},
  {n:'180',name:'Team Rocket\'s Watchtower',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.30,base:true},
  {n:'181',name:'TM Machine',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.18,base:true},
  {n:'182',name:'Team Rocket\'s Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.50,base:true},
  {n:'183',name:'Yanma',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:32.99,base:false},
  {n:'184',name:'Cynthia\'s Roserade',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:89.90,base:false,important:true},
  {n:'185',name:'Shaymin',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:57.99,base:false,important:true},
  {n:'186',name:'Crustle',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:25.00,base:false},
  {n:'187',name:'Team Rocket\'s Spidops',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:46.90,base:false},
  {n:'188',name:'Hydrapple',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:19.00,base:false},
  {n:'189',name:'Rapidash',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:34.90,base:false,important:true},
  {n:'190',name:'Ethan\'s Typhlosion',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:110.00,base:false,important:true},
  {n:'191',name:'Team Rocket\'s Houndoom',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:60.99,base:false,important:true},
  {n:'192',name:'Blaziken',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:35.00,base:false,important:true},
  {n:'193',name:'Misty\'s Psyduck',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:300.00,base:false,important:true},
  {n:'194',name:'Misty\'s Lapras',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:199.00,base:false,important:true},
  {n:'195',name:'Clamperl',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:24.89,base:false},
  {n:'196',name:'Electrike',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:14.90,base:false},
  {n:'197',name:'Rotom',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:13.00,base:false},
  {n:'198',name:'Team Rocket\'s Orbeetle',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:17.90,base:false},
  {n:'199',name:'Team Rocket\'s Weezing',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:49.79,base:false,important:true},
  {n:'200',name:'Team Rocket\'s Murkrow',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:50.00,base:false,important:true},
  {n:'201',name:'Zamazenta',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:19.90,base:false},
  {n:'202',name:'Team Rocket\'s Raticate',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:35.00,base:false},
  {n:'203',name:'Team Rocket\'s Meowth',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:115.90,base:false,important:true},
  {n:'204',name:'Kangaskhan',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:39.90,base:false,important:true},
  {n:'205',name:'Arven\'s Greedent',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:19.90,base:false},
  {n:'206',name:'Yanmega ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:9.90,base:false},
  {n:'207',name:'Arboliva ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:24.99,base:false},
  {n:'208',name:'Team Rocket\'s Moltres ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:22.90,base:false},
  {n:'209',name:'Ethan\'s Ho-Oh ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:20.00,base:false},
  {n:'210',name:'Cetitan ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:9.00,base:false},
  {n:'211',name:'Dondozo ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:4.99,base:false},
  {n:'212',name:'Electivire ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:8.50,base:false},
  {n:'213',name:'Team Rocket\'s Mewtwo ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:105.90,base:false,important:true},
  {n:'214',name:'Regirock ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:8.00,base:false},
  {n:'215',name:'Cynthia\'s Garchomp ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:26.90,base:false},
  {n:'216',name:'Team Rocket\'s Nidoking ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:21.90,base:false},
  {n:'217',name:'Team Rocket\'s Crobat ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:14.99,base:false},
  {n:'218',name:'Arven\'s Mabosstiff ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:9.50,base:false},
  {n:'219',name:'Team Rocket\'s Persian ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:23.99,base:false},
  {n:'220',name:'Emcee\'s Hype',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:19.90,base:false},
  {n:'221',name:'Ethan\'s Adventure',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:39.50,base:false},
  {n:'222',name:'Judge',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:23.00,base:false},
  {n:'223',name:'Team Rocket\'s Archer',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:29.90,base:false},
  {n:'224',name:'Team Rocket\'s Ariana',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:42.50,base:false},
  {n:'225',name:'Team Rocket\'s Giovanni',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:72.00,base:false},
  {n:'226',name:'Team Rocket\'s Petrel',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:85.00,base:false,important:true},
  {n:'227',name:'Team Rocket\'s Proton',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:45.00,base:false},
  {n:'228',name:'Yanmega ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:75.00,base:false,important:true},
  {n:'229',name:'Team Rocket\'s Moltres ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:299.90,base:false,important:true},
  {n:'230',name:'Ethan\'s Ho-Oh ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:535.00,base:false,important:true},
  {n:'231',name:'Team Rocket\'s Mewtwo ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:1350.00,base:false,important:true},
  {n:'232',name:'Cynthia\'s Garchomp ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:789.90,base:false,important:true},
  {n:'233',name:'Team Rocket\'s Nidoking ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:396.00,base:false,important:true},
  {n:'234',name:'Team Rocket\'s Crobat ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:350.00,base:false,important:true},
  {n:'235',name:'Arven\'s Mabosstiff ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:85.00,base:false,important:true},
  {n:'236',name:'Ethan\'s Adventure',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:144.42,base:false,important:true},
  {n:'237',name:'Team Rocket\'s Ariana',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:100.00,base:false,important:true},
  {n:'238',name:'Team Rocket\'s Giovanni',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:215.90,base:false,important:true},
  {n:'239',name:'Ethan\'s Ho-Oh ex',type:'Fogo',color:'#F44336',rare:'Hiper Rara',price:99.99,base:false,important:true},
  {n:'240',name:'Team Rocket\'s Mewtwo ex',type:'Psíquico',color:'#9C27B0',rare:'Hiper Rara',price:329.90,base:false,important:true},
  {n:'241',name:'Cynthia\'s Garchomp ex',type:'Lutador',color:'#FF9800',rare:'Hiper Rara',price:169.99,base:false,important:true},
  {n:'242',name:'Team Rocket\'s Crobat ex',type:'Sombrio',color:'#607D8B',rare:'Hiper Rara',price:89.90,base:false,important:true},
  {n:'243',name:'Jamming Tower',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:84.55,base:false,important:true},
  {n:'244',name:'Levincia',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:38.25,base:false,important:true}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV10 = CARDS_SV10;