// SV3PT5 — 151 (207 cartas)
// Lançamento EN: 2023/09/22
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV3PT5 = [
  {n:'001',dex:1,artist:"Yuu Nishida",name:'Bulbasaur',type:'Planta',color:'#4CAF50',rare:'Comum',price:1.00,base:true},
  {n:'002',dex:2,artist:"Yuu Nishida",name:'Ivysaur',type:'Planta',color:'#4CAF50',rare:'Incomum',price:2.90,base:true},
  {n:'003',dex:3,artist:"5ban Graphics",name:'Venusaur ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:14.25,base:true},
  {n:'004',dex:4,artist:"GIDORA",name:'Charmander',type:'Fogo',color:'#F44336',rare:'Comum',price:0.25,base:true},
  {n:'005',dex:5,artist:"GIDORA",name:'Charmeleon',type:'Fogo',color:'#F44336',rare:'Incomum',price:1.00,base:true},
  {n:'006',dex:6,artist:"PLANETA Mochizuki",name:'Charizard ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:69.90,base:true},
  {n:'007',dex:7,artist:"kantaro",name:'Squirtle',type:'Aquático',color:'#2196F3',rare:'Comum',price:9.90,base:true},
  {n:'008',dex:8,artist:"kantaro",name:'Wartortle',type:'Aquático',color:'#2196F3',rare:'Incomum',price:4.99,base:true},
  {n:'009',dex:9,artist:"PLANETA Yamashita",name:'Blastoise ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:16.90,base:true},
  {n:'010',dex:10,artist:"Tika Matsuno",name:'Caterpie',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'011',dex:11,artist:"Tika Matsuno",name:'Metapod',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.99,base:true},
  {n:'012',dex:12,artist:"Tika Matsuno",name:'Butterfree',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.50,base:true},
  {n:'013',dex:13,artist:"nisimono",name:'Weedle',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'014',dex:14,artist:"nisimono",name:'Kakuna',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.50,base:true},
  {n:'015',dex:15,artist:"nisimono",name:'Beedrill',type:'Planta',color:'#4CAF50',rare:'Rara',price:1.00,base:true},
  {n:'016',dex:16,artist:"Oswaldo KATO",name:'Pidgey',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.19,base:true},
  {n:'017',dex:17,artist:"Oswaldo KATO",name:'Pidgeotto',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.30,base:true},
  {n:'018',dex:18,artist:"Oswaldo KATO",name:'Pidgeot',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.40,base:true},
  {n:'019',dex:19,artist:"sowsow",name:'Rattata',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'020',dex:20,artist:"sowsow",name:'Raticate',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.49,base:true},
  {n:'021',dex:21,artist:"Gemi",name:'Spearow',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.32,base:true},
  {n:'022',dex:22,artist:"Gemi",name:'Fearow',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'023',dex:23,artist:"Kedamahadaitai Yawarakai",name:'Ekans',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.20,base:true},
  {n:'024',dex:24,artist:"Eske Yoshinob",name:'Arbok ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:22.99,base:true},
  {n:'025',dex:25,artist:"Naoyo Kimura",name:'Pikachu',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.99,base:true},
  {n:'026',dex:26,artist:"Naoyo Kimura",name:'Raichu',type:'Raio',color:'#FFEB3B',rare:'Rara',price:2.25,base:true},
  {n:'027',dex:27,artist:"kodama",name:'Sandshrew',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.25,base:true},
  {n:'028',dex:28,artist:"kodama",name:'Sandslash',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.32,base:true},
  {n:'029',dex:29,artist:"Teeziro",name:'Nidoran ♀',type:'Sombrio',color:'#607D8B',rare:'Comum',price:1.00,base:true},
  {n:'030',dex:30,artist:"Teeziro",name:'Nidorina',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.45,base:true},
  {n:'031',dex:31,artist:"Teeziro",name:'Nidoqueen',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.95,base:true},
  {n:'032',dex:32,artist:"Shiburingaru",name:'Nidoran ♂',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.90,base:true},
  {n:'033',dex:33,artist:"Shiburingaru",name:'Nidorino',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.60,base:true},
  {n:'034',dex:34,artist:"Shiburingaru",name:'Nidoking',type:'Sombrio',color:'#607D8B',rare:'Rara',price:5.00,base:true},
  {n:'035',dex:35,artist:"ryoma uratsuka",name:'Clefairy',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'036',dex:36,artist:"ryoma uratsuka",name:'Clefable',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.25,base:true},
  {n:'037',dex:37,artist:"kawayoo",name:'Vulpix',type:'Fogo',color:'#F44336',rare:'Comum',price:0.25,base:true},
  {n:'038',dex:38,artist:"kawayoo",name:'Ninetales ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:5.00,base:true},
  {n:'039',dex:39,artist:"saino misaki",name:'Jigglypuff',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.30,base:true},
  {n:'040',dex:40,artist:"Saki Hayashiro",name:'Wigglytuff ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:14.60,base:true},
  {n:'041',dex:41,artist:"Scav",name:'Zubat',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'042',dex:42,artist:"Scav",name:'Golbat',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.25,base:true},
  {n:'043',dex:43,artist:"Sekio",name:'Oddish',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.25,base:true},
  {n:'044',dex:44,artist:"Sekio",name:'Gloom',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.45,base:true},
  {n:'045',dex:45,artist:"Sekio",name:'Vileplume',type:'Planta',color:'#4CAF50',rare:'Rara',price:1.99,base:true},
  {n:'046',dex:46,artist:"Yoriyuki Ikegami",name:'Paras',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.25,base:true},
  {n:'047',dex:47,artist:"Yoriyuki Ikegami",name:'Parasect',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.49,base:true},
  {n:'048',dex:48,artist:"Kagemaru Himeno",name:'Venonat',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.49,base:true},
  {n:'049',dex:49,artist:"Kagemaru Himeno",name:'Venomoth',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.50,base:true},
  {n:'050',dex:50,artist:"Miki Tanaka",name:'Diglett',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.25,base:true},
  {n:'051',dex:51,artist:"Miki Tanaka",name:'Dugtrio',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.40,base:true},
  {n:'052',dex:52,artist:"Naoki Saito",name:'Meowth',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.45,base:true},
  {n:'053',dex:53,artist:"Naoki Saito",name:'Persian',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.49,base:true},
  {n:'054',dex:54,artist:"Taira Akitsu",name:'Psyduck',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.50,base:true},
  {n:'055',dex:55,artist:"Taira Akitsu",name:'Golduck',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.45,base:true},
  {n:'056',dex:56,artist:"Mina Nakai",name:'Mankey',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.25,base:true},
  {n:'057',dex:57,artist:"Mina Nakai",name:'Primeape',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'058',dex:58,artist:"Atsushi Furusawa",name:'Growlithe',type:'Fogo',color:'#F44336',rare:'Comum',price:0.20,base:true},
  {n:'059',dex:59,artist:"Atsushi Furusawa",name:'Arcanine',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.95,base:true},
  {n:'060',dex:60,artist:"Kurata So",name:'Poliwag',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.30,base:true},
  {n:'061',dex:61,artist:"Kurata So",name:'Poliwhirl',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.75,base:true},
  {n:'062',dex:62,artist:"Kurata So",name:'Poliwrath',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.25,base:true},
  {n:'063',dex:63,artist:"Mitsuhiro Arita",name:'Abra',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.49,base:true},
  {n:'064',dex:64,artist:"Mitsuhiro Arita",name:'Kadabra',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.90,base:true},
  {n:'065',dex:65,artist:"Mitsuhiro Arita",name:'Alakazam ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:12.50,base:true},
  {n:'066',dex:66,artist:"Ryuta Fuse",name:'Machop',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.30,base:true},
  {n:'067',dex:67,artist:"Ryuta Fuse",name:'Machoke',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.49,base:true},
  {n:'068',dex:68,artist:"Ryuta Fuse",name:'Machamp',type:'Lutador',color:'#FF9800',rare:'Rara',price:3.99,base:true},
  {n:'069',dex:69,artist:"Jerky",name:'Bellsprout',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.30,base:true},
  {n:'070',dex:70,artist:"Jerky",name:'Weepinbell',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'071',dex:71,artist:"Jerky",name:'Victreebel',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.50,base:true},
  {n:'072',dex:72,artist:"miki kudo",name:'Tentacool',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'073',dex:73,artist:"miki kudo",name:'Tentacruel',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.40,base:true},
  {n:'074',dex:74,artist:"Uta",name:'Geodude',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.25,base:true},
  {n:'075',dex:75,artist:"Uta",name:'Graveler',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'076',dex:76,artist:"Uta",name:'Golem ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:10.99,base:true},
  {n:'077',dex:77,artist:"Nurikabe",name:'Ponyta',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'078',dex:78,artist:"Nurikabe",name:'Rapidash',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.25,base:true},
  {n:'079',dex:79,artist:"OKACHEKE",name:'Slowpoke',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.25,base:true},
  {n:'080',dex:80,artist:"OKACHEKE",name:'Slowbro',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.40,base:true},
  {n:'081',dex:81,artist:"Yuka Morii",name:'Magnemite',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.20,base:true},
  {n:'082',dex:82,artist:"Yuka Morii",name:'Magneton',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.50,base:true},
  {n:'083',dex:83,artist:"KG-2000",name:'Farfetch\'d',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.30,base:true},
  {n:'084',dex:84,artist:"Anesaki Dynamic",name:'Doduo',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.25,base:true},
  {n:'085',dex:85,artist:"Anesaki Dynamic",name:'Dodrio',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:3.99,base:true},
  {n:'086',dex:86,artist:"aoki",name:'Seel',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'087',dex:87,artist:"aoki",name:'Dewgong',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.49,base:true},
  {n:'088',dex:88,artist:"Nisota Niso",name:'Grimer',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.30,base:true},
  {n:'089',dex:89,artist:"Nisota Niso",name:'Muk',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.47,base:true},
  {n:'090',dex:90,artist:"Nelnal",name:'Shellder',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.39,base:true},
  {n:'091',dex:91,artist:"Nelnal",name:'Cloyster',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.70,base:true},
  {n:'092',dex:92,artist:"Tomokazu Komiya",name:'Gastly',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.49,base:true},
  {n:'093',dex:93,artist:"Tomokazu Komiya",name:'Haunter',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:1.00,base:true},
  {n:'094',dex:94,artist:"Tomokazu Komiya",name:'Gengar',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:34.00,base:true},
  {n:'095',dex:95,artist:"Shin Nagasawa",name:'Onix',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.32,base:true},
  {n:'096',dex:96,artist:"Mousho",name:'Drowzee',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.25,base:true},
  {n:'097',dex:97,artist:"Mousho",name:'Hypno',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.40,base:true},
  {n:'098',dex:98,artist:"Yukiko Baba",name:'Krabby',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.25,base:true},
  {n:'099',dex:99,artist:"Yukiko Baba",name:'Kingler',type:'Aquático',color:'#2196F3',rare:'Incomum',price:1.00,base:true},
  {n:'100',dex:100,artist:"nagimiso",name:'Voltorb',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.25,base:true},
  {n:'101',dex:101,artist:"nagimiso",name:'Electrode',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.35,base:true},
  {n:'102',dex:102,artist:"Shigenori Negishi",name:'Exeggcute',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'103',dex:103,artist:"Shigenori Negishi",name:'Exeggutor',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.45,base:true},
  {n:'104',dex:104,artist:"Shinya Komatsu",name:'Cubone',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.25,base:true},
  {n:'105',dex:105,artist:"Shinya Komatsu",name:'Marowak',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.85,base:true},
  {n:'106',dex:106,artist:"Hitoshi Ariga",name:'Hitmonlee',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.99,base:true},
  {n:'107',dex:107,artist:"DOM",name:'Hitmonchan',type:'Lutador',color:'#FF9800',rare:'Incomum',price:3.95,base:true},
  {n:'108',dex:108,artist:"Saya Tsuruta",name:'Lickitung',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.25,base:true},
  {n:'109',dex:109,artist:"Shibuzoh.",name:'Koffing',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'110',dex:110,artist:"Shibuzoh.",name:'Weezing',type:'Sombrio',color:'#607D8B',rare:'Rara',price:2.90,base:true},
  {n:'111',dex:111,artist:"GOSSAN",name:'Rhyhorn',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.25,base:true},
  {n:'112',dex:112,artist:"GOSSAN",name:'Rhydon',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.49,base:true},
  {n:'113',dex:113,artist:"Taiga Kayama",name:'Chansey',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:4.50,base:true},
  {n:'114',dex:114,artist:"Aya Kusube",name:'Tangela',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.30,base:true},
  {n:'115',dex:115,artist:"N-DESIGN Inc.",name:'Kangaskhan ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:8.90,base:true},
  {n:'116',dex:116,artist:"aspara",name:'Horsea',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.24,base:true},
  {n:'117',dex:117,artist:"aspara",name:'Seadra',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.45,base:true},
  {n:'118',dex:118,artist:"SIE NANAHARA",name:'Goldeen',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.25,base:true},
  {n:'119',dex:119,artist:"SIE NANAHARA",name:'Seaking',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.50,base:true},
  {n:'120',dex:120,artist:"Arai Kiriko",name:'Staryu',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.28,base:true},
  {n:'121',dex:121,artist:"Arai Kiriko",name:'Starmie',type:'Aquático',color:'#2196F3',rare:'Rara',price:2.00,base:true},
  {n:'122',dex:122,artist:"OOYAMA",name:'Mr. Mime',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.49,base:true},
  {n:'123',dex:123,artist:"Hideki Ishikawa",name:'Scyther',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.40,base:true},
  {n:'124',dex:124,artist:"Ayaka Yoshida",name:'Jynx ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:10.67,base:true},
  {n:'125',dex:125,artist:"NC Empire",name:'Electabuzz',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.20,base:true},
  {n:'126',dex:126,artist:"Toshinao Aoki",name:'Magmar',type:'Fogo',color:'#F44336',rare:'Comum',price:0.25,base:true},
  {n:'127',dex:127,artist:"Yuya Oka",name:'Pinsir',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.32,base:true},
  {n:'128',dex:128,artist:"Takeshi Nakamura",name:'Tauros',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.42,base:true},
  {n:'129',dex:129,artist:"Kouki Saitou",name:'Magikarp',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.25,base:true},
  {n:'130',dex:130,artist:"Kouki Saitou",name:'Gyarados',type:'Aquático',color:'#2196F3',rare:'Rara',price:2.98,base:true},
  {n:'131',dex:131,artist:"LINNE",name:'Lapras',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.45,base:true},
  {n:'132',dex:132,artist:"KIYOTAKA OSHIYAMA",name:'Ditto',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:2.50,base:true},
  {n:'133',dex:133,artist:"Narumi Sato",name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.00,base:true},
  {n:'134',dex:134,artist:"kirisAki",name:'Vaporeon',type:'Aquático',color:'#2196F3',rare:'Rara',price:2.99,base:true},
  {n:'135',dex:135,artist:"sui",name:'Jolteon',type:'Raio',color:'#FFEB3B',rare:'Rara',price:4.79,base:true},
  {n:'136',dex:136,artist:"Ryota Murayama",name:'Flareon',type:'Fogo',color:'#F44336',rare:'Rara',price:1.00,base:true},
  {n:'137',dex:137,artist:"5ban Graphics",name:'Porygon',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.25,base:true},
  {n:'138',dex:138,artist:"Akira Komayama",name:'Omanyte',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.99,base:true},
  {n:'139',dex:139,artist:"Akira Komayama",name:'Omastar',type:'Aquático',color:'#2196F3',rare:'Rara',price:10.99,base:true},
  {n:'140',dex:140,artist:"Souichirou Gunjima",name:'Kabuto',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.99,base:true},
  {n:'141',dex:141,artist:"Souichirou Gunjima",name:'Kabutops',type:'Lutador',color:'#FF9800',rare:'Rara',price:9.99,base:true},
  {n:'142',dex:142,artist:"Shinji Kanda",name:'Aerodactyl',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:10.90,base:true},
  {n:'143',dex:143,artist:"HYOGONOSUKE",name:'Snorlax',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.95,base:true},
  {n:'144',dex:144,artist:"chibi",name:'Articuno',type:'Aquático',color:'#2196F3',rare:'Rara',price:4.24,base:true},
  {n:'145',dex:145,artist:"takuyoa",name:'Zapdos ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:4.00,base:true},
  {n:'146',dex:146,artist:"KEIICHIRO ITO",name:'Moltres',type:'Fogo',color:'#F44336',rare:'Rara',price:0.25,base:true},
  {n:'147',dex:147,artist:"Sanosuke Sakuma",name:'Dratini',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.50,base:true},
  {n:'148',dex:148,artist:"Sanosuke Sakuma",name:'Dragonair',type:'Dragão',color:'#3F51B5',rare:'Incomum',price:0.99,base:true},
  {n:'149',dex:149,artist:"Sanosuke Sakuma",name:'Dragonite',type:'Dragão',color:'#3F51B5',rare:'Rara',price:20.00,base:true},
  {n:'150',dex:150,artist:"AKIRA EGAWA",name:'Mewtwo',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:10.20,base:true},
  {n:'151',dex:151,artist:"aky CG Works",name:'Mew ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:29.90,base:true},
  {n:'152',artist:"AYUMI ODASHIMA",name:'Antique Dome Fossil',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'153',artist:"AYUMI ODASHIMA",name:'Antique Helix Fossil',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'154',artist:"AYUMI ODASHIMA",name:'Antique Old Amber',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'155',artist:"Toyste Beach",name:'Big Air Balloon',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'156',artist:"GIDORA",name:'Bill\'s Transfer',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'157',artist:"Oswaldo KATO",name:'Cycling Road',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'158',artist:"Tomomi Kaneko",name:'Daisy\'s Help',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'159',artist:"Ayaka Yoshida",name:'Energy Sticker',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'160',artist:"saino misaki",name:'Erika\'s Invitation',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'161',artist:"hncl",name:'Giovanni\'s Charisma',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.47,base:true},
  {n:'162',artist:"inose yukie",name:'Grabber',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.90,base:true},
  {n:'163',artist:"Studio Bora Inc.",name:'Leftovers',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.22,base:true},
  {n:'164',artist:"Toyste Beach",name:'Protective Goggles',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'165',artist:"Toyste Beach",name:'Rigid Band',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'166',dex:1,artist:"Yoriyuki Ikegami",name:'Bulbasaur',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:199.90,base:false,important:true},
  {n:'167',dex:2,artist:"Yoriyuki Ikegami",name:'Ivysaur',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:239.75,base:false,important:true},
  {n:'168',dex:4,artist:"miki kudo",name:'Charmander',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:319.90,base:false,important:true},
  {n:'169',dex:5,artist:"miki kudo",name:'Charmeleon',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:240.00,base:false,important:true},
  {n:'170',dex:7,artist:"Mitsuhiro Arita",name:'Squirtle',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:169.90,base:false,important:true},
  {n:'171',dex:8,artist:"Mitsuhiro Arita",name:'Wartortle',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:324.90,base:false,important:true},
  {n:'172',dex:10,artist:"Teeziro",name:'Caterpie',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:140.00,base:false,important:true},
  {n:'173',dex:25,artist:"Hiroyuki Yamamoto",name:'Pikachu',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:329.99,base:false,important:true},
  {n:'174',dex:34,artist:"Misaki Hashimoto",name:'Nidoking',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:129.98,base:false,important:true},
  {n:'175',dex:54,artist:"Whisker",name:'Psyduck',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:299.90,base:false,important:true},
  {n:'176',dex:61,artist:"Gemi",name:'Poliwhirl',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:200.00,base:false,important:true},
  {n:'177',dex:67,artist:"Tetsu Kayama",name:'Machoke',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:159.00,base:false,important:true},
  {n:'178',dex:114,artist:"Oswaldo KATO",name:'Tangela',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:109.90,base:false,important:true},
  {n:'179',dex:122,artist:"OKACHEKE",name:'Mr. Mime',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:109.90,base:false,important:true},
  {n:'180',dex:138,artist:"Yano Keiji",name:'Omanyte',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:99.99,base:false,important:true},
  {n:'181',dex:148,artist:"rika",name:'Dragonair',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada',price:220.00,base:false,important:true},
  {n:'182',dex:3,artist:"PLANETA Yamashita",name:'Venusaur ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:59.99,base:false,important:true},
  {n:'183',dex:6,artist:"PLANETA Mochizuki",name:'Charizard ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:199.90,base:false,important:true},
  {n:'184',dex:9,artist:"PLANETA Yamashita",name:'Blastoise ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:110.00,base:false,important:true},
  {n:'185',dex:24,artist:"Eske Yoshinob",name:'Arbok ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:42.25,base:false,important:true},
  {n:'186',dex:38,artist:"PLANETA Tsuji",name:'Ninetales ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:63.75,base:false,important:true},
  {n:'187',dex:40,artist:"Saki Hayashiro",name:'Wigglytuff ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:43.00,base:false,important:true},
  {n:'188',dex:65,artist:"PLANETA Tsuji",name:'Alakazam ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:59.00,base:false,important:true},
  {n:'189',dex:76,artist:"PLANETA Igarashi",name:'Golem ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:39.99,base:false},
  {n:'190',dex:115,artist:"N-DESIGN Inc.",name:'Kangaskhan ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:34.90,base:false},
  {n:'191',dex:124,artist:"Ayaka Yoshida",name:'Jynx ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:39.90,base:false,important:true},
  {n:'192',dex:145,artist:"takuyoa",name:'Zapdos ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:80.00,base:false,important:true},
  {n:'193',dex:151,artist:"aky CG Works",name:'Mew ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:224.90,base:false,important:true},
  {n:'194',artist:"GIDORA",name:'Bill\'s Transfer',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:19.90,base:false},
  {n:'195',artist:"Fumie Kittaka",name:'Daisy\'s Help',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:24.90,base:false},
  {n:'196',artist:"saino misaki",name:'Erika\'s Invitation',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:79.99,base:false,important:true},
  {n:'197',artist:"hncl",name:'Giovanni\'s Charisma',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:34.50,base:false},
  {n:'198',dex:3,artist:"Yoriyuki Ikegami",name:'Venusaur ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:700.00,base:false,important:true},
  {n:'199',dex:6,artist:"miki kudo",name:'Charizard ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:1400.00,base:false,important:true},
  {n:'200',dex:9,artist:"Mitsuhiro Arita",name:'Blastoise ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:699.80,base:false,important:true},
  {n:'201',dex:65,artist:"Shinya Komatsu",name:'Alakazam ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:349.90,base:false,important:true},
  {n:'202',dex:145,artist:"Shiburingaru",name:'Zapdos ex',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada Especial',price:419.99,base:false,important:true},
  {n:'203',artist:"Cona Nitanda",name:'Erika\'s Invitation',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:199.99,base:false,important:true},
  {n:'204',artist:"Hideki Ishikawa",name:'Giovanni\'s Charisma',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:149.99,base:false,important:true},
  {n:'205',dex:151,artist:"aky CG Works",name:'Mew ex',type:'Psíquico',color:'#9C27B0',rare:'Hiper Rara',price:127.50,base:false,important:true},
  {n:'206',artist:"Studio Bora Inc.",name:'Switch',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:24.90,base:false},
  {n:'207',name:'Basic Psychic Energy',type:'Psíquico',color:'#9C27B0',rare:'Hiper Rara',price:55.00,base:false}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV3PT5 = CARDS_SV3PT5;