// SV4 — Paradox Rift (266 cartas)
// Lançamento EN: 2023/11/03
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV4 = [
  {n:'001',name:'Surskit',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'002',name:'Masquerain',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.25,base:true},
  {n:'003',name:'Froslass ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:4.90,base:true},
  {n:'004',name:'Pansage',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'005',name:'Simisage',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.25,base:true},
  {n:'006',name:'Dwebble',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'007',name:'Crustle',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'008',name:'Bounsweet',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.13,base:true},
  {n:'009',name:'Steenee',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'010',name:'Blipbug',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'011',name:'Dottler',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'012',name:'Orbeetle',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'013',name:'Nymble',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.13,base:true},
  {n:'014',name:'Nymble',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'015',name:'Toedscool',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'016',name:'Toedscool',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'017',name:'Toedscruel',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'018',name:'Wo-Chien',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.35,base:true},
  {n:'019',name:'Magby',type:'Fogo',color:'#F44336',rare:'Comum',price:0.20,base:true},
  {n:'020',name:'Pansear',type:'Fogo',color:'#F44336',rare:'Comum',price:0.20,base:true},
  {n:'021',name:'Simisear',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.20,base:true},
  {n:'022',name:'Volcanion',type:'Fogo',color:'#F44336',rare:'Rara',price:0.26,base:true},
  {n:'023',name:'Fuecoco',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'024',name:'Crocalor',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.13,base:true},
  {n:'025',name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.25,base:true},
  {n:'026',name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.25,base:true},
  {n:'027',name:'Armarouge ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:7.65,base:true},
  {n:'028',name:'Iron Moth',type:'Fogo',color:'#F44336',rare:'Rara',price:0.35,base:true},
  {n:'029',name:'Chi-Yu',type:'Fogo',color:'#F44336',rare:'Rara',price:0.35,base:true},
  {n:'030',name:'Horsea',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.25,base:true},
  {n:'031',name:'Seadra',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.24,base:true},
  {n:'032',name:'Kingdra',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.34,base:true},
  {n:'033',name:'Remoraid',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'034',name:'Octillery',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'035',name:'Feebas',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.17,base:true},
  {n:'036',name:'Milotic',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.50,base:true},
  {n:'037',name:'Snorunt',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.25,base:true},
  {n:'038',name:'Garchomp ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:9.75,base:true},
  {n:'039',name:'Mantyke',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'040',name:'Palkia',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.20,base:true},
  {n:'041',name:'Panpour',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'042',name:'Simipour',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.13,base:true},
  {n:'043',name:'Vanillite',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'044',name:'Vanillish',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'045',name:'Vanilluxe',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.10,base:true},
  {n:'046',name:'Tsareena ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:6.99,base:true},
  {n:'047',name:'Wimpod',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'048',name:'Wimpod',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'049',name:'Golisopod',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.25,base:true},
  {n:'050',name:'Golisopod ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:4.90,base:true},
  {n:'051',name:'Wiglett',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'052',name:'Wiglett',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'053',name:'Wugtrio',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.24,base:true},
  {n:'054',name:'Veluza',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.25,base:true},
  {n:'055',name:'Dondozo',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.20,base:true},
  {n:'056',name:'Iron Bundle',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.17,base:true},
  {n:'057',name:'Chien-Pao',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.36,base:true},
  {n:'058',name:'Mewtwo ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:9.99,base:true},
  {n:'059',name:'Elekid',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.20,base:true},
  {n:'060',name:'Plusle',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.23,base:true},
  {n:'061',name:'Minun',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.25,base:true},
  {n:'062',name:'Blitzle',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.10,base:true},
  {n:'063',name:'Zebstrika',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.10,base:true},
  {n:'064',name:'Joltik',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.21,base:true},
  {n:'065',name:'Galvantula',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.24,base:true},
  {n:'066',name:'Zekrom',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.35,base:true},
  {n:'067',name:'Oricorio',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.21,base:true},
  {n:'068',name:'Tapu Koko ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:2.79,base:true},
  {n:'069',name:'Toxel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.10,base:true},
  {n:'070',name:'Iron Hands ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:4.90,base:true},
  {n:'071',name:'Natu',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'072',name:'Xatu',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.08,base:true},
  {n:'073',name:'Latios',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.35,base:true},
  {n:'074',name:'Deoxys',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.50,base:true},
  {n:'075',name:'Yamask',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'076',name:'Cofagrigus ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:2.90,base:true},
  {n:'077',name:'Pumpkaboo',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'078',name:'Gourgeist',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.13,base:true},
  {n:'079',name:'Flittle',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'080',name:'Flittle',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'081',name:'Espathra',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.18,base:true},
  {n:'082',name:'Tinkatink',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.17,base:true},
  {n:'083',name:'Tinkatink',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'084',name:'Tinkatuff',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'085',name:'Tinkaton',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.25,base:true},
  {n:'086',name:'Scream Tail',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.25,base:true},
  {n:'087',name:'Gimmighoul',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'088',name:'Gimmighoul',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'089',name:'Iron Valiant ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:2.99,base:true},
  {n:'090',name:'Onix',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'091',name:'Gligar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.13,base:true},
  {n:'092',name:'Gliscor',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.18,base:true},
  {n:'093',name:'Groudon',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.35,base:true},
  {n:'094',name:'Gible',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.21,base:true},
  {n:'095',name:'Gabite',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.25,base:true},
  {n:'096',name:'Mienfoo',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.17,base:true},
  {n:'097',name:'Mienshao',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.24,base:true},
  {n:'098',name:'Hoopa ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:4.90,base:true},
  {n:'099',name:'Minior',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.24,base:true},
  {n:'100',name:'Toxtricity ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:5.00,base:true},
  {n:'101',name:'Nacli',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'102',name:'Nacli',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.21,base:true},
  {n:'103',name:'Naclstack',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.25,base:true},
  {n:'104',name:'Garganacl',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.35,base:true},
  {n:'105',name:'Klawf',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.24,base:true},
  {n:'106',name:'Flamigo',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.21,base:true},
  {n:'107',name:'Slither Wing',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.10,base:true},
  {n:'108',name:'Sandy Shocks ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:2.99,base:true},
  {n:'109',name:'Ting-Lu',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.10,base:true},
  {n:'110',name:'Zubat',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'111',name:'Golbat',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.25,base:true},
  {n:'112',name:'Crobat',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.25,base:true},
  {n:'113',name:'Absol',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.17,base:true},
  {n:'114',name:'Purrloin',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.20,base:true},
  {n:'115',name:'Liepard',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.20,base:true},
  {n:'116',name:'Trubbish',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'117',name:'Garbodor',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  {n:'118',name:'Yveltal',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.25,base:true},
  {n:'119',name:'Nickit',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'120',name:'Thievul',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.35,base:true},
  {n:'121',name:'Morpeko',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.13,base:true},
  {n:'122',name:'Lokix',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.24,base:true},
  {n:'123',name:'Brute Bonnet',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.30,base:true},
  {n:'124',name:'Roaring Moon ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:3.90,base:true},
  {n:'125',name:'Steelix',type:'Metal',color:'#78909C',rare:'Rara',price:0.35,base:true},
  {n:'126',name:'Jirachi',type:'Metal',color:'#78909C',rare:'Comum',price:0.25,base:true},
  {n:'127',name:'Ferroseed',type:'Metal',color:'#78909C',rare:'Comum',price:0.15,base:true},
  {n:'128',name:'Ferrothorn',type:'Metal',color:'#78909C',rare:'Incomum',price:0.10,base:true},
  {n:'129',name:'Durant',type:'Metal',color:'#78909C',rare:'Incomum',price:0.20,base:true},
  {n:'130',name:'Honedge',type:'Metal',color:'#78909C',rare:'Comum',price:0.10,base:true},
  {n:'131',name:'Honedge',type:'Metal',color:'#78909C',rare:'Comum',price:0.20,base:true},
  {n:'132',name:'Doublade',type:'Metal',color:'#78909C',rare:'Comum',price:0.20,base:true},
  {n:'133',name:'Doublade',type:'Metal',color:'#78909C',rare:'Comum',price:0.25,base:true},
  {n:'134',name:'Aegislash',type:'Metal',color:'#78909C',rare:'Rara',price:0.30,base:true},
  {n:'135',name:'Aegislash ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:5.90,base:true},
  {n:'136',name:'Zacian',type:'Metal',color:'#78909C',rare:'Rara',price:0.25,base:true},
  {n:'137',name:'Skeledirge ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:7.19,base:true},
  {n:'138',name:'Orthworm',type:'Metal',color:'#78909C',rare:'Incomum',price:0.24,base:true},
  {n:'139',name:'Gholdengo ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:4.90,base:true},
  {n:'140',name:'Altaria ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:4.90,base:true},
  {n:'141',name:'Tatsugiri',type:'Dragão',color:'#3F51B5',rare:'Incomum',price:0.10,base:true},
  {n:'142',name:'Porygon',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'143',name:'Porygon2',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.24,base:true},
  {n:'144',name:'Porygon-Z',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.25,base:true},
  {n:'145',name:'Aipom',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.17,base:true},
  {n:'146',name:'Ambipom',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.24,base:true},
  {n:'147',name:'Miltank',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.25,base:true},
  {n:'148',name:'Whismur',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'149',name:'Loudred',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.23,base:true},
  {n:'150',name:'Exploud',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'151',name:'Spinda',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'152',name:'Swablu',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'153',name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.25,base:true},
  {n:'154',name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.25,base:true},
  {n:'155',name:'Maushold ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:13.00,base:true},
  {n:'156',name:'Bombirdier ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:4.90,base:true},
  {n:'157',name:'Cyclizar',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'158',name:'Iron Jugulis',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.30,base:true},
  {n:'159',name:'Ancient Booster Energy Capsule',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.23,base:true},
  {n:'160',name:'Counter Catcher',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.99,base:true},
  {n:'161',name:'Cursed Duster',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'162',name:'Defiance Vest',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'163',name:'Earthen Vessel',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'164',name:'Future Booster Energy Capsule',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.14,base:true},
  {n:'165',name:'Larry',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.13,base:true},
  {n:'166',name:'Luxurious Cape',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.30,base:true},
  {n:'167',name:'Mela',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'168',name:'Norman',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'169',name:'Parasol Lady',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'170',name:'Professor Sada\'s Vitality',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.13,base:true},
  {n:'171',name:'Professor Turo\'s Scenario',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.17,base:true},
  {n:'172',name:'Rika',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'173',name:'Roark',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'174',name:'Shauntal',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.18,base:true},
  {n:'175',name:'Snorlax Doll',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'176',name:'Technical Machine: Blindside',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'177',name:'Technical Machine: Devolution',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'178',name:'Technical Machine: Evolution',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.26,base:true},
  {n:'179',name:'Technical Machine: Turbo Energize',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'180',name:'Techno Radar',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'181',name:'Tulip',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.30,base:true},
  {n:'182',name:'Medical Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'183',name:'Crustle',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:29.75,base:false},
  {n:'184',name:'Dottler',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:34.90,base:false},
  {n:'185',name:'Toedscruel',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:22.50,base:false},
  {n:'186',name:'Magby',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:97.90,base:false,important:true},
  {n:'187',name:'Iron Moth',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:44.99,base:false,important:true},
  {n:'188',name:'Snorunt',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:28.50,base:false,important:true},
  {n:'189',name:'Mantyke',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:99.90,base:false,important:true},
  {n:'190',name:'Vanillish',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:44.90,base:false,important:true},
  {n:'191',name:'Wimpod',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:19.00,base:false,important:true},
  {n:'192',name:'Veluza',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:30.00,base:false,important:true},
  {n:'193',name:'Plusle',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:79.00,base:false,important:true},
  {n:'194',name:'Minun',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:89.00,base:false,important:true},
  {n:'195',name:'Blitzle',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:35.00,base:false,important:true},
  {n:'196',name:'Joltik',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:65.00,base:false,important:true},
  {n:'197',name:'Espathra',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:29.99,base:false},
  {n:'198',name:'Gimmighoul',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:42.00,base:false,important:true},
  {n:'199',name:'Groudon',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:144.42,base:false,important:true},
  {n:'200',name:'Mienshao',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:34.89,base:false,important:true},
  {n:'201',name:'Minior',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:49.90,base:false,important:true},
  {n:'202',name:'Garganacl',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:25.90,base:false},
  {n:'203',name:'Slither Wing',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:28.00,base:false},
  {n:'204',name:'Garbodor',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:50.00,base:false,important:true},
  {n:'205',name:'Yveltal',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:70.00,base:false,important:true},
  {n:'206',name:'Morpeko',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:110.00,base:false,important:true},
  {n:'207',name:'Brute Bonnet',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:67.00,base:false,important:true},
  {n:'208',name:'Steelix',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:89.90,base:false,important:true},
  {n:'209',name:'Ferrothorn',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:32.00,base:false},
  {n:'210',name:'Aegislash',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:40.90,base:false,important:true},
  {n:'211',name:'Aipom',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:179.90,base:false,important:true},
  {n:'212',name:'Loudred',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:49.90,base:false,important:true},
  {n:'213',name:'Swablu',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:69.50,base:false,important:true},
  {n:'214',name:'Porygon-Z',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:57.03,base:false,important:true},
  {n:'215',name:'Cyclizar',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:42.50,base:false},
  {n:'216',name:'Iron Jugulis',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:37.85,base:false,important:true},
  {n:'217',name:'Froslass ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:11.00,base:false},
  {n:'218',name:'Armarouge ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:12.90,base:false},
  {n:'219',name:'Garchomp ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:20.00,base:false},
  {n:'220',name:'Tsareena ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:23.99,base:false},
  {n:'221',name:'Golisopod ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:14.90,base:false},
  {n:'222',name:'Tapu Koko ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:19.50,base:false},
  {n:'223',name:'Iron Hands ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:17.75,base:false},
  {n:'224',name:'Cofagrigus ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:15.00,base:false},
  {n:'225',name:'Iron Valiant ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:24.90,base:false},
  {n:'226',name:'Hoopa ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:27.00,base:false},
  {n:'227',name:'Toxtricity ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:19.50,base:false},
  {n:'228',name:'Sandy Shocks ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:11.00,base:false},
  {n:'229',name:'Roaring Moon ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:15.00,base:false},
  {n:'230',name:'Aegislash ex',type:'Metal',color:'#78909C',rare:'Ultra Rara',price:12.00,base:false},
  {n:'231',name:'Gholdengo ex',type:'Metal',color:'#78909C',rare:'Ultra Rara',price:27.46,base:false},
  {n:'232',name:'Altaria ex',type:'Dragão',color:'#3F51B5',rare:'Ultra Rara',price:19.99,base:false},
  {n:'233',name:'Maushold ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:248.00,base:false,important:true},
  {n:'234',name:'Bombirdier ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:12.00,base:false},
  {n:'235',name:'Larry',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:9.00,base:false},
  {n:'236',name:'Mela',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:34.50,base:false},
  {n:'237',name:'Norman',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:12.99,base:false},
  {n:'238',name:'Parasol Lady',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:19.50,base:false},
  {n:'239',name:'Professor Sada\'s Vitality',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:9.90,base:false},
  {n:'240',name:'Professor Turo\'s Scenario',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:14.98,base:false},
  {n:'241',name:'Rika',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:24.90,base:false},
  {n:'242',name:'Roark',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:7.90,base:false},
  {n:'243',name:'Shauntal',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:19.90,base:false},
  {n:'244',name:'Tulip',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:30.00,base:false},
  {n:'245',name:'Garchomp ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:150.00,base:false,important:true},
  {n:'246',name:'Golisopod ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:139.90,base:false,important:true},
  {n:'247',name:'Tapu Koko ex',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada Especial',price:58.50,base:false,important:true},
  {n:'248',name:'Iron Hands ex',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada Especial',price:67.50,base:false,important:true},
  {n:'249',name:'Iron Valiant ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:119.90,base:false,important:true},
  {n:'250',name:'Sandy Shocks ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:69.00,base:false,important:true}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV4 = CARDS_SV4;