// SV4PT5 — Paldean Fates (245 cartas)
// Lançamento EN: 2024/01/26
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV4PT5 = [
  {n:'001',dex:204,artist:"Kouki Saitou",name:'Pineco',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'002',dex:205,artist:"5ban Graphics",name:'Forretress ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.80,base:true},
  {n:'003',dex:556,artist:"Masako Tomii",name:'Maractus',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.08,base:true},
  {n:'004',dex:948,artist:"Shin Nagasawa",name:'Toedscool',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'005',dex:949,artist:"5ban Graphics",name:'Toedscruel ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.99,base:true},
  {n:'006',dex:956,artist:"takuyoa",name:'Espathra ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.33,base:true},
  {n:'007',dex:4,artist:"GIDORA",name:'Charmander',type:'Fogo',color:'#F44336',rare:'Comum',price:0.09,base:true},
  {n:'008',dex:5,artist:"Tonji Matsuno",name:'Charmeleon',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.15,base:true},
  {n:'009',dex:126,artist:"miki kudo",name:'Magmar',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'010',dex:467,artist:"Hasuno",name:'Magmortar',type:'Fogo',color:'#F44336',rare:'Rara',price:0.20,base:true},
  {n:'011',dex:322,artist:"Mina Nakai",name:'Numel',type:'Fogo',color:'#F44336',rare:'Comum',price:0.15,base:true},
  {n:'012',dex:323,artist:"satoma",name:'Camerupt',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.10,base:true},
  {n:'013',dex:479,artist:"Scav",name:'Heat Rotom',type:'Fogo',color:'#F44336',rare:'Rara',price:0.26,base:true},
  {n:'014',dex:935,artist:"nagimiso",name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'015',dex:936,artist:"AKIRA EGAWA",name:'Armarouge',type:'Fogo',color:'#F44336',rare:'Rara',price:0.30,base:true},
  {n:'016',dex:131,artist:"Gemi",name:'Lapras',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'017',dex:996,artist:"rika",name:'Frigibax',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.15,base:true},
  {n:'018',dex:25,artist:"OKACHEKE",name:'Pikachu',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.49,base:true},
  {n:'019',dex:26,artist:"Naoyo Kimura",name:'Raichu',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.50,base:true},
  {n:'020',dex:170,artist:"yuu",name:'Chinchou',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.10,base:true},
  {n:'021',dex:171,artist:"aspara",name:'Lanturn',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.11,base:true},
  {n:'022',dex:941,artist:"AKIRA EGAWA",name:'Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.15,base:true},
  {n:'023',dex:102,artist:"Kariya",name:'Exeggcute',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'024',dex:103,artist:"Yoriyuki Ikegami",name:'Exeggutor',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.30,base:true},
  {n:'025',dex:177,artist:"Teeziro",name:'Natu',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'026',dex:178,artist:"DOM",name:'Xatu',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.30,base:true},
  {n:'027',dex:280,artist:"Tika Matsuno",name:'Ralts',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'028',dex:281,artist:"kawayoo",name:'Kirlia',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.23,base:true},
  {n:'029',dex:282,artist:"N-DESIGN Inc.",name:'Gardevoir ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:4.00,base:true},
  {n:'030',dex:358,artist:"sui",name:'Chimecho',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'031',dex:439,artist:"HYOGONOSUKE",name:'Mime Jr.',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'032',dex:527,artist:"Kagemaru Himeno",name:'Woobat',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'033',dex:528,artist:"Narumi Sato",name:'Swoobat',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'034',dex:546,artist:"kurumitsu",name:'Cottonee',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'035',dex:547,artist:"KYUPIYAMA",name:'Whimsicott',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'036',dex:702,artist:"Tika Matsuno",name:'Dedenne',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'037',dex:778,artist:"Kagemaru Himeno",name:'Mimikyu',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.25,base:true},
  {n:'038',dex:926,artist:"Mizue",name:'Fidough',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'039',dex:927,artist:"You Iribi",name:'Dachsbun',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.11,base:true},
  {n:'040',dex:937,artist:"Ryota Murayama",name:'Ceruledge',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.35,base:true},
  {n:'041',dex:955,artist:"kawayoo",name:'Flittle',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'042',dex:971,artist:"yuu",name:'Greavard',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'043',dex:972,artist:"Kouki Saitou",name:'Houndstone',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.22,base:true},
  {n:'044',dex:999,artist:"OKUBO",name:'Gimmighoul',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'045',dex:56,artist:"nagimiso",name:'Mankey',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'046',dex:57,artist:"Ryuta Fuse",name:'Primeape',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.10,base:true},
  {n:'047',dex:979,artist:"Anesaki Dynamic",name:'Annihilape',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.20,base:true},
  {n:'048',dex:231,artist:"Atsuko Nishida",name:'Phanpy',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'049',dex:232,artist:"Shin Nagasawa",name:'Donphan',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.15,base:true},
  {n:'050',dex:339,artist:"ryoma uratsuka",name:'Barboach',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'051',dex:852,artist:"Kedamahadaitai Yawarakai",name:'Clobbopus',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.13,base:true},
  {n:'052',dex:853,artist:"Sanosuke Sakuma",name:'Grapploct',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.10,base:true},
  {n:'053',dex:984,artist:"kawayoo",name:'Great Tusk ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:3.90,base:true},
  {n:'054',dex:6,artist:"5ban Graphics",name:'Charizard ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:8.00,base:true},
  {n:'055',dex:92,artist:"Nobuhiro Imagawa",name:'Gastly',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'056',dex:93,artist:"DOM",name:'Haunter',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.20,base:true},
  {n:'057',dex:94,artist:"Nelnal",name:'Gengar',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.30,base:true},
  {n:'058',dex:194,artist:"Kouki Saitou",name:'Paldean Wooper',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'059',dex:980,artist:"PLANETA Mochizuki",name:'Paldean Clodsire ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:3.50,base:true},
  {n:'060',dex:559,artist:"sowsow",name:'Scraggy',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.05,base:true},
  {n:'061',dex:560,artist:"Mousho",name:'Scrafty',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.14,base:true},
  {n:'062',dex:942,artist:"DOM",name:'Maschiff',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'063',dex:943,artist:"KIYOTAKA OSHIYAMA",name:'Mabosstiff',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.20,base:true},
  {n:'064',dex:965,artist:"Tetsu Kayama",name:'Varoom',type:'Metal',color:'#78909C',rare:'Comum',price:0.15,base:true},
  {n:'065',dex:966,artist:"Anesaki Dynamic",name:'Revavroom',type:'Metal',color:'#78909C',rare:'Rara',price:0.25,base:true},
  {n:'066',dex:990,artist:"toriyufu",name:'Iron Treads ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:3.00,base:true},
  {n:'067',dex:1000,artist:"Mitsuhiro Arita",name:'Gholdengo',type:'Metal',color:'#78909C',rare:'Rara',price:0.20,base:true},
  {n:'068',dex:714,artist:"chibi",name:'Noibat',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.10,base:true},
  {n:'069',dex:715,artist:"Nisota Niso",name:'Noivern ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:4.50,base:true},
  {n:'070',dex:967,artist:"GIDORA",name:'Cyclizar',type:'Dragão',color:'#3F51B5',rare:'Rara',price:0.17,base:true},
  {n:'071',dex:915,artist:"Mina Nakai",name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'072',dex:916,artist:"Akira Komayama",name:'Oinkologne',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.05,base:true},
  {n:'073',dex:924,artist:"Oswaldo KATO",name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'074',dex:925,artist:"KIYOTAKA OSHIYAMA",name:'Maushold',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'075',dex:931,artist:"PLANETA Mochizuki",name:'Squawkabilly ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:2.99,base:true},
  {n:'076',artist:"Oswaldo KATO",name:'Artazon',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'077',artist:"kantaro",name:'Atticus',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'078',artist:"GOSSAN",name:'Clive',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'079',artist:"Toyste Beach",name:'Electric Generator',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'080',artist:"Sanosuke Sakuma",name:'Iono',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'081',artist:"AYUMI ODASHIMA",name:'Moonlit Hill',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.13,base:true},
  {n:'082',artist:"Sanosuke Sakuma",name:'Nemona',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.14,base:true},
  {n:'083',artist:"AYUMI ODASHIMA",name:'Nemona\'s Backpack',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'084',artist:"Toyste Beach",name:'Nest Ball',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.19,base:true},
  {n:'085',artist:"Cona Nitanda",name:'Paldean Student',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.05,base:true},
  {n:'086',artist:"Naoki Saito",name:'Paldean Student',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.05,base:true},
  {n:'087',artist:"kirisAki",name:'Professor\'s Research',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.25,base:true},
  {n:'088',artist:"kirisAki",name:'Professor\'s Research',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.20,base:true},
  {n:'089',artist:"Studio Bora Inc.",name:'Rare Candy',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'090',artist:"Studio Bora Inc.",name:'Technical Machine: Crisis Punch',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'091',artist:"Ayaka Yoshida",name:'Ultra Ball',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'092',dex:43,artist:"otumami",name:'Oddish',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:19.90,base:false,important:true},
  {n:'093',dex:44,artist:"OKACHEKE",name:'Gloom',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:22.50,base:false},
  {n:'094',dex:45,artist:"0313",name:'Vileplume',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:24.99,base:false},
  {n:'095',dex:123,artist:"Hitoshi Ariga",name:'Scyther',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:19.90,base:false,important:true},
  {n:'096',dex:187,artist:"Saya Tsuruta",name:'Hoppip',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:5.00,base:false},
  {n:'097',dex:188,artist:"Mizue",name:'Skiploom',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:32.90,base:false},
  {n:'098',dex:189,artist:"Lee HyunJung",name:'Jumpluff',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:35.00,base:false},
  {n:'099',dex:204,artist:"Scav",name:'Pineco',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:6.90,base:false},
  {n:'100',dex:459,artist:"Saya Tsuruta",name:'Snover',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:7.00,base:false},
  {n:'101',dex:460,artist:"Hitoshi Ariga",name:'Abomasnow',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:24.89,base:false},
  {n:'102',dex:928,artist:"otumami",name:'Smoliv',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:19.99,base:false},
  {n:'103',dex:929,artist:"saino misaki",name:'Dolliv',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:17.90,base:false},
  {n:'104',dex:930,artist:"Hideki Ishikawa",name:'Arboliva',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:24.00,base:false},
  {n:'105',dex:948,artist:"Ryuta Fuse",name:'Toedscool',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:8.90,base:false},
  {n:'106',dex:951,artist:"OKACHEKE",name:'Capsakid',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:7.90,base:false},
  {n:'107',dex:952,artist:"Kouki Saitou",name:'Scovillain',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:18.00,base:false},
  {n:'108',dex:953,artist:"Misa Tsutsui",name:'Rellor',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:7.40,base:false},
  {n:'109',dex:4,artist:"sowsow",name:'Charmander',type:'Fogo',color:'#F44336',rare:'Rara Brilhante',price:61.90,base:false,important:true},
  {n:'110',dex:5,artist:"Kouki Saitou",name:'Charmeleon',type:'Fogo',color:'#F44336',rare:'Rara Brilhante',price:119.90,base:false,important:true},
  {n:'111',dex:128,artist:"Hitoshi Ariga",name:'Paldean Tauros',type:'Fogo',color:'#F44336',rare:'Rara Brilhante',price:19.90,base:false},
  {n:'112',dex:244,artist:"Ryuta Fuse",name:'Entei',type:'Fogo',color:'#F44336',rare:'Rara Brilhante',price:50.00,base:false,important:true},
  {n:'113',dex:741,artist:"Akira Komayama",name:'Oricorio',type:'Fogo',color:'#F44336',rare:'Rara Brilhante',price:7.40,base:false},
  {n:'114',dex:935,artist:"Masakazu Fukuda",name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Rara Brilhante',price:14.90,base:false},
  {n:'115',dex:936,artist:"Atsushi Furusawa",name:'Armarouge',type:'Fogo',color:'#F44336',rare:'Rara Brilhante',price:24.90,base:false},
  {n:'116',dex:79,artist:"Taira Akitsu",name:'Slowpoke',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:44.96,base:false,important:true},
  {n:'117',dex:80,artist:"Souichirou Gunjima",name:'Slowbro',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:119.00,base:false,important:true},
  {n:'118',dex:120,artist:"Nisota Niso",name:'Staryu',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:11.90,base:false},
  {n:'119',dex:121,artist:"Shigenori Negishi",name:'Starmie',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:47.89,base:false,important:true},
  {n:'120',dex:128,artist:"GOSSAN",name:'Paldean Tauros',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:14.90,base:false},
  {n:'121',dex:960,artist:"Misa Tsutsui",name:'Wiglett',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:12.00,base:false},
  {n:'122',dex:961,artist:"Kyoko Umemoto",name:'Wugtrio',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:10.90,base:false},
  {n:'123',dex:963,artist:"kurumitsu",name:'Finizen',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:9.90,base:false},
  {n:'124',dex:964,artist:"Shin Nagasawa",name:'Palafin',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:19.70,base:false},
  {n:'125',dex:976,artist:"Nelnal",name:'Veluza',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:10.99,base:false},
  {n:'126',dex:977,artist:"Shigenori Negishi",name:'Dondozo',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:17.00,base:false},
  {n:'127',dex:978,artist:"Kagemaru Himeno",name:'Tatsugiri',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:24.00,base:false},
  {n:'128',dex:996,artist:"Taira Akitsu",name:'Frigibax',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:27.50,base:false},
  {n:'129',dex:997,artist:"Kouki Saitou",name:'Arctibax',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:21.91,base:false},
  {n:'130',dex:998,artist:"GOSSAN",name:'Baxcalibur',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:20.00,base:false},
  {n:'131',dex:25,artist:"Yuu Nishida",name:'Pikachu',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:127.50,base:false,important:true},
  {n:'132',dex:26,artist:"Sanosuke Sakuma",name:'Raichu',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:59.99,base:false,important:true},
  {n:'133',dex:100,artist:"Misa Tsutsui",name:'Voltorb',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:12.51,base:false},
  {n:'134',dex:101,artist:"Masakazu Fukuda",name:'Electrode',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:39.60,base:false},
  {n:'135',dex:403,artist:"Saya Tsuruta",name:'Shinx',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:9.90,base:false,important:true},
  {n:'136',dex:404,artist:"Souichirou Gunjima",name:'Luxio',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:19.89,base:false},
  {n:'137',dex:405,artist:"kantaro",name:'Luxray',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:41.00,base:false,important:true},
  {n:'138',dex:417,artist:"saino misaki",name:'Pachirisu',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:64.90,base:false,important:true},
  {n:'139',dex:642,artist:"Shin Nagasawa",name:'Thundurus',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:23.90,base:false},
  {n:'140',dex:848,artist:"Lee HyunJung",name:'Toxel',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:29.50,base:false},
  {n:'141',dex:849,artist:"GIDORA",name:'Toxtricity',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:21.99,base:false},
  {n:'142',dex:921,artist:"kurumitsu",name:'Pawmi',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:9.90,base:false},
  {n:'143',dex:922,artist:"Mizue",name:'Pawmo',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:20.00,base:false},
  {n:'144',dex:923,artist:"Atsushi Furusawa",name:'Pawmot',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:29.99,base:false},
  {n:'145',dex:940,artist:"Scav",name:'Wattrel',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:9.90,base:false},
  {n:'146',dex:941,artist:"Nisota Niso",name:'Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:17.98,base:false},
  {n:'147',dex:40,artist:"Kagemaru Himeno",name:'Wigglytuff',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:25.49,base:false},
  {n:'148',dex:63,artist:"Kouki Saitou",name:'Abra',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:89.90,base:false,important:true},
  {n:'149',dex:64,artist:"Souichirou Gunjima",name:'Kadabra',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:48.90,base:false},
  {n:'150',dex:173,artist:"Mizue",name:'Cleffa',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:44.99,base:false},
  {n:'151',dex:177,artist:"sowsow",name:'Natu',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:7.99,base:false},
  {n:'152',dex:178,artist:"nagimiso",name:'Xatu',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:8.90,base:false},
  {n:'153',dex:280,artist:"yuu",name:'Ralts',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:53.98,base:false,important:true},
  {n:'154',dex:281,artist:"Ryuta Fuse",name:'Kirlia',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:60.00,base:false},
  {n:'155',dex:425,artist:"Kyoko Umemoto",name:'Drifloon',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:8.90,base:false},
  {n:'156',dex:426,artist:"otumami",name:'Drifblim',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:21.99,base:false},
  {n:'157',dex:439,artist:"Saya Tsuruta",name:'Mime Jr.',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:8.99,base:false},
  {n:'158',dex:442,artist:"MAHOU",name:'Spiritomb',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:40.00,base:false},
  {n:'159',dex:707,artist:"yuu",name:'Klefki',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:21.90,base:false},
  {n:'160',dex:778,artist:"Nelnal",name:'Mimikyu',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:145.00,base:false,important:true},
  {n:'161',dex:927,artist:"Sanosuke Sakuma",name:'Dachsbun',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:48.00,base:false,important:true},
  {n:'162',dex:937,artist:"Kouki Saitou",name:'Ceruledge',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:69.90,base:false,important:true},
  {n:'163',dex:954,artist:"Nelnal",name:'Rabsca',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:19.90,base:false},
  {n:'164',dex:955,artist:"Kyoko Umemoto",name:'Flittle',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:8.90,base:false},
  {n:'165',dex:957,artist:"yuu",name:'Tinkatink',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:50.00,base:false,important:true},
  {n:'166',dex:958,artist:"Yuu Nishida",name:'Tinkatuff',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:44.90,base:false},
  {n:'167',dex:959,artist:"Kagemaru Himeno",name:'Tinkaton',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:41.90,base:false,important:true},
  {n:'168',dex:972,artist:"Shin Nagasawa",name:'Houndstone',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:15.00,base:false},
  {n:'169',dex:56,artist:"nagimiso",name:'Mankey',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:9.50,base:false},
  {n:'170',dex:57,artist:"Scav",name:'Primeape',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:9.90,base:false},
  {n:'171',dex:979,artist:"Hitoshi Ariga",name:'Annihilape',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:29.90,base:false},
  {n:'172',dex:128,artist:"nagimiso",name:'Paldean Tauros',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:16.90,base:false},
  {n:'173',dex:447,artist:"sowsow",name:'Riolu',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:22.89,base:false,important:true},
  {n:'174',dex:448,artist:"Shin Nagasawa",name:'Lucario',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:73.00,base:false,important:true},
  {n:'175',dex:701,artist:"Souichirou Gunjima",name:'Hawlucha',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:33.90,base:false},
  {n:'176',dex:932,artist:"Yuu Nishida",name:'Nacli',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:19.90,base:false},
  {n:'177',dex:933,artist:"otumami",name:'Naclstack',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:13.50,base:false},
  {n:'178',dex:934,artist:"Kouki Saitou",name:'Garganacl',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:19.99,base:false},
  {n:'179',dex:969,artist:"nagimiso",name:'Glimmet',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:7.90,base:false},
  {n:'180',dex:194,artist:"Nisota Niso",name:'Paldean Wooper',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:19.90,base:false,important:true},
  {n:'181',dex:198,artist:"Hitoshi Ariga",name:'Murkrow',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:9.99,base:false},
  {n:'182',dex:215,artist:"Kagemaru Himeno",name:'Sneasel',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:24.90,base:false},
  {n:'183',dex:461,artist:"Shin Nagasawa",name:'Weavile',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:14.90,base:false},
  {n:'184',dex:302,artist:"nagimiso",name:'Sableye',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:47.00,base:false},
  {n:'185',dex:624,artist:"Misa Tsutsui",name:'Pawniard',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:8.99,base:false},
  {n:'186',dex:625,artist:"Souichirou Gunjima",name:'Bisharp',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:19.90,base:false},
  {n:'187',dex:983,artist:"Shin Nagasawa",name:'Kingambit',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:19.00,base:false},
  {n:'188',dex:943,artist:"Hitoshi Ariga",name:'Mabosstiff',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:15.40,base:false},
  {n:'189',dex:944,artist:"otumami",name:'Shroodle',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:7.80,base:false},
  {n:'190',dex:945,artist:"Scav",name:'Grafaiai',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:16.50,base:false},
  {n:'191',dex:212,artist:"GOSSAN",name:'Scizor',type:'Metal',color:'#78909C',rare:'Rara Brilhante',price:48.99,base:false,important:true},
  {n:'192',dex:965,artist:"Masakazu Fukuda",name:'Varoom',type:'Metal',color:'#78909C',rare:'Rara Brilhante',price:6.60,base:false},
  {n:'193',dex:966,artist:"GOSSAN",name:'Revavroom',type:'Metal',color:'#78909C',rare:'Rara Brilhante',price:14.00,base:false},
  {n:'194',dex:714,artist:"Nelnal",name:'Noibat',type:'Dragão',color:'#3F51B5',rare:'Rara Brilhante',price:24.89,base:false},
  {n:'195',dex:967,artist:"Souichirou Gunjima",name:'Cyclizar',type:'Dragão',color:'#3F51B5',rare:'Rara Brilhante',price:14.00,base:false},
  {n:'196',dex:16,artist:"sowsow",name:'Pidgey',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:43.99,base:false},
  {n:'197',dex:17,artist:"Kouki Saitou",name:'Pidgeotto',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:45.00,base:false},
  {n:'198',dex:39,artist:"Misa Tsutsui",name:'Jigglypuff',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:59.80,base:false,important:true},
  {n:'199',dex:84,artist:"Saya Tsuruta",name:'Doduo',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:55.00,base:false},
  {n:'200',dex:85,artist:"nagimiso",name:'Dodrio',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:29.75,base:false},
  {n:'201',dex:132,artist:"0313",name:'Ditto',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:104.90,base:false,important:true},
  {n:'202',dex:143,artist:"Shigenori Negishi",name:'Snorlax',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:199.99,base:false,important:true},
  {n:'203',dex:278,artist:"kurumitsu",name:'Wingull',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:31.90,base:false},
  {n:'204',dex:279,artist:"Masakazu Fukuda",name:'Pelipper',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:19.90,base:false},
  {n:'205',dex:819,artist:"Sanosuke Sakuma",name:'Skwovet',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:9.99,base:false},
  {n:'206',dex:820,artist:"Kagemaru Himeno",name:'Greedent',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:19.50,base:false},
  {n:'207',dex:915,artist:"Akira Komayama",name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:27.90,base:false,important:true},
  {n:'208',dex:916,artist:"Misa Tsutsui",name:'Oinkologne',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:29.75,base:false},
  {n:'209',dex:924,artist:"Lee HyunJung",name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:54.90,base:false,important:true},
  {n:'210',dex:925,artist:"Shigenori Negishi",name:'Maushold',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:99.90,base:false,important:true},
  {n:'211',dex:973,artist:"Akira Komayama",name:'Flamigo',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:22.90,base:false},
  {n:'212',dex:205,artist:"5ban Graphics",name:'Forretress ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara Brilhante',price:7.99,base:false},
  {n:'213',dex:949,artist:"5ban Graphics",name:'Toedscruel ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara Brilhante',price:9.79,base:false},
  {n:'214',dex:956,artist:"takuyoa",name:'Espathra ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara Brilhante',price:8.00,base:false},
  {n:'215',dex:65,artist:"PLANETA Tsuji",name:'Alakazam ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara Brilhante',price:28.90,base:false},
  {n:'216',dex:151,artist:"aky CG Works",name:'Mew ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara Brilhante',price:119.90,base:false,important:true},
  {n:'217',dex:282,artist:"N-DESIGN Inc.",name:'Gardevoir ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara Brilhante',price:39.00,base:false,important:true},
  {n:'218',dex:970,artist:"5ban Graphics",name:'Glimmora ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara Brilhante',price:6.90,base:false},
  {n:'219',dex:980,artist:"PLANETA Mochizuki",name:'Paldean Clodsire ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara Brilhante',price:7.00,base:false},
  {n:'220',dex:715,artist:"Eske Yoshinob",name:'Noivern ex',type:'Dragão',color:'#3F51B5',rare:'Ultra Rara Brilhante',price:9.88,base:false},
  {n:'221',dex:18,artist:"takuyoa",name:'Pidgeot ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara Brilhante',price:15.00,base:false},
  {n:'222',dex:40,artist:"Saki Hayashiro",name:'Wigglytuff ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara Brilhante',price:14.00,base:false},
  {n:'223',dex:931,artist:"PLANETA Mochizuki",name:'Squawkabilly ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara Brilhante',price:4.99,base:false},
  {n:'224',dex:961,artist:"Tetsu Kayama",name:'Wugtrio',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:8.00,base:false},
  {n:'225',dex:964,artist:"akagi",name:'Palafin',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:9.00,base:false},
  {n:'226',dex:921,artist:"REND",name:'Pawmi',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:9.90,base:false},
  {n:'227',artist:"GOSSAN",name:'Clive',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:3.90,base:false},
  {n:'228',artist:"Hideki Ishikawa",name:'Judge',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:17.00,base:false},
  {n:'229',artist:"Sanosuke Sakuma",name:'Nemona',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:6.00,base:false},
  {n:'230',artist:"Cona Nitanda",name:'Paldean Student',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:3.90,base:false},
  {n:'231',artist:"Naoki Saito",name:'Paldean Student',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:4.00,base:false},
  {n:'232',dex:151,artist:"USGMEN",name:'Mew ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:1999.00,base:false,important:true},
  {n:'233',dex:282,artist:"Kuroimori",name:'Gardevoir ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:349.90,base:false,important:true},
  {n:'234',dex:6,artist:"AKIRA EGAWA",name:'Charizard ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:499.99,base:false,important:true},
  {n:'235',artist:"aspara",name:'Arven',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:38.50,base:false,important:true},
  {n:'236',artist:"Taiga Kayama",name:'Clive',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:66.50,base:false,important:true},
  {n:'237',artist:"hanabushi",name:'Iono',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:104.50,base:false,important:true},
  {n:'238',artist:"aspara",name:'Nemona',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:30.00,base:false},
  {n:'239',artist:"aspara",name:'Penny',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:46.90,base:false,important:true},
  {n:'240',dex:1001,artist:"5ban Graphics",name:'Wo-Chien ex',type:'Planta',color:'#4CAF50',rare:'Hiper Rara',price:40.00,base:false},
  {n:'241',dex:1004,artist:"PLANETA Yamashita",name:'Chi-Yu ex',type:'Fogo',color:'#F44336',rare:'Hiper Rara',price:29.90,base:false,important:true},
  {n:'242',dex:1002,artist:"aky CG Works",name:'Chien-Pao ex',type:'Aquático',color:'#2196F3',rare:'Hiper Rara',price:42.00,base:false,important:true},
  {n:'243',dex:1008,artist:"5ban Graphics",name:'Miraidon ex',type:'Raio',color:'#FFEB3B',rare:'Hiper Rara',price:35.00,base:false,important:true},
  {n:'244',dex:1003,artist:"5ban Graphics",name:'Ting-Lu ex',type:'Lutador',color:'#FF9800',rare:'Hiper Rara',price:29.75,base:false},
  {n:'245',dex:1007,artist:"aky CG Works",name:'Koraidon ex',type:'Lutador',color:'#FF9800',rare:'Hiper Rara',price:59.90,base:false,important:true}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV4PT5 = CARDS_SV4PT5;