// SV5 — Temporal Forces (218 cartas)
// Lançamento EN: 2024/03/22
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV5 = [
  {n:'001',dex:123,artist:"Dsuke",name:'Scyther',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'002',dex:204,artist:"Midori Harada",name:'Pineco',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'003',dex:273,artist:"Asako Ito",name:'Seedot',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'004',dex:274,artist:"Lee HyunJung",name:'Nuzleaf',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'005',dex:275,artist:"Souichirou Gunjima",name:'Shiftry',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.23,base:true},
  {n:'006',dex:285,artist:"Yoriyuki Ikegami",name:'Shroomish',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'007',dex:286,artist:"Taiga Kasai",name:'Breloom',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'008',dex:315,artist:"Tomomi Kaneko",name:'Roselia',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.09,base:true},
  {n:'009',dex:407,artist:"matazo",name:'Roserade',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'010',dex:387,artist:"OKACHEKE",name:'Turtwig',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'011',dex:388,artist:"Uninori",name:'Grotle',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.23,base:true},
  {n:'012',dex:389,artist:"PLANETA Tsuji",name:'Torterra ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:4.00,base:true},
  {n:'013',dex:492,artist:"Atsushi Furusawa",name:'Shaymin',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.19,base:true},
  {n:'014',dex:546,artist:"Kyoko Umemoto",name:'Cottonee',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.13,base:true},
  {n:'015',dex:547,artist:"Mizue",name:'Whimsicott',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.23,base:true},
  {n:'016',dex:585,artist:"Rond",name:'Deerling',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'017',dex:586,artist:"Akira Komayama",name:'Sawsbuck',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.19,base:true},
  {n:'018',dex:736,artist:"Kagemaru Himeno",name:'Grubbin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.09,base:true},
  {n:'019',dex:781,artist:"Saya Tsuruta",name:'Dhelmise',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'020',dex:946,artist:"Tetsu Kayama",name:'Bramblin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'021',dex:947,artist:"otumami",name:'Brambleghast',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.25,base:true},
  {n:'022',dex:952,artist:"PLANETA Mochizuki",name:'Scovillain ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.50,base:true},
  {n:'023',dex:953,artist:"Saboteri",name:'Rellor',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'024',dex:954,artist:"mingo",name:'Rabsca',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.25,base:true},
  {n:'025',dex:1010,artist:"5ban Graphics",name:'Iron Leaves ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:5.00,base:true},
  {n:'026',dex:77,artist:"takashi shiraishi",name:'Ponyta',type:'Fogo',color:'#F44336',rare:'Comum',price:0.20,base:true},
  {n:'027',dex:78,artist:"Ryota Murayama",name:'Rapidash',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.20,base:true},
  {n:'028',dex:218,artist:"Haru Akasaka",name:'Slugma',type:'Fogo',color:'#F44336',rare:'Comum',price:0.20,base:true},
  {n:'029',dex:219,artist:"Mitsuhiro Arita",name:'Magcargo',type:'Fogo',color:'#F44336',rare:'Rara',price:0.20,base:true},
  {n:'030',dex:494,artist:"Shibuzoh.",name:'Victini',type:'Fogo',color:'#F44336',rare:'Comum',price:0.23,base:true},
  {n:'031',dex:631,artist:"Masakazu Fukuda",name:'Heatmor',type:'Fogo',color:'#F44336',rare:'Comum',price:0.15,base:true},
  {n:'032',dex:725,artist:"REND",name:'Litten',type:'Fogo',color:'#F44336',rare:'Comum',price:0.15,base:true},
  {n:'033',dex:726,artist:"Saya Tsuruta",name:'Torracat',type:'Fogo',color:'#F44336',rare:'Comum',price:0.25,base:true},
  {n:'034',dex:727,artist:"N-DESIGN Inc.",name:'Incineroar ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:5.95,base:true},
  {n:'035',dex:776,artist:"Shigenori Negishi",name:'Turtonator',type:'Fogo',color:'#F44336',rare:'Comum',price:0.15,base:true},
  {n:'036',dex:850,artist:"Yukiko Baba",name:'Sizzlipede',type:'Fogo',color:'#F44336',rare:'Comum',price:0.15,base:true},
  {n:'037',dex:851,artist:"Krgc",name:'Centiskorch',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.19,base:true},
  {n:'038',artist:"5ban Graphics",name:'Gouging Fire ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:3.99,base:true},
  {n:'039',dex:158,artist:"MINAMINAMI Take",name:'Totodile',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'040',dex:159,artist:"Jerky",name:'Croconaw',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.25,base:true},
  {n:'041',dex:160,artist:"GOSSAN",name:'Feraligatr',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.99,base:true},
  {n:'042',dex:318,artist:"Souichirou Gunjima",name:'Carvanha',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'043',dex:319,artist:"Shinji Kanda",name:'Sharpedo',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.20,base:true},
  {n:'044',dex:647,artist:"satoma",name:'Keldeo',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.25,base:true},
  {n:'045',dex:872,artist:"Orca",name:'Snom',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.15,base:true},
  {n:'046',dex:873,artist:"rika",name:'Frosmoth',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'047',dex:960,artist:"OKUBO",name:'Wiglett',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'048',dex:963,artist:"HYOGONOSUKE",name:'Finizen',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'049',dex:964,artist:"DOM",name:'Palafin',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.20,base:true},
  {n:'050',dex:1009,artist:"takuyoa",name:'Walking Wake ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:5.90,base:true},
  {n:'051',dex:25,artist:"kodama",name:'Pikachu',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.39,base:true},
  {n:'052',dex:26,artist:"cochi8i",name:'Raichu',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.35,base:true},
  {n:'053',dex:125,artist:"Uta",name:'Electabuzz',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.20,base:true},
  {n:'054',dex:466,artist:"Yuya Oka",name:'Electivire',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.25,base:true},
  {n:'055',dex:737,artist:"Misa Tsutsui",name:'Charjabug',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.19,base:true},
  {n:'056',dex:738,artist:"Hitoshi Ariga",name:'Vikavolt',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.18,base:true},
  {n:'057',dex:807,artist:"kantaro",name:'Zeraora',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.20,base:true},
  {n:'058',dex:835,artist:"kurumitsu",name:'Yamper',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.10,base:true},
  {n:'059',dex:836,artist:"Oswaldo KATO",name:'Boltund',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.13,base:true},
  {n:'060',dex:961,artist:"5ban Graphics",name:'Wugtrio ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:2.90,base:true},
  {n:'061',dex:992,artist:"Souichirou Gunjima",name:'Iron Hands',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.25,base:true},
  {n:'062',dex:995,artist:"Takeshi Nakamura",name:'Iron Thorns',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.25,base:true},
  {n:'063',dex:122,artist:"Nelnal",name:'Mr. Mime',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.23,base:true},
  {n:'064',dex:183,artist:"yuu",name:'Marill',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.19,base:true},
  {n:'065',dex:184,artist:"Makura Tami",name:'Azumarill',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.25,base:true},
  {n:'066',dex:203,artist:"matazo",name:'Girafarig',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'067',dex:380,artist:"Takumi Wada",name:'Latias',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.25,base:true},
  {n:'068',dex:436,artist:"Kedamahadaitai Yawarakai",name:'Bronzor',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'069',dex:437,artist:"Katsunori Sato",name:'Bronzong',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.35,base:true},
  {n:'070',dex:577,artist:"Cona Nitanda",name:'Solosis',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'071',dex:578,artist:"mele",name:'Duosion',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'072',dex:579,artist:"Gemi",name:'Reuniclus',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'073',dex:605,artist:"Tomokazu Komiya",name:'Elgyem',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'074',dex:606,artist:"Shinya Komatsu",name:'Beheeyem',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.20,base:true},
  {n:'075',dex:742,artist:"Sekio",name:'Cutiefly',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.17,base:true},
  {n:'076',dex:743,artist:"Tika Matsuno",name:'Ribombee',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.20,base:true},
  {n:'077',dex:985,artist:"kawayoo",name:'Scream Tail',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.10,base:true},
  {n:'078',dex:987,artist:"kodama",name:'Flutter Mane',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.32,base:true},
  {n:'079',dex:1006,artist:"takuyoa",name:'Iron Valiant',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.20,base:true},
  {n:'080',dex:1006,artist:"chibi",name:'Iron Valiant',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.40,base:true},
  {n:'081',artist:"5ban Graphics",name:'Iron Crown ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:5.00,base:true},
  {n:'082',dex:307,artist:"Natsumi Miyanose",name:'Meditite',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'083',dex:308,artist:"Masako Tomii",name:'Medicham',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.20,base:true},
  {n:'084',dex:369,artist:"Mina Nakai",name:'Relicanth',type:'Lutador',color:'#FF9800',rare:'Rara',price:1.00,base:true},
  {n:'085',dex:529,artist:"Kariya",name:'Drilbur',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.20,base:true},
  {n:'086',dex:530,artist:"Bun Toujo",name:'Excadrill',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'087',dex:622,artist:"miki kudo",name:'Golett',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.19,base:true},
  {n:'088',dex:623,artist:"Oku",name:'Golurk',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.10,base:true},
  {n:'089',dex:744,artist:"sui",name:'Rockruff',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'090',dex:745,artist:"Yoshioka",name:'Lycanroc',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'091',dex:749,artist:"Narumi Sato",name:'Mudbray',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'092',dex:750,artist:"Naoyo Kimura",name:'Mudsdale',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'093',dex:837,artist:"Aya Kusube",name:'Rolycoly',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.16,base:true},
  {n:'094',dex:838,artist:"Anesaki Dynamic",name:'Carkol',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.20,base:true},
  {n:'095',dex:839,artist:"Shiburingaru",name:'Coalossal',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'096',dex:984,artist:"Mitsuhiro Arita",name:'Great Tusk',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'097',dex:984,artist:"GIDORA",name:'Great Tusk',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.13,base:true},
  {n:'098',dex:989,artist:"DOM",name:'Sandy Shocks',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.20,base:true},
  {n:'099',artist:"5ban Graphics",name:'Iron Boulder ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:1.90,base:true},
  {n:'100',dex:23,artist:"Shimaris Yukichi",name:'Ekans',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.20,base:true},
  {n:'101',dex:24,artist:"Minato",name:'Arbok',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.30,base:true},
  {n:'102',dex:92,artist:"Fujimoto Gold",name:'Gastly',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.25,base:true},
  {n:'103',dex:93,artist:"MAHOU",name:'Haunter',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.33,base:true},
  {n:'104',dex:94,artist:"Nisota Niso",name:'Gengar ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:35.00,base:true},
  {n:'105',dex:261,artist:"Miki Tanaka",name:'Poochyena',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'106',dex:262,artist:"akagi",name:'Mightyena',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.18,base:true},
  {n:'107',dex:302,artist:"0313",name:'Sableye',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'108',dex:981,artist:"5ban Graphics",name:'Farigiraf ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:4.00,base:true},
  {n:'109',dex:1005,artist:"hncl",name:'Roaring Moon',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.45,base:true},
  {n:'110',dex:205,artist:"osare",name:'Forretress',type:'Metal',color:'#78909C',rare:'Incomum',price:0.20,base:true},
  {n:'111',dex:212,artist:"toriyufu",name:'Scizor ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:4.49,base:true},
  {n:'112',dex:303,artist:"aspara",name:'Mawile',type:'Metal',color:'#78909C',rare:'Comum',price:0.20,base:true},
  {n:'113',dex:374,artist:"hatachu",name:'Beldum',type:'Metal',color:'#78909C',rare:'Comum',price:0.25,base:true},
  {n:'114',dex:375,artist:"Nobuhiro Imagawa",name:'Metang',type:'Metal',color:'#78909C',rare:'Comum',price:8.90,base:true},
  {n:'115',dex:376,artist:"Nurikabe",name:'Metagross',type:'Metal',color:'#78909C',rare:'Incomum',price:0.20,base:true},
  {n:'116',dex:808,artist:"Taiga Kayama",name:'Meltan',type:'Metal',color:'#78909C',rare:'Comum',price:0.13,base:true},
  {n:'117',dex:809,artist:"Oswaldo KATO",name:'Melmetal',type:'Metal',color:'#78909C',rare:'Rara',price:0.17,base:true},
  {n:'118',dex:990,artist:"Tonji Matsuno",name:'Iron Treads',type:'Metal',color:'#78909C',rare:'Incomum',price:0.20,base:true},
  {n:'119',dex:1007,artist:"Teeziro",name:'Koraidon',type:'Dragão',color:'#3F51B5',rare:'Rara',price:0.30,base:true},
  {n:'120',dex:1007,artist:"PLANETA Igarashi",name:'Koraidon ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:4.00,base:true},
  {n:'121',dex:1008,artist:"GOSSAN",name:'Miraidon',type:'Dragão',color:'#3F51B5',rare:'Rara',price:0.15,base:true},
  {n:'122',dex:1008,artist:"PLANETA Mochizuki",name:'Miraidon ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:2.99,base:true},
  {n:'123',artist:"aky CG Works",name:'Raging Bolt ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:8.67,base:true},
  {n:'124',dex:108,artist:"nisimono",name:'Lickitung',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'125',dex:463,artist:"kirisAki",name:'Lickilicky',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'126',dex:163,artist:"ryoma uratsuka",name:'Hoothoot',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.17,base:true},
  {n:'127',dex:164,artist:"toi8",name:'Noctowl',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'128',dex:206,artist:"Sanosuke Sakuma",name:'Dunsparce',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.09,base:true},
  {n:'129',dex:982,artist:"Teeziro",name:'Dudunsparce',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:9.90,base:true},
  {n:'130',dex:300,artist:"Atsuko Nishida",name:'Skitty',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'131',dex:301,artist:"Keisin",name:'Delcatty',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'132',dex:441,artist:"GOTO minori",name:'Chatot',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'133',dex:519,artist:"Mékayu",name:'Pidove',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'134',dex:520,artist:"Pani Kobayashi",name:'Tranquill',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'135',dex:521,artist:"Anesaki Dynamic",name:'Unfezant',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'136',dex:572,artist:"Yuka Morii",name:'Minccino',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'137',dex:573,artist:"Yuu Nishida",name:'Cinccino',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'138',dex:780,artist:"Toshinao Aoki",name:'Drampa',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.20,base:true},
  {n:'139',dex:993,artist:"KEIICHIRO ITO",name:'Iron Jugulis',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'140',artist:"5ban Graphics",name:'Ancient Booster Energy Capsule',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'141',artist:"Toyste Beach",name:'Awakening Drum',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:3.79,base:false},
  {n:'142',artist:"En Morikura",name:'Bianca\'s Devotion',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.14,base:true},
  {n:'143',artist:"Studio Bora Inc.",name:'Boxed Order',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'144',artist:"AYUMI ODASHIMA",name:'Buddy-Buddy Poffin',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'145',artist:"Taira Akitsu",name:'Ciphermaniac\'s Codebreaking',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'146',artist:"GOSSAN",name:'Eri',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'147',artist:"Hideki Ishikawa",name:'Explorer\'s Guidance',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.12,base:true},
  {n:'148',artist:"AYUMI ODASHIMA",name:'Full Metal Lab',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'149',artist:"5ban Graphics",name:'Future Booster Energy Capsule',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.14,base:true},
  {n:'150',artist:"Ayaka Yoshida",name:'Hand Trimmer',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.18,base:true},
  {n:'151',artist:"Ayaka Yoshida",name:'Heavy Baton',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'152',artist:"Toyste Beach",name:'Hero\'s Cape',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:169.90,base:false,important:true},
  {n:'153',artist:"Studio Bora Inc.",name:'Master Ball',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:11.00,base:false},
  {n:'154',artist:"inose yukie",name:'Maximum Belt',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:14.90,base:false},
  {n:'155',artist:"GIDORA",name:'Morty\'s Conviction',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'156',artist:"AYUMI ODASHIMA",name:'Perilous Jungle',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'157',artist:"Toyste Beach",name:'Prime Catcher',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:3.50,base:false},
  {n:'158',artist:"inose yukie",name:'Reboot Pod',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:4.00,base:false},
  {n:'159',artist:"Toyste Beach",name:'Rescue Board',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'160',artist:"Ryuta Fuse",name:'Salvatore',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'161',name:'Mist Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:5.00,base:true},
  {n:'162',name:'Neo Upper Energy',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:95.90,base:false,important:true},
  {n:'163',dex:275,artist:"SIE NANAHARA",name:'Shiftry',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:29.50,base:false,important:true},
  {n:'164',dex:388,artist:"Oswaldo KATO",name:'Grotle',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:60.00,base:false,important:true},
  {n:'165',dex:585,artist:"Susumu Maeya",name:'Deerling',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:299.90,base:false,important:true},
  {n:'166',dex:586,artist:"Susumu Maeya",name:'Sawsbuck',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:59.90,base:false,important:true},
  {n:'167',dex:725,artist:"Makura Tami",name:'Litten',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:84.90,base:false,important:true},
  {n:'168',dex:872,artist:"N-DESIGN Inc.",name:'Snom',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:44.99,base:false,important:true},
  {n:'169',dex:737,artist:"Mina Nakai",name:'Charjabug',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:29.99,base:false,important:true},
  {n:'170',dex:436,artist:"sowsow",name:'Bronzor',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:38.00,base:false,important:true},
  {n:'171',dex:579,artist:"Atsushi Furusawa",name:'Reuniclus',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:48.99,base:false,important:true},
  {n:'172',dex:742,artist:"REND",name:'Cutiefly',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:69.90,base:false,important:true},
  {n:'173',dex:369,artist:"Mitsuhiro Arita",name:'Relicanth',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:37.91,base:false,important:true},
  {n:'174',dex:530,artist:"Saboteri",name:'Excadrill',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:35.00,base:false,important:true},
  {n:'175',dex:750,artist:"MINAMINAMI Take",name:'Mudsdale',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:19.25,base:false,important:true},
  {n:'176',dex:24,artist:"OKUBO",name:'Arbok',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:129.90,base:false,important:true},
  {n:'177',dex:92,artist:"Mousho",name:'Gastly',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:239.90,base:false,important:true},
  {n:'178',dex:376,artist:"Katsunori Sato",name:'Metagross',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:59.99,base:false,important:true},
  {n:'179',dex:808,artist:"Masa",name:'Meltan',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:30.86,base:false},
  {n:'180',dex:108,artist:"Orca",name:'Lickitung',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:198.99,base:false,important:true},
  {n:'181',dex:441,artist:"Scav",name:'Chatot',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:39.90,base:false,important:true},
  {n:'182',dex:572,artist:"Shibuzoh.",name:'Minccino',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:64.90,base:false,important:true},
  {n:'183',dex:573,artist:"Shibuzoh.",name:'Cinccino',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:129.90,base:false,important:true},
  {n:'184',dex:780,artist:"Mékayu",name:'Drampa',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:47.41,base:false,important:true},
  {n:'185',dex:389,artist:"PLANETA Tsuji",name:'Torterra ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:11.99,base:false},
  {n:'186',dex:1010,artist:"5ban Graphics",name:'Iron Leaves ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:15.90,base:false},
  {n:'187',dex:727,artist:"N-DESIGN Inc.",name:'Incineroar ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:14.00,base:false},
  {n:'188',artist:"5ban Graphics",name:'Gouging Fire ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:16.00,base:false},
  {n:'189',dex:1009,artist:"takuyoa",name:'Walking Wake ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:5.25,base:false},
  {n:'190',dex:961,artist:"5ban Graphics",name:'Wugtrio ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:5.00,base:false},
  {n:'191',artist:"5ban Graphics",name:'Iron Crown ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:8.50,base:false},
  {n:'192',artist:"5ban Graphics",name:'Iron Boulder ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:9.80,base:false},
  {n:'193',dex:94,artist:"Satoshi Shirai",name:'Gengar ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:118.75,base:false,important:true},
  {n:'194',dex:981,artist:"5ban Graphics",name:'Farigiraf ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:8.90,base:false},
  {n:'195',dex:212,artist:"Eske Yoshinob",name:'Scizor ex',type:'Metal',color:'#78909C',rare:'Ultra Rara',price:26.90,base:false},
  {n:'196',artist:"aky CG Works",name:'Raging Bolt ex',type:'Dragão',color:'#3F51B5',rare:'Ultra Rara',price:19.90,base:false},
  {n:'197',artist:"En Morikura",name:'Bianca\'s Devotion',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:20.00,base:false},
  {n:'198',artist:"Taira Akitsu",name:'Ciphermaniac\'s Codebreaking',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:47.90,base:false},
  {n:'199',artist:"GOSSAN",name:'Eri',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:24.89,base:false},
  {n:'200',artist:"Hideki Ishikawa",name:'Explorer\'s Guidance',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:19.90,base:false},
  {n:'201',artist:"GIDORA",name:'Morty\'s Conviction',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:34.90,base:false},
  {n:'202',artist:"Ryuta Fuse",name:'Salvatore',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:24.00,base:false},
  {n:'203',dex:1010,artist:"nagimiso",name:'Iron Leaves ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:115.00,base:false,important:true},
  {n:'204',artist:"Teeziro",name:'Gouging Fire ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:142.50,base:false,important:true},
  {n:'205',dex:1009,artist:"Teeziro",name:'Walking Wake ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:119.90,base:false,important:true},
  {n:'206',artist:"nagimiso",name:'Iron Crown ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:104.50,base:false,important:true},
  {n:'207',artist:"nagimiso",name:'Iron Boulder ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:59.90,base:false,important:true},
  {n:'208',artist:"Teeziro",name:'Raging Bolt ex',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada Especial',price:174.75,base:false,important:true},
  {n:'209',artist:"Cona Nitanda",name:'Bianca\'s Devotion',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:349.90,base:false,important:true},
  {n:'210',artist:"DOM",name:'Eri',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:69.00,base:false,important:true},
  {n:'211',artist:"Megumi Mizutani",name:'Morty\'s Conviction',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:249.90,base:false,important:true},
  {n:'212',artist:"Tetsu Kayama",name:'Salvatore',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:95.00,base:false,important:true},
  {n:'213',dex:1010,artist:"5ban Graphics",name:'Iron Leaves ex',type:'Planta',color:'#4CAF50',rare:'Hiper Rara',price:39.90,base:false,important:true},
  {n:'214',artist:"5ban Graphics",name:'Gouging Fire ex',type:'Fogo',color:'#F44336',rare:'Hiper Rara',price:24.50,base:false,important:true},
  {n:'215',dex:1009,artist:"takuyoa",name:'Walking Wake ex',type:'Aquático',color:'#2196F3',rare:'Hiper Rara',price:30.00,base:false,important:true},
  {n:'216',artist:"5ban Graphics",name:'Iron Crown ex',type:'Psíquico',color:'#9C27B0',rare:'Hiper Rara',price:40.00,base:false,important:true},
  {n:'217',artist:"5ban Graphics",name:'Iron Boulder ex',type:'Lutador',color:'#FF9800',rare:'Hiper Rara',price:36.00,base:false,important:true},
  {n:'218',artist:"aky CG Works",name:'Raging Bolt ex',type:'Dragão',color:'#3F51B5',rare:'Hiper Rara',price:49.90,base:false,important:true}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV5 = CARDS_SV5;