// SV8 — Surging Sparks (252 cartas)
// Lançamento EN: 2024/11/08
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV8 = [
  {n:'001',name:'Exeggcute',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.58,base:true},
  {n:'002',name:'Exeggcute',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.35,base:true},
  {n:'003',name:'Exeggutor',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.35,base:true},
  {n:'004',name:'Durant ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.13,base:true},
  {n:'005',name:'Scatterbug',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.41,base:true},
  {n:'006',name:'Spewpa',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.64,base:true},
  {n:'007',name:'Vivillon',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.46,base:true},
  {n:'008',name:'Morelull',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.52,base:true},
  {n:'009',name:'Shiinotic',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.41,base:true},
  {n:'010',name:'Dhelmise',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.41,base:true},
  {n:'011',name:'Zarude',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.3,base:true},
  {n:'012',name:'Capsakid',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.35,base:true},
  {n:'013',name:'Rellor',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.46,base:true},
  {n:'014',name:'Rabsca',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.3,base:true},
  {n:'015',name:'Wo-Chien',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.58,base:true},
  {n:'016',name:'Vulpix',type:'Fogo',color:'#F44336',rare:'Comum',price:0.58,base:true},
  {n:'017',name:'Ninetales',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.64,base:true},
  {n:'018',name:'Paldean Tauros',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.3,base:true},
  {n:'019',name:'Ho-Oh',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.41,base:true},
  {n:'020',name:'Castform Sunny Form',type:'Fogo',color:'#F44336',rare:'Comum',price:0.46,base:true},
  {n:'021',name:'Victini',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.75,base:true},
  {n:'022',name:'Pansear',type:'Fogo',color:'#F44336',rare:'Comum',price:0.3,base:true},
  {n:'023',name:'Simisear',type:'Fogo',color:'#F44336',rare:'Comum',price:0.41,base:true},
  {n:'024',name:'Larvesta',type:'Fogo',color:'#F44336',rare:'Comum',price:0.3,base:true},
  {n:'025',name:'Volcarona',type:'Fogo',color:'#F44336',rare:'Comum',price:0.41,base:true},
  {n:'026',name:'Oricorio',type:'Fogo',color:'#F44336',rare:'Comum',price:0.41,base:true},
  {n:'027',name:'Sizzlipede',type:'Fogo',color:'#F44336',rare:'Comum',price:0.41,base:true},
  {n:'028',name:'Centiskorch',type:'Fogo',color:'#F44336',rare:'Comum',price:0.52,base:true},
  {n:'029',name:'Fuecoco',type:'Fogo',color:'#F44336',rare:'Comum',price:0.41,base:true},
  {n:'030',name:'Crocalor',type:'Fogo',color:'#F44336',rare:'Comum',price:0.64,base:true},
  {n:'031',name:'Skeledirge',type:'Fogo',color:'#F44336',rare:'Rara',price:0.64,base:true},
  {n:'032',name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:1.04,base:true},
  {n:'033',name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.58,base:true},
  {n:'034',name:'Armarouge',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.52,base:true},
  {n:'035',name:'Ceruledge',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.58,base:true},
  {n:'036',name:'Ceruledge ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:7.08,base:true},
  {n:'037',name:'Scovillain ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:2.96,base:true},
  {n:'038',name:'Gouging Fire',type:'Fogo',color:'#F44336',rare:'Rara',price:0.52,base:true},
  {n:'039',name:'Paldean Tauros',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.46,base:true},
  {n:'040',name:'Mantine',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.52,base:true},
  {n:'041',name:'Feebas',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.46,base:true},
  {n:'042',name:'Milotic ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:3.89,base:true},
  {n:'043',name:'Spheal',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.52,base:true},
  {n:'044',name:'Sealeo',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.3,base:true},
  {n:'045',name:'Walrein',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.3,base:true},
  {n:'046',name:'Shellos',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.52,base:true},
  {n:'047',name:'Cryogonal',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.41,base:true},
  {n:'048',name:'Black Kyurem ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:3.13,base:true},
  {n:'049',name:'Bruxish',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.3,base:true},
  {n:'050',name:'Quaxly',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.3,base:true},
  {n:'051',name:'Quaxwell',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.35,base:true},
  {n:'052',name:'Quaquaval',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.3,base:true},
  {n:'053',name:'Cetoddle',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.3,base:true},
  {n:'054',name:'Cetitan',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.52,base:true},
  {n:'055',name:'Iron Bundle',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.3,base:true},
  {n:'056',name:'Chien-Pao',type:'Aquático',color:'#2196F3',rare:'Rara',price:1.1,base:true},
  {n:'057',name:'Pikachu ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:23.2,base:true},
  {n:'058',name:'Magnemite',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.41,base:true},
  {n:'059',name:'Magneton',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.7,base:true},
  {n:'060',name:'Magnezone',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.35,base:true},
  {n:'061',name:'Rotom',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.46,base:true},
  {n:'062',name:'Blitzle',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.52,base:true},
  {n:'063',name:'Zebstrika',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.46,base:true},
  {n:'064',name:'Stunfisk',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.41,base:true},
  {n:'065',name:'Tapu Koko',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.35,base:true},
  {n:'066',name:'Wattrel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.46,base:true},
  {n:'067',name:'Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.41,base:true},
  {n:'068',name:'Kilowattrel ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:3.19,base:true},
  {n:'069',name:'Miraidon',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.3,base:true},
  {n:'070',name:'Togepi',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.64,base:true},
  {n:'071',name:'Togetic',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.58,base:true},
  {n:'072',name:'Togekiss',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.64,base:true},
  {n:'073',name:'Marill',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.3,base:true},
  {n:'074',name:'Azumarill',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.41,base:true},
  {n:'075',name:'Smoochum',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:1.39,base:true},
  {n:'076',name:'Latias ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:31.2,base:true},
  {n:'077',name:'Latios',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.3,base:true},
  {n:'078',name:'Uxie',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.52,base:true},
  {n:'079',name:'Mesprit',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.64,base:true},
  {n:'080',name:'Azelf',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.52,base:true},
  {n:'081',name:'Sigilyph',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.3,base:true},
  {n:'082',name:'Yamask',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.3,base:true},
  {n:'083',name:'Cofagrigus',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.58,base:true},
  {n:'084',name:'Espurr',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.64,base:true},
  {n:'085',name:'Meowstic',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.58,base:true},
  {n:'086',name:'Sylveon ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:14.85,base:true},
  {n:'087',name:'Dedenne',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:1.16,base:true},
  {n:'088',name:'Xerneas',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.46,base:true},
  {n:'089',name:'Oricorio',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.7,base:true},
  {n:'090',name:'Sandygast',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.46,base:true},
  {n:'091',name:'Palossand ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:3.36,base:true},
  {n:'092',name:'Tapu Lele',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.7,base:true},
  {n:'093',name:'Indeedee',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.46,base:true},
  {n:'094',name:'Flittle',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.3,base:true},
  {n:'095',name:'Espathra',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.3,base:true},
  {n:'096',name:'Flutter Mane',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.46,base:true},
  {n:'097',name:'Gimmighoul',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.7,base:true},
  {n:'098',name:'Mankey',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.41,base:true},
  {n:'099',name:'Primeape',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.3,base:true},
  {n:'100',name:'Annihilape',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.93,base:true},
  {n:'101',name:'Paldean Tauros',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.41,base:true},
  {n:'102',name:'Phanpy',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.58,base:true},
  {n:'103',name:'Donphan',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.3,base:true},
  {n:'104',name:'Trapinch',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.41,base:true},
  {n:'105',name:'Vibrava',type:'Lutador',color:'#FF9800',rare:'Comum',price:1.1,base:true},
  {n:'106',name:'Flygon ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:3.6,base:true},
  {n:'107',name:'Gastrodon',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.58,base:true},
  {n:'108',name:'Drilbur',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.3,base:true},
  {n:'109',name:'Excadrill',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.41,base:true},
  {n:'110',name:'Landorus',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.3,base:true},
  {n:'111',name:'Passimian',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.99,base:true},
  {n:'112',name:'Clobbopus',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.52,base:true},
  {n:'113',name:'Grapploct',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.41,base:true},
  {n:'114',name:'Glimmet',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.3,base:true},
  {n:'115',name:'Glimmora',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.46,base:true},
  {n:'116',name:'Koraidon',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.41,base:true},
  {n:'117',name:'Deino',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.41,base:true},
  {n:'118',name:'Zweilous',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.87,base:true},
  {n:'119',name:'Hydreigon ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:4.06,base:true},
  {n:'120',name:'Shroodle',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.35,base:true},
  {n:'121',name:'Grafaiai',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.3,base:true},
  {n:'122',name:'Alolan Diglett',type:'Metal',color:'#78909C',rare:'Comum',price:0.3,base:true},
  {n:'123',name:'Alolan Dugtrio',type:'Metal',color:'#78909C',rare:'Incomum',price:0.46,base:true},
  {n:'124',name:'Skarmory',type:'Metal',color:'#78909C',rare:'Comum',price:0.52,base:true},
  {n:'125',name:'Registeel',type:'Metal',color:'#78909C',rare:'Incomum',price:0.46,base:true},
  {n:'126',name:'Bronzor',type:'Metal',color:'#78909C',rare:'Comum',price:0.3,base:true},
  {n:'127',name:'Bronzong',type:'Metal',color:'#78909C',rare:'Comum',price:0.52,base:true},
  {n:'128',name:'Klefki',type:'Metal',color:'#78909C',rare:'Comum',price:0.7,base:true},
  {n:'129',name:'Duraludon',type:'Metal',color:'#78909C',rare:'Comum',price:0.3,base:true},
  {n:'130',name:'Archaludon ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:3.07,base:true},
  {n:'131',name:'Gholdengo',type:'Metal',color:'#78909C',rare:'Incomum',price:0.41,base:true},
  {n:'132',name:'Iron Crown',type:'Metal',color:'#78909C',rare:'Rara',price:0.52,base:true},
  {n:'133',name:'Alolan Exeggutor ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:4.18,base:true},
  {n:'134',name:'Altaria',type:'Dragão',color:'#3F51B5',rare:'Incomum',price:0.35,base:true},
  {n:'135',name:'Dialga',type:'Dragão',color:'#3F51B5',rare:'Rara',price:0.41,base:true},
  {n:'136',name:'Palkia',type:'Dragão',color:'#3F51B5',rare:'Rara',price:0.81,base:true},
  {n:'137',name:'Turtonator',type:'Dragão',color:'#3F51B5',rare:'Incomum',price:0.41,base:true},
  {n:'138',name:'Applin',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.75,base:true},
  {n:'139',name:'Flapple',type:'Dragão',color:'#3F51B5',rare:'Incomum',price:0.52,base:true},
  {n:'140',name:'Appletun',type:'Dragão',color:'#3F51B5',rare:'Incomum',price:0.41,base:true},
  {n:'141',name:'Eternatus',type:'Dragão',color:'#3F51B5',rare:'Rara',price:0.41,base:true},
  {n:'142',name:'Tatsugiri ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:3.94,base:true},
  {n:'143',name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.81,base:true},
  {n:'144',name:'Snorlax',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.75,base:true},
  {n:'145',name:'Slakoth',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.46,base:true},
  {n:'146',name:'Vigoroth',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.35,base:true},
  {n:'147',name:'Slaking ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:3.19,base:true},
  {n:'148',name:'Swablu',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.64,base:true},
  {n:'149',name:'Zangoose',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.52,base:true},
  {n:'150',name:'Kecleon',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.3,base:true},
  {n:'151',name:'Bouffalant',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.46,base:true},
  {n:'152',name:'Rufflet',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.46,base:true},
  {n:'153',name:'Braviary',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.3,base:true},
  {n:'154',name:'Helioptile',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.35,base:true},
  {n:'155',name:'Heliolisk',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.64,base:true},
  {n:'156',name:'Oranguru',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.41,base:true},
  {n:'157',name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.04,base:true},
  {n:'158',name:'Maushold',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.28,base:true},
  {n:'159',name:'Cyclizar ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:3.71,base:true},
  {n:'160',name:'Flamigo ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:3.54,base:true},
  {n:'161',name:'Terapagos',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.46,base:true},
  {n:'162',name:'Amulet of Hope',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:2.44,base:false},
  {n:'163',name:'Babiri Berry',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.41,base:true},
  {n:'164',name:'Brilliant Blender',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:4.18,base:false},
  {n:'165',name:'Call Bell',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.35,base:true},
  {n:'166',name:'Chill Teaser Toy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.58,base:true},
  {n:'167',name:'Clemont\'s Quick Wit',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.58,base:true},
  {n:'168',name:'Colbur Berry',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.46,base:true},
  {n:'169',name:'Counter Gain',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.58,base:true},
  {n:'170',name:'Cyrano',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.28,base:true},
  {n:'171',name:'Deduction Kit',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.46,base:true},
  {n:'172',name:'Dragon Elixir',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.41,base:true},
  {n:'173',name:'Drasna',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.3,base:true},
  {n:'174',name:'Drayton',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.52,base:true},
  {n:'175',name:'Dusk Ball',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.99,base:true},
  {n:'176',name:'Energy Search Pro',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:4,base:false},
  {n:'177',name:'Gravity Mountain',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.75,base:true},
  {n:'178',name:'Jasmine\'s Gaze',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.46,base:true},
  {n:'179',name:'Lisia\'s Appeal',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.04,base:true},
  {n:'180',name:'Lively Stadium',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.41,base:true},
  {n:'181',name:'Meddling Memo',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.35,base:true},
  {n:'182',name:'Megaton Blower',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:2.15,base:false},
  {n:'183',name:'Miracle Headset',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:4.41,base:false},
  {n:'184',name:'Passho Berry',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.41,base:true},
  {n:'185',name:'Precious Trolley',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:12.82,base:false},
  {n:'186',name:'Scramble Switch',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:2.49,base:false},
  {n:'187',name:'Surfer',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.58,base:true},
  {n:'188',name:'Technical Machine: Fluorite',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.41,base:true},
  {n:'189',name:'Tera Orb',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.58,base:true},
  {n:'190',name:'Tyme',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.46,base:true},
  {n:'191',name:'Enriching Energy',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:20.47,base:false},
  {n:'192',name:'Exeggcute',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:45.76,base:false},
  {n:'193',name:'Vivillon',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:34.86,base:false},
  {n:'194',name:'Shiinotic',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:20.36,base:false},
  {n:'195',name:'Castform Sunny Form',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:53.94,base:false,important:true},
  {n:'196',name:'Larvesta',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:16.07,base:false},
  {n:'197',name:'Ceruledge',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:150.34,base:false,important:true},
  {n:'198',name:'Feebas',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:64.61,base:false,important:true},
  {n:'199',name:'Spheal',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:62.29,base:false,important:true},
  {n:'200',name:'Bruxish',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:16.24,base:false},
  {n:'201',name:'Cetitan',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:16.47,base:false},
  {n:'202',name:'Stunfisk',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:11.48,base:false},
  {n:'203',name:'Latios',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:239.6,base:false,important:true},
  {n:'204',name:'Mesprit',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:80.04,base:false,important:true},
  {n:'205',name:'Phanpy',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:54.4,base:false,important:true},
  {n:'206',name:'Vibrava',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:23.14,base:false},
  {n:'207',name:'Clobbopus',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:43.73,base:false},
  {n:'208',name:'Alolan Dugtrio',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:57.36,base:false,important:true},
  {n:'209',name:'Skarmory',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:61.94,base:false,important:true},
  {n:'210',name:'Flapple',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada',price:25.52,base:false},
  {n:'211',name:'Appletun',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada',price:47.27,base:false},
  {n:'212',name:'Slakoth',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:84.16,base:false,important:true},
  {n:'213',name:'Kecleon',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:44.37,base:false},
  {n:'214',name:'Braviary',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:33.06,base:false},
  {n:'215',name:'Durant ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:6.84,base:false},
  {n:'216',name:'Scovillain ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:6.84,base:false},
  {n:'217',name:'Milotic ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:14.91,base:false},
  {n:'218',name:'Black Kyurem ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:16.82,base:false},
  {n:'219',name:'Pikachu ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:185.02,base:false,important:true},
  {n:'220',name:'Latias ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:41.06,base:false},
  {n:'221',name:'Palossand ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:10.61,base:false},
  {n:'222',name:'Flygon ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:18.5,base:false},
  {n:'223',name:'Hydreigon ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:30.91,base:false},
  {n:'224',name:'Archaludon ex',type:'Metal',color:'#78909C',rare:'Ultra Rara',price:7.08,base:false},
  {n:'225',name:'Alolan Exeggutor ex',type:'Dragão',color:'#3F51B5',rare:'Ultra Rara',price:13.63,base:false},
  {n:'226',name:'Tatsugiri ex',type:'Dragão',color:'#3F51B5',rare:'Ultra Rara',price:12.3,base:false},
  {n:'227',name:'Slaking ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:6.73,base:false},
  {n:'228',name:'Cyclizar ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:9.69,base:false},
  {n:'229',name:'Clemont\'s Quick Wit',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8.06,base:false},
  {n:'230',name:'Cyrano',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:20.94,base:false},
  {n:'231',name:'Drasna',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:5.8,base:false},
  {n:'232',name:'Drayton',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:6.21,base:false},
  {n:'233',name:'Jasmine\'s Gaze',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:9.86,base:false},
  {n:'234',name:'Lisia\'s Appeal',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:22.04,base:false},
  {n:'235',name:'Surfer',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:6.26,base:false},
  {n:'236',name:'Durant ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:223.24,base:false,important:true},
  {n:'237',name:'Milotic ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:830.5,base:false,important:true},
  {n:'238',name:'Pikachu ex',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada Especial',price:2221.34,base:false,important:true},
  {n:'239',name:'Latias ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:1111.11,base:false,important:true},
  {n:'240',name:'Hydreigon ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:248.99,base:false,important:true},
  {n:'241',name:'Archaludon ex',type:'Metal',color:'#78909C',rare:'Rara Ilustrada Especial',price:83,base:false,important:true},
  {n:'242',name:'Alolan Exeggutor ex',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada Especial',price:203.41,base:false,important:true},
  {n:'243',name:'Clemont\'s Quick Wit',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:53.53,base:false,important:true},
  {n:'244',name:'Drayton',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:44.6,base:false},
  {n:'245',name:'Jasmine\'s Gaze',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:136.36,base:false,important:true},
  {n:'246',name:'Lisia\'s Appeal',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:185.95,base:false,important:true},
  {n:'247',name:'Pikachu ex',type:'Raio',color:'#FFEB3B',rare:'Hiper Rara',price:569.39,base:false,important:true},
  {n:'248',name:'Alolan Exeggutor ex',type:'Dragão',color:'#3F51B5',rare:'Hiper Rara',price:62,base:false,important:true},
  {n:'249',name:'Counter Gain',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:23.03,base:false},
  {n:'250',name:'Gravity Mountain',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:59.28,base:false,important:true}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV8 = CARDS_SV8;