// ME05 — Escuridão Absoluta (Abyss Eye / M5) — 118 cartas
// Lancamento Japao: 22 mai 2026 | Lancamento BR (Copag): 17 jul 2026 | Pre-lancamento: 4-12 jul 2026
// Tema: Mega Darkrai ex, Mega Zeraora ex, Mega Chandelure ex, Mega Excadrill ex
// Fonte: deckcerto.com (galeria completa + ranking top 20 mais caras, precos em USD, mercado internacional)
// NOTA: Precos de cartas fora do top 20 sao estimativas por raridade — ajustar quando o mercado BR abrir.
const CARDS_ME05 = [
  // ── SET BASE 001–081 ─────────────────────────────────────
  // CORRIGIDO 18/07/2026: as 8 cartas "ex" da base (004,015,026,036,043,046,
  // 053,063) estavam com rare:'Rara' (mesmo texto de Rare Holo comum), o que faz
  // getSlots() (app.js) cair no ramo [F,RH] — 2 versões colecionáveis. Na vida
  // real "ex" é raridade Double Rare (Rara Dupla), impressão única, sem reverse
  // holo (confirmado contra limitlesstcg.com/cards/PBL/4 — Lurantis ex é só
  // "Double Rare", 1 print). Trocado pra rare:'Rara Dupla', que já cai no ramo
  // [F] (1 versão) — mesmo padrão usado em cards_me02/03/04.js e cards_meg.js
  // pras cartas ex deles. Isso pedia 8 versões fantasma a mais no master set.
  // Ver [[project_pokemon_tcg]].
  {n:'001',name:'Tropius',         type:'Grama',   color:'#4CAF50',rare:'Comum',   price:0.15,base:true},
  {n:'002',name:'Grubbin',         type:'Grama',   color:'#4CAF50',rare:'Comum',   price:0.15,base:true},
  {n:'003',name:'Fomantis',        type:'Grama',   color:'#4CAF50',rare:'Comum',   price:0.15,base:true},
  {n:'004',name:'Lurantis ex',     type:'Grama',   color:'#4CAF50',rare:'Rara Dupla',price:3.15,base:true},
  {n:'005',name:'Poltchageist',    type:'Trevas',  color:'#212121',rare:'Comum',   price:0.15,base:true},
  {n:'006',name:'Sinistcha',       type:'Trevas',  color:'#212121',rare:'Incomum', price:0.20,base:true},
  {n:'007',name:'Heatran',        type:'Fogo',    color:'#F44336',rare:'Incomum', price:0.15,base:true},
  {n:'008',name:'Sizzlipede',      type:'Fogo',    color:'#F44336',rare:'Comum',   price:4.15,base:true},
  {n:'009',name:'Centiskorch',     type:'Fogo',    color:'#F44336',rare:'Incomum', price:0.15,base:true},
  {n:'010',name:'Charcadet',       type:'Fogo',    color:'#F44336',rare:'Comum',   price:0.15,base:true},
  {n:'011',name:'Armarouge',       type:'Fogo',    color:'#F44336',rare:'Incomum', price:0.15,base:true},
  {n:'012',name:'Goldeen',         type:'Agua',    color:'#2196F3',rare:'Comum',   price:0.25,base:true},
  {n:'013',name:'Seaking',         type:'Agua',    color:'#2196F3',rare:'Incomum', price:0.15,base:true},
  {n:'014',name:'Wailmer',         type:'Agua',    color:'#2196F3',rare:'Comum',   price:0.10,base:true},
  {n:'015',name:'Wailord ex',      type:'Agua',    color:'#2196F3',rare:'Rara Dupla',price:0.15,base:true},
  {n:'016',name:'Relicanth',       type:'Agua',    color:'#2196F3',rare:'Incomum', price:3.20,base:true},
  {n:'017',name:'Popplio',         type:'Agua',    color:'#2196F3',rare:'Comum',   price:0.20,base:true},
  {n:'018',name:'Brionne',         type:'Agua',    color:'#2196F3',rare:'Comum',   price:0.10,base:true},
  {n:'019',name:'Primarina',       type:'Agua',    color:'#2196F3',rare:'Incomum', price:0.15,base:true},
  {n:'020',name:'Finizen',         type:'Agua',    color:'#2196F3',rare:'Comum',   price:0.25,base:true},
  {n:'021',name:'Palafin',         type:'Agua',    color:'#2196F3',rare:'Incomum', price:0.15,base:true},
  {n:'022',name:'Electrike',       type:'Eletrico', color:'#FFC107',rare:'Comum',  price:0.10,base:true},
  {n:'023',name:'Manectric',       type:'Eletrico', color:'#FFC107',rare:'Incomum',price:0.15,base:true},
  {n:'024',name:'Charjabug',       type:'Eletrico', color:'#FFC107',rare:'Comum',  price:0.20,base:true},
  {n:'025',name:'Vikavolt',        type:'Eletrico', color:'#FFC107',rare:'Incomum',price:0.15,base:true},
  {n:'026',name:'Mega Zeraora ex', type:'Eletrico', color:'#FFC107',rare:'Rara Dupla',price:0.15,base:true},
  {n:'027',name:'Miraidon',        type:'Eletrico', color:'#FFC107',rare:'Incomum',price:4.50,base:true},
  {n:'028',name:'Slowpoke',        type:'Psiquico', color:'#9C27B0',rare:'Comum',  price:0.15,base:true},
  {n:'029',name:'Slowbro',         type:'Psiquico', color:'#9C27B0',rare:'Incomum',price:0.17,base:true},
  {n:'030',name:'Jynx',            type:'Psiquico', color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'031',name:'Shuppet',         type:'Trevas',  color:'#212121',rare:'Comum',   price:4.55,base:true},
  {n:'032',name:'Banette',         type:'Trevas',  color:'#212121',rare:'Incomum', price:0.15,base:true},
  {n:'033',name:'Spiritomb',       type:'Trevas',  color:'#212121',rare:'Incomum', price:0.15,base:true},
  {n:'034',name:'Litwick',         type:'Fogo',    color:'#F44336',rare:'Comum',   price:0.15,base:true},
  {n:'035',name:'Lampent',         type:'Fogo',    color:'#F44336',rare:'Incomum', price:0.25,base:true},
  {n:'036',name:'Mega Chandelure ex',type:'Fogo',  color:'#F44336',rare:'Rara Dupla',price:0.15,base:true},
  {n:'037',name:'Dhelmise',        type:'Grama',   color:'#4CAF50',rare:'Incomum', price:0.15,base:true},
  {n:'038',name:'Marshadow',       type:'Trevas',  color:'#212121',rare:'Incomum', price:8.45,base:true},
  {n:'039',name:'Annihilape',      type:'Luta',    color:'#FF6B35',rare:'Incomum', price:0.15,base:true},
  {n:'040',name:'Mankey',          type:'Luta',    color:'#FF6B35',rare:'Comum',   price:0.15,base:true},
  {n:'041',name:'Primeape',        type:'Luta',    color:'#FF6B35',rare:'Incomum', price:0.15,base:true},
  {n:'042',name:'Cranidos',        type:'Luta',    color:'#FF6B35',rare:'Comum',   price:0.15,base:true},
  {n:'043',name:'Rampardos ex',    type:'Luta',    color:'#FF6B35',rare:'Rara Dupla',price:0.15,base:true},
  {n:'044',name:'Drilbur',         type:'Luta',    color:'#FF6B35',rare:'Comum',   price:0.15,base:true},
  {n:'045',name:'Koraidon',        type:'Luta',    color:'#FF6B35',rare:'Incomum', price:3.75,base:true},
  {n:'046',name:'Mega Darkrai ex', type:'Trevas',  color:'#212121',rare:'Rara Dupla',price:0.15,base:true},
  {n:'047',name:'Vullaby',         type:'Trevas',  color:'#212121',rare:'Comum',   price:0.25,base:true},
  {n:'048',name:'Mandibuzz',       type:'Trevas',  color:'#212121',rare:'Incomum', price:10.90,base:true},
  {n:'049',name:'Inkay',           type:'Trevas',  color:'#212121',rare:'Comum',   price:0.10,base:true},
  {n:'050',name:'Malamar',         type:'Trevas',  color:'#212121',rare:'Incomum', price:0.15,base:true},
  {n:'051',name:'Nickit',          type:'Trevas',  color:'#212121',rare:'Comum',   price:0.15,base:true},
  {n:'052',name:'Thievul',         type:'Trevas',  color:'#212121',rare:'Incomum', price:0.15,base:true},
  {n:'053',name:'Morpeko ex',      type:'Eletrico', color:'#FFC107',rare:'Rara Dupla',price:0.15,base:true},
  {n:'054',name:'Zarude',          type:'Trevas',  color:'#212121',rare:'Incomum', price:0.15,base:true},
  {n:'055',name:'Maschiff',        type:'Trevas',  color:'#212121',rare:'Comum',   price:3.75,base:true},
  {n:'056',name:'Mabosstiff',      type:'Trevas',  color:'#212121',rare:'Incomum', price:0.25,base:true},
  {n:'057',name:'Chi-Yu',          type:'Fogo',    color:'#F44336',rare:'Incomum', price:0.15,base:true},
  {n:'058',name:'Skarmory',        type:'Metal',   color:'#607D8B',rare:'Incomum', price:0.15,base:true},
  {n:'059',name:'Shieldon',        type:'Metal',   color:'#607D8B',rare:'Comum',   price:0.25,base:true},
  {n:'060',name:'Bastiodon',       type:'Metal',   color:'#607D8B',rare:'Incomum', price:0.10,base:true},
  {n:'061',name:'Bronzor',         type:'Metal',   color:'#607D8B',rare:'Comum',   price:0.17,base:true},
  {n:'062',name:'Bronzong',        type:'Metal',   color:'#607D8B',rare:'Incomum', price:0.25,base:true},
  {n:'063',name:'Mega Excadrill ex',type:'Luta',   color:'#FF6B35',rare:'Rara Dupla',price:0.15,base:true},
  {n:'064',name:'Pikipek',         type:'Incolor', color:'#9E9E9E',rare:'Comum',   price:0.15,base:true},
  {n:'065',name:'Trumbeak',        type:'Incolor', color:'#9E9E9E',rare:'Comum',   price:9.00,base:true},
  {n:'066',name:'Toucannon',       type:'Incolor', color:'#9E9E9E',rare:'Incomum', price:0.15,base:true},
  {n:'067',name:'Tipo Nulo',       type:'Incolor', color:'#9E9E9E',rare:'Comum',   price:0.15,base:true},
  {n:'068',name:'Silvally',        type:'Incolor', color:'#9E9E9E',rare:'Incomum', price:0.20,base:true},
  {n:'069',name:'Bombirdier',      type:'Trevas',  color:'#212121',rare:'Incomum', price:0.10,base:true},
  {n:'070',name:'Dark Bell',       type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'071',name:'Antique Skull Fossil',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'072',name:'Antique Armor Fossil',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  {n:'073',name:'Terrific Bomb',   type:'Treinador',color:'#607D8B',rare:'Incomum', price:0.15,base:true},
  {n:'074',name:'Retry Badge',     type:'Treinador',color:'#607D8B',rare:'Incomum', price:0.20,base:true},
  {n:'075',name:"Misty's Cheerfulness",type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'076',name:"Gladion's Showdown",type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'077',name:'Rust Syndicate Grunt',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.19,base:true},
  {n:'078',name:'Gwynn',           type:'Treinador',color:'#607D8B',rare:'Incomum', price:0.20,base:true},
  {n:'079',name:'Fossil Excavation Site',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'080',name:'Volt Lightning Energy',type:'Energia',color:'#FFC107',rare:'Comum', price:0.20,base:true},
  {n:'081',name:'Shadow Darkness Energy',type:'Energia',color:'#212121',rare:'Comum', price:0.19,base:true},
  // ── SECRETAS 082–118 (acima do numero de regulacao) ─────
  // CORRIGIDO 18/07/2026: estavam todas com base:true, o que faz getSlots()
  // (app.js) cair no caso padrão [N, RH] — como se cada carta secreta tivesse
  // versão Normal E Reverse Holo. Art Rare/Super Rare/Special Art Rare/Mega
  // Ultra Rare são impressão única (mesma lógica já aplicada em cards_me04.js,
  // cards_me03.js, cards_meg.js pras cartas UR/Ilustr./Gold, que usam
  // base:false). Sem essa correção o master set do ME05 pedia 2 versões de
  // 37 cartas que só existem numa versão — 74 slots fantasmas. Ver [[project_pokemon_tcg]].
  {n:'082',name:'Fomantis',        type:'Grama',   color:'#4CAF50',rare:'Art Rare', price:0.19,base:false},
  {n:'083',name:'Armarouge',       type:'Fogo',    color:'#F44336',rare:'Art Rare', price:0.50,base:false},
  {n:'084',name:'Goldeen',         type:'Agua',    color:'#2196F3',rare:'Art Rare', price:0.50,base:false},
  {n:'085',name:'Primarina',       type:'Agua',    color:'#2196F3',rare:'Art Rare', price:15.99,base:false},
  {n:'086',name:'Manectric',       type:'Eletrico', color:'#FFC107',rare:'Art Rare',price:21.99,base:false},
  {n:'087',name:'Slowbro',         type:'Psiquico', color:'#9C27B0',rare:'Art Rare',price:35.00,base:false},
  {n:'088',name:'Dhelmise',        type:'Grama',   color:'#4CAF50',rare:'Art Rare', price:24.50,base:false},
  {n:'089',name:'Thievul',         type:'Trevas',  color:'#212121',rare:'Art Rare', price:11.90,base:false},
  {n:'090',name:'Zarude',          type:'Trevas',  color:'#212121',rare:'Art Rare', price:42.90,base:false},
  {n:'091',name:'Bastiodon',       type:'Metal',   color:'#607D8B',rare:'Art Rare', price:36.00,base:false},
  {n:'092',name:'Toucannon',       type:'Incolor', color:'#9E9E9E',rare:'Art Rare', price:8.49,base:false},
  {n:'093',name:'Silvally',        type:'Incolor', color:'#9E9E9E',rare:'Art Rare', price:22.00,base:false},
  {n:'094',name:'Lurantis ex',     type:'Grama',   color:'#4CAF50',rare:'Super Rare',price:19.90,base:false},
  {n:'095',name:'Wailord ex',      type:'Agua',    color:'#2196F3',rare:'Super Rare',price:26.89,base:false},
  {n:'096',name:'Mega Zeraora ex', type:'Eletrico', color:'#FFC107',rare:'Super Rare',price:12.20,base:false},
  {n:'097',name:'Mega Chandelure ex',type:'Fogo',  color:'#F44336', rare:'Super Rare',price:19.00,base:false},
  {n:'098',name:'Rampardos ex',    type:'Luta',    color:'#FF6B35', rare:'Super Rare',price:32.00,base:false},
  {n:'099',name:'Mega Darkrai ex', type:'Trevas',  color:'#212121', rare:'Super Rare',price:44.90,base:false},
  {n:'100',name:'Morpeko ex',      type:'Eletrico', color:'#FFC107',rare:'Super Rare',price:18.00,base:false},
  {n:'101',name:'Mega Excadrill ex',type:'Luta',   color:'#FF6B35', rare:'Super Rare',price:59.90,base:false},
  {n:'102',name:'Defensor Ferreo', type:'Treinador',color:'#607D8B',rare:'Super Rare',price:9.90,base:false},
  {n:'103',name:'Substituicao de Energia',type:'Treinador',color:'#607D8B',rare:'Super Rare',price:30.80,base:false},
  {n:'104',name:'Martelo Esmagador',type:'Treinador',color:'#607D8B',rare:'Super Rare',price:37.04,base:false},
  {n:'105',name:'Dark Bell',       type:'Treinador',color:'#607D8B',rare:'Super Rare',price:39.90,base:false},
  {n:'106',name:'Splendid Bomb',   type:'Treinador',color:'#607D8B',rare:'Super Rare',price:20.00,base:false},
  {n:'107',name:'Bracelete Bravio',type:'Treinador',color:'#607D8B',rare:'Super Rare',price:36.00,base:false},
  {n:'108',name:"Misty's Spirit (Energia da Misty)",type:'Treinador',color:'#607D8B',rare:'Super Rare',price:26.90,base:false},
  {n:'109',name:"Gladion's Showdown",type:'Treinador',color:'#607D8B',rare:'Super Rare',price:73.90,base:false},
  {n:'110',name:'Rust Syndicate Grunt',type:'Treinador',color:'#607D8B',rare:'Super Rare',price:17.50,base:false},
  {n:'111',name:'Gwynn',           type:'Treinador',color:'#607D8B',rare:'Super Rare',price:119.85,base:false},
  {n:'112',name:'Mega Zeraora ex', type:'Eletrico', color:'#FFC107',rare:'Special Art Rare',price:16.50,base:false},
  {n:'113',name:'Mega Chandelure ex',type:'Fogo',  color:'#F44336', rare:'Special Art Rare',price:18.04,base:false},
  {n:'114',name:'Mega Darkrai ex', type:'Trevas',  color:'#212121', rare:'Special Art Rare',price:294.00,base:false},
  {n:'115',name:'Morpeko ex',      type:'Eletrico', color:'#FFC107',rare:'Special Art Rare',price:249.00,base:false},
  {n:'116',name:"Gladion's Showdown",type:'Treinador',color:'#607D8B',rare:'Special Art Rare',price:990.00,base:false},
  {n:'117',name:'Gwynn',           type:'Treinador',color:'#607D8B',rare:'Special Art Rare',price:274.00,base:false},
  {n:'118',name:'Mega Darkrai ex Gold',type:'Trevas',color:'#212121',rare:'Mega Ultra Rare',price:139.90,base:false},
];
