// CEL30CN — 30周年庆典 (30thC, chinês simplificado) — 176 cartas (RECONSTRUÍDO 01/10/2026)
// Lançamento China: 16 set 2026.
// HISTÓRICO: a primeira versão deste arquivo usava pokipair.com/30th-anniversary-30thc-card-list
// (site de loja fã), com apenas 161 das 176 cartas oficiais capturadas (paginação/lazy-load
// incompleta) e hotlink direto nas miniaturas da loja. Essas imagens pararam de carregar no
// site ao vivo mesmo depois do fix de referrerpolicy="no-referrer" que resolveu o mesmíssimo
// problema pro japonês (CDN da limitlesstcg) — indicando que a proteção do pokipair.com não é
// só por Referer header (provavelmente bloqueia hotlink mesmo sem referer nenhum).
// FONTE NOVA (01/10/2026): dataset oficial duanxr/PTCG-CHS-Datasets (github.com/duanxr/
// PTCG-CHS-Datasets, coleção id 515 "补充包 30周年庆典"), que cobre as 176 cartas oficiais
// (103 base/Pikachu especiais + 32 secretas 104-135 + 30 Coleção Clássica 136-165 + 3 RGB
// especiais B/G/R + 8 energias), com imagem via CDN jsdelivr (público, sem bloqueio de
// hotlink — diferente da loja pokipair).
// CRUZAMENTO: name/type/color/rare (PT) vêm do cards_cel30.js (EN/PT já corrigido) via dex da
// Pokédex (campo pokedexCode do dataset oficial) + nome do ilustrador (campo illustratorName,
// que bate EXATAMENTE com o artist já catalogado no EN pra Pikachu/ex/secretas — confirma a
// identidade da ILUSTRAÇÃO, não só da espécie). Coleção Clássica (136-165) cruzada por
// identificação manual carta-a-carta (nomes em chinês traduzidos por conhecimento de contexto,
// dex quando disponível) contra as 30 reimpressões já catalogadas no EN. 2 cartas (114 Nidorina,
// 121 Ditto) são art-rares EXCLUSIVAS do produto chinês sem equivalente no EN — usam name/type/
// color do EN base (por dex) mas rare:'Rara Ilustrada' e artist próprio do dataset CN.
// PREÇO: sem fonte de mercado chinês confirmada — price:0 em todas (igual antes).
// IMAGEM: jsdelivr.net/gh/duanxr/... (arte oficial do dataset, não miniatura de loja).
const CARDS_CEL30CN = [
  // ── SET BASE 001–103 (Comum/Rara/Rara Dupla + 30 Pikachu especiais) ──
  {n:"001",dex:102,artist:"Nelnal",name:"Exeggcute",type:"Grama",color:"#4CAF50",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/0.png"},
  {n:"002",dex:103,artist:"Oswaldo KATO",name:"Exeggutor de Alola",nameEn:"Alolan Exeggutor",type:"Grama",color:"#4CAF50",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/1.png"},
  {n:"003",dex:313,artist:"Yoriyuki Ikegami",name:"Volbeat",type:"Grama",color:"#4CAF50",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/2.png"},
  {n:"004",dex:314,artist:"Shibuzoh.",name:"Illumise",type:"Grama",color:"#4CAF50",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/3.png"},
  {n:"005",dex:666,artist:"Jerky",name:"Vivillon",type:"Grama",color:"#4CAF50",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/4.png"},
  {n:"006",dex:146,artist:"HYOGONOSUKE",name:"Moltres",type:"Fogo",color:"#F44336",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/5.png"},
  {n:"007",dex:250,artist:"Anesaki Dynamic",name:"Ho-Oh",type:"Fogo",color:"#F44336",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/6.png"},
  {n:"008",dex:643,artist:"Uta",name:"Reshiram",type:"Fogo",color:"#F44336",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/7.png"},
  {n:"009",dex:909,artist:"5ban Graphics",name:"Fuecoco ex",type:"Fogo",color:"#F44336",rare:"Rara Dupla",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/8.png"},
  {n:"010",dex:79,artist:"Uninori",name:"Slowpoke",type:"Agua",color:"#2196F3",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/9.png"},
  {n:"011",dex:131,artist:"Masa",name:"Lapras",type:"Agua",color:"#2196F3",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/10.png"},
  {n:"012",dex:144,artist:"HYOGONOSUKE",name:"Articuno",type:"Agua",color:"#2196F3",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/11.png"},
  {n:"013",dex:382,artist:"Tonji Matsuno",name:"Kyogre",type:"Agua",color:"#2196F3",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/12.png"},
  {n:"014",dex:484,artist:"kawayoo",name:"Palkia",type:"Agua",color:"#2196F3",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/13.png"},
  {n:"015",dex:658,artist:"5ban Graphics",name:"Greninja ex",type:"Agua",color:"#2196F3",rare:"Rara Dupla",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/14.png"},
  {n:"016",dex:746,artist:"Narano",name:"Wishiwashi",type:"Agua",color:"#2196F3",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/15.png"},
  {n:"017",dex:25,artist:"Ken Sugimori",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/16.png"},
  {n:"018",dex:25,artist:"danciao",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/17.png"},
  {n:"019",dex:25,artist:"satoma",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/18.png"},
  {n:"020",dex:25,artist:"Takeshi Nakamura",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/19.png"},
  {n:"021",dex:25,artist:"Asako Ito",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/20.png"},
  {n:"022",dex:25,artist:"sowsow",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/21.png"},
  {n:"023",dex:25,artist:"James Turner",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/22.png"},
  {n:"024",dex:25,artist:"DOM",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/23.png"},
  {n:"025",dex:25,artist:"Atsushi Furusawa",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/24.png"},
  {n:"026",dex:25,artist:"Tomokazu Komiya",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/25.png"},
  {n:"027",dex:25,artist:"Narumi Sato",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/26.png"},
  {n:"028",dex:25,artist:"USGMEN",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/27.png"},
  {n:"029",dex:25,artist:"Susumu Maeya",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/28.png"},
  {n:"030",dex:25,artist:"OKACHEKE",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/29.png"},
  {n:"031",dex:25,artist:"Yuu Nishida",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/30.png"},
  {n:"032",dex:25,artist:"Tetsu Kayama",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/31.png"},
  {n:"033",dex:25,artist:"Teeziro",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/32.png"},
  {n:"034",dex:25,artist:"Shinji Kanda",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/33.png"},
  {n:"035",dex:25,artist:"Rianti Hidayat",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/34.png"},
  {n:"036",dex:25,artist:"Akira Komayama",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/35.png"},
  {n:"037",dex:25,artist:"OOYAMA",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/36.png"},
  {n:"038",dex:25,artist:"akagi",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/37.png"},
  {n:"039",dex:25,artist:"Naoyo Kimura",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/38.png"},
  {n:"040",dex:25,artist:"svlt",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/39.png"},
  {n:"041",dex:25,artist:"Atsuko Nishida",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/40.png"},
  {n:"042",dex:25,artist:"KIYOTAKA OSHIYAMA",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/41.png"},
  {n:"043",dex:25,artist:"Nurikabe",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/42.png"},
  {n:"044",dex:25,artist:"Shimaris Yukichi",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/43.png"},
  {n:"045",dex:25,artist:"nagimiso",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/44.png"},
  {n:"046",dex:25,artist:"Kazuki Minami",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/45.png"},
  {n:"047",dex:25,artist:"5ban Graphics",name:"Pikachu ex",type:"Eletrico",color:"#FFC107",rare:"Rara Dupla",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/46.png"},
  {n:"048",dex:25,artist:"takuyoa",name:"Pikachu ex",type:"Eletrico",color:"#FFC107",rare:"Rara Dupla",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/47.png"},
  {n:"049",dex:145,artist:"HYOGONOSUKE",name:"Zapdos",type:"Eletrico",color:"#FFC107",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/48.png"},
  {n:"050",dex:644,artist:"akagi",name:"Zekrom",type:"Eletrico",color:"#FFC107",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/49.png"},
  {n:"051",dex:849,artist:"Yuriko Akase",name:"Toxtricity",type:"Eletrico",color:"#FFC107",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/50.png"},
  {n:"052",dex:877,artist:"Naoki Saito",name:"Morpeko",type:"Eletrico",color:"#FFC107",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/51.png"},
  {n:"053",dex:1008,artist:"Kazumasa Yasukuni",name:"Miraidon",type:"Eletrico",color:"#FFC107",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/52.png"},
  {n:"054",dex:150,artist:"nagimiso",name:"Mewtwo",type:"Psiquico",color:"#9C27B0",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/53.png"},
  {n:"055",dex:150,artist:"5ban Graphics",name:"Mewtwo ex",type:"Psiquico",color:"#9C27B0",rare:"Rara Dupla",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/54.png"},
  {n:"056",dex:151,artist:"danciao",name:"Mew",type:"Psiquico",color:"#9C27B0",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/55.png"},
  {n:"057",dex:151,artist:"aky CG Works",name:"Mew ex",type:"Psiquico",color:"#9C27B0",rare:"Rara Dupla",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/56.png"},
  {n:"058",dex:196,artist:"aspara",name:"Espeon",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/57.png"},
  {n:"059",dex:196,artist:"5ban Graphics",name:"Espeon ex",type:"Psiquico",color:"#9C27B0",rare:"Rara Dupla",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/58.png"},
  {n:"060",dex:201,artist:"mingo",name:"Unown",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/59.png"},
  {n:"061",dex:425,artist:"Shinya Komatsu",name:"Drifloon",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/60.png"},
  {n:"062",dex:609,artist:"Yoshioka",name:"Chandelure",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/61.png"},
  {n:"063",dex:716,artist:"kodama",name:"Xerneas",type:"Psiquico",color:"#9C27B0",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/62.png"},
  {n:"064",dex:789,artist:"Mina Nakai",name:"Cosmog",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/63.png"},
  {n:"065",dex:790,artist:"Masako Tomii",name:"Cosmoem",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/64.png"},
  {n:"066",dex:792,artist:"Bun Toujo",name:"Lunala",type:"Psiquico",color:"#9C27B0",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/65.png"},
  {n:"067",dex:999,artist:"Fujimoto Gold",name:"Gimmighoul",type:"Psiquico",color:"#9C27B0",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/66.png"},
  {n:"068",dex:383,artist:"Takumi Wada",name:"Groudon",type:"Luta",color:"#FF6B35",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/67.png"},
  {n:"069",dex:448,artist:"Hideki Ishikawa",name:"Lucario",type:"Luta",color:"#FF6B35",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/68.png"},
  {n:"070",dex:537,artist:"Kurata So",name:"Seismitoad",type:"Luta",color:"#FF6B35",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/69.png"},
  {n:"071",dex:745,artist:"matazo",name:"Lycanroc",type:"Luta",color:"#FF6B35",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/70.png"},
  {n:"072",dex:1007,artist:"Mitsuhiro Arita",name:"Koraidon",type:"Luta",color:"#FF6B35",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/71.png"},
  {n:"073",dex:29,artist:"Taira Akitsu",name:"Nidoran Fêmea",nameEn:"Nidoran♀",type:"Trevas",color:"#212121",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/72.png"},
  {n:"074",dex:30,artist:"Miki Tanaka",name:"Nidorina",type:"Trevas",color:"#212121",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/73.png"},
  {n:"075",dex:52,artist:"Natsumi Yoshida",name:"Meowth de Alola",nameEn:"Alolan Meowth",type:"Trevas",color:"#212121",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/74.png"},
  {n:"076",dex:700,artist:"5ban Graphics",name:"Sylveon ex",type:"Psiquico",color:"#9C27B0",rare:"Rara Dupla",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/75.png"},
  {n:"077",dex:197,artist:"Iori Suzuki",name:"Umbreon",type:"Trevas",color:"#212121",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/76.png"},
  {n:"078",dex:559,artist:"Souichirou Gunjima",name:"Scraggy",type:"Trevas",color:"#212121",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/77.png"},
  {n:"079",dex:717,artist:"hncl",name:"Yveltal",type:"Trevas",color:"#212121",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/78.png"},
  {n:"080",dex:52,artist:"Mékayu",name:"Meowth de Galar",nameEn:"Galarian Meowth",type:"Metal",color:"#607D8B",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/79.png"},
  {n:"081",dex:94,artist:"5ban Graphics",name:"Gengar ex",type:"Trevas",color:"#212121",rare:"Rara Dupla",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/80.png"},
  {n:"082",dex:483,artist:"toriyufu",name:"Dialga",type:"Metal",color:"#607D8B",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/81.png"},
  {n:"083",dex:598,artist:"Po-Suzuki",name:"Ferrothorn",type:"Metal",color:"#607D8B",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/82.png"},
  {n:"084",dex:791,artist:"Nurikabe",name:"Solgaleo",type:"Metal",color:"#607D8B",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/83.png"},
  {n:"085",dex:888,artist:"AKIRA EGAWA",name:"Zacian",type:"Metal",color:"#607D8B",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/84.png"},
  {n:"086",dex:889,artist:"Tsuyoshi Nagano",name:"Zamazenta",type:"Metal",color:"#607D8B",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/85.png"},
  {n:"087",dex:1000,artist:"Sanosuke Sakuma",name:"Gholdengo",type:"Metal",color:"#607D8B",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/86.png"},
  {n:"088",dex:385,artist:"5ban Graphics",name:"Jirachi ex",type:"Metal",color:"#607D8B",rare:"Rara Dupla",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/87.png"},
  {n:"089",dex:782,artist:"miki kudo",name:"Jangmo-o",type:"Dragao",color:"#673AB7",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/88.png"},
  {n:"090",dex:783,artist:"Jiro Sasumo",name:"Hakamo-o",type:"Dragao",color:"#673AB7",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/89.png"},
  {n:"091",dex:784,artist:"MARINA Chikazawa",name:"Kommo-o",type:"Dragao",color:"#673AB7",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/90.png"},
  {n:"092",dex:52,artist:"MINAMINAMI Take",name:"Meowth",type:"Incolor",color:"#9E9E9E",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/91.png"},
  {n:"093",dex:132,artist:"Toshinao Aoki",name:"Ditto",type:"Incolor",color:"#9E9E9E",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/92.png"},
  {n:"094",dex:133,artist:"Wintr Wandr",name:"Eevee",type:"Incolor",color:"#9E9E9E",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/93.png"},
  {n:"095",dex:143,artist:"Aya Kusube",name:"Snorlax",type:"Incolor",color:"#9E9E9E",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/94.png"},
  {n:"096",dex:174,artist:"Kanami Ogata",name:"Igglybuff",type:"Incolor",color:"#9E9E9E",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/95.png"},
  {n:"097",dex:249,artist:"Kazuki Minami",name:"Lugia",type:"Incolor",color:"#9E9E9E",rare:"Rara",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/96.png"},
  {n:"098",dex:570,artist:"Megumi Mizutani",name:"Zorua de Hisui",nameEn:"Hisuian Zorua",type:"Incolor",color:"#9E9E9E",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/97.png"},
  {n:"099",dex:571,artist:"Kamome Shirahama",name:"Zoroark de Hisui",nameEn:"Hisuian Zoroark",type:"Incolor",color:"#9E9E9E",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/98.png"},
  {n:"100",dex:925,artist:"Kariya",name:"Maushold",type:"Incolor",color:"#9E9E9E",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/99.png"},
  {n:"101",artist:"Yuka Morii",name:"Ultra Bola",nameEn:"Ultra Ball",type:"Treinador",color:"#607D8B",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/100.png"},
  {n:"102",artist:"Yuka Morii",name:"Poké Tablet",nameEn:"Poké Pad",type:"Treinador",color:"#607D8B",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/101.png"},
  {n:"103",artist:"Yuka Morii",name:"Substituição",nameEn:"Switch",type:"Treinador",color:"#607D8B",rare:"Comum",price:0,base:true,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/102.png"},
  // ── SECRETAS 104–135 (Art Rare/Special Art Rare/Full Art Ultra) ──
  {n:"104",dex:103,artist:"AYUMI ODASHIMA",name:"Exeggutor de Alola",nameEn:"Alolan Exeggutor",type:"Grama",color:"#4CAF50",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/103.png"},
  {n:"105",dex:146,artist:"mashu",name:"Moltres",type:"Fogo",color:"#F44336",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/104.png"},
  {n:"106",dex:131,artist:"Amelicart",name:"Lapras",type:"Agua",color:"#2196F3",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/105.png"},
  {n:"107",dex:144,artist:"mashu",name:"Articuno",type:"Agua",color:"#2196F3",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/106.png"},
  {n:"108",dex:145,artist:"mashu",name:"Zapdos",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/107.png"},
  {n:"109",dex:849,artist:"Kazumasa Yasukuni",name:"Toxtricity",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/108.png"},
  {n:"110",dex:877,artist:"Yoshimi Miyoshi",name:"Morpeko",type:"Eletrico",color:"#FFC107",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/109.png"},
  {n:"111",dex:425,artist:"Whisker",name:"Drifloon",type:"Psiquico",color:"#9C27B0",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/110.png"},
  {n:"112",dex:609,artist:"YASHIRO Nanaco",name:"Chandelure",type:"Psiquico",color:"#9C27B0",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/111.png"},
  {n:"113",dex:745,artist:"Raita Kazama",name:"Lycanroc",type:"Luta",color:"#FF6B35",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/112.png"},
  {n:"114",dex:30,artist:"Taiga Kasai",name:"Nidorina",type:"Trevas",color:"#212121",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/113.png"},
  {n:"115",dex:52,artist:"OKUBO",name:"Meowth de Alola",nameEn:"Alolan Meowth",type:"Trevas",color:"#212121",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/114.png"},
  {n:"116",dex:559,artist:"GOSSAN",name:"Scraggy",type:"Trevas",color:"#212121",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/115.png"},
  {n:"117",dex:52,artist:"OKUBO",name:"Meowth de Galar",nameEn:"Galarian Meowth",type:"Metal",color:"#607D8B",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/116.png"},
  {n:"118",dex:1000,artist:"toriyufu",name:"Gholdengo",type:"Metal",color:"#607D8B",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/117.png"},
  {n:"119",dex:784,artist:"Gemi",name:"Kommo-o",type:"Dragao",color:"#673AB7",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/118.png"},
  {n:"120",dex:52,artist:"OKUBO",name:"Meowth",type:"Incolor",color:"#9E9E9E",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/119.png"},
  {n:"121",dex:132,artist:"Ounishi",name:"Ditto",type:"Incolor",color:"#9E9E9E",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/120.png"},
  {n:"122",dex:570,artist:"0313",name:"Zorua de Hisui",nameEn:"Hisuian Zorua",type:"Incolor",color:"#9E9E9E",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/121.png"},
  {n:"123",dex:925,artist:"osare",name:"Maushold",type:"Incolor",color:"#9E9E9E",rare:"Rara Ilustrada",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/122.png"},
  {n:"124",dex:909,artist:"Atsushi Furusawa",name:"Fuecoco ex",type:"Fogo",color:"#F44336",rare:"Ilustr. Esp. Rara",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/123.png"},
  {n:"125",dex:658,artist:"GIDORA",name:"Greninja ex",type:"Agua",color:"#2196F3",rare:"Ilustr. Esp. Rara",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/124.png"},
  {n:"126",dex:25,artist:"kantaro",name:"Pikachu ex",type:"Eletrico",color:"#FFC107",rare:"Ilustr. Esp. Rara",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/125.png"},
  {n:"127",dex:25,artist:"kantaro",name:"Pikachu ex",type:"Eletrico",color:"#FFC107",rare:"Ilustr. Esp. Rara",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/126.png"},
  {n:"128",dex:150,artist:"Yano Keiji",name:"Mewtwo ex",type:"Psiquico",color:"#9C27B0",rare:"Ilustr. Esp. Rara",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/127.png"},
  {n:"129",dex:151,artist:"Kuroimori",name:"Mew ex",type:"Psiquico",color:"#9C27B0",rare:"Ilustr. Esp. Rara",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/128.png"},
  {n:"130",dex:700,artist:"You Iribi",name:"Sylveon ex",type:"Psiquico",color:"#9C27B0",rare:"Ilustr. Esp. Rara",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/129.png"},
  {n:"131",dex:94,artist:"CHORISO",name:"Gengar ex",type:"Trevas",color:"#212121",rare:"Ilustr. Esp. Rara",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/130.png"},
  {n:"132",dex:385,artist:"AKIRA EGAWA",name:"Jirachi ex",type:"Metal",color:"#607D8B",rare:"Ilustr. Esp. Rara",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/131.png"},
  {n:"133",dex:373,artist:"Ryota Murayama",name:"Salamence ex",type:"Dragao",color:"#673AB7",rare:"Ilustr. Esp. Rara",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/132.png"},
  {n:"134",dex:150,artist:"YOSHIROTTEN",name:"Mewtwo ex",type:"Psiquico",color:"#9C27B0",rare:"Rara Ultra",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/133.png"},
  {n:"135",dex:151,artist:"YOSHIROTTEN",name:"Mew ex",type:"Psiquico",color:"#9C27B0",rare:"Rara Ultra",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/134.png"},
  // ── COLEÇÃO CLÁSSICA 136–165 (numeração própria do set de origem, igual ao EN) ──
  {n:"136",dex:25,artist:"Mitsuhiro Arita",name:"Pikachu",type:"Eletrico",color:"#FFC107",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/135.png"},
  {n:"137",dex:6,artist:"Mitsuhiro Arita",name:"Charizard",type:"Fogo",color:"#F44336",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/136.png"},
  {n:"138",artist:"Ken Sugimori",name:"Misty",type:"Treinador",color:"#607D8B",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/137.png"},
  {n:"139",dex:39,artist:"Ken Sugimori",name:"Jigglypuff da Érica",nameEn:"Erika's Jigglypuff",type:"Incolor",color:"#9E9E9E",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/138.png"},
  {n:"140",dex:215,artist:"Ken Sugimori",name:"Sneasel",type:"Trevas",color:"#212121",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/139.png"},
  {n:"141",dex:251,artist:"Hironobu Yoshida",name:"Celebi Luminescente",nameEn:"Shining Celebi",type:"Grama",color:"#4CAF50",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/140.png"},
  {n:"142",dex:249,artist:"Naoyo Kimura",name:"Lugia",type:"Incolor",color:"#9E9E9E",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/141.png"},
  {n:"143",dex:301,artist:"Atsuko Nishida",name:"Delcatty",type:"Incolor",color:"#9E9E9E",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/142.png"},
  {n:"144",dex:248,artist:"Nakaoka",name:"Tyranitar Sombrio",nameEn:"Dark Tyranitar",type:"Trevas",color:"#212121",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/143.png"},
  {n:"145",dex:212,artist:"Mitsuhiro Arita",name:"Scizor ex",type:"Metal",color:"#607D8B",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/144.png"},
  {n:"146",dex:376,artist:"Masakazu Fukuda",name:"Metagross δ",nameEn:"Metagross",type:"Eletrico",color:"#FFC107",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/145.png"},
  {n:"147",dex:484,artist:"Ryo Ueda",name:"Palkia LV.X",type:"Agua",color:"#2196F3",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/146.png"},
  {n:"148",dex:480,artist:"Ken Sugimori",name:"Uxie",type:"Psiquico",color:"#9C27B0",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/147.png"},
  {n:"149",dex:169,artist:"Makoto Imai",name:"Crobat G",type:"Psiquico",color:"#9C27B0",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/148.png"},
  {n:"150",dex:94,artist:"Takashi Yamaguchi",name:"Gengar",type:"Psiquico",color:"#9C27B0",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/149.png"},
  {n:"151",dex:491,artist:"Shinji Higuchi & Noriko Takaya",name:"Darkrai & Cresselia LEGEND",type:"Trevas",color:"#212121",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/150.png"},
  {n:"152",dex:488,artist:"Shinji Higuchi & Noriko Takaya",name:"Darkrai & Cresselia LEGEND",type:"Trevas",color:"#212121",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/151.png"},
  {n:"153",artist:"Ken Sugimori",name:"N",type:"Treinador",color:"#607D8B",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/152.png"},
  {n:"154",dex:384,artist:"Eske Yoshinob",name:"Rayquaza-EX",type:"Dragao",color:"#673AB7",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/153.png"},
  {n:"155",dex:649,artist:"Eske Yoshinob",name:"Genesect-EX",type:"Grama",color:"#4CAF50",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/154.png"},
  {n:"156",dex:282,artist:"5ban Graphics",name:"M Gardevoir-EX",type:"Psiquico",color:"#9C27B0",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/155.png"},
  {n:"157",dex:658,artist:"5ban Graphics",name:"Greninja BREAK",type:"Agua",color:"#2196F3",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/156.png"},
  {n:"158",dex:791,artist:"PLANETA",name:"Solgaleo-GX",type:"Metal",color:"#607D8B",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/157.png"},
  {n:"159",dex:794,artist:"5ban Graphics",name:"Buzzwole-GX",type:"Luta",color:"#FF6B35",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/158.png"},
  {n:"160",dex:25,artist:"Mitsuhiro Arita",name:"Pikachu e Zekrom-GX",nameEn:"Pikachu & Zekrom-GX",type:"Eletrico",color:"#FFC107",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/159.png"},
  {n:"161",dex:888,artist:"5ban Graphics",name:"Zacian-V",nameEn:"Zacian V",type:"Metal",color:"#607D8B",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/160.png"},
  {n:"162",dex:243,artist:"Hideki Ishikawa",name:"Raikou",type:"Eletrico",color:"#FFC107",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/161.png"},
  {n:"163",dex:151,artist:"5ban Graphics",name:"Mew-VMAX",nameEn:"Mew VMAX",type:"Psiquico",color:"#9C27B0",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/162.png"},
  {n:"164",dex:493,artist:"5ban Graphics",name:"Arceus VSTAR",type:"Incolor",color:"#9E9E9E",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/163.png"},
  {n:"165",dex:129,artist:"Shinji Kanda",name:"Magikarp",type:"Agua",color:"#2196F3",rare:"Coleção Clássica",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/164.png"},
  // ── CARTAS RGB — Mew (fora da contagem oficial) ──
  {n:"B/RGB",dex:151,artist:"YOSHIROTTEN",name:"Mew",type:"Psiquico",color:"#9C27B0",rare:"Rara Secreta",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/165.png"},
  {n:"G/RGB",dex:151,artist:"YOSHIROTTEN",name:"Mew",type:"Psiquico",color:"#9C27B0",rare:"Rara Secreta",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/169.png"},
  {n:"R/RGB",dex:151,artist:"YOSHIROTTEN",name:"Mew",type:"Psiquico",color:"#9C27B0",rare:"Rara Secreta",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/174.png"},
  // ── ENERGIAS BÁSICAS ──
  {n:"DAR",artist:"YOSHIROTTEN",name:"Energia de Escuridão Básica",type:"Energia",color:"#212121",rare:"Comum",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/166.png"},
  {n:"FIG",artist:"YOSHIROTTEN",name:"Energia de Luta Básica",type:"Energia",color:"#FF6B35",rare:"Comum",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/167.png"},
  {n:"FIR",artist:"YOSHIROTTEN",name:"Energia de Fogo Básica",type:"Energia",color:"#F44336",rare:"Comum",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/168.png"},
  {n:"GRA",artist:"YOSHIROTTEN",name:"Energia de Planta Básica",type:"Energia",color:"#4CAF50",rare:"Comum",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/170.png"},
  {n:"LIG",artist:"YOSHIROTTEN",name:"Energia de Raio Básica",type:"Energia",color:"#FFC107",rare:"Comum",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/171.png"},
  {n:"MET",artist:"YOSHIROTTEN",name:"Energia de Metal Básica",type:"Energia",color:"#607D8B",rare:"Comum",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/172.png"},
  {n:"PSY",artist:"YOSHIROTTEN",name:"Energia Psíquica Básica",type:"Energia",color:"#9C27B0",rare:"Comum",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/173.png"},
  {n:"WAT",artist:"YOSHIROTTEN",name:"Energia de Água Básica",type:"Energia",color:"#2196F3",rare:"Comum",price:0,base:false,img:"https://cdn.jsdelivr.net/gh/duanxr/PTCG-CHS-Datasets@main/img/515/175.png"},
];
