// ME05 — Escuridão Absoluta (Abyss Eye / M5) — 118 cartas
// Lancamento Japao: 22 mai 2026 | Lancamento BR (Copag): 17 jul 2026 | Pre-lancamento: 4-12 jul 2026
// Tema: Mega Darkrai ex, Mega Zeraora ex, Mega Chandelure ex, Mega Excadrill ex
// Fonte: deckcerto.com (galeria completa + ranking top 20 mais caras, precos em USD, mercado internacional)
// NOTA: Precos de cartas fora do top 20 sao estimativas por raridade — ajustar quando o mercado BR abrir.
const CARDS_ME05 = [
  // ── SET BASE 001–081 ─────────────────────────────────────
  // CORRIGIDO 18/07/2026: as 8 cartas "ex" da base (004,015,026,036,043,046,
  // 053,063) estavam com rare:'Rara' (mesmo texto de Rare Holo comum), o que faz
  // getSlots() (app.js) cair no ramo [F,RH] — 2 versões colecionáveis. Na vida
  // real "ex" é raridade Double Rare (Rara Dupla), impressão única, sem reverse
  // holo (confirmado contra limitlesstcg.com/cards/PBL/4 — Lurantis ex é só
  // "Double Rare", 1 print). Trocado pra rare:'Rara Dupla', que já cai no ramo
  // [F] (1 versão) — mesmo padrão usado em cards_me02/03/04.js e cards_meg.js
  // pras cartas ex deles. Isso pedia 8 versões fantasma a mais no master set.
  // Ver [[project_pokemon_tcg]].
  {n:'001',dex:357,artist:"Akino Fukuji",name:'Tropius',         type:'Grama',   color:'#4CAF50',rare:'Comum',   price:0.15,base:true},
  {n:'002',dex:736,artist:"Mina Nakai",name:'Grubbin',         type:'Grama',   color:'#4CAF50',rare:'Comum',   price:0.15,base:true},
  {n:'003',dex:753,artist:"nisimono",name:'Fomantis',        type:'Grama',   color:'#4CAF50',rare:'Comum',   price:0.15,base:true},
  {n:'004',dex:754,artist:"5ban Graphics",name:'Lurantis ex',     type:'Grama',   color:'#4CAF50',rare:'Rara Dupla',price:3.00,base:true},
  {n:'005',dex:1012,artist:"Mousho",name:'Poltchageist',    type:'Trevas',  color:'#212121',rare:'Comum',   price:0.15,base:true},
  {n:'006',dex:1013,artist:"mingo",name:'Sinistcha',       type:'Trevas',  color:'#212121',rare:'Incomum', price:0.20,base:true},
  {n:'007',dex:485,artist:"Takeshi Nakamura",name:'Heatran',        type:'Fogo',    color:'#F44336',rare:'Incomum', price:0.15,base:true},
  {n:'008',dex:655,artist:"5ban Graphics",name:'Sizzlipede',      type:'Fogo',    color:'#F44336',rare:'Comum',   price:4.00,base:true},
  {n:'009',dex:850,artist:"Yuya Oka",name:'Centiskorch',     type:'Fogo',    color:'#F44336',rare:'Incomum', price:0.15,base:true},
  {n:'010',dex:851,artist:"Kouki Saitou",name:'Charcadet',       type:'Fogo',    color:'#F44336',rare:'Comum',   price:0.15,base:true},
  {n:'011',dex:935,artist:"Ryuta Fuse",name:'Armarouge',       type:'Fogo',    color:'#F44336',rare:'Incomum', price:0.15,base:true},
  {n:'012',dex:936,artist:"Jiro Sasumo",name:'Goldeen',         type:'Agua',    color:'#2196F3',rare:'Comum',   price:0.24,base:true},
  {n:'013',dex:118,artist:"Shibuzoh.",name:'Seaking',         type:'Agua',    color:'#2196F3',rare:'Incomum', price:0.15,base:true},
  {n:'014',dex:119,artist:"OKUBO",name:'Wailmer',         type:'Agua',    color:'#2196F3',rare:'Comum',   price:0.10,base:true},
  {n:'015',dex:320,artist:"Asako Ito",name:'Wailord ex',      type:'Agua',    color:'#2196F3',rare:'Rara Dupla',price:0.15,base:true},
  {n:'016',dex:321,artist:"5ban Graphics",name:'Relicanth',       type:'Agua',    color:'#2196F3',rare:'Incomum', price:2.90,base:true},
  {n:'017',dex:369,artist:"Naoyo Kimura",name:'Popplio',         type:'Agua',    color:'#2196F3',rare:'Comum',   price:0.20,base:true},
  {n:'018',dex:728,artist:"Oswaldo KATO",name:'Brionne',         type:'Agua',    color:'#2196F3',rare:'Comum',   price:0.10,base:true},
  {n:'019',dex:729,artist:"MINAMINAMI Take",name:'Primarina',       type:'Agua',    color:'#2196F3',rare:'Incomum', price:0.15,base:true},
  {n:'020',dex:730,artist:"Taira Akitsu",name:'Finizen',         type:'Agua',    color:'#2196F3',rare:'Comum',   price:0.24,base:true},
  {n:'021',dex:963,artist:"Yukiko Baba",name:'Palafin',         type:'Agua',    color:'#2196F3',rare:'Incomum', price:0.15,base:true},
  {n:'022',dex:964,artist:"satoma",name:'Electrike',       type:'Eletrico', color:'#FFC107',rare:'Comum',  price:0.10,base:true},
  {n:'023',dex:309,artist:"Dsuke",name:'Manectric',       type:'Eletrico', color:'#FFC107',rare:'Incomum',price:0.15,base:true},
  {n:'024',dex:310,artist:"Uninori",name:'Charjabug',       type:'Eletrico', color:'#FFC107',rare:'Comum',  price:0.20,base:true},
  {n:'025',dex:737,artist:"Kazuhisa Uragami",name:'Vikavolt',        type:'Eletrico', color:'#FFC107',rare:'Incomum',price:0.15,base:true},
  {n:'026',dex:738,artist:"KEIICHIRO ITO",name:'Mega Zeraora ex', type:'Eletrico', color:'#FFC107',rare:'Rara Dupla',price:0.15,base:true},
  {n:'027',dex:807,artist:"5ban Graphics",name:'Miraidon',        type:'Eletrico', color:'#FFC107',rare:'Incomum',price:4.00,base:true},
  {n:'028',dex:1008,artist:"mashu",name:'Slowpoke',        type:'Psiquico', color:'#9C27B0',rare:'Comum',  price:0.15,base:true},
  {n:'029',dex:79,artist:"Nelnal",name:'Slowbro',         type:'Psiquico', color:'#9C27B0',rare:'Incomum',price:0.17,base:true},
  {n:'030',dex:80,artist:"CHORISO",name:'Jynx',            type:'Psiquico', color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'031',dex:80,artist:"5ban Graphics",name:'Shuppet',         type:'Trevas',  color:'#212121',rare:'Comum',   price:4.58,base:true},
  {n:'032',dex:124,artist:"Yoshimoto Yoshimon",name:'Banette',         type:'Trevas',  color:'#212121',rare:'Incomum', price:0.15,base:true},
  {n:'033',dex:353,artist:"Bun Toujo",name:'Spiritomb',       type:'Trevas',  color:'#212121',rare:'Incomum', price:0.15,base:true},
  {n:'034',dex:354,artist:"Mugi Hamada",name:'Litwick',         type:'Fogo',    color:'#F44336',rare:'Comum',   price:0.15,base:true},
  {n:'035',dex:442,artist:"danciao",name:'Lampent',         type:'Fogo',    color:'#F44336',rare:'Incomum', price:0.30,base:true},
  {n:'036',dex:607,artist:"HYOGONOSUKE",name:'Mega Chandelure ex',type:'Fogo',  color:'#F44336',rare:'Rara Dupla',price:0.15,base:true},
  {n:'037',dex:608,artist:"sowsow",name:'Dhelmise',        type:'Grama',   color:'#4CAF50',rare:'Incomum', price:0.15,base:true},
  {n:'038',dex:609,artist:"5ban Graphics",name:'Marshadow',       type:'Trevas',  color:'#212121',rare:'Incomum', price:7.40,base:true},
  {n:'039',dex:781,artist:"Oku",name:'Annihilape',      type:'Luta',    color:'#FF6B35',rare:'Incomum', price:0.15,base:true},
  {n:'040',dex:802,artist:"Nakamura Ippan",name:'Mankey',          type:'Luta',    color:'#FF6B35',rare:'Comum',   price:0.15,base:true},
  {n:'041',dex:979,artist:"Haru Akasaka",name:'Primeape',        type:'Luta',    color:'#FF6B35',rare:'Incomum', price:0.14,base:true},
  {n:'042',dex:56,name:'Cranidos',        type:'Luta',    color:'#FF6B35',rare:'Comum',   price:0.15,base:true},
  {n:'043',dex:57,artist:"GOSSAN",name:'Rampardos ex',    type:'Luta',    color:'#FF6B35',rare:'Rara Dupla',price:0.15,base:true},
  {n:'044',dex:408,artist:"Hideki Ishikawa",name:'Drilbur',         type:'Luta',    color:'#FF6B35',rare:'Comum',   price:0.15,base:true},
  {n:'045',dex:409,artist:"hncl",name:'Koraidon',        type:'Luta',    color:'#FF6B35',rare:'Incomum', price:3.00,base:true},
  {n:'046',dex:529,name:'Mega Darkrai ex', type:'Trevas',  color:'#212121',rare:'Rara Dupla',price:0.15,base:true},
  {n:'047',dex:1007,name:'Vullaby',         type:'Trevas',  color:'#212121',rare:'Comum',   price:0.24,base:true},
  {n:'048',dex:491,artist:"5ban Graphics",name:'Mandibuzz',       type:'Trevas',  color:'#212121',rare:'Incomum', price:8.50,base:true},
  {n:'049',dex:629,artist:"Shiburingaru",name:'Inkay',           type:'Trevas',  color:'#212121',rare:'Comum',   price:0.10,base:true},
  {n:'050',dex:630,artist:"Nisota Niso",name:'Malamar',         type:'Trevas',  color:'#212121',rare:'Incomum', price:0.15,base:true},
  {n:'051',dex:686,artist:"Yuriko Akase",name:'Nickit',          type:'Trevas',  color:'#212121',rare:'Comum',   price:0.15,base:true},
  {n:'052',dex:687,artist:"Naoki Saito",name:'Thievul',         type:'Trevas',  color:'#212121',rare:'Incomum', price:0.15,base:true},
  {n:'053',dex:827,artist:"Krgc",name:'Morpeko ex',      type:'Eletrico', color:'#FFC107',rare:'Rara Dupla',price:0.15,base:true},
  {n:'054',dex:828,artist:"GOTO minori",name:'Zarude',          type:'Trevas',  color:'#212121',rare:'Incomum', price:0.15,base:true},
  {n:'055',dex:877,artist:"aky GG Works",name:'Maschiff',        type:'Trevas',  color:'#212121',rare:'Comum',   price:2.99,base:true},
  {n:'056',dex:893,artist:"matazo",name:'Mabosstiff',      type:'Trevas',  color:'#212121',rare:'Incomum', price:0.24,base:true},
  {n:'057',dex:942,artist:"ryoma uratsuka",name:'Chi-Yu',          type:'Fogo',    color:'#F44336',rare:'Incomum', price:0.15,base:true},
  {n:'058',dex:943,artist:"kawayoo",name:'Skarmory',        type:'Metal',   color:'#607D8B',rare:'Incomum', price:0.15,base:true},
  {n:'059',dex:1004,artist:"IKEDA Saki",name:'Shieldon',        type:'Metal',   color:'#607D8B',rare:'Comum',   price:0.24,base:true},
  {n:'060',dex:227,artist:"Anesaki Dynamic",name:'Bastiodon',       type:'Metal',   color:'#607D8B',rare:'Incomum', price:0.10,base:true},
  {n:'061',dex:410,artist:"Kurata So",name:'Bronzor',         type:'Metal',   color:'#607D8B',rare:'Comum',   price:0.20,base:true},
  {n:'062',dex:411,artist:"Kinu Nishimura",name:'Bronzong',        type:'Metal',   color:'#607D8B',rare:'Incomum', price:0.20,base:true},
  {n:'063',dex:436,artist:"Saboteri",name:'Mega Excadrill ex',type:'Luta',   color:'#FF6B35',rare:'Rara Dupla',price:0.15,base:true},
  {n:'064',dex:437,artist:"Uta",name:'Pikipek',         type:'Incolor', color:'#9E9E9E',rare:'Comum',   price:0.15,base:true},
  {n:'065',dex:530,artist:"Keisuke Azuma",name:'Trumbeak',        type:'Incolor', color:'#9E9E9E',rare:'Comum',   price:7.80,base:true},
  {n:'066',dex:731,artist:"Koji Nakata",name:'Toucannon',       type:'Incolor', color:'#9E9E9E',rare:'Incomum', price:0.15,base:true},
  {n:'067',dex:732,name:'Tipo Nulo',       type:'Incolor', color:'#9E9E9E',rare:'Comum',   price:0.15,base:true},
  {n:'068',dex:733,artist:"Masako Tomii",name:'Silvally',        type:'Incolor', color:'#9E9E9E',rare:'Incomum', price:0.20,base:true},
  {n:'069',dex:772,artist:"Ligton",name:'Bombirdier',      type:'Trevas',  color:'#212121',rare:'Incomum', price:0.10,base:true},
  {n:'070',dex:773,artist:"Takumi Wada",name:'Dark Bell',       type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'071',dex:962,artist:"Wintr Wandr",name:'Antique Skull Fossil',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'072',artist:"AYUMI ODASHIMA",name:'Antique Armor Fossil',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  {n:'073',artist:"AYUMI ODASHIMA",name:'Terrific Bomb',   type:'Treinador',color:'#607D8B',rare:'Incomum', price:0.15,base:true},
  {n:'074',artist:"Toyste Beach",name:'Retry Badge',     type:'Treinador',color:'#607D8B',rare:'Incomum', price:0.20,base:true},
  {n:'075',artist:"Toyste Beach",name:"Misty's Cheerfulness",type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'076',artist:"Oswaldo KATO",name:"Gladion's Showdown",type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'077',artist:"akagi",name:'Rust Syndicate Grunt',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.19,base:true},
  {n:'078',artist:"nagimiso",name:'Gwynn',           type:'Treinador',color:'#607D8B',rare:'Incomum', price:0.20,base:true},
  {n:'079',artist:"GIDORA",name:'Fossil Excavation Site',type:'Treinador',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'080',artist:"En Morikura",name:'Volt Lightning Energy',type:'Energia',color:'#FFC107',rare:'Comum', price:0.20,base:true},
  {n:'081',artist:"Teeziro",name:'Shadow Darkness Energy',type:'Energia',color:'#212121',rare:'Comum', price:0.19,base:true},
  // ── SECRETAS 082–118 (acima do numero de regulacao) ─────
  // CORRIGIDO 18/07/2026: estavam todas com base:true, o que faz getSlots()
  // (app.js) cair no caso padrão [N, RH] — como se cada carta secreta tivesse
  // versão Normal E Reverse Holo. Art Rare/Super Rare/Special Art Rare/Mega
  // Ultra Rare são impressão única (mesma lógica já aplicada em cards_me04.js,
  // cards_me03.js, cards_meg.js pras cartas UR/Ilustr./Gold, que usam
  // base:false). Sem essa correção o master set do ME05 pedia 2 versões de
  // 37 cartas que só existem numa versão — 74 slots fantasmas. Ver [[project_pokemon_tcg]].
  {n:'082',artist:"inose yukie",name:'Fomantis',        type:'Grama',   color:'#4CAF50',rare:'Art Rare', price:0.19,base:false},
  {n:'083',name:'Armarouge',       type:'Fogo',    color:'#F44336',rare:'Art Rare', price:0.35,base:false},
  {n:'084',name:'Goldeen',         type:'Agua',    color:'#2196F3',rare:'Art Rare', price:0.35,base:false},
  {n:'085',dex:753,artist:"Jiro Sasumo",name:'Primarina',       type:'Agua',    color:'#2196F3',rare:'Art Rare', price:14.88,base:false},
  {n:'086',dex:936,artist:"Iwamoto05",name:'Manectric',       type:'Eletrico', color:'#FFC107',rare:'Art Rare',price:19.50,base:false},
  {n:'087',dex:118,artist:"Gemi",name:'Slowbro',         type:'Psiquico', color:'#9C27B0',rare:'Art Rare',price:35.00,base:false},
  {n:'088',dex:730,artist:"satoma",name:'Dhelmise',        type:'Grama',   color:'#4CAF50',rare:'Art Rare', price:22.50,base:false},
  {n:'089',dex:310,artist:"HICO KIM",name:'Thievul',         type:'Trevas',  color:'#212121',rare:'Art Rare', price:11.99,base:false},
  {n:'090',dex:80,artist:"Mékayu",name:'Zarude',          type:'Trevas',  color:'#212121',rare:'Art Rare', price:45.00,base:false},
  {n:'091',dex:781,artist:"Nakamura Ippan",name:'Bastiodon',       type:'Metal',   color:'#607D8B',rare:'Art Rare', price:32.00,base:false},
  {n:'092',dex:828,artist:"Jerky",name:'Toucannon',       type:'Incolor', color:'#9E9E9E',rare:'Art Rare', price:7.99,base:false},
  {n:'093',dex:411,artist:"Yoriyuki Ikegami",name:'Silvally',        type:'Incolor', color:'#9E9E9E',rare:'Art Rare', price:19.50,base:false},
  {n:'094',dex:733,artist:"miki kudo",name:'Lurantis ex',     type:'Grama',   color:'#4CAF50',rare:'Super Rare',price:19.90,base:false},
  {n:'095',dex:773,artist:"DOM",name:'Wailord ex',      type:'Agua',    color:'#2196F3',rare:'Super Rare',price:22.50,base:false},
  {n:'096',dex:754,artist:"5ban Graphics",name:'Mega Zeraora ex', type:'Eletrico', color:'#FFC107',rare:'Super Rare',price:11.00,base:false},
  {n:'097',dex:321,artist:"5ban Graphics",name:'Mega Chandelure ex',type:'Fogo',  color:'#F44336', rare:'Super Rare',price:18.99,base:false},
  {n:'098',dex:807,artist:"5ban Graphics",name:'Rampardos ex',    type:'Luta',    color:'#FF6B35', rare:'Super Rare',price:31.98,base:false},
  {n:'099',dex:609,artist:"5ban Graphics",name:'Mega Darkrai ex', type:'Trevas',  color:'#212121', rare:'Super Rare',price:42.00,base:false},
  {n:'100',dex:409,artist:"5ban Graphics",name:'Morpeko ex',      type:'Eletrico', color:'#FFC107',rare:'Super Rare',price:18.00,base:false},
  {n:'101',dex:491,artist:"5ban Graphics",name:'Mega Excadrill ex',type:'Luta',   color:'#FF6B35', rare:'Super Rare',price:59.99,base:false},
  {n:'102',dex:877,artist:"5ban Graphics",name:'Defensor Ferreo', type:'Treinador',color:'#607D8B',rare:'Super Rare',price:9.90,base:false},
  {n:'103',dex:530,artist:"Keisuke Azuma",name:'Substituicao de Energia',type:'Treinador',color:'#607D8B',rare:'Super Rare',price:31.90,base:false},
  {n:'104',artist:"Toyste Beach",name:'Martelo Esmagador',type:'Treinador',color:'#607D8B',rare:'Super Rare',price:36.50,base:false},
  {n:'105',artist:"Ayaka Yoshida",name:'Dark Bell',       type:'Treinador',color:'#607D8B',rare:'Super Rare',price:37.50,base:false},
  {n:'106',name:'Splendid Bomb',   type:'Treinador',color:'#607D8B',rare:'Super Rare',price:18.50,base:false},
  {n:'107',name:'Bracelete Bravio',type:'Treinador',color:'#607D8B',rare:'Super Rare',price:33.97,base:false},
  {n:'108',artist:"akagi",name:"Misty's Spirit (Energia da Misty)",type:'Treinador',color:'#607D8B',rare:'Super Rare',price:26.40,base:false},
  {n:'109',artist:"nagimiso",name:"Gladion's Showdown",type:'Treinador',color:'#607D8B',rare:'Super Rare',price:64.99,base:false},
  {n:'110',artist:"Studio Bora Inc.",name:'Rust Syndicate Grunt',type:'Treinador',color:'#607D8B',rare:'Super Rare',price:15.49,base:false},
  {n:'111',artist:"En Morikura",name:'Gwynn',           type:'Treinador',color:'#607D8B',rare:'Super Rare',price:107.80,base:false},
  {n:'112',artist:"Teeziro",name:'Mega Zeraora ex', type:'Eletrico', color:'#FFC107',rare:'Special Art Rare',price:15.00,base:false},
  {n:'113',artist:"inose yukie",name:'Mega Chandelure ex',type:'Fogo',  color:'#F44336', rare:'Special Art Rare',price:17.00,base:false},
  {n:'114',dex:807,artist:"GIDORA",name:'Mega Darkrai ex', type:'Trevas',  color:'#212121', rare:'Special Art Rare',price:258.99,base:false},
  {n:'115',dex:609,name:'Morpeko ex',      type:'Eletrico', color:'#FFC107',rare:'Special Art Rare',price:205.99,base:false},
  {n:'116',dex:491,artist:"AKIRA EGAWA",name:"Gladion's Showdown",type:'Treinador',color:'#607D8B',rare:'Special Art Rare',price:900.00,base:false},
  {n:'117',dex:877,artist:"NG Empire",name:'Gwynn',           type:'Treinador',color:'#607D8B',rare:'Special Art Rare',price:260.00,base:false},
  {n:'118',artist:"DOM",name:'Mega Darkrai ex Gold',type:'Trevas',color:'#212121',rare:'Mega Ultra Rare',price:135.00,base:false},
];
