// SV9 — Journey Together (190 cartas)
// Lançamento EN: 2025/03/28
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV9 = [
  {n:'001',name:'Caterpie',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'002',name:'Metapod',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'003',name:'Butterfree',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.15,base:true},
  {n:'004',name:'Paras',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'005',name:'Parasect',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.14,base:true},
  {n:'006',name:'Petilil',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'007',name:'Lilligant',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.15,base:true},
  {n:'008',name:'Maractus',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.15,base:true},
  {n:'009',name:'Karrablast',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'010',name:'Foongus',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.12,base:true},
  {n:'011',name:'Amoonguss ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.00,base:true},
  {n:'012',name:'Shelmet',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.09,base:true},
  {n:'013',name:'Accelgor',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.09,base:true},
  {n:'014',name:'Durant',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.09,base:true},
  {n:'015',name:'Virizion',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.12,base:true},
  {n:'016',name:'Sprigatito',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'017',name:'Floragato',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.14,base:true},
  {n:'018',name:'Meowscarada',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.34,base:true},
  {n:'019',name:'Nymble',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'020',name:'Magmar',type:'Fogo',color:'#F44336',rare:'Comum',price:0.08,base:true},
  {n:'021',name:'Magmortar',type:'Fogo',color:'#F44336',rare:'Rara',price:0.18,base:true},
  {n:'022',name:'Torchic',type:'Fogo',color:'#F44336',rare:'Comum',price:0.14,base:true},
  {n:'023',name:'Combusken',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.15,base:true},
  {n:'024',name:'Blaziken ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:19.50,base:true},
  {n:'025',name:'Torkoal',type:'Fogo',color:'#F44336',rare:'Comum',price:0.14,base:true},
  {n:'026',name:'N\'s Darumaka',type:'Fogo',color:'#F44336',rare:'Comum',price:0.08,base:true},
  {n:'027',name:'N\'s Darmanitan',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.12,base:true},
  {n:'028',name:'Larvesta',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'029',name:'Volcarona',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.12,base:true},
  {n:'030',name:'Reshiram ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:4.00,base:true},
  {n:'031',name:'Volcanion ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:4.09,base:true},
  {n:'032',name:'Articuno',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.14,base:true},
  {n:'033',name:'Remoraid',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.09,base:true},
  {n:'034',name:'Octillery',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.10,base:true},
  {n:'035',name:'Lotad',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.14,base:true},
  {n:'036',name:'Lombre',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.14,base:true},
  {n:'037',name:'Ludicolo',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.23,base:true},
  {n:'038',name:'Wingull',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'039',name:'Pelipper',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.15,base:true},
  {n:'040',name:'Wailmer',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.14,base:true},
  {n:'041',name:'Wailord',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.24,base:true},
  {n:'042',name:'Regice',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.15,base:true},
  {n:'043',name:'Veluza ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:1.99,base:true},
  {n:'044',name:'Alolan Geodude',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'045',name:'Alolan Graveler',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'046',name:'Alolan Golem',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.10,base:true},
  {n:'047',name:'Iono\'s Voltorb',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.14,base:true},
  {n:'048',name:'Iono\'s Electrode',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.15,base:true},
  {n:'049',name:'N\'s Joltik',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.05,base:true},
  {n:'050',name:'Togedemaru',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'051',name:'Tapu Koko ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:3.00,base:true},
  {n:'052',name:'Iono\'s Tadbulb',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'053',name:'Iono\'s Bellibolt ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:3.90,base:true},
  {n:'054',name:'Iono\'s Wattrel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'055',name:'Iono\'s Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.18,base:true},
  {n:'056',name:'Lillie\'s Clefairy ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:17.90,base:true},
  {n:'057',name:'Alolan Marowak',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.13,base:true},
  {n:'058',name:'Mr. Mime',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'059',name:'Shuppet',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'060',name:'Banette',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'061',name:'Beldum',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'062',name:'Metang',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'063',name:'Metagross',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.24,base:true},
  {n:'064',name:'N\'s Sigilyph',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'065',name:'Oricorio',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'066',name:'Lillie\'s Cutiefly',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'067',name:'Lillie\'s Ribombee',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.21,base:true},
  {n:'068',name:'Lillie\'s Comfey',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'069',name:'Mimikyu ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:7.00,base:true},
  {n:'070',name:'Dhelmise',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'071',name:'Impidimp',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'072',name:'Morgrem',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'073',name:'Grimmsnarl',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.14,base:true},
  {n:'074',name:'Milcery',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'075',name:'Alcremie ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:4.75,base:true},
  {n:'076',name:'Cubone',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.12,base:true},
  {n:'077',name:'Swinub',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'078',name:'Piloswine',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.14,base:true},
  {n:'079',name:'Mamoswine ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:1.90,base:true},
  {n:'080',name:'Larvitar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'081',name:'Pupitar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'082',name:'Regirock',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.17,base:true},
  {n:'083',name:'Pancham',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'084',name:'Rockruff',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'085',name:'Lycanroc',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.25,base:true},
  {n:'086',name:'Hop\'s Silicobra',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.14,base:true},
  {n:'087',name:'Hop\'s Sandaconda',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.15,base:true},
  {n:'088',name:'Toedscool',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'089',name:'Toedscruel',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.15,base:true},
  {n:'090',name:'Klawf',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.09,base:true},
  {n:'091',name:'Koffing',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'092',name:'Weezing',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'093',name:'Paldean Wooper',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'094',name:'Paldean Clodsire ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:3.00,base:true},
  {n:'095',name:'Tyranitar',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.25,base:true},
  {n:'096',name:'N\'s Purrloin',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'097',name:'N\'s Zorua',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.13,base:true},
  {n:'098',name:'N\'s Zoroark ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:18.70,base:true},
  {n:'099',name:'Pangoro',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.09,base:true},
  {n:'100',name:'Lokix',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'101',name:'Bombirdier',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.09,base:true},
  {n:'102',name:'Escavalier',type:'Metal',color:'#78909C',rare:'Incomum',price:0.10,base:true},
  {n:'103',name:'N\'s Klink',type:'Metal',color:'#78909C',rare:'Comum',price:0.14,base:true},
  {n:'104',name:'N\'s Klang',type:'Metal',color:'#78909C',rare:'Comum',price:0.10,base:true},
  {n:'105',name:'N\'s Klinklang',type:'Metal',color:'#78909C',rare:'Incomum',price:0.10,base:true},
  {n:'106',name:'Galarian Stunfisk',type:'Metal',color:'#78909C',rare:'Comum',price:0.13,base:true},
  {n:'107',name:'Magearna',type:'Metal',color:'#78909C',rare:'Rara',price:0.17,base:true},
  {n:'108',name:'Hop\'s Corviknight',type:'Metal',color:'#78909C',rare:'Incomum',price:0.15,base:true},
  {n:'109',name:'Cufant',type:'Metal',color:'#78909C',rare:'Comum',price:0.12,base:true},
  {n:'110',name:'Copperajah',type:'Metal',color:'#78909C',rare:'Incomum',price:0.14,base:true},
  {n:'111',name:'Hop\'s Zacian ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:4.13,base:true},
  {n:'112',name:'Bagon',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.13,base:true},
  {n:'113',name:'Shelgon',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.14,base:true},
  {n:'114',name:'Salamence ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:4.00,base:true},
  {n:'115',name:'Druddigon',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.10,base:true},
  {n:'116',name:'N\'s Reshiram',type:'Dragão',color:'#3F51B5',rare:'Rara',price:0.28,base:true},
  {n:'117',name:'Hop\'s Snorlax',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.24,base:true},
  {n:'118',name:'Sentret',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.14,base:true},
  {n:'119',name:'Furret',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.13,base:true},
  {n:'120',name:'Dunsparce',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:17.99,base:true},
  {n:'121',name:'Dudunsparce ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:11.50,base:true},
  {n:'122',name:'Kecleon',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'123',name:'Tropius',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.13,base:true},
  {n:'124',name:'Audino',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'125',name:'Minccino',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'126',name:'Cinccino',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'127',name:'Noibat',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.05,base:true},
  {n:'128',name:'Noivern',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.17,base:true},
  {n:'129',name:'Komala',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'130',name:'Drampa',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'131',name:'Skwovet',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.09,base:true},
  {n:'132',name:'Greedent',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'133',name:'Hop\'s Rookidee',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.05,base:true},
  {n:'134',name:'Hop\'s Corvisquire',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'135',name:'Hop\'s Wooloo',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'136',name:'Hop\'s Dubwool',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.20,base:true},
  {n:'137',name:'Cramorant',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.13,base:true},
  {n:'138',name:'Hop\'s Cramorant',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'139',name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'140',name:'Oinkologne',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.08,base:true},
  {n:'141',name:'Squawkabilly',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'142',name:'Billy & O\'Nare',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.14,base:true},
  {n:'143',name:'Black Belt\'s Training',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'144',name:'Black Belt\'s Training',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.14,base:true},
  {n:'145',name:'Black Belt\'s Training',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'146',name:'Brock\'s Scouting',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.17,base:true},
  {n:'147',name:'Hop\'s Bag',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.12,base:true},
  {n:'148',name:'Hop\'s Choice Band',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'149',name:'Iris\'s Fighting Spirit',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'150',name:'Levincia',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'151',name:'Lillie\'s Pearl',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.08,base:true},
  {n:'152',name:'N\'s Castle',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.14,base:true},
  {n:'153',name:'N\'s PP Up',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'154',name:'Postwick',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'155',name:'Professor\'s Research',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'156',name:'Redeemable Ticket',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'157',name:'Ruffian',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'158',name:'Super Potion',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'159',name:'Spiky Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.18,base:true},
  {n:'160',name:'Maractus',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:11.90,base:false},
  {n:'161',name:'Articuno',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:79.99,base:false,important:true},
  {n:'162',name:'Wailord',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:37.91,base:false,important:true},
  {n:'163',name:'Iono\'s Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:32.90,base:false},
  {n:'164',name:'Lillie\'s Ribombee',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:44.90,base:false},
  {n:'165',name:'Swinub',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:9.90,base:false},
  {n:'166',name:'Lycanroc',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:16.50,base:false},
  {n:'167',name:'N\'s Reshiram',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada',price:32.00,base:false,important:true},
  {n:'168',name:'Furret',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:25.50,base:false},
  {n:'169',name:'Noibat',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:28.00,base:false},
  {n:'170',name:'Hop\'s Wooloo',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:23.99,base:false},
  {n:'171',name:'Volcanion ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:9.50,base:false},
  {n:'172',name:'Iono\'s Bellibolt ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:12.00,base:false},
  {n:'173',name:'Lillie\'s Clefairy ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:49.90,base:false,important:true},
  {n:'174',name:'Mamoswine ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:4.99,base:false},
  {n:'175',name:'N\'s Zoroark ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:24.99,base:false},
  {n:'176',name:'Hop\'s Zacian ex',type:'Metal',color:'#78909C',rare:'Ultra Rara',price:9.90,base:false},
  {n:'177',name:'Salamence ex',type:'Dragão',color:'#3F51B5',rare:'Ultra Rara',price:8.50,base:false},
  {n:'178',name:'Dudunsparce ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:22.00,base:false},
  {n:'179',name:'Brock\'s Scouting',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:20.00,base:false},
  {n:'180',name:'Iris\'s Fighting Spirit',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:16.00,base:false},
  {n:'181',name:'Ruffian',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:7.90,base:false},
  {n:'182',name:'Volcanion ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:69.90,base:false,important:true},
  {n:'183',name:'Iono\'s Bellibolt ex',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada Especial',price:150.00,base:false,important:true},
  {n:'184',name:'Lillie\'s Clefairy ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:297.50,base:false,important:true},
  {n:'185',name:'N\'s Zoroark ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:297.42,base:false,important:true},
  {n:'186',name:'Hop\'s Zacian ex',type:'Metal',color:'#78909C',rare:'Rara Ilustrada Especial',price:139.75,base:false,important:true},
  {n:'187',name:'Salamence ex',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada Especial',price:157.00,base:false,important:true},
  {n:'188',name:'Iono\'s Bellibolt ex',type:'Raio',color:'#FFEB3B',rare:'Hiper Rara',price:52.90,base:false,important:true},
  {n:'189',name:'N\'s Zoroark ex',type:'Sombrio',color:'#607D8B',rare:'Hiper Rara',price:100.00,base:false,important:true},
  {n:'190',name:'Spiky Energy',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:27.50,base:false}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV9 = CARDS_SV9;