// SV9 — Journey Together (190 cartas)
// Lançamento EN: 2025/03/28
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV9 = [
  {n:'001',dex:10,artist:"Shimaris Yukichi",name:'Caterpie',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'002',dex:11,artist:"OKUBO",name:'Metapod',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'003',dex:12,artist:"satoma",name:'Butterfree',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.15,base:true},
  {n:'004',dex:46,artist:"Ayako Ozaki",name:'Paras',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'005',dex:47,artist:"Tetsu Kayama",name:'Parasect',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.14,base:true},
  {n:'006',dex:548,artist:"Shibuzoh.",name:'Petilil',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'007',dex:549,artist:"Jiro Sasumo",name:'Lilligant',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'008',dex:556,artist:"Dsuke",name:'Maractus',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.10,base:true},
  {n:'009',dex:588,artist:"Yuka Morii",name:'Karrablast',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.13,base:true},
  {n:'010',dex:590,artist:"Saboteri",name:'Foongus',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.12,base:true},
  {n:'011',dex:591,artist:"PLANETA Mochizuki",name:'Amoonguss ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.20,base:true},
  {n:'012',dex:616,artist:"Toshinao Aoki",name:'Shelmet',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.09,base:true},
  {n:'013',dex:617,artist:"Kazumasa Yasukuni",name:'Accelgor',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.09,base:true},
  {n:'014',dex:632,artist:"KEIICHIRO ITO",name:'Durant',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.09,base:true},
  {n:'015',dex:640,artist:"Anesaki Dynamic",name:'Virizion',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.11,base:true},
  {n:'016',dex:906,artist:"Mina Nakai",name:'Sprigatito',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'017',dex:907,artist:"Felicia Chen",name:'Floragato',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'018',dex:908,artist:"kodama",name:'Meowscarada',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.25,base:true},
  {n:'019',dex:919,artist:"Ayako Ozaki",name:'Nymble',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.12,base:true},
  {n:'020',dex:126,artist:"Naoyo Kimura",name:'Magmar',type:'Fogo',color:'#F44336',rare:'Comum',price:0.08,base:true},
  {n:'021',dex:467,artist:"Tonji Matsuno",name:'Magmortar',type:'Fogo',color:'#F44336',rare:'Rara',price:0.18,base:true},
  {n:'022',dex:255,artist:"OKACHEKE",name:'Torchic',type:'Fogo',color:'#F44336',rare:'Comum',price:0.14,base:true},
  {n:'023',dex:256,artist:"Fujimoto Gold",name:'Combusken',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.15,base:true},
  {n:'024',dex:257,artist:"takuyoa",name:'Blaziken ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:22.25,base:true},
  {n:'025',dex:324,artist:"kodama",name:'Torkoal',type:'Fogo',color:'#F44336',rare:'Comum',price:0.14,base:true},
  {n:'026',dex:554,artist:"Gemi",name:'N\'s Darumaka',type:'Fogo',color:'#F44336',rare:'Comum',price:0.08,base:true},
  {n:'027',dex:555,artist:"nagimiso",name:'N\'s Darmanitan',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.15,base:true},
  {n:'028',dex:636,artist:"Kyoko Umemoto",name:'Larvesta',type:'Fogo',color:'#F44336',rare:'Comum',price:0.14,base:true},
  {n:'029',dex:637,artist:"Mitsuhiro Arita",name:'Volcarona',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.14,base:true},
  {n:'030',dex:643,artist:"PLANETA Mochizuki",name:'Reshiram ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:4.00,base:true},
  {n:'031',dex:721,artist:"5ban Graphics",name:'Volcanion ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:4.60,base:true},
  {n:'032',dex:144,artist:"Takumi Wada",name:'Articuno',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.14,base:true},
  {n:'033',dex:223,artist:"Minahamu",name:'Remoraid',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.09,base:true},
  {n:'034',dex:224,artist:"Toshinao Aoki",name:'Octillery',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.10,base:true},
  {n:'035',dex:270,artist:"Ayako Ozaki",name:'Lotad',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.14,base:true},
  {n:'036',dex:271,artist:"Mousho",name:'Lombre',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.14,base:true},
  {n:'037',dex:272,artist:"Jerky",name:'Ludicolo',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.23,base:true},
  {n:'038',dex:278,artist:"Mékayu",name:'Wingull',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'039',dex:279,artist:"Nelnal",name:'Pelipper',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.15,base:true},
  {n:'040',dex:320,artist:"Shinya Mizuno",name:'Wailmer',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.14,base:true},
  {n:'041',dex:321,artist:"Takeshi Nakamura",name:'Wailord',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.24,base:true},
  {n:'042',dex:378,artist:"Takumi Wada",name:'Regice',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.17,base:true},
  {n:'043',dex:976,artist:"5ban Graphics",name:'Veluza ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:1.58,base:true},
  {n:'044',dex:74,artist:"svlt",name:'Alolan Geodude',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'045',dex:75,artist:"HYOGONOSUKE",name:'Alolan Graveler',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.19,base:true},
  {n:'046',dex:76,artist:"Takeshi Nakamura",name:'Alolan Golem',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.10,base:true},
  {n:'047',dex:100,artist:"Kazumasa Yasukuni",name:'Iono\'s Voltorb',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.14,base:true},
  {n:'048',dex:101,artist:"GOTO minori",name:'Iono\'s Electrode',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.17,base:true},
  {n:'049',dex:595,artist:"Iori Suzuki",name:'N\'s Joltik',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.05,base:true},
  {n:'050',dex:777,artist:"Susumu Maeya",name:'Togedemaru',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'051',dex:785,artist:"PLANETA Igarashi",name:'Tapu Koko ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:2.90,base:true},
  {n:'052',dex:938,artist:"kurumitsu",name:'Iono\'s Tadbulb',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'053',dex:939,artist:"5ban Graphics",name:'Iono\'s Bellibolt ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:4.00,base:true},
  {n:'054',dex:940,artist:"Akira Komayama",name:'Iono\'s Wattrel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'055',dex:941,artist:"chibi",name:'Iono\'s Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.18,base:true},
  {n:'056',dex:35,artist:"5ban Graphics",name:'Lillie\'s Clefairy ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:25.00,base:true},
  {n:'057',dex:105,artist:"Uta",name:'Alolan Marowak',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.13,base:true},
  {n:'058',dex:122,artist:"GOTO minori",name:'Mr. Mime',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'059',dex:353,artist:"miki kudo",name:'Shuppet',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'060',dex:354,artist:"Anesaki Dynamic",name:'Banette',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.17,base:true},
  {n:'061',dex:374,artist:"Izucch",name:'Beldum',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'062',dex:375,artist:"Oswaldo KATO",name:'Metang',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'063',dex:376,artist:"Mitsuhiro Arita",name:'Metagross',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.24,base:true},
  {n:'064',dex:561,artist:"Shiburingaru",name:'N\'s Sigilyph',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'065',dex:741,artist:"aspara",name:'Oricorio',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'066',dex:742,artist:"Saya Tsuruta",name:'Lillie\'s Cutiefly',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.17,base:true},
  {n:'067',dex:743,artist:"mashu",name:'Lillie\'s Ribombee',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.17,base:true},
  {n:'068',dex:764,artist:"Narumi Sato",name:'Lillie\'s Comfey',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.19,base:true},
  {n:'069',dex:778,artist:"PLANETA Igarashi",name:'Mimikyu ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:6.50,base:true},
  {n:'070',dex:781,artist:"Sanosuke Sakuma",name:'Dhelmise',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'071',dex:859,artist:"Haru Akasaka",name:'Impidimp',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'072',dex:860,artist:"Lee HyunJung",name:'Morgrem',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'073',dex:861,artist:"Nisota Niso",name:'Grimmsnarl',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'074',dex:868,artist:"Shibuzoh.",name:'Milcery',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'075',dex:869,artist:"PLANETA Mochizuki",name:'Alcremie ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:5.90,base:true},
  {n:'076',dex:104,artist:"Mugi Hamada",name:'Cubone',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'077',dex:220,artist:"REND",name:'Swinub',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'078',dex:221,artist:"Aliya Chen",name:'Piloswine',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.14,base:true},
  {n:'079',dex:473,artist:"Nisota Niso",name:'Mamoswine ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:1.90,base:true},
  {n:'080',dex:246,artist:"Dsuke",name:'Larvitar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.13,base:true},
  {n:'081',dex:247,artist:"Scav",name:'Pupitar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'082',dex:377,artist:"Uta",name:'Regirock',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.17,base:true},
  {n:'083',dex:674,artist:"Yuriko Akase",name:'Pancham',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'084',dex:744,artist:"Yoshimi Miyoshi",name:'Rockruff',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'085',dex:745,artist:"Shiburingaru",name:'Lycanroc',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.25,base:true},
  {n:'086',dex:843,artist:"aspara",name:'Hop\'s Silicobra',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.14,base:true},
  {n:'087',dex:844,artist:"Sanosuke Sakuma",name:'Hop\'s Sandaconda',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.16,base:true},
  {n:'088',dex:948,artist:"osare",name:'Toedscool',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'089',dex:949,artist:"Masako Tomii",name:'Toedscruel',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.15,base:true},
  {n:'090',dex:950,artist:"Shinya Komatsu",name:'Klawf',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.09,base:true},
  {n:'091',dex:109,artist:"Rond",name:'Koffing',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'092',dex:110,artist:"KEIICHIRO ITO",name:'Weezing',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.16,base:true},
  {n:'093',dex:194,artist:"Lee HyunJung",name:'Paldean Wooper',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'094',dex:980,artist:"PLANETA Tsuji",name:'Paldean Clodsire ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:3.49,base:true},
  {n:'095',dex:248,artist:"AKIRA EGAWA",name:'Tyranitar',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.25,base:true},
  {n:'096',dex:509,artist:"Keisin",name:'N\'s Purrloin',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'097',dex:570,artist:"Jiro Sasumo",name:'N\'s Zorua',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.13,base:true},
  {n:'098',dex:571,artist:"takuyoa",name:'N\'s Zoroark ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:12.99,base:true},
  {n:'099',dex:675,artist:"nagimiso",name:'Pangoro',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.09,base:true},
  {n:'100',dex:920,artist:"AKIRA EGAWA",name:'Lokix',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'101',dex:962,artist:"Gemi",name:'Bombirdier',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.09,base:true},
  {n:'102',dex:589,artist:"Takumi Wada",name:'Escavalier',type:'Metal',color:'#78909C',rare:'Incomum',price:0.12,base:true},
  {n:'103',dex:599,artist:"Saboteri",name:'N\'s Klink',type:'Metal',color:'#78909C',rare:'Comum',price:0.14,base:true},
  {n:'104',dex:600,artist:"KEIICHIRO ITO",name:'N\'s Klang',type:'Metal',color:'#78909C',rare:'Comum',price:0.10,base:true},
  {n:'105',dex:601,artist:"matazo",name:'N\'s Klinklang',type:'Metal',color:'#78909C',rare:'Incomum',price:0.10,base:true},
  {n:'106',dex:618,artist:"Aya Kusube",name:'Galarian Stunfisk',type:'Metal',color:'#78909C',rare:'Comum',price:0.13,base:true},
  {n:'107',dex:801,artist:"rika",name:'Magearna',type:'Metal',color:'#78909C',rare:'Rara',price:0.17,base:true},
  {n:'108',dex:823,artist:"GIDORA",name:'Hop\'s Corviknight',type:'Metal',color:'#78909C',rare:'Incomum',price:0.15,base:true},
  {n:'109',dex:878,artist:"kodama",name:'Cufant',type:'Metal',color:'#78909C',rare:'Comum',price:0.12,base:true},
  {n:'110',dex:879,artist:"Ryuta Fuse",name:'Copperajah',type:'Metal',color:'#78909C',rare:'Incomum',price:0.14,base:true},
  {n:'111',dex:888,artist:"aky CG Works",name:'Hop\'s Zacian ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:4.50,base:true},
  {n:'112',dex:371,artist:"Miki Tanaka",name:'Bagon',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.12,base:true},
  {n:'113',dex:372,artist:"Julie Hang",name:'Shelgon',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.14,base:true},
  {n:'114',dex:373,artist:"toriyufu",name:'Salamence ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:2.80,base:true},
  {n:'115',dex:621,artist:"kawayoo",name:'Druddigon',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.10,base:true},
  {n:'116',dex:643,artist:"rika",name:'N\'s Reshiram',type:'Dragão',color:'#3F51B5',rare:'Rara',price:0.28,base:true},
  {n:'117',dex:143,artist:"GOSSAN",name:'Hop\'s Snorlax',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.24,base:true},
  {n:'118',dex:161,artist:"Taiga Kayama",name:'Sentret',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.14,base:true},
  {n:'119',dex:162,artist:"Tomomi Ozaki",name:'Furret',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.13,base:true},
  {n:'120',dex:206,artist:"Asako Ito",name:'Dunsparce',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:19.90,base:true},
  {n:'121',dex:982,artist:"5ban Graphics",name:'Dudunsparce ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:8.00,base:true},
  {n:'122',dex:352,artist:"0313",name:'Kecleon',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'123',dex:357,artist:"Atsuya Uki",name:'Tropius',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.13,base:true},
  {n:'124',dex:531,artist:"Minahamu",name:'Audino',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'125',dex:572,artist:"Oswaldo KATO",name:'Minccino',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'126',dex:573,artist:"En Morikura",name:'Cinccino',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.16,base:true},
  {n:'127',dex:714,artist:"Tomokazu Komiya",name:'Noibat',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.05,base:true},
  {n:'128',dex:715,artist:"Anesaki Dynamic",name:'Noivern',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.17,base:true},
  {n:'129',dex:775,artist:"Natsumi Yoshida",name:'Komala',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.18,base:true},
  {n:'130',dex:780,artist:"Tetsu Kayama",name:'Drampa',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'131',dex:819,artist:"sowsow",name:'Skwovet',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.09,base:true},
  {n:'132',dex:820,artist:"Jerky",name:'Greedent',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'133',dex:821,artist:"Shinya Mizuno",name:'Hop\'s Rookidee',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.05,base:true},
  {n:'134',dex:822,artist:"Souichirou Gunjima",name:'Hop\'s Corvisquire',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.13,base:true},
  {n:'135',dex:831,artist:"Tomomi Ozaki",name:'Hop\'s Wooloo',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'136',dex:832,artist:"Ryota Murayama",name:'Hop\'s Dubwool',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.20,base:true},
  {n:'137',dex:845,artist:"Tomomi Ozaki",name:'Cramorant',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.13,base:true},
  {n:'138',dex:845,artist:"Saboteri",name:'Hop\'s Cramorant',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'139',dex:915,artist:"OKACHEKE",name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.13,base:true},
  {n:'140',dex:916,artist:"Mina Nakai",name:'Oinkologne',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.08,base:true},
  {n:'141',dex:931,artist:"sowsow",name:'Squawkabilly',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'142',artist:"Sanosuke Sakuma",name:'Billy & O\'Nare',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.14,base:true},
  {n:'143',artist:"GOSSAN",name:'Black Belt\'s Training',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'144',artist:"GOSSAN",name:'Black Belt\'s Training',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.14,base:true},
  {n:'145',artist:"GOSSAN",name:'Black Belt\'s Training',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.14,base:true},
  {n:'146',artist:"Teeziro",name:'Brock\'s Scouting',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.17,base:true},
  {n:'147',artist:"AYUMI ODASHIMA",name:'Hop\'s Bag',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'148',artist:"Toyste Beach",name:'Hop\'s Choice Band',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'149',artist:"yuu",name:'Iris\'s Fighting Spirit',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'150',artist:"MARINA Chikazawa",name:'Levincia',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.13,base:true},
  {n:'151',artist:"AYUMI ODASHIMA",name:'Lillie\'s Pearl',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.11,base:true},
  {n:'152',artist:"AYUMI ODASHIMA",name:'N\'s Castle',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.14,base:true},
  {n:'153',artist:"Toyste Beach",name:'N\'s PP Up',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'154',artist:"AYUMI ODASHIMA",name:'Postwick',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.14,base:true},
  {n:'155',artist:"Taira Akitsu",name:'Professor\'s Research',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.14,base:true},
  {n:'156',artist:"Studio Bora Inc.",name:'Redeemable Ticket',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'157',artist:"Hideki Ishikawa",name:'Ruffian',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'158',artist:"Studio Bora Inc.",name:'Super Potion',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'159',name:'Spiky Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.18,base:true},
  {n:'160',dex:556,artist:"Ounishi",name:'Maractus',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:11.90,base:false},
  {n:'161',dex:144,artist:"Kuroimori",name:'Articuno',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:89.90,base:false,important:true},
  {n:'162',dex:321,artist:"Katsunori Sato",name:'Wailord',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:32.90,base:false,important:true},
  {n:'163',dex:941,artist:"Terada Tera",name:'Iono\'s Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:30.00,base:false},
  {n:'164',dex:743,artist:"saino misaki",name:'Lillie\'s Ribombee',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:40.00,base:false},
  {n:'165',dex:220,artist:"Nakamura Ippan",name:'Swinub',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:9.90,base:false},
  {n:'166',dex:745,artist:"GIDORA",name:'Lycanroc',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:18.00,base:false},
  {n:'167',dex:643,artist:"Bun Toujo",name:'N\'s Reshiram',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada',price:50.00,base:false,important:true},
  {n:'168',dex:162,artist:"REND",name:'Furret',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:32.55,base:false},
  {n:'169',dex:714,artist:"sowsow",name:'Noibat',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:29.75,base:false},
  {n:'170',dex:831,artist:"MINAMINAMI Take",name:'Hop\'s Wooloo',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:24.90,base:false},
  {n:'171',dex:721,artist:"5ban Graphics",name:'Volcanion ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:7.70,base:false},
  {n:'172',dex:939,artist:"5ban Graphics",name:'Iono\'s Bellibolt ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:12.00,base:false},
  {n:'173',dex:35,artist:"5ban Graphics",name:'Lillie\'s Clefairy ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:57.00,base:false,important:true},
  {n:'174',dex:473,artist:"N-DESIGN Inc.",name:'Mamoswine ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:4.99,base:false},
  {n:'175',dex:571,artist:"takuyoa",name:'N\'s Zoroark ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:37.00,base:false},
  {n:'176',dex:888,artist:"aky CG Works",name:'Hop\'s Zacian ex',type:'Metal',color:'#78909C',rare:'Ultra Rara',price:9.90,base:false},
  {n:'177',dex:373,artist:"5ban Graphics",name:'Salamence ex',type:'Dragão',color:'#3F51B5',rare:'Ultra Rara',price:8.50,base:false},
  {n:'178',dex:982,artist:"5ban Graphics",name:'Dudunsparce ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:14.90,base:false},
  {n:'179',artist:"Teeziro",name:'Brock\'s Scouting',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:23.89,base:false},
  {n:'180',artist:"yuu",name:'Iris\'s Fighting Spirit',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:13.00,base:false},
  {n:'181',artist:"Hideki Ishikawa",name:'Ruffian',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8.99,base:false},
  {n:'182',dex:721,artist:"akagi",name:'Volcanion ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:69.90,base:false,important:true},
  {n:'183',dex:939,artist:"Yuu Nishida",name:'Iono\'s Bellibolt ex',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada Especial',price:169.50,base:false,important:true},
  {n:'184',dex:35,artist:"Susumu Maeya",name:'Lillie\'s Clefairy ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:300.00,base:false,important:true},
  {n:'185',dex:571,artist:"Megumi Mizutani",name:'N\'s Zoroark ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:297.42,base:false,important:true},
  {n:'186',dex:888,artist:"DOM",name:'Hop\'s Zacian ex',type:'Metal',color:'#78909C',rare:'Rara Ilustrada Especial',price:147.90,base:false,important:true},
  {n:'187',dex:373,artist:"Tsuyoshi Nagano",name:'Salamence ex',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada Especial',price:149.90,base:false,important:true},
  {n:'188',dex:939,artist:"5ban Graphics",name:'Iono\'s Bellibolt ex',type:'Raio',color:'#FFEB3B',rare:'Hiper Rara',price:52.90,base:false,important:true},
  {n:'189',dex:571,artist:"takuyoa",name:'N\'s Zoroark ex',type:'Sombrio',color:'#607D8B',rare:'Hiper Rara',price:100.00,base:false,important:true},
  {n:'190',name:'Spiky Energy',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:9.90,base:false}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV9 = CARDS_SV9;