// PGO(PGO) — Pokémon GO — 88 cartas (78 base + 10 secretas)
// Lançamento EN: 01 jul 2022 | Série: Sword & Shield (Espada & Escudo)
// Tema: Pokémon GO x TCG — Radiant Pokémon, Team Leaders (Blanche/Candela/Spark),
//       itens do app (PokéStop, Lure Module, Egg Incubator) como cartas de Treinador.
// Fonte: api.pokemontcg.io (set.id:pgo — 88/88 cartas confirmadas ao vivo em 13/08/2026,
// preço TCGPlayer market USD*5.80 convertido; ver [[project_pokemon_tcg]]).
// Preço em inglês (price_en) via TCGCSV: scripts/tcgcsv_sets.json groupId 3064.
// Preço BR (Liga) via scripts/liga_sets.json.
// NOTA: printedTotal=78 (cartas 001-078) / total=88 (079-088 = secretas: Ultra Rara,
// Rara Rainbow, Rara Secreta). base:true = numeração 001-078, base:false = 079-088.
const CARDS_PGO = [
  {n:'001',dex:1,name:'Bulbasaur',artist:'sowsow',type:'Planta',color:'#4CAF50',rare:'Comum',price:1.00,base:true},
  {n:'002',dex:2,name:'Ivysaur',artist:'zig',type:'Planta',color:'#4CAF50',rare:'Incomum',price:1.90,base:true},
  {n:'003',dex:3,name:'Venusaur',artist:'KEIICHIRO ITO',type:'Planta',color:'#4CAF50',rare:'Rara Holo',price:16.00,base:true},
  {n:'004',dex:3,name:'Radiant Venusaur',artist:'Misa Tsutsui',type:'Planta',color:'#4CAF50',rare:'Rara Radiante',price:39.90,base:true},
  {n:'005',dex:103,name:'Alolan Exeggutor V',artist:'MUGENUP',type:'Planta',color:'#4CAF50',rare:'Rara Holo V',price:5.95,base:true},
  {n:'006',dex:167,name:'Spinarak',artist:'Yuka Morii',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.25,base:true},
  {n:'007',dex:168,name:'Ariados',artist:'Misa Tsutsui',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.22,base:true},
  {n:'008',dex:4,name:'Charmander',artist:'saino misaki',type:'Fogo',color:'#F44336',rare:'Comum',price:0.46,base:true},
  {n:'009',dex:5,name:'Charmeleon',artist:'Shiburingaru',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.55,base:true},
  {n:'010',dex:6,name:'Charizard',artist:'N-DESIGN Inc.',type:'Fogo',color:'#F44336',rare:'Rara Holo',price:19.00,base:true},
  {n:'011',dex:6,name:'Radiant Charizard',artist:'Shigenori Negishi',type:'Fogo',color:'#F44336',rare:'Rara Radiante',price:115.00,base:true},
  {n:'012',dex:146,name:'Moltres',artist:'Pani Kobayashi',type:'Fogo',color:'#F44336',rare:'Rara Holo',price:1.50,base:true},
  {n:'013',dex:322,name:'Numel',artist:'Shibuzoh.',type:'Fogo',color:'#F44336',rare:'Comum',price:0.15,base:true},
  {n:'014',dex:323,name:'Camerupt',artist:'yuu',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.25,base:true},
  {n:'015',dex:7,name:'Squirtle',artist:'sowsow',type:'Aquático',color:'#2196F3',rare:'Comum',price:3.90,base:true},
  {n:'016',dex:8,name:'Wartortle',artist:'kurumitsu',type:'Aquático',color:'#2196F3',rare:'Incomum',price:5.00,base:true},
  {n:'017',dex:9,name:'Blastoise',artist:'NC Empire',type:'Aquático',color:'#2196F3',rare:'Rara Holo',price:19.00,base:true},
  {n:'018',dex:9,name:'Radiant Blastoise',artist:'Masakazu Fukuda',type:'Aquático',color:'#2196F3',rare:'Rara Radiante',price:45.00,base:true},
  {n:'019',dex:79,name:'Slowpoke',artist:'N-DESIGN Inc.',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'020',dex:80,name:'Slowbro',artist:'Mina Nakai',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.30,base:true},
  {n:'021',dex:129,name:'Magikarp',artist:'N-DESIGN Inc.',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.29,base:true},
  {n:'022',dex:130,name:'Gyarados',artist:'Mitsuhiro Arita',type:'Aquático',color:'#2196F3',rare:'Rara Holo',price:2.50,base:true},
  {n:'023',dex:131,name:'Lapras',artist:'N-DESIGN Inc.',type:'Aquático',color:'#2196F3',rare:'Rara Holo',price:0.85,base:true},
  {n:'024',dex:144,name:'Articuno',artist:'Jiro Sasumo',type:'Aquático',color:'#2196F3',rare:'Rara Holo',price:4.20,base:true},
  {n:'025',dex:767,name:'Wimpod',artist:'Miki Tanaka',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'026',dex:768,name:'Golisopod',artist:'otumami',type:'Aquático',color:'#2196F3',rare:'Rara Holo',price:0.51,base:true},
  {n:'027',dex:25,name:'Pikachu',artist:'N-DESIGN Inc.',type:'Raio',color:'#FFEB3B',rare:'Comum',price:3.90,base:true},
  {n:'028',dex:25,name:'Pikachu',artist:'Narumi Sato',type:'Raio',color:'#FFEB3B',rare:'Rara Holo',price:29.99,base:true},
  {n:'029',dex:145,name:'Zapdos',artist:'Yuya Oka',type:'Raio',color:'#FFEB3B',rare:'Rara Holo',price:1.99,base:true},
  {n:'030',dex:150,name:'Mewtwo V',artist:'Nurikabe',type:'Psíquico',color:'#9C27B0',rare:'Rara Holo V',price:28.00,base:true},
  {n:'031',dex:150,name:'Mewtwo VSTAR',artist:'PLANETA Mochizuki',type:'Psíquico',color:'#9C27B0',rare:'Rara Holo VSTAR',price:19.90,base:true},
  {n:'032',dex:177,name:'Natu',artist:'HYOGONOSUKE',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'033',dex:178,name:'Xatu',artist:'Hataya',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'034',dex:337,name:'Lunatone',artist:'miki kudo',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.13,base:true},
  {n:'035',dex:700,name:'Sylveon',artist:'Atsushi Furusawa',type:'Psíquico',color:'#9C27B0',rare:'Rara Holo',price:5.00,base:true},
  {n:'036',dex:95,name:'Onix',artist:'Mitsuhiro Arita',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.25,base:true},
  {n:'037',dex:246,name:'Larvitar',artist:'sui',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.17,base:true},
  {n:'038',dex:247,name:'Pupitar',artist:'Sumiyoshi Kizuki',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.25,base:true},
  {n:'039',dex:338,name:'Solrock',artist:'Sekio',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.21,base:true},
  {n:'040',dex:534,name:'Conkeldurr V',artist:'Ayaka Yoshida',type:'Lutador',color:'#FF9800',rare:'Rara Holo V',price:4.50,base:true},
  {n:'041',dex:19,name:'Alolan Rattata',artist:'KIYOTAKA OSHIYAMA',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.13,base:true},
  {n:'042',dex:20,name:'Alolan Raticate',artist:'Atsuko Nishida',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'043',dex:248,name:'Tyranitar',artist:'Nisota Niso',type:'Sombrio',color:'#607D8B',rare:'Rara Holo',price:1.00,base:true},
  {n:'044',dex:208,name:'Steelix',artist:'GOSSAN',type:'Metal',color:'#78909C',rare:'Incomum',price:0.23,base:true},
  {n:'045',dex:808,name:'Meltan',artist:'Sumiyoshi Kizuki',type:'Metal',color:'#78909C',rare:'Comum',price:0.25,base:true},
  {n:'046',dex:809,name:'Melmetal',artist:'Shigenori Negishi',type:'Metal',color:'#78909C',rare:'Rara Holo',price:0.68,base:true},
  {n:'047',dex:809,name:'Melmetal V',artist:'sadaji',type:'Metal',color:'#78909C',rare:'Rara Holo V',price:3.00,base:true},
  {n:'048',dex:809,name:'Melmetal VMAX',artist:'PLANETA Tsuji',type:'Metal',color:'#78909C',rare:'Rara Holo VMAX',price:9.99,base:true},
  {n:'049',dex:149,name:'Dragonite V',artist:'kawayoo',type:'Dragão',color:'#3F51B5',rare:'Rara Holo V',price:39.90,base:true},
  {n:'050',dex:149,name:'Dragonite VSTAR',artist:'PLANETA Tsuji',type:'Dragão',color:'#3F51B5',rare:'Rara Holo VSTAR',price:15.00,base:true},
  {n:'051',dex:113,name:'Chansey',artist:'ryoma uratsuka',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.35,base:true},
  {n:'052',dex:242,name:'Blissey',artist:'Teeziro',type:'Incolor',color:'#9E9E9E',rare:'Rara Holo',price:1.89,base:true},
  {n:'053',dex:132,name:'Ditto',artist:'Misa Tsutsui',type:'Incolor',color:'#9E9E9E',rare:'Rara Holo',price:34.90,base:true},
  {n:'054',dex:133,name:'Eevee',artist:'N-DESIGN Inc.',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.50,base:true},
  {n:'055',dex:143,name:'Snorlax',artist:'N-DESIGN Inc.',type:'Incolor',color:'#9E9E9E',rare:'Rara Holo',price:4.90,base:true},
  {n:'056',dex:190,name:'Aipom',artist:'Sanosuke Sakuma',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'057',dex:424,name:'Ambipom',artist:'Scav',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.25,base:true},
  {n:'058',dex:289,name:'Slaking V',artist:'Saki Hayashiro',type:'Incolor',color:'#9E9E9E',rare:'Rara Holo V',price:2.50,base:true},
  {n:'059',dex:399,name:'Bidoof',artist:'Tomokazu Komiya',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.22,base:true},
  {n:'060',dex:400,name:'Bibarel',artist:'KIYOTAKA OSHIYAMA',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.21,base:true},
  {n:'061',dex:519,name:'Pidove',artist:'N-DESIGN Inc.',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'062',dex:520,name:'Tranquill',artist:'0313',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'063',dex:521,name:'Unfezant',artist:'GIDORA',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'064',name:'Blanche',artist:'Anesaki Dynamic',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'065',name:'Candela',artist:'Ryuta Fuse',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'066',name:'Egg Incubator',artist:'sadaji',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'067',name:'Lure Module',artist:'ORBITALLINK Inc.',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'068',name:'PokéStop',artist:'Studio Bora Inc.',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'069',name:'Rare Candy',artist:'Ayaka Yoshida',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.40,base:true},
  {n:'070',name:'Spark',artist:'Naoki Saito',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'071',dex:103,name:'Alolan Exeggutor V',artist:'MUGENUP',type:'Planta',color:'#4CAF50',rare:'Rara Ultra',price:15.00,base:true},
  {n:'072',dex:150,name:'Mewtwo V',artist:'N-DESIGN Inc.',type:'Psíquico',color:'#9C27B0',rare:'Rara Ultra',price:127.50,base:true},
  {n:'073',dex:534,name:'Conkeldurr V',artist:'Ayaka Yoshida',type:'Lutador',color:'#FF9800',rare:'Rara Ultra',price:14.95,base:true},
  {n:'074',dex:534,name:'Conkeldurr V',artist:'N-DESIGN Inc.',type:'Lutador',color:'#FF9800',rare:'Rara Ultra',price:20.00,base:true},
  {n:'075',dex:809,name:'Melmetal V',artist:'sadaji',type:'Metal',color:'#78909C',rare:'Rara Ultra',price:4.00,base:true},
  {n:'076',dex:149,name:'Dragonite V',artist:'5ban Graphics',type:'Dragão',color:'#3F51B5',rare:'Rara Ultra',price:86.00,base:true},
  {n:'077',dex:289,name:'Slaking V',artist:'Saki Hayashiro',type:'Incolor',color:'#9E9E9E',rare:'Rara Ultra',price:9.90,base:true},
  {n:'078',name:'Professor\'s Research',artist:'Yusuke Kozaki',type:'Incolor',color:'#9E9E9E',rare:'Rara Ultra',price:21.38,base:true},
  {n:'079',dex:150,name:'Mewtwo VSTAR',artist:'PLANETA Mochizuki',type:'Psíquico',color:'#9C27B0',rare:'Rara Rainbow',price:149.90,base:false},
  {n:'080',dex:809,name:'Melmetal VMAX',artist:'PLANETA Tsuji',type:'Metal',color:'#78909C',rare:'Rara Rainbow',price:74.90,base:false},
  {n:'081',dex:149,name:'Dragonite VSTAR',artist:'PLANETA Tsuji',type:'Dragão',color:'#3F51B5',rare:'Rara Rainbow',price:109.90,base:false},
  {n:'082',name:'Blanche',artist:'Anesaki Dynamic',type:'Incolor',color:'#9E9E9E',rare:'Rara Rainbow',price:59.90,base:false},
  {n:'083',name:'Candela',artist:'Ryuta Fuse',type:'Incolor',color:'#9E9E9E',rare:'Rara Rainbow',price:49.75,base:false},
  {n:'084',name:'Professor\'s Research',artist:'Yusuke Kozaki',type:'Incolor',color:'#9E9E9E',rare:'Rara Rainbow',price:79.90,base:false},
  {n:'085',name:'Spark',artist:'Naoki Saito',type:'Incolor',color:'#9E9E9E',rare:'Rara Rainbow',price:29.00,base:false},
  {n:'086',dex:150,name:'Mewtwo VSTAR',artist:'PLANETA Mochizuki',type:'Psíquico',color:'#9C27B0',rare:'Rara Secreta',price:131.75,base:false},
  {n:'087',name:'Egg Incubator',artist:'sadaji',type:'Incolor',color:'#9E9E9E',rare:'Rara Secreta',price:16.90,base:false},
  {n:'088',name:'Lure Module',artist:'ORBITALLINK Inc.',type:'Incolor',color:'#9E9E9E',rare:'Rara Secreta',price:23.99,base:false}
];
