// ME02 — Fogo Fantasmagórico (130 cartas)
const CARDS_ME02 = [
  // ── BASE 001–094 ──────────────────────────────────────────────────────────
  // GRAMA
  {n:'001',dex:43,artist:"MINAMINAMI Take",name:'Oddish',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.05,base:true},
  {n:'002',dex:44,artist:"Yoriyuki Ikegami",name:'Gloom',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'003',dex:45,artist:"Shibuzoh.",name:'Vileplume',type:'Grama',color:'#4CAF50',rare:'Rara Holo',price:0.15,base:true},
  {n:'004',dex:214,artist:"5ban Graphics",name:'Mega Heracross ex',type:'Grama',color:'#4CAF50',rare:'Rara Dupla',price:3.00,base:true},
  {n:'005',dex:270,artist:"Wintr Wandr",name:'Lotad',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'006',dex:271,artist:"Shigenori Negishi",name:'Lombre',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.05,base:true},
  {n:'007',dex:272,artist:"Anesaki Dynamic",name:'Ludicolo',type:'Grama',color:'#4CAF50',rare:'Incomum',price:0.10,base:true},
  {n:'008',dex:649,artist:"Mitsuhiro Arita",name:'Genesect',type:'Grama',color:'#4CAF50',rare:'Rara Holo',price:0.15,base:true},
  {n:'009',dex:919,artist:"Yuka Morii",name:'Nymble',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'010',dex:920,artist:"Taiga Kasai",name:'Lokix',type:'Grama',color:'#4CAF50',rare:'Incomum',price:0.10,base:true},
  // FOGO
  {n:'011',dex:4,artist:"HYOGONOSUKE",name:'Charmander',type:'Fogo',color:'#F44336',rare:'Comum',price:0.05,base:true},
  {n:'012',dex:5,artist:"Uninori",name:'Charmeleon',type:'Fogo',color:'#F44336',rare:'Comum',price:0.07,base:true},
  {n:'013',dex:6,artist:"takuyoa",name:'Mega Charizard X ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:9.90,base:true,important:true},
  {n:'014',dex:146,artist:"Kazumasa Yasukuni",name:'Moltres',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.13,base:true},
  {n:'015',dex:554,artist:"NC Empire",name:'Darumaka',type:'Fogo',color:'#F44336',rare:'Comum',price:0.05,base:true},
  {n:'016',dex:555,artist:"Uta",name:'Darmanitan',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.05,base:true},
  {n:'017',dex:643,artist:"AKIRA EGAWA",name:'Reshiram',type:'Fogo',color:'#F44336',rare:'Rara Holo',price:0.15,base:true},
  {n:'018',dex:741,artist:"akagi",name:'Oricorio ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:2.00,base:true},
  {n:'019',dex:935,artist:"Tomokazu Komiya",name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.05,base:true},
  {n:'020',dex:937,artist:"Gemi",name:'Ceruledge',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.05,base:true},
  // AQUÁTICO
  {n:'021',dex:86,artist:"svlt",name:'Seel',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'022',dex:87,artist:"Taira Akitsu",name:'Dewgong',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.05,base:true},
  {n:'023',dex:220,artist:"imoniii",name:'Swinub',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'024',dex:221,artist:"Shinya Komatsu",name:'Piloswine',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.05,base:true},
  {n:'025',dex:473,artist:"Takumi Wada",name:'Mamoswine',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.10,base:true},
  {n:'026',dex:245,artist:"Takeshi Nakamura",name:'Suicune',type:'Aquático',color:'#2196F3',rare:'Rara Holo',price:0.15,base:true},
  {n:'027',dex:393,artist:"Hideki Ishikawa",name:'Piplup',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'028',dex:394,artist:"Atsuya Uki",name:'Prinplup',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  // RAIO
  {n:'029',dex:479,artist:"5ban Graphics",name:'Rotom ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:1.20,base:true},
  {n:'030',dex:835,artist:"Ayako Ozaki",name:'Yamper',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.04,base:true},
  {n:'031',dex:836,artist:"Orca",name:'Boltund',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.08,base:true},
  {n:'032',dex:921,artist:"Shimaris Yukichi",name:'Pawmi',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.05,base:true},
  {n:'033',dex:922,artist:"Taiga Kayama",name:'Pawmo',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.09,base:true},
  {n:'034',dex:923,artist:"satoma",name:'Pawmot',type:'Raio',color:'#FFEB3B',rare:'Rara Holo',price:0.15,base:true},
  // PSÍQUICO
  {n:'035',dex:200,artist:"Mousho",name:'Misdreavus',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.05,base:true},
  {n:'036',dex:429,artist:"5ban Graphics",name:'Mismagius ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:2.80,base:true},
  {n:'037',dex:209,artist:"Gapao",name:'Snubbull',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.04,base:true},
  {n:'038',dex:210,artist:"Ryuta Fuse",name:'Granbull',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.10,base:true},
  {n:'039',dex:488,artist:"Raita Kazama",name:'Cresselia',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.10,base:true},
  {n:'040',dex:648,artist:"MINAMINAMI Take",name:'Meloetta',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.10,base:true},
  {n:'041',dex:719,artist:"aky CG Works",name:'Mega Diancie ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:3.80,base:true},
  {n:'042',dex:778,artist:"miki kudo",name:'Mimikyu',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.05,base:true},
  {n:'043',dex:868,artist:"Taiga Kayama",name:'Milcery',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.03,base:true},
  {n:'044',dex:869,artist:"Narumi Sato",name:'Alcremie',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.04,base:true},
  {n:'045',dex:888,artist:"kawayoo",name:'Zacian',type:'Psíquico',color:'#9C27B0',rare:'Rara Holo',price:0.15,base:true},
  {n:'046',dex:946,artist:"Takeshi Nakamura",name:'Bramblin',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.05,base:true},
  {n:'047',dex:947,artist:"Tetsu Kayama",name:'Brambleghast',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.10,base:true},
  // LUTADOR
  {n:'048',dex:128,artist:"Souichirou Gunjima",name:'Paldean Tauros',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'049',dex:207,artist:"Kazumasa Yasukuni",name:'Gligar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true,important:true},
  {n:'050',dex:472,artist:"Dsuke",name:'Gliscor',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.08,base:true},
  {n:'051',dex:328,artist:"Uta",name:'Trapinch',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.08,base:true},
  {n:'052',dex:329,artist:"Miki Tanaka",name:'Vibrava',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.09,base:true},
  {n:'053',dex:330,artist:"Jerky",name:'Flygon',type:'Lutador',color:'#FF9800',rare:'Rara Holo',price:0.15,base:true},
  // ESCURIDÃO
  {n:'054',dex:92,artist:"Saboteri",name:'Gastly',type:'Escuridão',color:'#607D8B',rare:'Comum',price:0.05,base:true},
  {n:'055',dex:93,artist:"Rianti Hidayat",name:'Haunter',type:'Escuridão',color:'#607D8B',rare:'Incomum',price:0.05,base:true},
  {n:'056',dex:94,artist:"5ban Graphics",name:'Mega Gengar ex',type:'Escuridão',color:'#607D8B',rare:'Rara Dupla',price:7.50,base:true},
  {n:'057',dex:198,artist:"Tomokazu Komiya",name:'Murkrow',type:'Escuridão',color:'#607D8B',rare:'Comum',price:0.04,base:true},
  {n:'058',dex:430,artist:"Anesaki Dynamic",name:'Honchkrow',type:'Escuridão',color:'#607D8B',rare:'Incomum',price:0.05,base:true},
  {n:'059',dex:302,artist:"osare",name:'Sableye',type:'Escuridão',color:'#607D8B',rare:'Comum',price:0.07,base:true},
  {n:'060',dex:318,artist:"Shin Nagasawa",name:'Carvanha',type:'Escuridão',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'061',dex:319,artist:"5ban Graphics",name:'Mega Sharpedo ex',type:'Escuridão',color:'#607D8B',rare:'Rara Dupla',price:2.91,base:true},
  {n:'062',dex:336,artist:"hncl",name:'Seviper',type:'Escuridão',color:'#607D8B',rare:'Incomum',price:0.09,base:true},
  {n:'063',dex:359,artist:"Takumi Wada",name:'Absol',type:'Escuridão',color:'#607D8B',rare:'Incomum',price:0.05,base:true},
  {n:'064',dex:551,artist:"Taiga Kasai",name:'Sandile',type:'Escuridão',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'065',dex:552,artist:"Uninori",name:'Krokorok',type:'Escuridão',color:'#607D8B',rare:'Comum',price:0.05,base:true},
  {n:'066',dex:553,artist:"Ryuta Fuse",name:'Krookodile',type:'Escuridão',color:'#607D8B',rare:'Incomum',price:0.05,base:true},
  {n:'067',dex:848,artist:"OKACHEKE",name:'Toxel',type:'Escuridão',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'068',dex:849,artist:"DOM",name:'Toxtricity',type:'Escuridão',color:'#607D8B',rare:'Rara Holo',price:0.19,base:true,important:true},
  {n:'069',dex:890,artist:"akagi",name:'Eternatus',type:'Escuridão',color:'#607D8B',rare:'Incomum',price:0.12,base:true},
  // METAL
  {n:'070',dex:395,artist:"5ban Graphics",name:'Empoleon ex',type:'Metal',color:'#9E9E9E',rare:'Rara Dupla',price:2.50,base:true},
  {n:'071',dex:436,artist:"OKUBO",name:'Bronzor',type:'Metal',color:'#9E9E9E',rare:'Comum',price:0.05,base:true},
  {n:'072',dex:437,artist:"Masako Tomii",name:'Bronzong',type:'Metal',color:'#9E9E9E',rare:'Incomum',price:0.05,base:true},
  {n:'073',dex:777,artist:"Bun Toujo",name:'Togedemaru',type:'Metal',color:'#9E9E9E',rare:'Comum',price:0.05,base:true},
  {n:'074',dex:884,artist:"Shinji Kanda",name:'Duraludon',type:'Metal',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'075',dex:1018,artist:"toriyufu",name:'Archaludon',type:'Metal',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  // INCOLOR
  {n:'076',dex:39,artist:"Naoyo Kimura",name:'Jigglypuff',type:'Incolor',color:'#78909C',rare:'Comum',price:0.05,base:true},
  {n:'077',dex:40,artist:"En Morikura",name:'Wigglytuff',type:'Incolor',color:'#78909C',rare:'Incomum',price:0.10,base:true},
  {n:'078',dex:190,artist:"Saboteri",name:'Aipom',type:'Incolor',color:'#78909C',rare:'Comum',price:0.05,base:true},
  {n:'079',dex:424,artist:"hncl",name:'Ambipom',type:'Incolor',color:'#78909C',rare:'Rara Holo',price:0.15,base:true},
  {n:'080',dex:235,artist:"REND",name:'Smeargle',type:'Incolor',color:'#78909C',rare:'Comum',price:0.05,base:true},
  {n:'081',dex:263,artist:"Dsuke",name:'Zigzagoon',type:'Incolor',color:'#78909C',rare:'Comum',price:0.10,base:true},
  {n:'082',dex:264,artist:"nagimiso",name:'Linoone',type:'Incolor',color:'#78909C',rare:'Incomum',price:0.09,base:true},
  {n:'083',dex:427,artist:"tono",name:'Buneary',type:'Incolor',color:'#78909C',rare:'Comum',price:0.10,base:true},
  {n:'084',dex:428,artist:"5ban Graphics",name:'Mega Lopunny ex',type:'Incolor',color:'#78909C',rare:'Rara Dupla',price:3.90,base:true},
  // TREINADORES
  {n:'085',artist:"MARINA Chikazawa",name:'Gaiola de Batalha',type:'Estádio',color:'#795548',rare:'Incomum',price:0.20,base:true},
  {n:'086',artist:"Toyste Beach",name:'Maçarico',type:'Item',color:'#5C6BC0',rare:'Incomum',price:0.07,base:true},
  {n:'087',artist:"Yuu Nishida",name:'Aurora',type:'Suporte',color:'#E91E63',rare:'Incomum',price:0.35,base:true,important:true},
  {n:'088',artist:"AYUMI ODASHIMA",name:'Vale Tontear',type:'Estádio',color:'#795548',rare:'Incomum',price:0.10,base:true},
  {n:'089',artist:"Naoki Saito",name:'Piromaníaco',type:'Suporte',color:'#E91E63',rare:'Incomum',price:0.08,base:true},
  {n:'090',artist:"GIDORA",name:'Movimento do Grimsley',type:'Suporte',color:'#E91E63',rare:'Incomum',price:0.10,base:true},
  {n:'091',artist:"AYUMI ODASHIMA",name:'Sorvetão Jumbo',type:'Item',color:'#5C6BC0',rare:'Incomum',price:0.10,base:true},
  {n:'092',artist:"Studio Bora Inc.",name:'Capacete Punk',type:'Item Ferramenta',color:'#5C6BC0',rare:'Incomum',price:0.10,base:true},
  {n:'093',artist:"Toyste Beach",name:'Amuleto Sagrado',type:'Item Ferramenta',color:'#5C6BC0',rare:'Incomum',price:0.10,base:true},
  {n:'094',artist:"Studio Bora Inc.",name:'Wondrous Patch',type:'Item',color:'#5C6BC0',rare:'Incomum',price:0.09,base:true,important:true},
  // ── SECRETAS 095–130 ──────────────────────────────────────────────────────
  // Ilustração Rara (IR) 095–107
  {n:'095',dex:272,artist:"Jerky",name:'Ludicolo (IR)',type:'Grama',color:'#4CAF50',rare:'Ilustr. Rara',price:11.75,base:false},
  {n:'096',dex:919,artist:"Nakamura Ippan",name:'Nymble (IR)',type:'Grama',color:'#4CAF50',rare:'Ilustr. Rara',price:5.90,base:false},
  {n:'097',dex:87,artist:"satoma",name:'Dewgong (IR)',type:'Aquático',color:'#2196F3',rare:'Ilustr. Rara',price:24.90,base:false},
  {n:'098',dex:393,artist:"Jiro Sasumo",name:'Piplup (IR)',type:'Aquático',color:'#2196F3',rare:'Ilustr. Rara',price:24.90,base:false},
  {n:'099',dex:835,artist:"tono",name:'Yamper (IR)',type:'Raio',color:'#FFEB3B',rare:'Ilustr. Rara',price:12.90,base:false},
  {n:'100',dex:888,artist:"Yoriyuki Ikegami",name:'Zacian (IR)',type:'Psíquico',color:'#9C27B0',rare:'Ilustr. Rara',price:16.90,base:false},
  {n:'101',dex:330,artist:"Ryota Murayama",name:'Flygon (IR)',type:'Lutador',color:'#FF9800',rare:'Ilustr. Rara',price:14.00,base:false},
  {n:'102',dex:194,artist:"OKACHEKE",name:'Paldean Wooper (IR)',type:'Água',color:'#2196F3',rare:'Ilustr. Rara',price:10.90,base:false},
  {n:'103',dex:849,artist:"Terada Tera",name:'Toxtricity (IR)',type:'Escuridão',color:'#607D8B',rare:'Ilustr. Rara',price:15.00,base:false},
  {n:'104',dex:777,artist:"Orca",name:'Togedemaru (IR)',type:'Metal',color:'#9E9E9E',rare:'Ilustr. Rara',price:11.90,base:false},
  {n:'105',dex:40,artist:"REND",name:'Wigglytuff (IR)',type:'Incolor',color:'#78909C',rare:'Ilustr. Rara',price:25.09,base:false},
  {n:'106',dex:52,artist:"Uninori",name:'Aurora (IR)',type:'Suporte',color:'#E91E63',rare:'Ilustr. Rara',price:103.00,base:false},
  {n:'107',dex:424,artist:"Shigenori Negishi",name:'Movimento do Grimsley (IR)',type:'Suporte',color:'#E91E63',rare:'Ilustr. Rara',price:11.00,base:false},
  // Rara Ultra (UR) 108–124
  {n:'108',dex:214,artist:"5ban Graphics",name:'Mega Charizard X ex (UR)',type:'Fogo',color:'#F44336',rare:'Rara Ultra',price:9.90,base:false},
  {n:'109',dex:6,artist:"takuyoa",name:'Mega Heracross ex (UR)',type:'Grama',color:'#4CAF50',rare:'Rara Ultra',price:159.99,base:false},
  {n:'110',dex:741,artist:"5ban Graphics",name:'Mega Gengar ex (UR)',type:'Escuridão',color:'#607D8B',rare:'Rara Ultra',price:2.00,base:false},
  {n:'111',dex:479,artist:"5ban Graphics",name:'Mega Sharpedo ex (UR)',type:'Escuridão',color:'#607D8B',rare:'Rara Ultra',price:8.97,base:false},
  {n:'112',dex:429,artist:"5ban Graphics",name:'Mega Diancie ex (UR)',type:'Psíquico',color:'#9C27B0',rare:'Rara Ultra',price:9.90,base:false},
  {n:'113',dex:319,artist:"5ban Graphics",name:'Mega Lopunny ex (UR)',type:'Incolor',color:'#78909C',rare:'Rara Ultra',price:14.00,base:false},
  {n:'114',dex:395,artist:"5ban Graphics",name:'Oricorio ex (UR)',type:'Fogo',color:'#F44336',rare:'Rara Ultra',price:14.00,base:false},
  {n:'115',dex:428,artist:"5ban Graphics",name:'Rotom ex (UR)',type:'Raio',color:'#FFEB3B',rare:'Rara Ultra',price:23.80,base:false},
  {n:'116',artist:"MARINA Chikazawa",name:'Mismagius ex (UR)',type:'Psíquico',color:'#9C27B0',rare:'Rara Ultra',price:15.00,base:false},
  {n:'117',artist:"Toyste Beach",name:'Empoleon ex (UR)',type:'Metal',color:'#9E9E9E',rare:'Rara Ultra',price:6.25,base:false},
  {n:'118',artist:"Yuu Nishida",name:'Aurora (UR)',type:'Suporte',color:'#E91E63',rare:'Rara Ultra',price:29.75,base:false},
  {n:'119',artist:"Naoki Saito",name:'Piromaníaco (UR)',type:'Suporte',color:'#E91E63',rare:'Rara Ultra',price:5.90,base:false},
  {n:'120',artist:"GIDORA",name:'Movimento do Grimsley (UR)',type:'Suporte',color:'#E91E63',rare:'Rara Ultra',price:11.70,base:false},
  {n:'121',artist:"Studio Bora Inc.",name:'Wondrous Patch (UR)',type:'Item',color:'#5C6BC0',rare:'Rara Ultra',price:7.80,base:false},
  {n:'122',artist:"Toyste Beach",name:'Sorvetão Jumbo (UR)',type:'Item',color:'#5C6BC0',rare:'Rara Ultra',price:4.99,base:false},
  {n:'123',artist:"Studio Bora Inc.",name:'Capacete Punk (UR)',type:'Item Ferramenta',color:'#5C6BC0',rare:'Rara Ultra',price:12.89,base:false},
  {n:'124',name:'Gaiola de Batalha (UR)',type:'Estádio',color:'#795548',rare:'Rara Ultra',price:19.80,base:false},
  // Ilustração Rara Especial (SAR) 125–129
  {n:'125',dex:6,artist:"danciao",name:'Mega Charizard X ex (SAR)',type:'Fogo',color:'#F44336',rare:'Ilustr. Esp. Rara',price:1799.00,base:false},
  {n:'126',dex:479,artist:"Yoshimi Miyoshi",name:'Mega Gengar ex (SAR)',type:'Escuridão',color:'#607D8B',rare:'Ilustr. Esp. Rara',price:79.90,base:false},
  {n:'127',dex:319,artist:"nagimiso",name:'Mega Lopunny ex (SAR)',type:'Incolor',color:'#78909C',rare:'Ilustr. Esp. Rara',price:53.00,base:false},
  {n:'128',dex:428,artist:"Kinu Nishimura",name:'Aurora (SAR)',type:'Suporte',color:'#E91E63',rare:'Ilustr. Esp. Rara',price:74.90,base:false},
  {n:'129',artist:"Atsushi Furusawa",name:'Movimento do Grimsley (SAR)',type:'Suporte',color:'#E91E63',rare:'Ilustr. Esp. Rara',price:163.90,base:false},
  // Mega Hyper Rare 130
  {n:'130',dex:6,artist:"takuyoa",name:'Mega Charizard X ex GOLD',type:'Fogo',color:'#FFD700',rare:'Mega Hyper Rare',price:1140.00,base:false},
];
