// SV4PT5 — Paldean Fates (245 cartas)
// Lançamento EN: 2024/01/26
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV4PT5 = [
  {n:'001',name:'Pineco',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'002',name:'Forretress ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.80,base:true},
  {n:'003',name:'Maractus',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.08,base:true},
  {n:'004',name:'Toedscool',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'005',name:'Toedscruel ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.96,base:true},
  {n:'006',name:'Espathra ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.50,base:true},
  {n:'007',name:'Charmander',type:'Fogo',color:'#F44336',rare:'Comum',price:0.09,base:true},
  {n:'008',name:'Charmeleon',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.15,base:true},
  {n:'009',name:'Magmar',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'010',name:'Magmortar',type:'Fogo',color:'#F44336',rare:'Rara',price:0.20,base:true},
  {n:'011',name:'Numel',type:'Fogo',color:'#F44336',rare:'Comum',price:0.15,base:true},
  {n:'012',name:'Camerupt',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.10,base:true},
  {n:'013',name:'Heat Rotom',type:'Fogo',color:'#F44336',rare:'Rara',price:0.26,base:true},
  {n:'014',name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'015',name:'Armarouge',type:'Fogo',color:'#F44336',rare:'Rara',price:0.30,base:true},
  {n:'016',name:'Lapras',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.15,base:true},
  {n:'017',name:'Frigibax',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.15,base:true},
  {n:'018',name:'Pikachu',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.15,base:true},
  {n:'019',name:'Raichu',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.49,base:true},
  {n:'020',name:'Chinchou',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.10,base:true},
  {n:'021',name:'Lanturn',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.11,base:true},
  {n:'022',name:'Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.15,base:true},
  {n:'023',name:'Exeggcute',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'024',name:'Exeggutor',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.30,base:true},
  {n:'025',name:'Natu',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.14,base:true},
  {n:'026',name:'Xatu',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.30,base:true},
  {n:'027',name:'Ralts',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'028',name:'Kirlia',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'029',name:'Gardevoir ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:3.59,base:true},
  {n:'030',name:'Chimecho',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'031',name:'Mime Jr.',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'032',name:'Woobat',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'033',name:'Swoobat',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'034',name:'Cottonee',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'035',name:'Whimsicott',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.15,base:true},
  {n:'036',name:'Dedenne',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'037',name:'Mimikyu',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.50,base:true},
  {n:'038',name:'Fidough',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'039',name:'Dachsbun',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.10,base:true},
  {n:'040',name:'Ceruledge',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.35,base:true},
  {n:'041',name:'Flittle',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'042',name:'Greavard',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'043',name:'Houndstone',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.22,base:true},
  {n:'044',name:'Gimmighoul',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.15,base:true},
  {n:'045',name:'Mankey',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'046',name:'Primeape',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.10,base:true},
  {n:'047',name:'Annihilape',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.20,base:true},
  {n:'048',name:'Phanpy',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'049',name:'Donphan',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.15,base:true},
  {n:'050',name:'Barboach',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.15,base:true},
  {n:'051',name:'Clobbopus',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.13,base:true},
  {n:'052',name:'Grapploct',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.10,base:true},
  {n:'053',name:'Great Tusk ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:3.75,base:true},
  {n:'054',name:'Charizard ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:4.90,base:true},
  {n:'055',name:'Gastly',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'056',name:'Haunter',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'057',name:'Gengar',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.15,base:true},
  {n:'058',name:'Paldean Wooper',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'059',name:'Paldean Clodsire ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:3.50,base:true},
  {n:'060',name:'Scraggy',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.05,base:true},
  {n:'061',name:'Scrafty',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.14,base:true},
  {n:'062',name:'Maschiff',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'063',name:'Mabosstiff',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.20,base:true},
  {n:'064',name:'Varoom',type:'Metal',color:'#78909C',rare:'Comum',price:0.15,base:true},
  {n:'065',name:'Revavroom',type:'Metal',color:'#78909C',rare:'Rara',price:0.25,base:true},
  {n:'066',name:'Iron Treads ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:3.50,base:true},
  {n:'067',name:'Gholdengo',type:'Metal',color:'#78909C',rare:'Rara',price:0.20,base:true},
  {n:'068',name:'Noibat',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.10,base:true},
  {n:'069',name:'Noivern ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:4.50,base:true},
  {n:'070',name:'Cyclizar',type:'Dragão',color:'#3F51B5',rare:'Rara',price:0.17,base:true},
  {n:'071',name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'072',name:'Oinkologne',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.05,base:true},
  {n:'073',name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'074',name:'Maushold',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'075',name:'Squawkabilly ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:2.99,base:true},
  {n:'076',name:'Artazon',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'077',name:'Atticus',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'078',name:'Clive',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'079',name:'Electric Generator',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'080',name:'Iono',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'081',name:'Moonlit Hill',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.13,base:true},
  {n:'082',name:'Nemona',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.14,base:true},
  {n:'083',name:'Nemona\'s Backpack',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'084',name:'Nest Ball',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'085',name:'Paldean Student',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.05,base:true},
  {n:'086',name:'Paldean Student',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.05,base:true},
  {n:'087',name:'Professor\'s Research',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.25,base:true},
  {n:'088',name:'Professor\'s Research',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.20,base:true},
  {n:'089',name:'Rare Candy',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'090',name:'Technical Machine: Crisis Punch',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'091',name:'Ultra Ball',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'092',name:'Oddish',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:12.60,base:false,important:true},
  {n:'093',name:'Gloom',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:17.00,base:false},
  {n:'094',name:'Vileplume',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:37.89,base:false},
  {n:'095',name:'Scyther',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:19.90,base:false,important:true},
  {n:'096',name:'Hoppip',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:9.89,base:false},
  {n:'097',name:'Skiploom',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:24.15,base:false},
  {n:'098',name:'Jumpluff',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:29.90,base:false},
  {n:'099',name:'Pineco',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:7.00,base:false},
  {n:'100',name:'Snover',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:2.90,base:false},
  {n:'101',name:'Abomasnow',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:24.90,base:false},
  {n:'102',name:'Smoliv',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:20.90,base:false},
  {n:'103',name:'Dolliv',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:17.90,base:false},
  {n:'104',name:'Arboliva',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:19.90,base:false},
  {n:'105',name:'Toedscool',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:9.00,base:false},
  {n:'106',name:'Capsakid',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:7.00,base:false},
  {n:'107',name:'Scovillain',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:19.90,base:false},
  {n:'108',name:'Rellor',type:'Planta',color:'#4CAF50',rare:'Rara Brilhante',price:7.00,base:false},
  {n:'109',name:'Charmander',type:'Fogo',color:'#F44336',rare:'Rara Brilhante',price:61.90,base:false,important:true},
  {n:'110',name:'Charmeleon',type:'Fogo',color:'#F44336',rare:'Rara Brilhante',price:119.90,base:false,important:true},
  {n:'111',name:'Paldean Tauros',type:'Fogo',color:'#F44336',rare:'Rara Brilhante',price:19.90,base:false},
  {n:'112',name:'Entei',type:'Fogo',color:'#F44336',rare:'Rara Brilhante',price:50.00,base:false,important:true},
  {n:'113',name:'Oricorio',type:'Fogo',color:'#F44336',rare:'Rara Brilhante',price:7.40,base:false},
  {n:'114',name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Rara Brilhante',price:14.90,base:false},
  {n:'115',name:'Armarouge',type:'Fogo',color:'#F44336',rare:'Rara Brilhante',price:37.90,base:false},
  {n:'116',name:'Slowpoke',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:24.00,base:false,important:true},
  {n:'117',name:'Slowbro',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:119.00,base:false,important:true},
  {n:'118',name:'Staryu',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:12.00,base:false},
  {n:'119',name:'Starmie',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:42.90,base:false,important:true},
  {n:'120',name:'Paldean Tauros',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:24.00,base:false},
  {n:'121',name:'Wiglett',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:14.00,base:false},
  {n:'122',name:'Wugtrio',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:10.90,base:false},
  {n:'123',name:'Finizen',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:10.49,base:false},
  {n:'124',name:'Palafin',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:19.75,base:false},
  {n:'125',name:'Veluza',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:10.99,base:false},
  {n:'126',name:'Dondozo',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:13.00,base:false},
  {n:'127',name:'Tatsugiri',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:22.90,base:false},
  {n:'128',name:'Frigibax',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:27.50,base:false},
  {n:'129',name:'Arctibax',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:23.90,base:false},
  {n:'130',name:'Baxcalibur',type:'Aquático',color:'#2196F3',rare:'Rara Brilhante',price:21.46,base:false},
  {n:'131',name:'Pikachu',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:127.50,base:false,important:true},
  {n:'132',name:'Raichu',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:70.00,base:false,important:true},
  {n:'133',name:'Voltorb',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:11.00,base:false},
  {n:'134',name:'Electrode',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:39.90,base:false},
  {n:'135',name:'Shinx',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:11.90,base:false,important:true},
  {n:'136',name:'Luxio',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:19.90,base:false},
  {n:'137',name:'Luxray',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:45.00,base:false,important:true},
  {n:'138',name:'Pachirisu',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:38.90,base:false,important:true},
  {n:'139',name:'Thundurus',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:23.90,base:false},
  {n:'140',name:'Toxel',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:27.90,base:false},
  {n:'141',name:'Toxtricity',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:20.89,base:false},
  {n:'142',name:'Pawmi',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:9.90,base:false},
  {n:'143',name:'Pawmo',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:19.90,base:false},
  {n:'144',name:'Pawmot',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:24.50,base:false},
  {n:'145',name:'Wattrel',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:10.00,base:false},
  {n:'146',name:'Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Rara Brilhante',price:18.00,base:false},
  {n:'147',name:'Wigglytuff',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:23.99,base:false},
  {n:'148',name:'Abra',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:30.00,base:false,important:true},
  {n:'149',name:'Kadabra',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:31.50,base:false},
  {n:'150',name:'Cleffa',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:35.00,base:false},
  {n:'151',name:'Natu',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:7.99,base:false},
  {n:'152',name:'Xatu',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:9.00,base:false},
  {n:'153',name:'Ralts',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:49.78,base:false,important:true},
  {n:'154',name:'Kirlia',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:49.99,base:false},
  {n:'155',name:'Drifloon',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:8.90,base:false},
  {n:'156',name:'Drifblim',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:19.00,base:false},
  {n:'157',name:'Mime Jr.',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:8.99,base:false},
  {n:'158',name:'Spiritomb',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:40.00,base:false},
  {n:'159',name:'Klefki',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:21.90,base:false},
  {n:'160',name:'Mimikyu',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:110.00,base:false,important:true},
  {n:'161',name:'Dachsbun',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:58.99,base:false,important:true},
  {n:'162',name:'Ceruledge',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:79.90,base:false,important:true},
  {n:'163',name:'Rabsca',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:19.90,base:false},
  {n:'164',name:'Flittle',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:8.90,base:false},
  {n:'165',name:'Tinkatink',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:50.00,base:false,important:true},
  {n:'166',name:'Tinkatuff',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:38.25,base:false},
  {n:'167',name:'Tinkaton',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:46.75,base:false,important:true},
  {n:'168',name:'Houndstone',type:'Psíquico',color:'#9C27B0',rare:'Rara Brilhante',price:15.00,base:false},
  {n:'169',name:'Mankey',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:9.00,base:false},
  {n:'170',name:'Primeape',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:9.90,base:false},
  {n:'171',name:'Annihilape',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:29.90,base:false},
  {n:'172',name:'Paldean Tauros',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:16.90,base:false},
  {n:'173',name:'Riolu',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:22.89,base:false,important:true},
  {n:'174',name:'Lucario',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:73.00,base:false,important:true},
  {n:'175',name:'Hawlucha',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:36.26,base:false},
  {n:'176',name:'Nacli',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:19.90,base:false},
  {n:'177',name:'Naclstack',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:13.50,base:false},
  {n:'178',name:'Garganacl',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:22.90,base:false},
  {n:'179',name:'Glimmet',type:'Lutador',color:'#FF9800',rare:'Rara Brilhante',price:8.84,base:false},
  {n:'180',name:'Paldean Wooper',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:18.99,base:false,important:true},
  {n:'181',name:'Murkrow',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:9.99,base:false},
  {n:'182',name:'Sneasel',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:24.90,base:false},
  {n:'183',name:'Weavile',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:19.90,base:false},
  {n:'184',name:'Sableye',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:47.00,base:false},
  {n:'185',name:'Pawniard',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:9.50,base:false},
  {n:'186',name:'Bisharp',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:19.90,base:false},
  {n:'187',name:'Kingambit',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:15.90,base:false},
  {n:'188',name:'Mabosstiff',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:14.89,base:false},
  {n:'189',name:'Shroodle',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:7.80,base:false},
  {n:'190',name:'Grafaiai',type:'Sombrio',color:'#607D8B',rare:'Rara Brilhante',price:16.50,base:false},
  {n:'191',name:'Scizor',type:'Metal',color:'#78909C',rare:'Rara Brilhante',price:48.90,base:false,important:true},
  {n:'192',name:'Varoom',type:'Metal',color:'#78909C',rare:'Rara Brilhante',price:6.27,base:false},
  {n:'193',name:'Revavroom',type:'Metal',color:'#78909C',rare:'Rara Brilhante',price:19.50,base:false},
  {n:'194',name:'Noibat',type:'Dragão',color:'#3F51B5',rare:'Rara Brilhante',price:20.00,base:false},
  {n:'195',name:'Cyclizar',type:'Dragão',color:'#3F51B5',rare:'Rara Brilhante',price:14.00,base:false},
  {n:'196',name:'Pidgey',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:43.99,base:false},
  {n:'197',name:'Pidgeotto',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:45.00,base:false},
  {n:'198',name:'Jigglypuff',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:40.90,base:false,important:true},
  {n:'199',name:'Doduo',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:55.00,base:false},
  {n:'200',name:'Dodrio',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:37.50,base:false},
  {n:'201',name:'Ditto',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:104.90,base:false,important:true},
  {n:'202',name:'Snorlax',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:151.92,base:false,important:true},
  {n:'203',name:'Wingull',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:28.90,base:false},
  {n:'204',name:'Pelipper',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:19.90,base:false},
  {n:'205',name:'Skwovet',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:9.99,base:false},
  {n:'206',name:'Greedent',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:16.90,base:false},
  {n:'207',name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:21.89,base:false,important:true},
  {n:'208',name:'Oinkologne',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:16.90,base:false},
  {n:'209',name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:49.99,base:false,important:true},
  {n:'210',name:'Maushold',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:79.90,base:false,important:true},
  {n:'211',name:'Flamigo',type:'Incolor',color:'#9E9E9E',rare:'Rara Brilhante',price:22.90,base:false},
  {n:'212',name:'Forretress ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara Brilhante',price:3.00,base:false},
  {n:'213',name:'Toedscruel ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara Brilhante',price:9.78,base:false},
  {n:'214',name:'Espathra ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara Brilhante',price:7.90,base:false},
  {n:'215',name:'Alakazam ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara Brilhante',price:18.00,base:false},
  {n:'216',name:'Mew ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara Brilhante',price:89.00,base:false,important:true},
  {n:'217',name:'Gardevoir ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara Brilhante',price:39.00,base:false,important:true},
  {n:'218',name:'Glimmora ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara Brilhante',price:7.20,base:false},
  {n:'219',name:'Paldean Clodsire ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara Brilhante',price:7.00,base:false},
  {n:'220',name:'Noivern ex',type:'Dragão',color:'#3F51B5',rare:'Ultra Rara Brilhante',price:12.00,base:false},
  {n:'221',name:'Pidgeot ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara Brilhante',price:15.00,base:false},
  {n:'222',name:'Wigglytuff ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara Brilhante',price:14.89,base:false},
  {n:'223',name:'Squawkabilly ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara Brilhante',price:7.50,base:false},
  {n:'224',name:'Wugtrio',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:7.99,base:false},
  {n:'225',name:'Palafin',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:7.00,base:false},
  {n:'226',name:'Pawmi',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:9.49,base:false},
  {n:'227',name:'Clive',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:3.90,base:false},
  {n:'228',name:'Judge',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:17.00,base:false},
  {n:'229',name:'Nemona',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:6.00,base:false},
  {n:'230',name:'Paldean Student',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:4.90,base:false},
  {n:'231',name:'Paldean Student',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:4.50,base:false},
  {n:'232',name:'Mew ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:2000.00,base:false,important:true},
  {n:'233',name:'Gardevoir ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:349.90,base:false,important:true},
  {n:'234',name:'Charizard ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:499.99,base:false,important:true},
  {n:'235',name:'Arven',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:38.90,base:false,important:true},
  {n:'236',name:'Clive',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:60.00,base:false,important:true},
  {n:'237',name:'Iono',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:99.00,base:false,important:true},
  {n:'238',name:'Nemona',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:34.90,base:false},
  {n:'239',name:'Penny',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:41.90,base:false,important:true},
  {n:'240',name:'Wo-Chien ex',type:'Planta',color:'#4CAF50',rare:'Hiper Rara',price:32.00,base:false},
  {n:'241',name:'Chi-Yu ex',type:'Fogo',color:'#F44336',rare:'Hiper Rara',price:29.90,base:false,important:true},
  {n:'242',name:'Chien-Pao ex',type:'Aquático',color:'#2196F3',rare:'Hiper Rara',price:42.00,base:false,important:true},
  {n:'243',name:'Miraidon ex',type:'Raio',color:'#FFEB3B',rare:'Hiper Rara',price:35.00,base:false,important:true},
  {n:'244',name:'Ting-Lu ex',type:'Lutador',color:'#FF9800',rare:'Hiper Rara',price:29.75,base:false},
  {n:'245',name:'Koraidon ex',type:'Lutador',color:'#FF9800',rare:'Hiper Rara',price:59.90,base:false,important:true}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV4PT5 = CARDS_SV4PT5;