// SV6 — Twilight Masquerade (226 cartas)
// Lançamento EN: 2024/05/24
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV6 = [
  {n:'001',name:'Tangela',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.35,base:true},
  {n:'002',name:'Tangrowth',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.75,base:true},
  {n:'003',name:'Pinsir',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.81,base:true},
  {n:'004',name:'Spinarak',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.41,base:true},
  {n:'005',name:'Ariados',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.46,base:true},
  {n:'006',name:'Sunkern',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.35,base:true},
  {n:'007',name:'Sunflora',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.41,base:true},
  {n:'008',name:'Heracross',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.58,base:true},
  {n:'009',name:'Volbeat',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.87,base:true},
  {n:'010',name:'Illumise',type:'Planta',color:'#4CAF50',rare:'Comum',price:1.1,base:true},
  {n:'011',name:'Leafeon',type:'Planta',color:'#4CAF50',rare:'Incomum',price:1.22,base:true},
  {n:'012',name:'Phantump',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.46,base:true},
  {n:'013',name:'Trevenant',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.64,base:true},
  {n:'014',name:'Grookey',type:'Planta',color:'#4CAF50',rare:'Comum',price:1.1,base:true},
  {n:'015',name:'Thwackey',type:'Planta',color:'#4CAF50',rare:'Comum',price:2.2,base:true},
  {n:'016',name:'Rillaboom',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.7,base:true},
  {n:'017',name:'Applin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.81,base:true},
  {n:'018',name:'Dipplin',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.75,base:true},
  {n:'019',name:'Iron Leaves',type:'Planta',color:'#4CAF50',rare:'Rara',price:1.1,base:true},
  {n:'020',name:'Poltchageist',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.87,base:true},
  {n:'021',name:'Poltchageist',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.93,base:true},
  {n:'022',name:'Sinistcha',type:'Planta',color:'#4CAF50',rare:'Rara',price:1.16,base:true},
  {n:'023',name:'Sinistcha ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.54,base:true},
  {n:'024',name:'Teal Mask Ogerpon',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.7,base:true},
  {n:'025',name:'Teal Mask Ogerpon ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:22.27,base:true},
  {n:'026',name:'Vulpix',type:'Fogo',color:'#F44336',rare:'Comum',price:1.16,base:true},
  {n:'027',name:'Ninetales',type:'Fogo',color:'#F44336',rare:'Comum',price:0.93,base:true},
  {n:'028',name:'Slugma',type:'Fogo',color:'#F44336',rare:'Comum',price:0.58,base:true},
  {n:'029',name:'Magcargo ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:3.19,base:true},
  {n:'030',name:'Torkoal',type:'Fogo',color:'#F44336',rare:'Comum',price:1.22,base:true},
  {n:'031',name:'Chimchar',type:'Fogo',color:'#F44336',rare:'Comum',price:0.58,base:true},
  {n:'032',name:'Monferno',type:'Fogo',color:'#F44336',rare:'Comum',price:1.04,base:true},
  {n:'033',name:'Infernape',type:'Fogo',color:'#F44336',rare:'Rara',price:1.04,base:true},
  {n:'034',name:'Darumaka',type:'Fogo',color:'#F44336',rare:'Comum',price:0.3,base:true},
  {n:'035',name:'Darmanitan',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.41,base:true},
  {n:'036',name:'Litwick',type:'Fogo',color:'#F44336',rare:'Comum',price:0.87,base:true},
  {n:'037',name:'Lampent',type:'Fogo',color:'#F44336',rare:'Comum',price:0.7,base:true},
  {n:'038',name:'Chandelure',type:'Fogo',color:'#F44336',rare:'Rara',price:0.52,base:true},
  {n:'039',name:'Chi-Yu',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.87,base:true},
  {n:'040',name:'Hearthflame Mask Ogerpon ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:3.48,base:true},
  {n:'041',name:'Poliwag',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.58,base:true},
  {n:'042',name:'Poliwhirl',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.93,base:true},
  {n:'043',name:'Poliwrath',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.87,base:true},
  {n:'044',name:'Goldeen',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.58,base:true},
  {n:'045',name:'Seaking',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.52,base:true},
  {n:'046',name:'Jynx',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.52,base:true},
  {n:'047',name:'Corphish',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.3,base:true},
  {n:'048',name:'Crawdaunt',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.7,base:true},
  {n:'049',name:'Feebas',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.46,base:true},
  {n:'050',name:'Milotic',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.81,base:true},
  {n:'051',name:'Snorunt',type:'Aquático',color:'#2196F3',rare:'Comum',price:1.04,base:true},
  {n:'052',name:'Glalie',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.93,base:true},
  {n:'053',name:'Froslass',type:'Aquático',color:'#2196F3',rare:'Rara',price:1.51,base:true},
  {n:'054',name:'Glaceon',type:'Aquático',color:'#2196F3',rare:'Incomum',price:1.33,base:true},
  {n:'055',name:'Phione',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.7,base:true},
  {n:'056',name:'Froakie',type:'Aquático',color:'#2196F3',rare:'Comum',price:1.33,base:true},
  {n:'057',name:'Frogadier',type:'Aquático',color:'#2196F3',rare:'Comum',price:1.22,base:true},
  {n:'058',name:'Cramorant',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.81,base:true},
  {n:'059',name:'Finizen',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.41,base:true},
  {n:'060',name:'Palafin',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.87,base:true},
  {n:'061',name:'Palafin ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:3.02,base:true},
  {n:'062',name:'Iron Bundle',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.46,base:true},
  {n:'063',name:'Walking Wake',type:'Aquático',color:'#2196F3',rare:'Rara',price:1.16,base:true},
  {n:'064',name:'Wellspring Mask Ogerpon ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:5.63,base:true},
  {n:'065',name:'Zapdos',type:'Raio',color:'#FFEB3B',rare:'Rara',price:1.68,base:true},
  {n:'066',name:'Shinx',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.52,base:true},
  {n:'067',name:'Luxio',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.75,base:true},
  {n:'068',name:'Luxray ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:4.76,base:true},
  {n:'069',name:'Emolga',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.3,base:true},
  {n:'070',name:'Helioptile',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.3,base:true},
  {n:'071',name:'Heliolisk',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.75,base:true},
  {n:'072',name:'Morpeko',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.99,base:true},
  {n:'073',name:'Tadbulb',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.35,base:true},
  {n:'074',name:'Bellibolt',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.87,base:true},
  {n:'075',name:'Wattrel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.99,base:true},
  {n:'076',name:'Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.52,base:true},
  {n:'077',name:'Iron Thorns ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:3.42,base:true},
  {n:'078',name:'Clefairy',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:1.28,base:true},
  {n:'079',name:'Clefable',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:1.16,base:true},
  {n:'080',name:'Abra',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.81,base:true},
  {n:'081',name:'Kadabra',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:1.1,base:true},
  {n:'082',name:'Alakazam',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:1.91,base:true},
  {n:'083',name:'Girafarig',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:1.1,base:true},
  {n:'084',name:'Farigiraf',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.7,base:true},
  {n:'085',name:'Chimecho',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.75,base:true},
  {n:'086',name:'Flabébé',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.35,base:true},
  {n:'087',name:'Floette',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.46,base:true},
  {n:'088',name:'Florges',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.52,base:true},
  {n:'089',name:'Swirlix',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.87,base:true},
  {n:'090',name:'Slurpuff',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.99,base:true},
  {n:'091',name:'Sandygast',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:1.1,base:true},
  {n:'092',name:'Palossand',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.58,base:true},
  {n:'093',name:'Enamorus',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.41,base:true},
  {n:'094',name:'Scream Tail ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:3.71,base:true},
  {n:'095',name:'Munkidori',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:1.62,base:true},
  {n:'096',name:'Fezandipiti',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.58,base:true},
  {n:'097',name:'Sandshrew',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.3,base:true},
  {n:'098',name:'Sandslash',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.41,base:true},
  {n:'099',name:'Hisuian Growlithe',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.41,base:true},
  {n:'100',name:'Hisuian Arcanine',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.87,base:true},
  {n:'101',name:'Nosepass',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.52,base:true},
  {n:'102',name:'Probopass',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.46,base:true},
  {n:'103',name:'Timburr',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.3,base:true},
  {n:'104',name:'Gurdurr',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.7,base:true},
  {n:'105',name:'Conkeldurr',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.99,base:true},
  {n:'106',name:'Greninja ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:36.71,base:true},
  {n:'107',name:'Hawlucha',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.7,base:true},
  {n:'108',name:'Glimmet',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.3,base:true},
  {n:'109',name:'Glimmora',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.52,base:true},
  {n:'110',name:'Ting-Lu',type:'Lutador',color:'#FF9800',rare:'Rara',price:1.1,base:true},
  {n:'111',name:'Okidogi',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.93,base:true},
  {n:'112',name:'Cornerstone Mask Ogerpon ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:4.23,base:true},
  {n:'113',name:'Poochyena',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.3,base:true},
  {n:'114',name:'Mightyena',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.52,base:true},
  {n:'115',name:'Venipede',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.7,base:true},
  {n:'116',name:'Whirlipede',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.41,base:true},
  {n:'117',name:'Scolipede',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.93,base:true},
  {n:'118',name:'Brute Bonnet',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.93,base:true},
  {n:'119',name:'Skarmory',type:'Metal',color:'#78909C',rare:'Comum',price:0.75,base:true},
  {n:'120',name:'Aron',type:'Metal',color:'#78909C',rare:'Comum',price:0.7,base:true},
  {n:'121',name:'Lairon',type:'Metal',color:'#78909C',rare:'Comum',price:0.7,base:true},
  {n:'122',name:'Aggron',type:'Metal',color:'#78909C',rare:'Incomum',price:0.75,base:true},
  {n:'123',name:'Heatran',type:'Metal',color:'#78909C',rare:'Rara',price:0.93,base:true},
  {n:'124',name:'Varoom',type:'Metal',color:'#78909C',rare:'Comum',price:0.41,base:true},
  {n:'125',name:'Revavroom',type:'Metal',color:'#78909C',rare:'Incomum',price:0.35,base:true},
  {n:'126',name:'Applin',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.93,base:true},
  {n:'127',name:'Dipplin',type:'Dragão',color:'#3F51B5',rare:'Incomum',price:0.64,base:true},
  {n:'128',name:'Dreepy',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.93,base:true},
  {n:'129',name:'Drakloak',type:'Dragão',color:'#3F51B5',rare:'Comum',price:1.57,base:true},
  {n:'130',name:'Dragapult ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:8.58,base:true},
  {n:'131',name:'Tatsugiri',type:'Dragão',color:'#3F51B5',rare:'Incomum',price:1.04,base:true},
  {n:'132',name:'Farfetch\'d',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.93,base:true},
  {n:'133',name:'Chansey',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.22,base:true},
  {n:'134',name:'Blissey ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:3.31,base:true},
  {n:'135',name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.28,base:true},
  {n:'136',name:'Snorlax',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.39,base:true},
  {n:'137',name:'Aipom',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.3,base:true},
  {n:'138',name:'Ambipom',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.35,base:true},
  {n:'139',name:'Ducklett',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.35,base:true},
  {n:'140',name:'Swanna',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.35,base:true},
  {n:'141',name:'Bloodmoon Ursaluna ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:4.06,base:true},
  {n:'142',name:'Accompanying Flute',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.46,base:true},
  {n:'143',name:'Bug Catching Set',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.1,base:true},
  {n:'144',name:'Caretaker',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.35,base:true},
  {n:'145',name:'Carmine',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.93,base:true},
  {n:'146',name:'Community Center',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.64,base:true},
  {n:'147',name:'Cook',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.46,base:true},
  {n:'148',name:'Enhanced Hammer',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.87,base:true},
  {n:'149',name:'Festival Grounds',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.7,base:true},
  {n:'150',name:'Handheld Fan',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.57,base:true},
  {n:'151',name:'Hassel',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.1,base:true},
  {n:'152',name:'Hyper Aroma',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:3.07,base:false},
  {n:'153',name:'Jamming Tower',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.28,base:true},
  {n:'154',name:'Kieran',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.1,base:true},
  {n:'155',name:'Lana\'s Aid',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.62,base:true},
  {n:'156',name:'Love Ball',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.04,base:true},
  {n:'157',name:'Lucian',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.81,base:true},
  {n:'158',name:'Lucky Helmet',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.28,base:true},
  {n:'159',name:'Ogre\'s Mask',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.3,base:true},
  {n:'160',name:'Perrin',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.52,base:true},
  {n:'161',name:'Raifort',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.46,base:true},
  {n:'162',name:'Scoop Up Cyclone',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:3.07,base:false},
  {n:'163',name:'Secret Box',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:32.25,base:false},
  {n:'164',name:'Survival Brace',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:2.2,base:false},
  {n:'165',name:'Unfair Stamp',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:86.48,base:false,important:true},
  {n:'166',name:'Boomerang Energy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.99,base:true},
  {n:'167',name:'Legacy Energy',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:20.18,base:false},
  {n:'168',name:'Pinsir',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:102.25,base:false,important:true},
  {n:'169',name:'Sunflora',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:52.78,base:false,important:true},
  {n:'170',name:'Dipplin',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:78.59,base:false,important:true},
  {n:'171',name:'Poltchageist',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:36.54,base:false},
  {n:'172',name:'Torkoal',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:39.21,base:false},
  {n:'173',name:'Infernape',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:86.77,base:false,important:true},
  {n:'174',name:'Froslass',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:49.36,base:false},
  {n:'175',name:'Phione',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:80.74,base:false,important:true},
  {n:'176',name:'Cramorant',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:31.44,base:false},
  {n:'177',name:'Heliolisk',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:29.46,base:false},
  {n:'178',name:'Wattrel',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:32.19,base:false},
  {n:'179',name:'Chimecho',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:36.6,base:false},
  {n:'180',name:'Enamorus',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:37.7,base:false},
  {n:'181',name:'Hisuian Growlithe',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:199.64,base:false,important:true},
  {n:'182',name:'Probopass',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:30.33,base:false},
  {n:'183',name:'Timburr',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:38.57,base:false},
  {n:'184',name:'Lairon',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:35.67,base:false},
  {n:'185',name:'Applin',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada',price:74.53,base:false,important:true},
  {n:'186',name:'Tatsugiri',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada',price:135.84,base:false,important:true},
  {n:'187',name:'Chansey',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:344.23,base:false,important:true},
  {n:'188',name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:543.4,base:false,important:true},
  {n:'189',name:'Sinistcha ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:7.54,base:false},
  {n:'190',name:'Teal Mask Ogerpon ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:38.11,base:false},
  {n:'191',name:'Magcargo ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:9.28,base:false},
  {n:'192',name:'Hearthflame Mask Ogerpon ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:13.17,base:false},
  {n:'193',name:'Palafin ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:8.29,base:false},
  {n:'194',name:'Wellspring Mask Ogerpon ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:23.32,base:false},
  {n:'195',name:'Luxray ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:17.46,base:false},
  {n:'196',name:'Iron Thorns ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:15.08,base:false},
  {n:'197',name:'Scream Tail ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:16.36,base:false},
  {n:'198',name:'Greninja ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:145.64,base:false,important:true},
  {n:'199',name:'Cornerstone Mask Ogerpon ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:22.27,base:false},
  {n:'200',name:'Dragapult ex',type:'Dragão',color:'#3F51B5',rare:'Ultra Rara',price:89.9,base:false,important:true},
  {n:'201',name:'Blissey ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:20.76,base:false},
  {n:'202',name:'Bloodmoon Ursaluna ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:16.07,base:false},
  {n:'203',name:'Caretaker',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:4.93,base:false},
  {n:'204',name:'Carmine',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:31.73,base:false},
  {n:'205',name:'Hassel',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:11.19,base:false},
  {n:'206',name:'Kieran',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:21.29,base:false},
  {n:'207',name:'Lana\'s Aid',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:35.26,base:false},
  {n:'208',name:'Lucian',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8.47,base:false},
  {n:'209',name:'Perrin',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:29.75,base:false},
  {n:'210',name:'Sinistcha ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:191.52,base:false,important:true},
  {n:'211',name:'Teal Mask Ogerpon ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:163.62,base:false,important:true},
  {n:'212',name:'Hearthflame Mask Ogerpon ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:75.23,base:false,important:true},
  {n:'213',name:'Wellspring Mask Ogerpon ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:99.82,base:false,important:true},
  {n:'214',name:'Greninja ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:2324.41,base:false,important:true},
  {n:'215',name:'Cornerstone Mask Ogerpon ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:93.09,base:false,important:true},
  {n:'216',name:'Bloodmoon Ursaluna ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:284.55,base:false,important:true},
  {n:'217',name:'Carmine',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:419.22,base:false,important:true},
  {n:'218',name:'Kieran',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:197.26,base:false,important:true},
  {n:'219',name:'Lana\'s Aid',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:232.75,base:false,important:true},
  {n:'220',name:'Perrin',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:1079.44,base:false,important:true},
  {n:'221',name:'Teal Mask Ogerpon ex',type:'Planta',color:'#4CAF50',rare:'Hiper Rara',price:63.63,base:false,important:true},
  {n:'222',name:'Bloodmoon Ursaluna ex',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:58.41,base:false,important:true},
  {n:'223',name:'Buddy-Buddy Poffin',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:83.23,base:false,important:true},
  {n:'224',name:'Enhanced Hammer',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:36.83,base:false},
  {n:'225',name:'Rescue Board',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:12.82,base:false},
  {n:'226',name:'Luminous Energy',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:33.41,base:false}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV6 = CARDS_SV6;