// SV1 — Scarlet & Violet (258 cartas)
// Lançamento EN: 2023/03/31
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV1 = [
  {n:'001',name:'Pineco',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.52,base:true},
  {n:'002',name:'Heracross',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.64,base:true},
  {n:'003',name:'Shroomish',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.46,base:true},
  {n:'004',name:'Breloom',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.64,base:true},
  {n:'005',name:'Cacnea',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.81,base:true},
  {n:'006',name:'Cacturne',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.3,base:true},
  {n:'007',name:'Tropius',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.64,base:true},
  {n:'008',name:'Scatterbug',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.99,base:true},
  {n:'009',name:'Spewpa',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.7,base:true},
  {n:'010',name:'Vivillon',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.75,base:true},
  {n:'011',name:'Skiddo',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.52,base:true},
  {n:'012',name:'Gogoat',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.87,base:true},
  {n:'013',name:'Sprigatito',type:'Planta',color:'#4CAF50',rare:'Comum',price:1.28,base:true},
  {n:'014',name:'Floragato',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.75,base:true},
  {n:'015',name:'Meowscarada',type:'Planta',color:'#4CAF50',rare:'Rara',price:1.16,base:true},
  {n:'016',name:'Tarountula',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.81,base:true},
  {n:'017',name:'Tarountula',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.52,base:true},
  {n:'018',name:'Tarountula',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.64,base:true},
  {n:'019',name:'Spidops ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:3.48,base:true},
  {n:'020',name:'Smoliv',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.99,base:true},
  {n:'021',name:'Smoliv',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.81,base:true},
  {n:'022',name:'Dolliv',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.58,base:true},
  {n:'023',name:'Arboliva',type:'Planta',color:'#4CAF50',rare:'Rara',price:1.22,base:true},
  {n:'024',name:'Toedscool',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.46,base:true},
  {n:'025',name:'Toedscool',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.41,base:true},
  {n:'026',name:'Toedscruel',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.35,base:true},
  {n:'027',name:'Capsakid',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.81,base:true},
  {n:'028',name:'Capsakid',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.93,base:true},
  {n:'029',name:'Scovillain',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.81,base:true},
  {n:'030',name:'Growlithe',type:'Fogo',color:'#F44336',rare:'Comum',price:0.87,base:true},
  {n:'031',name:'Growlithe',type:'Fogo',color:'#F44336',rare:'Comum',price:0.93,base:true},
  {n:'032',name:'Arcanine ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:7.02,base:true},
  {n:'033',name:'Houndour',type:'Fogo',color:'#F44336',rare:'Comum',price:0.3,base:true},
  {n:'034',name:'Houndoom',type:'Fogo',color:'#F44336',rare:'Comum',price:1.16,base:true},
  {n:'035',name:'Torkoal',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.58,base:true},
  {n:'036',name:'Fuecoco',type:'Fogo',color:'#F44336',rare:'Comum',price:0.7,base:true},
  {n:'037',name:'Crocalor',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.75,base:true},
  {n:'038',name:'Skeledirge',type:'Fogo',color:'#F44336',rare:'Rara',price:0.93,base:true},
  {n:'039',name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.75,base:true},
  {n:'040',name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.7,base:true},
  {n:'041',name:'Armarouge',type:'Fogo',color:'#F44336',rare:'Rara',price:1.51,base:true},
  {n:'042',name:'Slowpoke',type:'Aquático',color:'#2196F3',rare:'Comum',price:1.04,base:true},
  {n:'043',name:'Slowbro',type:'Aquático',color:'#2196F3',rare:'Rara',price:1.91,base:true},
  {n:'044',name:'Magikarp',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.99,base:true},
  {n:'045',name:'Gyarados ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:9.74,base:true},
  {n:'046',name:'Buizel',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.7,base:true},
  {n:'047',name:'Floatzel',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.41,base:true},
  {n:'048',name:'Alomomola',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.75,base:true},
  {n:'049',name:'Clauncher',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.35,base:true},
  {n:'050',name:'Clawitzer',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.41,base:true},
  {n:'051',name:'Bruxish',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.7,base:true},
  {n:'052',name:'Quaxly',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.64,base:true},
  {n:'053',name:'Quaxwell',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.52,base:true},
  {n:'054',name:'Quaquaval',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.99,base:true},
  {n:'055',name:'Wiglett',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.52,base:true},
  {n:'056',name:'Wiglett',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.64,base:true},
  {n:'057',name:'Wugtrio',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.7,base:true},
  {n:'058',name:'Cetoddle',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.46,base:true},
  {n:'059',name:'Cetoddle',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.41,base:true},
  {n:'060',name:'Cetitan',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.3,base:true},
  {n:'061',name:'Dondozo',type:'Aquático',color:'#2196F3',rare:'Rara',price:1.04,base:true},
  {n:'062',name:'Tatsugiri',type:'Aquático',color:'#2196F3',rare:'Incomum',price:1.1,base:true},
  {n:'063',name:'Magnemite',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.3,base:true},
  {n:'064',name:'Magneton',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.46,base:true},
  {n:'065',name:'Magnezone ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:3.71,base:true},
  {n:'066',name:'Mareep',type:'Raio',color:'#FFEB3B',rare:'Comum',price:1.33,base:true},
  {n:'067',name:'Flaaffy',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:1.04,base:true},
  {n:'068',name:'Pachirisu',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.7,base:true},
  {n:'069',name:'Rotom',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.52,base:true},
  {n:'070',name:'Rotom',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.46,base:true},
  {n:'071',name:'Toxel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.52,base:true},
  {n:'072',name:'Toxtricity',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.58,base:true},
  {n:'073',name:'Pawmi',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.81,base:true},
  {n:'074',name:'Pawmi',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.46,base:true},
  {n:'075',name:'Pawmo',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.75,base:true},
  {n:'076',name:'Pawmot',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.99,base:true},
  {n:'077',name:'Wattrel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.81,base:true},
  {n:'078',name:'Wattrel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.58,base:true},
  {n:'079',name:'Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.41,base:true},
  {n:'080',name:'Miraidon',type:'Raio',color:'#FFEB3B',rare:'Rara',price:1.04,base:true},
  {n:'081',name:'Miraidon ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:3.77,base:true},
  {n:'082',name:'Drowzee',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.41,base:true},
  {n:'083',name:'Hypno',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.52,base:true},
  {n:'084',name:'Ralts',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.64,base:true},
  {n:'085',name:'Kirlia',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.81,base:true},
  {n:'086',name:'Gardevoir ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:4.47,base:true},
  {n:'087',name:'Shuppet',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.46,base:true},
  {n:'088',name:'Banette ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:3.65,base:true},
  {n:'089',name:'Drifloon',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.58,base:true},
  {n:'090',name:'Drifblim',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.41,base:true},
  {n:'091',name:'Flabébé',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.52,base:true},
  {n:'092',name:'Floette',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.41,base:true},
  {n:'093',name:'Florges',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.52,base:true},
  {n:'094',name:'Dedenne',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.58,base:true},
  {n:'095',name:'Dedenne',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:1.04,base:true},
  {n:'096',name:'Klefki',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:1.51,base:true},
  {n:'097',name:'Fidough',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.58,base:true},
  {n:'098',name:'Fidough',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.93,base:true},
  {n:'099',name:'Dachsbun',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.64,base:true},
  {n:'100',name:'Flittle',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.35,base:true},
  {n:'101',name:'Flittle',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.3,base:true},
  {n:'102',name:'Flittle',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.46,base:true},
  {n:'103',name:'Espathra',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.3,base:true},
  {n:'104',name:'Greavard',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.64,base:true},
  {n:'105',name:'Greavard',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.35,base:true},
  {n:'106',name:'Houndstone',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.93,base:true},
  {n:'107',name:'Mankey',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.64,base:true},
  {n:'108',name:'Primeape',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.64,base:true},
  {n:'109',name:'Annihilape',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.75,base:true},
  {n:'110',name:'Meditite',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.52,base:true},
  {n:'111',name:'Medicham',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.64,base:true},
  {n:'112',name:'Riolu',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.75,base:true},
  {n:'113',name:'Riolu',type:'Lutador',color:'#FF9800',rare:'Comum',price:1.16,base:true},
  {n:'114',name:'Lucario',type:'Lutador',color:'#FF9800',rare:'Incomum',price:1.16,base:true},
  {n:'115',name:'Sandile',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.75,base:true},
  {n:'116',name:'Krokorok',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.58,base:true},
  {n:'117',name:'Krookodile',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.46,base:true},
  {n:'118',name:'Hawlucha',type:'Lutador',color:'#FF9800',rare:'Rara',price:1.68,base:true},
  {n:'119',name:'Silicobra',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.7,base:true},
  {n:'120',name:'Sandaconda',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.35,base:true},
  {n:'121',name:'Stonjourner',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.87,base:true},
  {n:'122',name:'Klawf',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.93,base:true},
  {n:'123',name:'Great Tusk ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:3.65,base:true},
  {n:'124',name:'Koraidon',type:'Lutador',color:'#FF9800',rare:'Rara',price:1.1,base:true},
  {n:'125',name:'Koraidon ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:3.77,base:true},
  {n:'126',name:'Grimer',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.75,base:true},
  {n:'127',name:'Muk',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.52,base:true},
  {n:'128',name:'Seviper',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.41,base:true},
  {n:'129',name:'Spiritomb',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.35,base:true},
  {n:'130',name:'Croagunk',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.52,base:true},
  {n:'131',name:'Toxicroak ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:3.19,base:true},
  {n:'132',name:'Pawniard',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.58,base:true},
  {n:'133',name:'Bisharp',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.58,base:true},
  {n:'134',name:'Kingambit',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.99,base:true},
  {n:'135',name:'Maschiff',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.58,base:true},
  {n:'136',name:'Maschiff',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.75,base:true},
  {n:'137',name:'Mabosstiff',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.52,base:true},
  {n:'138',name:'Bombirdier',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.3,base:true},
  {n:'139',name:'Forretress',type:'Metal',color:'#78909C',rare:'Incomum',price:0.46,base:true},
  {n:'140',name:'Varoom',type:'Metal',color:'#78909C',rare:'Comum',price:0.46,base:true},
  {n:'141',name:'Varoom',type:'Metal',color:'#78909C',rare:'Comum',price:0.64,base:true},
  {n:'142',name:'Revavroom',type:'Metal',color:'#78909C',rare:'Rara',price:0.81,base:true},
  {n:'143',name:'Iron Treads ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:3.25,base:true},
  {n:'144',name:'Chansey',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.75,base:true},
  {n:'145',name:'Blissey',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.87,base:true},
  {n:'146',name:'Zangoose',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.64,base:true},
  {n:'147',name:'Zangoose',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.81,base:true},
  {n:'148',name:'Starly',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.87,base:true},
  {n:'149',name:'Staravia',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.41,base:true},
  {n:'150',name:'Staraptor',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.7,base:true},
  {n:'151',name:'Skwovet',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.87,base:true},
  {n:'152',name:'Greedent',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.64,base:true},
  {n:'153',name:'Indeedee',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.99,base:true},
  {n:'154',name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.75,base:true},
  {n:'155',name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.87,base:true},
  {n:'156',name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.81,base:true},
  {n:'157',name:'Oinkologne',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.75,base:true},
  {n:'158',name:'Oinkologne ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:4,base:true},
  {n:'159',name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.57,base:true},
  {n:'160',name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.45,base:true},
  {n:'161',name:'Maushold',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.16,base:true},
  {n:'162',name:'Squawkabilly',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.93,base:true},
  {n:'163',name:'Cyclizar',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.3,base:true},
  {n:'164',name:'Cyclizar',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.64,base:true},
  {n:'165',name:'Flamigo',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.81,base:true},
  {n:'166',name:'Arven',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.33,base:true},
  {n:'167',name:'Beach Court',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.99,base:true},
  {n:'168',name:'Crushing Hammer',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.99,base:true},
  {n:'169',name:'Defiance Band',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.28,base:true},
  {n:'170',name:'Electric Generator',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.22,base:true},
  {n:'171',name:'Energy Retrieval',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.57,base:true},
  {n:'172',name:'Energy Search',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.22,base:true},
  {n:'173',name:'Energy Switch',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.45,base:true},
  {n:'174',name:'Exp. Share',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.22,base:true},
  {n:'175',name:'Jacq',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.22,base:true},
  {n:'176',name:'Judge',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.16,base:true},
  {n:'177',name:'Katy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.7,base:true},
  {n:'178',name:'Mesagoza',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.93,base:true},
  {n:'179',name:'Miriam',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.93,base:true},
  {n:'180',name:'Nemona',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.46,base:true},
  {n:'181',name:'Nest Ball',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.16,base:true},
  {n:'182',name:'Pal Pad',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.33,base:true},
  {n:'183',name:'Penny',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.16,base:true},
  {n:'184',name:'Picnic Basket',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.04,base:true},
  {n:'185',name:'Poké Ball',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.87,base:true},
  {n:'186',name:'Pokégear 3.0',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.91,base:true},
  {n:'187',name:'Pokémon Catcher',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.93,base:true},
  {n:'188',name:'Potion',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.7,base:true},
  {n:'189',name:'Professor\'s Research (Professor Sada)',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:1.04,base:true},
  {n:'190',name:'Professor\'s Research (Professor Turo)',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:1.16,base:true},
  {n:'191',name:'Rare Candy',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.16,base:true},
  {n:'192',name:'Rock Chestplate',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.75,base:true},
  {n:'193',name:'Rocky Helmet',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.93,base:true},
  {n:'194',name:'Switch',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.87,base:true},
  {n:'195',name:'Team Star Grunt',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.75,base:true},
  {n:'196',name:'Ultra Ball',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.99,base:true},
  {n:'197',name:'Vitality Band',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.64,base:true},
  {n:'198',name:'Youngster',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.64,base:true},
  {n:'199',name:'Tarountula',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:85.78,base:false,important:true},
  {n:'200',name:'Dolliv',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:46.05,base:false},
  {n:'201',name:'Toedscool',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:34.16,base:false},
  {n:'202',name:'Scovillain',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:38.4,base:false},
  {n:'203',name:'Armarouge',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:105.85,base:false,important:true},
  {n:'204',name:'Slowpoke',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:276.37,base:false,important:true},
  {n:'205',name:'Clauncher',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:48.31,base:false},
  {n:'206',name:'Wiglett',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:174.58,base:false,important:true},
  {n:'207',name:'Dondozo',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:91.12,base:false,important:true},
  {n:'208',name:'Pachirisu',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:122.26,base:false,important:true},
  {n:'209',name:'Pawmot',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:62.76,base:false,important:true},
  {n:'210',name:'Drowzee',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:416.79,base:false,important:true},
  {n:'211',name:'Ralts',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:319.64,base:false,important:true},
  {n:'212',name:'Kirlia',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:309.66,base:false,important:true},
  {n:'213',name:'Fidough',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:148.77,base:false,important:true},
  {n:'214',name:'Greavard',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:142.74,base:false,important:true},
  {n:'215',name:'Riolu',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:245.4,base:false,important:true},
  {n:'216',name:'Sandile',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:35.67,base:false},
  {n:'217',name:'Klawf',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:33.87,base:false},
  {n:'218',name:'Mabosstiff',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:47.21,base:false},
  {n:'219',name:'Bombirdier',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:31.84,base:false},
  {n:'220',name:'Kingambit',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:62.35,base:false,important:true},
  {n:'221',name:'Starly',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:84.27,base:false,important:true},
  {n:'222',name:'Skwovet',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:49.94,base:false},
  {n:'223',name:'Spidops ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:7.08,base:false},
  {n:'224',name:'Arcanine ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:93.5,base:false,important:true},
  {n:'225',name:'Gyarados ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:67.16,base:false,important:true},
  {n:'226',name:'Magnezone ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:9.22,base:false},
  {n:'227',name:'Miraidon ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:17.4,base:false},
  {n:'228',name:'Gardevoir ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:27.78,base:false},
  {n:'229',name:'Banette ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:11.48,base:false},
  {n:'230',name:'Great Tusk ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:6.79,base:false},
  {n:'231',name:'Koraidon ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:10.5,base:false},
  {n:'232',name:'Toxicroak ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:10.5,base:false},
  {n:'233',name:'Iron Treads ex',type:'Metal',color:'#78909C',rare:'Ultra Rara',price:6.61,base:false},
  {n:'234',name:'Oinkologne ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8.18,base:false},
  {n:'235',name:'Arven',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:16.36,base:false},
  {n:'236',name:'Jacq',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:12.06,base:false},
  {n:'237',name:'Katy',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:14.15,base:false},
  {n:'238',name:'Miriam',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:35.09,base:false},
  {n:'239',name:'Penny',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:25.11,base:false},
  {n:'240',name:'Professor\'s Research (Professor Sada)',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:16.7,base:false},
  {n:'241',name:'Professor\'s Research (Professor Turo)',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:10.9,base:false},
  {n:'242',name:'Team Star Grunt',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8.76,base:false},
  {n:'243',name:'Spidops ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:68.03,base:false,important:true},
  {n:'244',name:'Miraidon ex',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada Especial',price:173.19,base:false,important:true},
  {n:'245',name:'Gardevoir ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:505.93,base:false,important:true},
  {n:'246',name:'Great Tusk ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:78.13,base:false,important:true},
  {n:'247',name:'Koraidon ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:140.48,base:false,important:true},
  {n:'248',name:'Iron Treads ex',type:'Metal',color:'#78909C',rare:'Rara Ilustrada Especial',price:38.8,base:false},
  {n:'249',name:'Arven',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:34.92,base:false},
  {n:'250',name:'Jacq',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:27.14,base:false}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV1 = CARDS_SV1;