// SV3 — Obsidian Flames (230 cartas)
// Lançamento EN: 2023/08/11
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV3 = [
  {n:'001',name:'Oddish',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.7,base:true},
  {n:'002',name:'Gloom',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.87,base:true},
  {n:'003',name:'Bellossom',type:'Planta',color:'#4CAF50',rare:'Incomum',price:1.45,base:true},
  {n:'004',name:'Scyther',type:'Planta',color:'#4CAF50',rare:'Comum',price:1.04,base:true},
  {n:'005',name:'Shuckle',type:'Planta',color:'#4CAF50',rare:'Comum',price:1.22,base:true},
  {n:'006',name:'Surskit',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.58,base:true},
  {n:'007',name:'Masquerain',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.7,base:true},
  {n:'008',name:'Combee',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.87,base:true},
  {n:'009',name:'Foongus',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.64,base:true},
  {n:'010',name:'Amoonguss',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.75,base:true},
  {n:'011',name:'Phantump',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.52,base:true},
  {n:'012',name:'Trevenant',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.52,base:true},
  {n:'013',name:'Rowlet',type:'Planta',color:'#4CAF50',rare:'Comum',price:1.1,base:true},
  {n:'014',name:'Dartrix',type:'Planta',color:'#4CAF50',rare:'Incomum',price:1.22,base:true},
  {n:'015',name:'Decidueye ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:5.57,base:true},
  {n:'016',name:'Bounsweet',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.81,base:true},
  {n:'017',name:'Steenee',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.64,base:true},
  {n:'018',name:'Tsareena',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.99,base:true},
  {n:'019',name:'Smoliv',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.3,base:true},
  {n:'020',name:'Dolliv',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.87,base:true},
  {n:'021',name:'Arboliva',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.7,base:true},
  {n:'022',name:'Toedscruel ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:4.12,base:true},
  {n:'023',name:'Capsakid',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.64,base:true},
  {n:'024',name:'Capsakid',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.87,base:true},
  {n:'025',name:'Scovillain',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.93,base:true},
  {n:'026',name:'Charmander',type:'Fogo',color:'#F44336',rare:'Comum',price:1.45,base:true},
  {n:'027',name:'Charmeleon',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.75,base:true},
  {n:'028',name:'Vulpix',type:'Fogo',color:'#F44336',rare:'Comum',price:0.52,base:true},
  {n:'029',name:'Ninetales',type:'Fogo',color:'#F44336',rare:'Incomum',price:1.22,base:true},
  {n:'030',name:'Entei',type:'Fogo',color:'#F44336',rare:'Rara',price:1.1,base:true},
  {n:'031',name:'Numel',type:'Fogo',color:'#F44336',rare:'Comum',price:0.35,base:true},
  {n:'032',name:'Camerupt',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.64,base:true},
  {n:'033',name:'Victini ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:6.5,base:true},
  {n:'034',name:'Darumaka',type:'Fogo',color:'#F44336',rare:'Comum',price:0.46,base:true},
  {n:'035',name:'Darmanitan',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.41,base:true},
  {n:'036',name:'Litwick',type:'Fogo',color:'#F44336',rare:'Comum',price:0.46,base:true},
  {n:'037',name:'Lampent',type:'Fogo',color:'#F44336',rare:'Comum',price:0.81,base:true},
  {n:'038',name:'Chandelure',type:'Fogo',color:'#F44336',rare:'Incomum',price:1.16,base:true},
  {n:'039',name:'Heatmor',type:'Fogo',color:'#F44336',rare:'Comum',price:0.7,base:true},
  {n:'040',name:'Larvesta',type:'Fogo',color:'#F44336',rare:'Comum',price:0.99,base:true},
  {n:'041',name:'Volcarona',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.52,base:true},
  {n:'042',name:'Eiscue ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:5.51,base:true},
  {n:'043',name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.99,base:true},
  {n:'044',name:'Armarouge',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.52,base:true},
  {n:'045',name:'Lapras',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.93,base:true},
  {n:'046',name:'Carvanha',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.58,base:true},
  {n:'047',name:'Sharpedo',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.81,base:true},
  {n:'048',name:'Buizel',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.3,base:true},
  {n:'049',name:'Floatzel',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.3,base:true},
  {n:'050',name:'Tympole',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.58,base:true},
  {n:'051',name:'Palpitoad',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.93,base:true},
  {n:'052',name:'Seismitoad',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.81,base:true},
  {n:'053',name:'Cubchoo',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.75,base:true},
  {n:'054',name:'Beartic',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.35,base:true},
  {n:'055',name:'Cryogonal',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.75,base:true},
  {n:'056',name:'Froakie',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.75,base:true},
  {n:'057',name:'Frogadier',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.75,base:true},
  {n:'058',name:'Wiglett',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.7,base:true},
  {n:'059',name:'Wugtrio',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.75,base:true},
  {n:'060',name:'Finizen',type:'Aquático',color:'#2196F3',rare:'Comum',price:1.28,base:true},
  {n:'061',name:'Finizen',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.7,base:true},
  {n:'062',name:'Palafin',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.7,base:true},
  {n:'063',name:'Magnemite',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.46,base:true},
  {n:'064',name:'Magneton',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.81,base:true},
  {n:'065',name:'Magnezone',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.81,base:true},
  {n:'066',name:'Tyranitar ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:8.35,base:true},
  {n:'067',name:'Tynamo',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.58,base:true},
  {n:'068',name:'Eelektrik',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.7,base:true},
  {n:'069',name:'Eelektross',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.87,base:true},
  {n:'070',name:'Thundurus',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.87,base:true},
  {n:'071',name:'Toxel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.81,base:true},
  {n:'072',name:'Toxtricity',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.7,base:true},
  {n:'073',name:'Pawmot ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:4.12,base:true},
  {n:'074',name:'Tadbulb',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.46,base:true},
  {n:'075',name:'Tadbulb',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.52,base:true},
  {n:'076',name:'Tadbulb',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.75,base:true},
  {n:'077',name:'Bellibolt',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:1.1,base:true},
  {n:'078',name:'Bellibolt',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.99,base:true},
  {n:'079',name:'Miraidon ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:5.68,base:true},
  {n:'080',name:'Cleffa',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:1.91,base:true},
  {n:'081',name:'Clefairy',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:1.62,base:true},
  {n:'082',name:'Clefable ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:6.67,base:true},
  {n:'083',name:'Togepi',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.99,base:true},
  {n:'084',name:'Togetic',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.75,base:true},
  {n:'085',name:'Togekiss',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:1.1,base:true},
  {n:'086',name:'Espeon',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:1.57,base:true},
  {n:'087',name:'Snubbull',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.7,base:true},
  {n:'088',name:'Granbull',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.64,base:true},
  {n:'089',name:'Mawile',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.75,base:true},
  {n:'090',name:'Spoink',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.64,base:true},
  {n:'091',name:'Grumpig',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.46,base:true},
  {n:'092',name:'Lunatone',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.7,base:true},
  {n:'093',name:'Solrock',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.46,base:true},
  {n:'094',name:'Baltoy',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.52,base:true},
  {n:'095',name:'Claydol',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.99,base:true},
  {n:'096',name:'Vespiquen ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:4.64,base:true},
  {n:'097',name:'Sinistea',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:1.33,base:true},
  {n:'098',name:'Polteageist',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.75,base:true},
  {n:'099',name:'Greavard',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.93,base:true},
  {n:'100',name:'Greavard',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.75,base:true},
  {n:'101',name:'Houndstone',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.46,base:true},
  {n:'102',name:'Houndstone ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:4.23,base:true},
  {n:'103',name:'Diglett',type:'Lutador',color:'#FF9800',rare:'Comum',price:1.1,base:true},
  {n:'104',name:'Dugtrio',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.58,base:true},
  {n:'105',name:'Larvitar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.3,base:true},
  {n:'106',name:'Pupitar',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.7,base:true},
  {n:'107',name:'Nosepass',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.81,base:true},
  {n:'108',name:'Barboach',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.52,base:true},
  {n:'109',name:'Whiscash',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.75,base:true},
  {n:'110',name:'Bonsly',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.93,base:true},
  {n:'111',name:'Drilbur',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.87,base:true},
  {n:'112',name:'Stunfisk',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.58,base:true},
  {n:'113',name:'Diggersby',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.41,base:true},
  {n:'114',name:'Crabrawler',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.58,base:true},
  {n:'115',name:'Crabominable',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.35,base:true},
  {n:'116',name:'Rockruff',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.87,base:true},
  {n:'117',name:'Lycanroc',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.81,base:true},
  {n:'118',name:'Toedscool',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.35,base:true},
  {n:'119',name:'Toedscruel',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.41,base:true},
  {n:'120',name:'Klawf ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:5.57,base:true},
  {n:'121',name:'Glimmet',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.64,base:true},
  {n:'122',name:'Glimmet',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.41,base:true},
  {n:'123',name:'Glimmora ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:5.28,base:true},
  {n:'124',name:'Koraidon ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:4.7,base:true},
  {n:'125',name:'Charizard ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:31.32,base:true},
  {n:'126',name:'Paldean Wooper',type:'Sombrio',color:'#607D8B',rare:'Comum',price:1.22,base:true},
  {n:'127',name:'Paldean Wooper',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.87,base:true},
  {n:'128',name:'Paldean Clodsire',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:1.33,base:true},
  {n:'129',name:'Paldean Clodsire',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:1.39,base:true},
  {n:'130',name:'Umbreon',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:1.74,base:true},
  {n:'131',name:'Houndour',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.46,base:true},
  {n:'132',name:'Houndour',type:'Sombrio',color:'#607D8B',rare:'Comum',price:1.04,base:true},
  {n:'133',name:'Houndoom',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.93,base:true},
  {n:'134',name:'Houndoom ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:6.67,base:true},
  {n:'135',name:'Absol ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:6.03,base:true},
  {n:'136',name:'Darkrai',type:'Sombrio',color:'#607D8B',rare:'Rara',price:1.04,base:true},
  {n:'137',name:'Inkay',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.81,base:true},
  {n:'138',name:'Malamar',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.7,base:true},
  {n:'139',name:'Salandit',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.64,base:true},
  {n:'140',name:'Salazzle',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.7,base:true},
  {n:'141',name:'Scizor',type:'Metal',color:'#78909C',rare:'Rara',price:1.28,base:true},
  {n:'142',name:'Skarmory',type:'Metal',color:'#78909C',rare:'Incomum',price:0.87,base:true},
  {n:'143',name:'Mawile',type:'Metal',color:'#78909C',rare:'Incomum',price:0.7,base:true},
  {n:'144',name:'Bronzor',type:'Metal',color:'#78909C',rare:'Comum',price:1.22,base:true},
  {n:'145',name:'Bronzong',type:'Metal',color:'#78909C',rare:'Incomum',price:0.35,base:true},
  {n:'146',name:'Probopass',type:'Metal',color:'#78909C',rare:'Incomum',price:0.81,base:true},
  {n:'147',name:'Excadrill',type:'Metal',color:'#78909C',rare:'Incomum',price:0.58,base:true},
  {n:'148',name:'Pawniard',type:'Metal',color:'#78909C',rare:'Comum',price:0.58,base:true},
  {n:'149',name:'Bisharp',type:'Metal',color:'#78909C',rare:'Comum',price:0.52,base:true},
  {n:'150',name:'Kingambit',type:'Metal',color:'#78909C',rare:'Incomum',price:0.7,base:true},
  {n:'151',name:'Togedemaru',type:'Metal',color:'#78909C',rare:'Comum',price:0.35,base:true},
  {n:'152',name:'Meltan',type:'Metal',color:'#78909C',rare:'Comum',price:0.7,base:true},
  {n:'153',name:'Melmetal ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:5.28,base:true},
  {n:'154',name:'Varoom',type:'Metal',color:'#78909C',rare:'Comum',price:0.7,base:true},
  {n:'155',name:'Varoom',type:'Metal',color:'#78909C',rare:'Comum',price:0.64,base:true},
  {n:'156',name:'Revavroom ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:4.87,base:true},
  {n:'157',name:'Dratini',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.99,base:true},
  {n:'158',name:'Dragonair',type:'Dragão',color:'#3F51B5',rare:'Incomum',price:1.22,base:true},
  {n:'159',name:'Dragonite ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:16.01,base:true},
  {n:'160',name:'Altaria',type:'Dragão',color:'#3F51B5',rare:'Incomum',price:1.04,base:true},
  {n:'161',name:'Drampa',type:'Dragão',color:'#3F51B5',rare:'Incomum',price:0.93,base:true},
  {n:'162',name:'Pidgey',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.33,base:true},
  {n:'163',name:'Pidgeotto',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.22,base:true},
  {n:'164',name:'Pidgeot ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:9.34,base:true},
  {n:'165',name:'Kangaskhan',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.93,base:true},
  {n:'166',name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.22,base:true},
  {n:'167',name:'Zigzagoon',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.7,base:true},
  {n:'168',name:'Linoone',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.35,base:true},
  {n:'169',name:'Swablu',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.87,base:true},
  {n:'170',name:'Lillipup',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.16,base:true},
  {n:'171',name:'Herdier',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.7,base:true},
  {n:'172',name:'Stoutland',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.81,base:true},
  {n:'173',name:'Audino',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.1,base:true},
  {n:'174',name:'Bouffalant',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.46,base:true},
  {n:'175',name:'Bunnelby',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.35,base:true},
  {n:'176',name:'Yungoos',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.75,base:true},
  {n:'177',name:'Gumshoos',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.46,base:true},
  {n:'178',name:'Skwovet',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.7,base:true},
  {n:'179',name:'Greedent ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:4.93,base:true},
  {n:'180',name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.33,base:true},
  {n:'181',name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.16,base:true},
  {n:'182',name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.81,base:true},
  {n:'183',name:'Oinkologne',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.81,base:true},
  {n:'184',name:'Oinkologne',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.75,base:true},
  {n:'185',name:'Flamigo',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.58,base:true},
  {n:'186',name:'Arven',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.8,base:true},
  {n:'187',name:'Brassius',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.93,base:true},
  {n:'188',name:'Geeta',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.64,base:true},
  {n:'189',name:'Letter of Encouragement',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.99,base:true},
  {n:'190',name:'Ortega',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.7,base:true},
  {n:'191',name:'Patrol Cap',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.87,base:true},
  {n:'192',name:'Pokémon League Headquarters',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.99,base:true},
  {n:'193',name:'Poppy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:1.22,base:true},
  {n:'194',name:'Ryme',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.75,base:true},
  {n:'195',name:'Team Star Grunt',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.93,base:true},
  {n:'196',name:'Town Store',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:1.22,base:true},
  {n:'197',name:'Vengeful Punch',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.93,base:true},
  {n:'198',name:'Gloom',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:164.37,base:false,important:true},
  {n:'199',name:'Ninetales',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:264.65,base:false,important:true},
  {n:'200',name:'Palafin',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:36.95,base:false},
  {n:'201',name:'Bellibolt',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:36.31,base:false},
  {n:'202',name:'Cleffa',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:251.6,base:false,important:true},
  {n:'203',name:'Larvitar',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:39.5,base:false},
  {n:'204',name:'Houndour',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:67.45,base:false,important:true},
  {n:'205',name:'Scizor',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:114.38,base:false,important:true},
  {n:'206',name:'Varoom',type:'Metal',color:'#78909C',rare:'Rara Ilustrada',price:18.15,base:false},
  {n:'207',name:'Pidgey',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:126.5,base:false,important:true},
  {n:'208',name:'Pidgeotto',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:69.08,base:false,important:true},
  {n:'209',name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:84.85,base:false,important:true},
  {n:'210',name:'Eiscue ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:11.66,base:false},
  {n:'211',name:'Tyranitar ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:35.26,base:false},
  {n:'212',name:'Vespiquen ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:7.48,base:false},
  {n:'213',name:'Glimmora ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:6.09,base:false},
  {n:'214',name:'Absol ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:16.88,base:false},
  {n:'215',name:'Charizard ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:133.34,base:false,important:true},
  {n:'216',name:'Revavroom ex',type:'Metal',color:'#78909C',rare:'Ultra Rara',price:5.74,base:false},
  {n:'217',name:'Pidgeot ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:11.89,base:false},
  {n:'218',name:'Geeta',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:6.73,base:false},
  {n:'219',name:'Ortega',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:6.5,base:false},
  {n:'220',name:'Poppy',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8,base:false},
  {n:'221',name:'Ryme',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:4.35,base:false},
  {n:'222',name:'Eiscue ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:74.7,base:false,important:true},
  {n:'223',name:'Charizard ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:701.16,base:false,important:true},
  {n:'224',name:'Revavroom ex',type:'Metal',color:'#78909C',rare:'Rara Ilustrada Especial',price:37.99,base:false},
  {n:'225',name:'Pidgeot ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:142.97,base:false,important:true},
  {n:'226',name:'Geeta',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:19.72,base:false},
  {n:'227',name:'Poppy',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:20.94,base:false},
  {n:'228',name:'Charizard ex',type:'Sombrio',color:'#607D8B',rare:'Hiper Rara',price:244.06,base:false,important:true},
  {n:'229',name:'Artazon',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:8.41,base:false},
  {n:'230',name:'Basic Fire Energy',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:25,base:false}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV3 = CARDS_SV3;