// SV8PT5 — Prismatic Evolutions (180 cartas)
// Lançamento EN: 2025/01/17
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV8PT5 = [
  {n:'001',name:'Exeggcute',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.09,base:true},
  {n:'002',name:'Exeggutor',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.12,base:true},
  {n:'003',name:'Pinsir',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.08,base:true},
  {n:'004',name:'Budew',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.19,base:true},
  {n:'005',name:'Leafeon',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.35,base:true},
  {n:'006',name:'Leafeon ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:19.90,base:true},
  {n:'007',name:'Cottonee',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.09,base:true},
  {n:'008',name:'Whimsicott',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.14,base:true},
  {n:'009',name:'Applin',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.09,base:true},
  {n:'010',name:'Dipplin',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.09,base:true},
  {n:'011',name:'Hydrapple ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:7.00,base:true},
  {n:'012',name:'Teal Mask Ogerpon ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:29.75,base:true},
  {n:'013',name:'Flareon',type:'Fogo',color:'#F44336',rare:'Rara',price:0.80,base:true},
  {n:'014',name:'Flareon ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:26.51,base:true},
  {n:'015',name:'Litleo',type:'Fogo',color:'#F44336',rare:'Comum',price:0.10,base:true},
  {n:'016',name:'Pyroar',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.09,base:true},
  {n:'017',name:'Hearthflame Mask Ogerpon ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:3.90,base:true},
  {n:'018',name:'Slowpoke',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.09,base:true},
  {n:'019',name:'Slowking',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.09,base:true},
  {n:'020',name:'Goldeen',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.09,base:true},
  {n:'021',name:'Seaking',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.09,base:true},
  {n:'022',name:'Vaporeon',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.48,base:true},
  {n:'023',name:'Vaporeon ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:17.99,base:true},
  {n:'024',name:'Suicune',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.09,base:true},
  {n:'025',name:'Glaceon',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.35,base:true},
  {n:'026',name:'Glaceon ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:3.00,base:true},
  {n:'027',name:'Wellspring Mask Ogerpon ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:7.80,base:true},
  {n:'028',name:'Pikachu ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:18.90,base:true},
  {n:'029',name:'Jolteon',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.49,base:true},
  {n:'030',name:'Jolteon ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:19.00,base:true},
  {n:'031',name:'Iron Hands ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:3.80,base:true},
  {n:'032',name:'Iron Thorns ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:3.88,base:true},
  {n:'033',name:'Espeon',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.98,base:true},
  {n:'034',name:'Espeon ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:16.90,base:true},
  {n:'035',name:'Duskull',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'036',name:'Dusclops',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'037',name:'Dusknoir',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.50,base:true},
  {n:'038',name:'Spritzee',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.09,base:true},
  {n:'039',name:'Aromatisse',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'040',name:'Sylveon',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.99,base:true},
  {n:'041',name:'Sylveon ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:22.10,base:true},
  {n:'042',name:'Scream Tail',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.08,base:true},
  {n:'043',name:'Flutter Mane',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.13,base:true},
  {n:'044',name:'Munkidori',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:1.90,base:true},
  {n:'045',name:'Fezandipiti',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.14,base:true},
  {n:'046',name:'Iron Boulder',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.15,base:true},
  {n:'047',name:'Larvitar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.07,base:true},
  {n:'048',name:'Pupitar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.09,base:true},
  {n:'049',name:'Groudon',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.19,base:true},
  {n:'050',name:'Riolu',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.14,base:true},
  {n:'051',name:'Lucario ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:5.85,base:true},
  {n:'052',name:'Hippopotas',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.07,base:true},
  {n:'053',name:'Hippowdon',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'054',name:'Bloodmoon Ursaluna',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.17,base:true},
  {n:'055',name:'Great Tusk',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.10,base:true},
  {n:'056',name:'Sandy Shocks ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:4.00,base:true},
  {n:'057',name:'Okidogi',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.17,base:true},
  {n:'058',name:'Cornerstone Mask Ogerpon ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:7.00,base:true},
  {n:'059',name:'Umbreon',type:'Sombrio',color:'#607D8B',rare:'Rara',price:1.00,base:true},
  {n:'060',name:'Umbreon ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:18.95,base:true},
  {n:'061',name:'Sneasel',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.09,base:true},
  {n:'062',name:'Houndour',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.08,base:true},
  {n:'063',name:'Houndoom',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.12,base:true},
  {n:'064',name:'Tyranitar ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:4.75,base:true},
  {n:'065',name:'Roaring Moon',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.18,base:true},
  {n:'066',name:'Bronzor',type:'Metal',color:'#78909C',rare:'Comum',price:0.08,base:true},
  {n:'067',name:'Bronzong',type:'Metal',color:'#78909C',rare:'Incomum',price:0.07,base:true},
  {n:'068',name:'Heatran',type:'Metal',color:'#78909C',rare:'Incomum',price:0.07,base:true},
  {n:'069',name:'Duraludon',type:'Metal',color:'#78909C',rare:'Comum',price:0.09,base:true},
  {n:'070',name:'Archaludon',type:'Metal',color:'#78909C',rare:'Rara',price:0.18,base:true},
  {n:'071',name:'Dreepy',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.10,base:true},
  {n:'072',name:'Drakloak',type:'Dragão',color:'#3F51B5',rare:'Comum',price:0.09,base:true},
  {n:'073',name:'Dragapult ex',type:'Dragão',color:'#3F51B5',rare:'Rara Dupla',price:4.35,base:true},
  {n:'074',name:'Eevee',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'075',name:'Eevee ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:19.90,base:true},
  {n:'076',name:'Snorlax ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:4.80,base:true},
  {n:'077',name:'Hoothoot',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.08,base:true},
  {n:'078',name:'Noctowl',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.25,base:true},
  {n:'079',name:'Dunsparce',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.15,base:true},
  {n:'080',name:'Dudunsparce',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:5.00,base:true},
  {n:'081',name:'Miltank',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.08,base:true},
  {n:'082',name:'Lugia ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:7.50,base:true},
  {n:'083',name:'Buneary',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.08,base:true},
  {n:'084',name:'Lopunny',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.13,base:true},
  {n:'085',name:'Fan Rotom',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.12,base:true},
  {n:'086',name:'Regigigas',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'087',name:'Shaymin',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'088',name:'Furfrou',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.09,base:true},
  {n:'089',name:'Hawlucha',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.12,base:true},
  {n:'090',name:'Noibat',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.08,base:true},
  {n:'091',name:'Noivern ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:3.80,base:true},
  {n:'092',name:'Terapagos ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:4.70,base:true},
  {n:'093',name:'Amarys',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.09,base:true},
  {n:'094',name:'Area Zero Underdepths',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'095',name:'Binding Mochi',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.07,base:true},
  {n:'096',name:'Black Belt\'s Training',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'097',name:'Black Belt\'s Training',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.06,base:true},
  {n:'098',name:'Black Belt\'s Training',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'099',name:'Black Belt\'s Training',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.08,base:true},
  {n:'100',name:'Briar',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'101',name:'Buddy-Buddy Poffin',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'102',name:'Bug Catching Set',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.13,base:true},
  {n:'103',name:'Carmine',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'104',name:'Ciphermaniac\'s Codebreaking',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'105',name:'Crispin',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'106',name:'Earthen Vessel',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.14,base:true},
  {n:'107',name:'Explorer\'s Guidance',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'108',name:'Festival Grounds',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.18,base:true},
  {n:'109',name:'Friends in Paldea',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'110',name:'Glass Trumpet',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.08,base:true},
  {n:'111',name:'Haban Berry',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.08,base:true},
  {n:'112',name:'Janine\'s Secret Art',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.11,base:true},
  {n:'113',name:'Kieran',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'114',name:'Lacey',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'115',name:'Larry\'s Skill',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.09,base:true},
  {n:'116',name:'Max Rod',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:7.10,base:false},
  {n:'117',name:'Maximum Belt',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:18.80,base:false},
  {n:'118',name:'Ogre\'s Mask',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.07,base:true},
  {n:'119',name:'Prime Catcher',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:4.59,base:false},
  {n:'120',name:'Professor Sada\'s Vitality',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'121',name:'Professor Turo\'s Scenario',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'122',name:'Professor\'s Research',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'123',name:'Professor\'s Research',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.08,base:true},
  {n:'124',name:'Professor\'s Research',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.09,base:true},
  {n:'125',name:'Professor\'s Research',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'126',name:'Rescue Board',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'127',name:'Roto-Stick',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.16,base:true},
  {n:'128',name:'Scoop Up Cyclone',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:3.90,base:false},
  {n:'129',name:'Sparkling Crystal',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:3.50,base:false},
  {n:'130',name:'Techno Radar',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'131',name:'Treasure Tracker',type:'Incolor',color:'#9E9E9E',rare:'ACE SPEC',price:2.80,base:false},
  {n:'132',name:'Amarys',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:2.50,base:false},
  {n:'133',name:'Atticus',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:5.10,base:false},
  {n:'134',name:'Atticus',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:4.80,base:false},
  {n:'135',name:'Brassius',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:4.90,base:false},
  {n:'136',name:'Eri',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8.80,base:false},
  {n:'137',name:'Friends in Paldea',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:2.00,base:false},
  {n:'138',name:'Giacomo',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:4.50,base:false},
  {n:'139',name:'Larry\'s Skill',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:7.88,base:false},
  {n:'140',name:'Mela',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:7.90,base:false},
  {n:'141',name:'Ortega',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:4.70,base:false},
  {n:'142',name:'Raifort',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:4.90,base:false},
  {n:'143',name:'Tyme',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:3.67,base:false},
  {n:'144',name:'Leafeon ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:719.90,base:false,important:true},
  {n:'145',name:'Teal Mask Ogerpon ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:145.50,base:false,important:true},
  {n:'146',name:'Flareon ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:759.89,base:false,important:true},
  {n:'147',name:'Ceruledge ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:212.00,base:false,important:true},
  {n:'148',name:'Hearthflame Mask Ogerpon ex',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada Especial',price:92.40,base:false,important:true},
  {n:'149',name:'Vaporeon ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:599.90,base:false,important:true},
  {n:'150',name:'Glaceon ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:595.00,base:false,important:true},
  {n:'151',name:'Palafin ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:294.45,base:false,important:true},
  {n:'152',name:'Wellspring Mask Ogerpon ex',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada Especial',price:94.90,base:false,important:true},
  {n:'153',name:'Jolteon ex',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada Especial',price:450.00,base:false,important:true},
  {n:'154',name:'Iron Hands ex',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada Especial',price:89.90,base:false,important:true},
  {n:'155',name:'Espeon ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:899.99,base:false,important:true},
  {n:'156',name:'Sylveon ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:1789.00,base:false,important:true},
  {n:'157',name:'Iron Valiant ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:167.99,base:false,important:true},
  {n:'158',name:'Iron Crown ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:104.50,base:false,important:true},
  {n:'159',name:'Sandy Shocks ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:103.99,base:false,important:true},
  {n:'160',name:'Cornerstone Mask Ogerpon ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:106.00,base:false,important:true},
  {n:'161',name:'Umbreon ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:3498.96,base:false,important:true},
  {n:'162',name:'Roaring Moon ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:260.00,base:false,important:true},
  {n:'163',name:'Pecharunt ex',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada Especial',price:268.80,base:false,important:true},
  {n:'164',name:'Gholdengo ex',type:'Metal',color:'#78909C',rare:'Rara Ilustrada Especial',price:118.75,base:false,important:true},
  {n:'165',name:'Dragapult ex',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada Especial',price:479.99,base:false,important:true},
  {n:'166',name:'Raging Bolt ex',type:'Dragão',color:'#3F51B5',rare:'Rara Ilustrada Especial',price:199.90,base:false,important:true},
  {n:'167',name:'Eevee ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:338.00,base:false,important:true},
  {n:'168',name:'Bloodmoon Ursaluna ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:184.90,base:false,important:true},
  {n:'169',name:'Terapagos ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:150.00,base:false,important:true},
  {n:'170',name:'Amarys',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:98.00,base:false,important:true},
  {n:'171',name:'Crispin',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:259.00,base:false,important:true},
  {n:'172',name:'Drayton',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:109.90,base:false,important:true},
  {n:'173',name:'Janine\'s Secret Art',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:140.00,base:false,important:true},
  {n:'174',name:'Kieran',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:115.00,base:false,important:true},
  {n:'175',name:'Lacey',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:119.90,base:false,important:true},
  {n:'176',name:'Iron Leaves ex',type:'Planta',color:'#4CAF50',rare:'Hiper Rara',price:34.90,base:false},
  {n:'177',name:'Teal Mask Ogerpon ex',type:'Planta',color:'#4CAF50',rare:'Hiper Rara',price:54.50,base:false,important:true},
  {n:'178',name:'Walking Wake ex',type:'Aquático',color:'#2196F3',rare:'Hiper Rara',price:32.90,base:false},
  {n:'179',name:'Pikachu ex',type:'Raio',color:'#FFEB3B',rare:'Hiper Rara',price:219.90,base:false,important:true},
  {n:'180',name:'Terapagos ex',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:29.99,base:false,important:true}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV8PT5 = CARDS_SV8PT5;