// ME02 — Fogo Fantasmagórico (130 cartas)
const CARDS_ME02 = [
  // ── BASE 001–094 ──────────────────────────────────────────────────────────
  // GRAMA
  {n:'001',name:'Oddish',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.05,base:true},
  {n:'002',name:'Gloom',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.05,base:true},
  {n:'003',name:'Vileplume',type:'Grama',color:'#4CAF50',rare:'Rara Holo',price:0.15,base:true},
  {n:'004',name:'Mega Heracross ex',type:'Grama',color:'#4CAF50',rare:'Rara Dupla',price:3.39,base:true},
  {n:'005',name:'Lotad',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.05,base:true},
  {n:'006',name:'Lombre',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.05,base:true},
  {n:'007',name:'Ludicolo',type:'Grama',color:'#4CAF50',rare:'Incomum',price:0.05,base:true},
  {n:'008',name:'Genesect',type:'Grama',color:'#4CAF50',rare:'Rara Holo',price:0.15,base:true},
  {n:'009',name:'Nymble',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.05,base:true},
  {n:'010',name:'Lokix',type:'Grama',color:'#4CAF50',rare:'Incomum',price:0.05,base:true},
  // FOGO
  {n:'011',name:'Charmander',type:'Fogo',color:'#F44336',rare:'Comum',price:0.05,base:true},
  {n:'012',name:'Charmeleon',type:'Fogo',color:'#F44336',rare:'Comum',price:0.05,base:true},
  {n:'013',name:'Mega Charizard X ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:13.90,base:true,important:true},
  {n:'014',name:'Moltres',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.20,base:true},
  {n:'015',name:'Darumaka',type:'Fogo',color:'#F44336',rare:'Comum',price:0.05,base:true},
  {n:'016',name:'Darmanitan',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.05,base:true},
  {n:'017',name:'Reshiram',type:'Fogo',color:'#F44336',rare:'Rara Holo',price:0.10,base:true},
  {n:'018',name:'Oricorio ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:2.79,base:true},
  {n:'019',name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.05,base:true},
  {n:'020',name:'Ceruledge',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.05,base:true},
  // AQUÁTICO
  {n:'021',name:'Seel',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.07,base:true},
  {n:'022',name:'Dewgong',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.05,base:true},
  {n:'023',name:'Swinub',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.09,base:true},
  {n:'024',name:'Piloswine',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.05,base:true},
  {n:'025',name:'Mamoswine',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.05,base:true},
  {n:'026',name:'Suicune',type:'Aquático',color:'#2196F3',rare:'Rara Holo',price:0.12,base:true},
  {n:'027',name:'Piplup',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.05,base:true},
  {n:'028',name:'Prinplup',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  // RAIO
  {n:'029',name:'Rotom ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:1.99,base:true},
  {n:'030',name:'Yamper',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.04,base:true},
  {n:'031',name:'Boltund',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.06,base:true},
  {n:'032',name:'Pawmi',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.05,base:true},
  {n:'033',name:'Pawmo',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.09,base:true},
  {n:'034',name:'Pawmot',type:'Raio',color:'#FFEB3B',rare:'Rara Holo',price:0.10,base:true},
  // PSÍQUICO
  {n:'035',name:'Misdreavus',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.05,base:true},
  {n:'036',name:'Mismagius ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:2.90,base:true},
  {n:'037',name:'Snubbull',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.04,base:true},
  {n:'038',name:'Granbull',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.05,base:true},
  {n:'039',name:'Cresselia',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.05,base:true},
  {n:'040',name:'Meloetta',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.10,base:true},
  {n:'041',name:'Mega Diancie ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:3.79,base:true},
  {n:'042',name:'Mimikyu',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.05,base:true},
  {n:'043',name:'Milcery',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.03,base:true},
  {n:'044',name:'Alcremie',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.04,base:true},
  {n:'045',name:'Zacian',type:'Psíquico',color:'#9C27B0',rare:'Rara Holo',price:0.12,base:true},
  {n:'046',name:'Bramblin',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.10,base:true},
  {n:'047',name:'Brambleghast',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.08,base:true},
  // LUTADOR
  {n:'048',name:'Paldean Tauros',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'049',name:'Gligar',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.06,base:true,important:true},
  {n:'050',name:'Gliscor',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.08,base:true},
  {n:'051',name:'Trapinch',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.05,base:true},
  {n:'052',name:'Vibrava',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.07,base:true},
  {n:'053',name:'Flygon',type:'Lutador',color:'#FF9800',rare:'Rara Holo',price:0.12,base:true},
  // ESCURIDÃO
  {n:'054',name:'Gastly',type:'Escuridão',color:'#607D8B',rare:'Comum',price:0.05,base:true},
  {n:'055',name:'Haunter',type:'Escuridão',color:'#607D8B',rare:'Incomum',price:0.05,base:true},
  {n:'056',name:'Mega Gengar ex',type:'Escuridão',color:'#607D8B',rare:'Rara Dupla',price:5.90,base:true},
  {n:'057',name:'Murkrow',type:'Escuridão',color:'#607D8B',rare:'Comum',price:0.04,base:true},
  {n:'058',name:'Honchkrow',type:'Escuridão',color:'#607D8B',rare:'Incomum',price:0.05,base:true},
  {n:'059',name:'Sableye',type:'Escuridão',color:'#607D8B',rare:'Comum',price:0.07,base:true},
  {n:'060',name:'Carvanha',type:'Escuridão',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'061',name:'Mega Sharpedo ex',type:'Escuridão',color:'#607D8B',rare:'Rara Dupla',price:4.80,base:true},
  {n:'062',name:'Seviper',type:'Escuridão',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  {n:'063',name:'Absol',type:'Escuridão',color:'#607D8B',rare:'Incomum',price:0.05,base:true},
  {n:'064',name:'Sandile',type:'Escuridão',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'065',name:'Krokorok',type:'Escuridão',color:'#607D8B',rare:'Comum',price:0.05,base:true},
  {n:'066',name:'Krookodile',type:'Escuridão',color:'#607D8B',rare:'Incomum',price:0.05,base:true},
  {n:'067',name:'Toxel',type:'Escuridão',color:'#607D8B',rare:'Comum',price:0.10,base:true},
  {n:'068',name:'Toxtricity',type:'Escuridão',color:'#607D8B',rare:'Rara Holo',price:0.15,base:true,important:true},
  {n:'069',name:'Eternatus',type:'Escuridão',color:'#607D8B',rare:'Incomum',price:0.10,base:true},
  // METAL
  {n:'070',name:'Empoleon ex',type:'Metal',color:'#9E9E9E',rare:'Rara Dupla',price:2.80,base:true},
  {n:'071',name:'Bronzor',type:'Metal',color:'#9E9E9E',rare:'Comum',price:0.05,base:true},
  {n:'072',name:'Bronzong',type:'Metal',color:'#9E9E9E',rare:'Incomum',price:0.05,base:true},
  {n:'073',name:'Togedemaru',type:'Metal',color:'#9E9E9E',rare:'Comum',price:0.05,base:true},
  {n:'074',name:'Duraludon',type:'Metal',color:'#9E9E9E',rare:'Comum',price:0.05,base:true},
  {n:'075',name:'Archaludon',type:'Metal',color:'#9E9E9E',rare:'Incomum',price:0.12,base:true},
  // INCOLOR
  {n:'076',name:'Jigglypuff',type:'Incolor',color:'#78909C',rare:'Comum',price:0.05,base:true},
  {n:'077',name:'Wigglytuff',type:'Incolor',color:'#78909C',rare:'Incomum',price:0.10,base:true},
  {n:'078',name:'Aipom',type:'Incolor',color:'#78909C',rare:'Comum',price:0.05,base:true},
  {n:'079',name:'Ambipom',type:'Incolor',color:'#78909C',rare:'Rara Holo',price:0.15,base:true},
  {n:'080',name:'Smeargle',type:'Incolor',color:'#78909C',rare:'Comum',price:0.05,base:true},
  {n:'081',name:'Zigzagoon',type:'Incolor',color:'#78909C',rare:'Comum',price:0.05,base:true},
  {n:'082',name:'Linoone',type:'Incolor',color:'#78909C',rare:'Incomum',price:0.05,base:true},
  {n:'083',name:'Buneary',type:'Incolor',color:'#78909C',rare:'Comum',price:0.05,base:true},
  {n:'084',name:'Mega Lopunny ex',type:'Incolor',color:'#78909C',rare:'Rara Dupla',price:4.00,base:true},
  // TREINADORES
  {n:'085',name:'Gaiola de Batalha',type:'Estádio',color:'#795548',rare:'Incomum',price:0.20,base:true},
  {n:'086',name:'Maçarico',type:'Item',color:'#5C6BC0',rare:'Incomum',price:0.05,base:true},
  {n:'087',name:'Aurora',type:'Suporte',color:'#E91E63',rare:'Incomum',price:0.36,base:true,important:true},
  {n:'088',name:'Vale Tontear',type:'Estádio',color:'#795548',rare:'Incomum',price:0.10,base:true},
  {n:'089',name:'Piromaníaco',type:'Suporte',color:'#E91E63',rare:'Incomum',price:0.08,base:true},
  {n:'090',name:'Movimento do Grimsley',type:'Suporte',color:'#E91E63',rare:'Incomum',price:0.10,base:true},
  {n:'091',name:'Sorvetão Jumbo',type:'Item',color:'#5C6BC0',rare:'Incomum',price:0.10,base:true},
  {n:'092',name:'Capacete Punk',type:'Item Ferramenta',color:'#5C6BC0',rare:'Incomum',price:0.09,base:true},
  {n:'093',name:'Amuleto Sagrado',type:'Item Ferramenta',color:'#5C6BC0',rare:'Incomum',price:0.10,base:true},
  {n:'094',name:'Wondrous Patch',type:'Item',color:'#5C6BC0',rare:'Incomum',price:0.09,base:true,important:true},
  // ── SECRETAS 095–130 ──────────────────────────────────────────────────────
  // Ilustração Rara (IR) 095–107
  {n:'095',name:'Ludicolo (IR)',type:'Grama',color:'#4CAF50',rare:'Ilustr. Rara',price:10.90,base:false},
  {n:'096',name:'Nymble (IR)',type:'Grama',color:'#4CAF50',rare:'Ilustr. Rara',price:5.90,base:false},
  {n:'097',name:'Dewgong (IR)',type:'Aquático',color:'#2196F3',rare:'Ilustr. Rara',price:14.00,base:false},
  {n:'098',name:'Piplup (IR)',type:'Aquático',color:'#2196F3',rare:'Ilustr. Rara',price:24.90,base:false},
  {n:'099',name:'Yamper (IR)',type:'Raio',color:'#FFEB3B',rare:'Ilustr. Rara',price:10.90,base:false},
  {n:'100',name:'Zacian (IR)',type:'Psíquico',color:'#9C27B0',rare:'Ilustr. Rara',price:17.90,base:false},
  {n:'101',name:'Flygon (IR)',type:'Lutador',color:'#FF9800',rare:'Ilustr. Rara',price:13.90,base:false},
  {n:'102',name:'Paldean Wooper (IR)',type:'Água',color:'#2196F3',rare:'Ilustr. Rara',price:10.50,base:false},
  {n:'103',name:'Toxtricity (IR)',type:'Escuridão',color:'#607D8B',rare:'Ilustr. Rara',price:12.90,base:false},
  {n:'104',name:'Togedemaru (IR)',type:'Metal',color:'#9E9E9E',rare:'Ilustr. Rara',price:9.90,base:false},
  {n:'105',name:'Wigglytuff (IR)',type:'Incolor',color:'#78909C',rare:'Ilustr. Rara',price:23.00,base:false},
  {n:'106',name:'Aurora (IR)',type:'Suporte',color:'#E91E63',rare:'Ilustr. Rara',price:95.00,base:false},
  {n:'107',name:'Movimento do Grimsley (IR)',type:'Suporte',color:'#E91E63',rare:'Ilustr. Rara',price:8.90,base:false},
  // Rara Ultra (UR) 108–124
  {n:'108',name:'Mega Charizard X ex (UR)',type:'Fogo',color:'#F44336',rare:'Rara Ultra',price:9.50,base:false},
  {n:'109',name:'Mega Heracross ex (UR)',type:'Grama',color:'#4CAF50',rare:'Rara Ultra',price:129.90,base:false},
  {n:'110',name:'Mega Gengar ex (UR)',type:'Escuridão',color:'#607D8B',rare:'Rara Ultra',price:8.90,base:false},
  {n:'111',name:'Mega Sharpedo ex (UR)',type:'Escuridão',color:'#607D8B',rare:'Rara Ultra',price:8.50,base:false},
  {n:'112',name:'Mega Diancie ex (UR)',type:'Psíquico',color:'#9C27B0',rare:'Rara Ultra',price:11.50,base:false},
  {n:'113',name:'Mega Lopunny ex (UR)',type:'Incolor',color:'#78909C',rare:'Rara Ultra',price:13.50,base:false},
  {n:'114',name:'Oricorio ex (UR)',type:'Fogo',color:'#F44336',rare:'Rara Ultra',price:11.50,base:false},
  {n:'115',name:'Rotom ex (UR)',type:'Raio',color:'#FFEB3B',rare:'Rara Ultra',price:23.90,base:false},
  {n:'116',name:'Mismagius ex (UR)',type:'Psíquico',color:'#9C27B0',rare:'Rara Ultra',price:13.50,base:false},
  {n:'117',name:'Empoleon ex (UR)',type:'Metal',color:'#9E9E9E',rare:'Rara Ultra',price:4.00,base:false},
  {n:'118',name:'Aurora (UR)',type:'Suporte',color:'#E91E63',rare:'Rara Ultra',price:38.90,base:false},
  {n:'119',name:'Piromaníaco (UR)',type:'Suporte',color:'#E91E63',rare:'Rara Ultra',price:6.49,base:false},
  {n:'120',name:'Movimento do Grimsley (UR)',type:'Suporte',color:'#E91E63',rare:'Rara Ultra',price:10.90,base:false},
  {n:'121',name:'Wondrous Patch (UR)',type:'Item',color:'#5C6BC0',rare:'Rara Ultra',price:7.50,base:false},
  {n:'122',name:'Sorvetão Jumbo (UR)',type:'Item',color:'#5C6BC0',rare:'Rara Ultra',price:3.94,base:false},
  {n:'123',name:'Capacete Punk (UR)',type:'Item Ferramenta',color:'#5C6BC0',rare:'Rara Ultra',price:12.90,base:false},
  {n:'124',name:'Gaiola de Batalha (UR)',type:'Estádio',color:'#795548',rare:'Rara Ultra',price:21.90,base:false},
  // Ilustração Rara Especial (SAR) 125–129
  {n:'125',name:'Mega Charizard X ex (SAR)',type:'Fogo',color:'#F44336',rare:'Ilustr. Esp. Rara',price:1550.00,base:false},
  {n:'126',name:'Mega Gengar ex (SAR)',type:'Escuridão',color:'#607D8B',rare:'Ilustr. Esp. Rara',price:63.90,base:false},
  {n:'127',name:'Mega Lopunny ex (SAR)',type:'Incolor',color:'#78909C',rare:'Ilustr. Esp. Rara',price:79.90,base:false},
  {n:'128',name:'Aurora (SAR)',type:'Suporte',color:'#E91E63',rare:'Ilustr. Esp. Rara',price:85.90,base:false},
  {n:'129',name:'Movimento do Grimsley (SAR)',type:'Suporte',color:'#E91E63',rare:'Ilustr. Esp. Rara',price:167.99,base:false},
  // Mega Hyper Rare 130
  {n:'130',name:'Mega Charizard X ex GOLD',type:'Fogo',color:'#FFD700',rare:'Mega Hyper Rare',price:1290.00,base:false},
];
