// MEG — Megaevolução (188 cartas)
const CARDS_MEG = [
  // ── BASE 001–132 ──────────────────────────────────────────────────────────
  // GRAMA
  {n:'001',name:'Bulbasaur',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.25,base:true},
  {n:'002',name:'Ivysaur',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.21,base:true},
  {n:'003',name:'Mega Venusaur ex',type:'Grama',color:'#4CAF50',rare:'Rara Dupla',price:0.78,base:true,important:true},
  {n:'004',name:'Exeggcute',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.07,base:true},
  {n:'005',name:'Exeggutor',type:'Grama',color:'#4CAF50',rare:'Incomum',price:0.07,base:true},
  {n:'006',name:'Tangela',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.09,base:true},
  {n:'007',name:'Tangrowth',type:'Grama',color:'#4CAF50',rare:'Incomum',price:0.06,base:true},
  {n:'008',name:'Chikorita',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.19,base:true},
  {n:'009',name:'Bayleef',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.22,base:true},
  {n:'010',name:'Meganium',type:'Grama',color:'#4CAF50',rare:'Rara',price:0.24,base:true},
  {n:'011',name:'Shuckle',type:'Grama',color:'#4CAF50',rare:'Incomum',price:0.09,base:true},
  {n:'012',name:'Celebi',type:'Grama',color:'#4CAF50',rare:'Incomum',price:0.21,base:true},
  {n:'013',name:'Seedot',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.05,base:true},
  {n:'014',name:'Nuzleaf',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'015',name:'Shiftry',type:'Grama',color:'#4CAF50',rare:'Incomum',price:0.04,base:true},
  {n:'016',name:'Nincada',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.07,base:true},
  {n:'017',name:'Ninjask',type:'Grama',color:'#4CAF50',rare:'Incomum',price:0.09,base:true},
  {n:'018',name:'Dhelmise',type:'Grama',color:'#4CAF50',rare:'Comum',price:0.06,base:true},
  // FOGO
  {n:'019',name:'Vulpix',type:'Fogo',color:'#F44336',rare:'Comum',price:0.13,base:true},
  {n:'020',name:'Ninetales',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.11,base:true,important:true},
  {n:'021',name:'Numel',type:'Fogo',color:'#F44336',rare:'Comum',price:0.12,base:true},
  {n:'022',name:'Mega Camerupt ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:0.47,base:true},
  {n:'023',name:'Litleo',type:'Fogo',color:'#F44336',rare:'Comum',price:0.06,base:true},
  {n:'024',name:'Pyroar',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.05,base:true},
  {n:'025',name:'Volcanion',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.05,base:true},
  {n:'026',name:'Scorbunny',type:'Fogo',color:'#F44336',rare:'Comum',price:0.05,base:true},
  {n:'027',name:'Raboot',type:'Fogo',color:'#F44336',rare:'Comum',price:0.09,base:true},
  {n:'028',name:'Cinderace',type:'Fogo',color:'#F44336',rare:'Rara',price:0.18,base:true},
  {n:'029',name:'Sizzlipede',type:'Fogo',color:'#F44336',rare:'Comum',price:0.07,base:true},
  {n:'030',name:'Centiskorch',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.04,base:true},
  {n:'031',name:'Chi-Yu',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.07,base:true},
  // AQUÁTICO
  {n:'032',name:'Mantine',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.12,base:true},
  {n:'033',name:'Corphish',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.04,base:true},
  {n:'034',name:'Kyogre',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.14,base:true},
  {n:'035',name:'Snover',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.12,base:true},
  {n:'036',name:'Mega Abomasnow ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:0.48,base:true},
  {n:'037',name:'Clauncher',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.10,base:true},
  {n:'038',name:'Clawitzer',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.05,base:true},
  {n:'039',name:'Sobble',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'040',name:'Drizzile',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'041',name:'Inteleon',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.11,base:true},
  {n:'042',name:'Snom',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.15,base:true},
  {n:'043',name:'Frosmoth',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.07,base:true},
  {n:'044',name:'Eiscue',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.06,base:true},
  // RAIO
  {n:'045',name:'Magnemite',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.06,base:true},
  {n:'046',name:'Magneton',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.17,base:true},
  {n:'047',name:'Magnezone',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.07,base:true},
  {n:'048',name:'Raikou',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.11,base:true},
  {n:'049',name:'Electrike',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.09,base:true},
  {n:'050',name:'Mega Manectric ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:0.40,base:true},
  {n:'051',name:'Pachirisu',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.09,base:true},
  {n:'052',name:'Helioptile',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.10,base:true},
  {n:'053',name:'Heliolisk',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.03,base:true},
  // PSÍQUICO
  {n:'054',name:'Abra',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'055',name:'Kadabra',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.19,base:true},
  {n:'056',name:'Alakazam',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.32,base:true},
  {n:'057',name:'Jynx',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'058',name:'Ralts',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.19,base:true},
  {n:'059',name:'Kirlia',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.25,base:true},
  {n:'060',name:'Mega Gardevoir ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:0.64,base:true},
  {n:'061',name:'Shedinja',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.06,base:true},
  {n:'062',name:'Spoink',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.08,base:true},
  {n:'063',name:'Grumpig',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.03,base:true},
  {n:'064',name:'Xerneas',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.15,base:true},
  {n:'065',name:'Greavard',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.05,base:true},
  {n:'066',name:'Houndstone',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.06,base:true},
  {n:'067',name:'Gimmighoul',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.09,base:true},
  // LUTADOR
  {n:'068',name:'Sandshrew',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.08,base:true},
  {n:'069',name:'Sandslash',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.06,base:true},
  {n:'070',name:'Onix',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.08,base:true},
  {n:'071',name:'Tyrogue',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.16,base:true},
  {n:'072',name:'Makuhita',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.14,base:true},
  {n:'073',name:'Hariyama',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.16,base:true,important:true},
  {n:'074',name:'Lunatone',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.27,base:true},
  {n:'075',name:'Solrock',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.16,base:true},
  {n:'076',name:'Riolu',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.16,base:true},
  {n:'077',name:'Mega Lucario ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:0.76,base:true},
  {n:'078',name:'Croagunk',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.08,base:true},
  {n:'079',name:'Toxicroak',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.07,base:true},
  {n:'080',name:'Marshadow',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.05,base:true},
  {n:'081',name:'Stonjourner',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.07,base:true},
  {n:'082',name:'Nacli',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.09,base:true},
  {n:'083',name:'Naclstack',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.13,base:true},
  {n:'084',name:'Garganacl',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.06,base:true},
  // ESCURIDÃO
  {n:'085',name:'Crawdaunt',type:'Escuridão',color:'#607D8B',rare:'Incomum',price:0.05,base:true},
  {n:'086',name:'Mega Absol ex',type:'Escuridão',color:'#607D8B',rare:'Rara Dupla',price:0.71,base:true},
  {n:'087',name:'Spiritomb',type:'Escuridão',color:'#607D8B',rare:'Incomum',price:0.09,base:true},
  {n:'088',name:'Yveltal',type:'Escuridão',color:'#607D8B',rare:'Rara',price:0.23,base:true},
  {n:'089',name:'Nickit',type:'Escuridão',color:'#607D8B',rare:'Comum',price:0.05,base:true},
  {n:'090',name:'Thievul',type:'Escuridão',color:'#607D8B',rare:'Incomum',price:0.08,base:true},
  {n:'091',name:'Shroodle',type:'Escuridão',color:'#607D8B',rare:'Comum',price:0.04,base:true},
  {n:'092',name:'Grafaiai',type:'Escuridão',color:'#607D8B',rare:'Incomum',price:0.05,base:true},
  // METAL
  {n:'093',name:'Steelix',type:'Metal',color:'#9E9E9E',rare:'Rara',price:0.11,base:true},
  {n:'094',name:'Mega Mawile ex',type:'Metal',color:'#9E9E9E',rare:'Rara Dupla',price:0.58,base:true},
  {n:'095',name:'Dialga',type:'Metal',color:'#9E9E9E',rare:'Rara',price:0.10,base:true},
  {n:'096',name:'Tinkatink',type:'Metal',color:'#9E9E9E',rare:'Comum',price:0.07,base:true},
  {n:'097',name:'Tinkatuff',type:'Metal',color:'#9E9E9E',rare:'Incomum',price:0.11,base:true},
  {n:'098',name:'Tinkaton',type:'Metal',color:'#9E9E9E',rare:'Rara',price:0.10,base:true},
  {n:'099',name:'Gholdengo',type:'Metal',color:'#9E9E9E',rare:'Incomum',price:0.03,base:true,important:true},
  // DRAGÃO
  {n:'100',name:'Latios',type:'Dragão',color:'#00BCD4',rare:'Rara',price:0.57,base:true},
  {n:'101',name:'Mega Latias ex',type:'Dragão',color:'#00BCD4',rare:'Rara Dupla',price:0.08,base:true},
  // INCOLOR
  {n:'102',name:'Spearow',type:'Incolor',color:'#78909C',rare:'Comum',price:0.07,base:true},
  {n:'103',name:'Fearow',type:'Incolor',color:'#78909C',rare:'Incomum',price:0.07,base:true},
  {n:'104',name:'Mega Kangaskhan ex',type:'Incolor',color:'#78909C',rare:'Rara Dupla',price:0.95,base:true},
  {n:'105',name:'Delibird',type:'Incolor',color:'#78909C',rare:'Incomum',price:0.06,base:true},
  {n:'106',name:'Miltank',type:'Incolor',color:'#78909C',rare:'Incomum',price:0.14,base:true},
  {n:'107',name:'Buneary',type:'Incolor',color:'#78909C',rare:'Comum',price:0.11,base:true},
  {n:'108',name:'Lopunny',type:'Incolor',color:'#78909C',rare:'Incomum',price:0.08,base:true},
  {n:'109',name:'Yungoos',type:'Incolor',color:'#78909C',rare:'Comum',price:0.07,base:true},
  {n:'110',name:'Gumshoos',type:'Incolor',color:'#78909C',rare:'Incomum',price:0.05,base:true},
  {n:'111',name:'Stufful',type:'Incolor',color:'#78909C',rare:'Comum',price:0.08,base:true},
  {n:'112',name:'Bewear',type:'Incolor',color:'#78909C',rare:'Incomum',price:0.05,base:true},
  // TREINADORES
  {n:'113',name:'Travessura da Acerola',type:'Suporte',color:'#E91E63',rare:'Incomum',price:0.08,base:true},
  {n:'114',name:'Ordens do Chefe (Ghetsis)',type:'Suporte',color:'#E91E63',rare:'Incomum',price:0.25,base:true},
  {n:'115',name:'Troca de Energia',type:'Item',color:'#5C6BC0',rare:'Incomum',price:0.16,base:true},
  {n:'116',name:'Super Poção',type:'Item',color:'#5C6BC0',rare:'Incomum',price:0.12,base:true},
  {n:'117',name:'Determinação da Lillie',type:'Suporte',color:'#E91E63',rare:'Incomum',price:0.20,base:true},
  {n:'118',name:'Barganha do Cel. Marte',type:'Suporte',color:'#E91E63',rare:'Incomum',price:0.07,base:true},
  {n:'119',name:'Mega Poção',type:'Item',color:'#5C6BC0',rare:'Incomum',price:0.40,base:true},
  {n:'120',name:'QG da Liga Pokémon',type:'Estádio',color:'#795548',rare:'Incomum',price:0.13,base:true},
  {n:'121',name:'Portador de Resgate',type:'Item',color:'#5C6BC0',rare:'Incomum',price:.60,base:true},
  {n:'122',name:'Faixa de Vitalidade',type:'Item',color:'#5C6BC0',rare:'Incomum',price:.60,base:true},
  // ENERGIA BASE
  {n:'123',name:'Energia Grama',type:'Energia',color:'#4CAF50',rare:'Comum',price:.30,base:true},
  {n:'124',name:'Energia Fogo',type:'Energia',color:'#F44336',rare:'Comum',price:.30,base:true},
  {n:'125',name:'Energia Aquático',type:'Energia',color:'#2196F3',rare:'Comum',price:.30,base:true},
  {n:'126',name:'Energia Raio',type:'Energia',color:'#FFEB3B',rare:'Comum',price:.30,base:true},
  {n:'127',name:'Energia Psíquico',type:'Energia',color:'#9C27B0',rare:'Comum',price:.30,base:true},
  {n:'128',name:'Energia Lutador',type:'Energia',color:'#FF9800',rare:'Comum',price:.30,base:true},
  {n:'129',name:'Energia Escuridão',type:'Energia',color:'#607D8B',rare:'Comum',price:.30,base:true},
  {n:'130',name:'Energia Metal',type:'Energia',color:'#9E9E9E',rare:'Comum',price:.30,base:true},
  {n:'131',name:'Energia Dupla Turbo',type:'Energia',color:'#78909C',rare:'Incomum',price:.80,base:true},
  {n:'132',name:'Energia Turbo Escuridão',type:'Energia',color:'#607D8B',rare:'Incomum',price:.80,base:true},
  // ── SECRETAS 133–188 ──────────────────────────────────────────────────────
  // Ilustração Rara (IR) 133–154
  {n:'133',name:'Bulbasaur (IR)',type:'Grama',color:'#4CAF50',rare:'Ilustr. Rara',price:25.47,base:false},
  {n:'134',name:'Mega Venusaur ex (IR)',type:'Grama',color:'#4CAF50',rare:'Ilustr. Rara',price:22.94,base:false},
  {n:'135',name:'Vulpix (IR)',type:'Fogo',color:'#F44336',rare:'Ilustr. Rara',price:5.40,base:false},
  {n:'136',name:'Mega Camerupt ex (IR)',type:'Fogo',color:'#F44336',rare:'Ilustr. Rara',price:6.33,base:false},
  {n:'137',name:'Kyogre (IR)',type:'Aquático',color:'#2196F3',rare:'Ilustr. Rara',price:4.12,base:false},
  {n:'138',name:'Mega Abomasnow ex (IR)',type:'Aquático',color:'#2196F3',rare:'Ilustr. Rara',price:21.11,base:false},
  {n:'139',name:'Clawitzer (IR)',type:'Aquático',color:'#2196F3',rare:'Ilustr. Rara',price:4.51,base:false},
  {n:'140',name:'Snover (IR)',type:'Aquático',color:'#2196F3',rare:'Ilustr. Rara',price:1.81,base:false,important:true},
  {n:'141',name:'Mega Manectric ex (IR)',type:'Raio',color:'#FFEB3B',rare:'Ilustr. Rara',price:2.04,base:false},
  {n:'142',name:'Mega Gardevoir ex (IR)',type:'Psíquico',color:'#9C27B0',rare:'Ilustr. Rara',price:2.57,base:false},
  {n:'143',name:'Xerneas (IR)',type:'Psíquico',color:'#9C27B0',rare:'Ilustr. Rara',price:3.36,base:false},
  {n:'144',name:'Hariyama (IR)',type:'Lutador',color:'#FF9800',rare:'Ilustr. Rara',price:2.76,base:false},
  {n:'145',name:'Mega Lucario ex (IR)',type:'Lutador',color:'#FF9800',rare:'Ilustr. Rara',price:2.83,base:false},
  {n:'146',name:'Marshadow (IR)',type:'Lutador',color:'#FF9800',rare:'Ilustr. Rara',price:18.26,base:false},
  {n:'147',name:'Mega Absol ex (IR)',type:'Escuridão',color:'#607D8B',rare:'Ilustr. Rara',price:1.54,base:false},
  {n:'148',name:'Yveltal (IR)',type:'Escuridão',color:'#607D8B',rare:'Ilustr. Rara',price:2.91,base:false},
  {n:'149',name:'Mega Mawile ex (IR)',type:'Metal',color:'#9E9E9E',rare:'Ilustr. Rara',price:2.03,base:false},
  {n:'150',name:'Gholdengo (IR)',type:'Metal',color:'#9E9E9E',rare:'Ilustr. Rara',price:7.16,base:false},
  {n:'151',name:'Mega Latias ex (IR)',type:'Dragão',color:'#00BCD4',rare:'Ilustr. Rara',price:4.04,base:false},
  {n:'152',name:'Mega Kangaskhan ex (IR)',type:'Incolor',color:'#78909C',rare:'Ilustr. Rara',price:2.66,base:false},
  {n:'153',name:'Determinação da Lillie (IR)',type:'Suporte',color:'#E91E63',rare:'Ilustr. Rara',price:4.16,base:false},
  {n:'154',name:'Travessura da Acerola (IR)',type:'Suporte',color:'#E91E63',rare:'Ilustr. Rara',price:7.40,base:false},
  // Rara Ultra (UR) 155–176
  {n:'155',name:'Mega Venusaur ex (UR)',type:'Grama',color:'#4CAF50',rare:'Rara Ultra',price:13.86,base:false},
  {n:'156',name:'Mega Camerupt ex (UR)',type:'Fogo',color:'#F44336',rare:'Rara Ultra',price:2.03,base:false},
  {n:'157',name:'Mega Abomasnow ex (UR)',type:'Aquático',color:'#2196F3',rare:'Rara Ultra',price:2.04,base:false},
  {n:'158',name:'Mega Manectric ex (UR)',type:'Raio',color:'#FFEB3B',rare:'Rara Ultra',price:2.17,base:false},
  {n:'159',name:'Mega Gardevoir ex (UR)',type:'Psíquico',color:'#9C27B0',rare:'Rara Ultra',price:5.73,base:false},
  {n:'160',name:'Mega Lucario ex (UR)',type:'Lutador',color:'#FF9800',rare:'Rara Ultra',price:13.88,base:false},
  {n:'161',name:'Mega Absol ex (UR)',type:'Escuridão',color:'#607D8B',rare:'Rara Ultra',price:5.11,base:false},
  {n:'162',name:'Mega Mawile ex (UR)',type:'Metal',color:'#9E9E9E',rare:'Rara Ultra',price:2.91,base:false},
  {n:'163',name:'Mega Latias ex (UR)',type:'Dragão',color:'#00BCD4',rare:'Rara Ultra',price:4.93,base:false},
  {n:'164',name:'Mega Kangaskhan ex (UR)',type:'Incolor',color:'#78909C',rare:'Rara Ultra',price:5.33,base:false},
  {n:'165',name:'Ordens do Chefe - Ghetsis (UR)',type:'Suporte',color:'#E91E63',rare:'Rara Ultra',price:2.17,base:false},
  {n:'166',name:'Determinação da Lillie (UR)',type:'Suporte',color:'#E91E63',rare:'Rara Ultra',price:2.09,base:false},
  {n:'167',name:'Barganha do Cel. Marte (UR)',type:'Suporte',color:'#E91E63',rare:'Rara Ultra',price:5.76,base:false},
  {n:'168',name:'Travessura da Acerola (UR)',type:'Suporte',color:'#E91E63',rare:'Rara Ultra',price:2.29,base:false},
  {n:'169',name:'Faixa de Vitalidade (UR)',type:'Item',color:'#5C6BC0',rare:'Rara Ultra',price:26.04,base:false},
  {n:'170',name:'Troca de Energia (UR)',type:'Item',color:'#5C6BC0',rare:'Rara Ultra',price:1.01,base:false},
  {n:'171',name:'Super Poção (UR)',type:'Item',color:'#5C6BC0',rare:'Rara Ultra',price:1.01,base:false},
  {n:'172',name:'Mega Poção (UR)',type:'Item',color:'#5C6BC0',rare:'Rara Ultra',price:1.10,base:false},
  {n:'173',name:'Portador de Resgate (UR)',type:'Item',color:'#5C6BC0',rare:'Rara Ultra',price:6.34,base:false},
  {n:'174',name:'QG da Liga Pokémon (UR)',type:'Estádio',color:'#795548',rare:'Rara Ultra',price:2.20,base:false},
  {n:'175',name:'Energia Dupla Turbo (UR)',type:'Energia',color:'#78909C',rare:'Rara Ultra',price:4.12,base:false},
  {n:'176',name:'Energia Turbo Escuridão (UR)',type:'Energia',color:'#607D8B',rare:'Rara Ultra',price:3.47,base:false},
  // Ilustração Rara Especial (SAR) 177–186
  {n:'177',name:'Mega Venusaur ex (SAR)',type:'Grama',color:'#4CAF50',rare:'Ilustr. Esp. Rara',price:180.31,base:false},
  {n:'178',name:'Mega Camerupt ex (SAR)',type:'Fogo',color:'#F44336',rare:'Ilustr. Esp. Rara',price:204.82,base:false},
  {n:'179',name:'Mega Abomasnow ex (SAR)',type:'Aquático',color:'#2196F3',rare:'Ilustr. Esp. Rara',price:247.05,base:false},
  {n:'180',name:'Mega Gardevoir ex (SAR)',type:'Psíquico',color:'#9C27B0',rare:'Ilustr. Esp. Rara',price:71.52,base:false},
  {n:'181',name:'Mega Latias ex (SAR)',type:'Dragão',color:'#00BCD4',rare:'Ilustr. Esp. Rara',price:92.83,base:false},
  {n:'182',name:'Mega Kangaskhan ex (SAR)',type:'Incolor',color:'#78909C',rare:'Ilustr. Esp. Rara',price:71.71,base:false},
  {n:'183',name:'Travessura da Acerola (SAR)',type:'Suporte',color:'#E91E63',rare:'Ilustr. Esp. Rara',price:36.28,base:false},
  {n:'184',name:'Ordens do Chefe - Ghetsis (SAR)',type:'Suporte',color:'#E91E63',rare:'Ilustr. Esp. Rara',price:75.18,base:false},
  {n:'185',name:'Determinação da Lillie (SAR)',type:'Suporte',color:'#E91E63',rare:'Ilustr. Esp. Rara',price:18.81,base:false},
  {n:'186',name:'Barganha do Cel. Marte (SAR)',type:'Suporte',color:'#E91E63',rare:'Ilustr. Esp. Rara',price:24.52,base:false},
  // Mega Hyper Rare 187–188
  {n:'187',name:'Mega Lucario ex GOLD',type:'Lutador',color:'#FFD700',rare:'Mega Hyper Rare',price:225.16,base:false},
  {n:'188',name:'Mega Greninja ex GOLD',type:'Aquático',color:'#FFD700',rare:'Mega Hyper Rare',price:284.15,base:false},
];
