// SV1 — Scarlet & Violet (258 cartas)
// Lançamento EN: 2023/03/31
// Gerado por generate_set.js em 2026-06-26
// USD/BRL usado: 5.8
// ATENÇÃO: nomes em inglês — traduza para português conforme necessário
const CARDS_SV1 = [
  {n:'001',dex:204,artist:"Shigenori Negishi",name:'Pineco',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'002',dex:214,artist:"Taira Akitsu",name:'Heracross',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.25,base:true},
  {n:'003',dex:285,artist:"kurumitsu",name:'Shroomish',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'004',dex:286,artist:"Ryuta Fuse",name:'Breloom',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.17,base:true},
  {n:'005',dex:331,artist:"Tika Matsuno",name:'Cacnea',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.21,base:true},
  {n:'006',dex:332,artist:"DOM",name:'Cacturne',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.21,base:true},
  {n:'007',dex:357,artist:"aoki",name:'Tropius',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.22,base:true},
  {n:'008',dex:664,artist:"sowsow",name:'Scatterbug',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'009',dex:665,artist:"Kagemaru Himeno",name:'Spewpa',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'010',dex:666,artist:"Atsuko Nishida",name:'Vivillon',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'011',dex:672,artist:"Tika Matsuno",name:'Skiddo',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'012',dex:673,artist:"Gemi",name:'Gogoat',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'013',dex:906,artist:"Saya Tsuruta",name:'Sprigatito',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'014',dex:907,artist:"Kouki Saitou",name:'Floragato',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.22,base:true},
  {n:'015',dex:908,artist:"Ryota Murayama",name:'Meowscarada',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.50,base:true},
  {n:'016',dex:917,artist:"Tika Matsuno",name:'Tarountula',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'017',dex:917,artist:"Pani Kobayashi",name:'Tarountula',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'018',dex:917,artist:"Kouki Saitou",name:'Tarountula',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'019',dex:918,artist:"takuyoa",name:'Spidops ex',type:'Planta',color:'#4CAF50',rare:'Rara Dupla',price:4.00,base:true},
  {n:'020',dex:928,artist:"yuu",name:'Smoliv',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.18,base:true},
  {n:'021',dex:928,artist:"Shibuzoh.",name:'Smoliv',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.20,base:true},
  {n:'022',dex:929,artist:"Mina Nakai",name:'Dolliv',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.23,base:true},
  {n:'023',dex:930,artist:"Kouki Saitou",name:'Arboliva',type:'Planta',color:'#4CAF50',rare:'Rara',price:0.28,base:true},
  {n:'024',dex:948,artist:"Shin Nagasawa",name:'Toedscool',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.17,base:true},
  {n:'025',dex:948,artist:"Tika Matsuno",name:'Toedscool',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.14,base:true},
  {n:'026',dex:949,artist:"nagimiso",name:'Toedscruel',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.20,base:true},
  {n:'027',dex:951,artist:"Kouki Saitou",name:'Capsakid',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.19,base:true},
  {n:'028',dex:951,artist:"GIDORA",name:'Capsakid',type:'Planta',color:'#4CAF50',rare:'Comum',price:0.10,base:true},
  {n:'029',dex:952,artist:"KEIICHIRO ITO",name:'Scovillain',type:'Planta',color:'#4CAF50',rare:'Incomum',price:0.22,base:true},
  {n:'030',dex:58,artist:"kawayoo",name:'Growlithe',type:'Fogo',color:'#F44336',rare:'Comum',price:0.22,base:true},
  {n:'031',dex:58,artist:"Tika Matsuno",name:'Growlithe',type:'Fogo',color:'#F44336',rare:'Comum',price:0.50,base:true},
  {n:'032',dex:59,artist:"5ban Graphics",name:'Arcanine ex',type:'Fogo',color:'#F44336',rare:'Rara Dupla',price:11.90,base:true},
  {n:'033',dex:228,artist:"nagimiso",name:'Houndour',type:'Fogo',color:'#F44336',rare:'Comum',price:0.20,base:true},
  {n:'034',dex:229,artist:"hncl",name:'Houndoom',type:'Fogo',color:'#F44336',rare:'Comum',price:0.22,base:true},
  {n:'035',dex:324,artist:"Kurata So",name:'Torkoal',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.20,base:true},
  {n:'036',dex:909,artist:"Akira Komayama",name:'Fuecoco',type:'Fogo',color:'#F44336',rare:'Comum',price:0.13,base:true},
  {n:'037',dex:910,artist:"kantaro",name:'Crocalor',type:'Fogo',color:'#F44336',rare:'Incomum',price:0.35,base:true},
  {n:'038',dex:911,artist:"nagimiso",name:'Skeledirge',type:'Fogo',color:'#F44336',rare:'Rara',price:0.40,base:true},
  {n:'039',dex:935,artist:"Souichirou Gunjima",name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.23,base:true},
  {n:'040',dex:935,artist:"nagimiso",name:'Charcadet',type:'Fogo',color:'#F44336',rare:'Comum',price:0.18,base:true},
  {n:'041',dex:936,artist:"AKIRA EGAWA",name:'Armarouge',type:'Fogo',color:'#F44336',rare:'Rara',price:0.26,base:true},
  {n:'042',dex:79,artist:"Narumi Sato",name:'Slowpoke',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.29,base:true},
  {n:'043',dex:80,artist:"Shinji Kanda",name:'Slowbro',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.89,base:true},
  {n:'044',dex:129,artist:"KIYOTAKA OSHIYAMA",name:'Magikarp',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'045',dex:130,artist:"5ban Graphics",name:'Gyarados ex',type:'Aquático',color:'#2196F3',rare:'Rara Dupla',price:9.19,base:true},
  {n:'046',dex:418,artist:"Mizue",name:'Buizel',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.13,base:true},
  {n:'047',dex:419,artist:"Gemi",name:'Floatzel',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.13,base:true},
  {n:'048',dex:594,artist:"Shinji Kanda",name:'Alomomola',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.29,base:true},
  {n:'049',dex:692,artist:"miki kudo",name:'Clauncher',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.17,base:true},
  {n:'050',dex:693,artist:"Souichirou Gunjima",name:'Clawitzer',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.21,base:true},
  {n:'051',dex:779,artist:"kurumitsu",name:'Bruxish',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.15,base:true},
  {n:'052',dex:912,artist:"Mizue",name:'Quaxly',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'053',dex:913,artist:"kirisAki",name:'Quaxwell',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.13,base:true},
  {n:'054',dex:914,artist:"Kouki Saitou",name:'Quaquaval',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.25,base:true},
  {n:'055',dex:960,artist:"Shin Nagasawa",name:'Wiglett',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.17,base:true},
  {n:'056',dex:960,artist:"Tika Matsuno",name:'Wiglett',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.25,base:true},
  {n:'057',dex:961,artist:"KIYOTAKA OSHIYAMA",name:'Wugtrio',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.25,base:true},
  {n:'058',dex:974,artist:"Shin Nagasawa",name:'Cetoddle',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'059',dex:974,artist:"Kouki Saitou",name:'Cetoddle',type:'Aquático',color:'#2196F3',rare:'Comum',price:0.20,base:true},
  {n:'060',dex:975,artist:"Anesaki Dynamic",name:'Cetitan',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.26,base:true},
  {n:'061',dex:977,artist:"Souichirou Gunjima",name:'Dondozo',type:'Aquático',color:'#2196F3',rare:'Rara',price:0.30,base:true},
  {n:'062',dex:978,artist:"OKACHEKE",name:'Tatsugiri',type:'Aquático',color:'#2196F3',rare:'Incomum',price:0.15,base:true},
  {n:'063',dex:81,artist:"KIYOTAKA OSHIYAMA",name:'Magnemite',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.25,base:true},
  {n:'064',dex:82,artist:"Shiburingaru",name:'Magneton',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.22,base:true},
  {n:'065',dex:462,artist:"hncl",name:'Magnezone ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:4.00,base:true},
  {n:'066',dex:179,artist:"Narumi Sato",name:'Mareep',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.10,base:true},
  {n:'067',dex:180,artist:"Kurata So",name:'Flaaffy',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.22,base:true},
  {n:'068',dex:417,artist:"Naoki Saito",name:'Pachirisu',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.30,base:true},
  {n:'069',dex:479,artist:"Nisota Niso",name:'Rotom',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.13,base:true},
  {n:'070',dex:479,artist:"Kouki Saitou",name:'Rotom',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.10,base:true},
  {n:'071',dex:848,artist:"Yuu Nishida",name:'Toxel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.26,base:true},
  {n:'072',dex:849,artist:"Atsushi Furusawa",name:'Toxtricity',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.21,base:true},
  {n:'073',dex:921,artist:"Tika Matsuno",name:'Pawmi',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.20,base:true},
  {n:'074',dex:921,artist:"kantaro",name:'Pawmi',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.20,base:true},
  {n:'075',dex:922,artist:"Saya Tsuruta",name:'Pawmo',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.20,base:true},
  {n:'076',dex:923,artist:"Mizue",name:'Pawmot',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.17,base:true},
  {n:'077',dex:940,artist:"Saya Tsuruta",name:'Wattrel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.09,base:true},
  {n:'078',dex:940,artist:"Shin Nagasawa",name:'Wattrel',type:'Raio',color:'#FFEB3B',rare:'Comum',price:0.20,base:true},
  {n:'079',dex:941,artist:"Kouki Saitou",name:'Kilowattrel',type:'Raio',color:'#FFEB3B',rare:'Incomum',price:0.10,base:true},
  {n:'080',dex:1008,artist:"Kouki Saitou",name:'Miraidon',type:'Raio',color:'#FFEB3B',rare:'Rara',price:0.42,base:true},
  {n:'081',dex:1008,artist:"5ban Graphics",name:'Miraidon ex',type:'Raio',color:'#FFEB3B',rare:'Rara Dupla',price:2.90,base:true},
  {n:'082',dex:96,artist:"OKACHEKE",name:'Drowzee',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.22,base:true},
  {n:'083',dex:97,artist:"Toshinao Aoki",name:'Hypno',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.25,base:true},
  {n:'084',dex:280,artist:"Tika Matsuno",name:'Ralts',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'085',dex:281,artist:"kawayoo",name:'Kirlia',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.30,base:true},
  {n:'086',dex:282,artist:"N-DESIGN Inc.",name:'Gardevoir ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:3.98,base:true},
  {n:'087',dex:353,artist:"Jerky",name:'Shuppet',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'088',dex:354,artist:"PLANETA Mochizuki",name:'Banette ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Dupla',price:4.60,base:true},
  {n:'089',dex:425,artist:"Taira Akitsu",name:'Drifloon',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'090',dex:426,artist:"Yuu Nishida",name:'Drifblim',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.13,base:true},
  {n:'091',dex:669,artist:"Mizue",name:'Flabébé',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'092',dex:670,artist:"saino misaki",name:'Floette',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.25,base:true},
  {n:'093',dex:671,artist:"Haru Akasaka",name:'Florges',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.20,base:true},
  {n:'094',dex:702,artist:"zig",name:'Dedenne',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'095',dex:702,artist:"Nelnal",name:'Dedenne',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.43,base:true},
  {n:'096',dex:707,artist:"GOSSAN",name:'Klefki',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:1.00,base:true},
  {n:'097',dex:926,artist:"Mizue",name:'Fidough',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.22,base:true},
  {n:'098',dex:926,artist:"Saya Tsuruta",name:'Fidough',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.25,base:true},
  {n:'099',dex:927,artist:"You Iribi",name:'Dachsbun',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.09,base:true},
  {n:'100',dex:955,artist:"Hitoshi Ariga",name:'Flittle',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'101',dex:955,artist:"Tika Matsuno",name:'Flittle',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.13,base:true},
  {n:'102',dex:955,artist:"Pani Kobayashi",name:'Flittle',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'103',dex:956,artist:"Hitoshi Ariga",name:'Espathra',type:'Psíquico',color:'#9C27B0',rare:'Incomum',price:0.13,base:true},
  {n:'104',dex:971,artist:"yuu",name:'Greavard',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'105',dex:971,artist:"Shin Nagasawa",name:'Greavard',type:'Psíquico',color:'#9C27B0',rare:'Comum',price:0.20,base:true},
  {n:'106',dex:972,artist:"Kouki Saitou",name:'Houndstone',type:'Psíquico',color:'#9C27B0',rare:'Rara',price:0.30,base:true},
  {n:'107',dex:56,artist:"nagimiso",name:'Mankey',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.09,base:true},
  {n:'108',dex:57,artist:"Ryuta Fuse",name:'Primeape',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.20,base:true},
  {n:'109',dex:979,artist:"Anesaki Dynamic",name:'Annihilape',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.21,base:true},
  {n:'110',dex:307,artist:"miki kudo",name:'Meditite',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'111',dex:308,artist:"Jerky",name:'Medicham',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.13,base:true},
  {n:'112',dex:447,artist:"Naoyo Kimura",name:'Riolu',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.10,base:true},
  {n:'113',dex:447,artist:"chibi",name:'Riolu',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.24,base:true},
  {n:'114',dex:448,artist:"Nurikabe",name:'Lucario',type:'Lutador',color:'#FF9800',rare:'Incomum',price:3.49,base:true},
  {n:'115',dex:551,artist:"Tomokazu Komiya",name:'Sandile',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.20,base:true},
  {n:'116',dex:552,artist:"kantaro",name:'Krokorok',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.25,base:true},
  {n:'117',dex:553,artist:"Misa Tsutsui",name:'Krookodile',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.26,base:true},
  {n:'118',dex:701,artist:"GOSSAN",name:'Hawlucha',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.30,base:true},
  {n:'119',dex:843,artist:"Kouki Saitou",name:'Silicobra',type:'Lutador',color:'#FF9800',rare:'Comum',price:0.20,base:true},
  {n:'120',dex:844,artist:"Yuya Oka",name:'Sandaconda',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.17,base:true},
  {n:'121',dex:874,artist:"Yuka Morii",name:'Stonjourner',type:'Lutador',color:'#FF9800',rare:'Incomum',price:0.10,base:true},
  {n:'122',dex:950,artist:"nagimiso",name:'Klawf',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.25,base:true},
  {n:'123',dex:984,artist:"5ban Graphics",name:'Great Tusk ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:3.98,base:true},
  {n:'124',dex:1007,artist:"Kouki Saitou",name:'Koraidon',type:'Lutador',color:'#FF9800',rare:'Rara',price:0.26,base:true},
  {n:'125',dex:1007,artist:"aky CG Works",name:'Koraidon ex',type:'Lutador',color:'#FF9800',rare:'Rara Dupla',price:4.00,base:true},
  {n:'126',dex:88,artist:"Kouki Saitou",name:'Grimer',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.20,base:true},
  {n:'127',dex:89,artist:"Haru Akasaka",name:'Muk',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.40,base:true},
  {n:'128',dex:336,artist:"sui",name:'Seviper',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.22,base:true},
  {n:'129',dex:442,artist:"Naoyo Kimura",name:'Spiritomb',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.20,base:true},
  {n:'130',dex:453,artist:"Shiburingaru",name:'Croagunk',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.19,base:true},
  {n:'131',dex:454,artist:"Nisota Niso",name:'Toxicroak ex',type:'Sombrio',color:'#607D8B',rare:'Rara Dupla',price:3.99,base:true},
  {n:'132',dex:624,artist:"sowsow",name:'Pawniard',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.13,base:true},
  {n:'133',dex:625,artist:"Hideki Ishikawa",name:'Bisharp',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.15,base:true},
  {n:'134',dex:983,artist:"Anesaki Dynamic",name:'Kingambit',type:'Sombrio',color:'#607D8B',rare:'Rara',price:0.35,base:true},
  {n:'135',dex:942,artist:"kantaro",name:'Maschiff',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.17,base:true},
  {n:'136',dex:942,artist:"KEIICHIRO ITO",name:'Maschiff',type:'Sombrio',color:'#607D8B',rare:'Comum',price:0.20,base:true},
  {n:'137',dex:943,artist:"KIYOTAKA OSHIYAMA",name:'Mabosstiff',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.19,base:true},
  {n:'138',dex:962,artist:"nagimiso",name:'Bombirdier',type:'Sombrio',color:'#607D8B',rare:'Incomum',price:0.18,base:true},
  {n:'139',dex:205,artist:"Lee HyunJung",name:'Forretress',type:'Metal',color:'#78909C',rare:'Incomum',price:0.20,base:true},
  {n:'140',dex:965,artist:"Shin Nagasawa",name:'Varoom',type:'Metal',color:'#78909C',rare:'Comum',price:0.10,base:true},
  {n:'141',dex:965,artist:"nagimiso",name:'Varoom',type:'Metal',color:'#78909C',rare:'Comum',price:0.20,base:true},
  {n:'142',dex:966,artist:"Anesaki Dynamic",name:'Revavroom',type:'Metal',color:'#78909C',rare:'Rara',price:0.21,base:true},
  {n:'143',dex:990,artist:"5ban Graphics",name:'Iron Treads ex',type:'Metal',color:'#78909C',rare:'Rara Dupla',price:3.90,base:true},
  {n:'144',dex:113,artist:"sui",name:'Chansey',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.22,base:true},
  {n:'145',dex:242,artist:"chibi",name:'Blissey',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.21,base:true},
  {n:'146',dex:335,artist:"Yuya Oka",name:'Zangoose',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.25,base:true},
  {n:'147',dex:335,artist:"aoki",name:'Zangoose',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.21,base:true},
  {n:'148',dex:396,artist:"Yuka Morii",name:'Starly',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'149',dex:397,artist:"kantaro",name:'Staravia',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'150',dex:398,artist:"Atsushi Furusawa",name:'Staraptor',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'151',dex:819,artist:"HYOGONOSUKE",name:'Skwovet',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.32,base:true},
  {n:'152',dex:820,artist:"kantaro",name:'Greedent',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'153',dex:876,artist:"Kagemaru Himeno",name:'Indeedee',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.34,base:true},
  {n:'154',dex:915,artist:"Teeziro",name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'155',dex:915,artist:"kodama",name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.07,base:true},
  {n:'156',dex:915,artist:"Mina Nakai",name:'Lechonk',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'157',dex:916,artist:"kirisAki",name:'Oinkologne',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.19,base:true},
  {n:'158',dex:916,artist:"aky CG Works",name:'Oinkologne ex',type:'Incolor',color:'#9E9E9E',rare:'Rara Dupla',price:1.90,base:true},
  {n:'159',dex:924,artist:"Pani Kobayashi",name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.43,base:true},
  {n:'160',dex:924,artist:"yuu",name:'Tandemaus',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.25,base:true},
  {n:'161',dex:925,artist:"KIYOTAKA OSHIYAMA",name:'Maushold',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.30,base:true},
  {n:'162',dex:931,artist:"Oswaldo KATO",name:'Squawkabilly',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.09,base:true},
  {n:'163',dex:967,artist:"AKIRA EGAWA",name:'Cyclizar',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'164',dex:967,artist:"Ryota Murayama",name:'Cyclizar',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.27,base:true},
  {n:'165',dex:973,artist:"kantaro",name:'Flamigo',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.09,base:true},
  {n:'166',artist:"GIDORA",name:'Arven',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.30,base:true},
  {n:'167',artist:"Oswaldo KATO",name:'Beach Court',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'168',artist:"Ayaka Yoshida",name:'Crushing Hammer',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.45,base:true},
  {n:'169',artist:"inose yukie",name:'Defiance Band',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'170',artist:"Toyste Beach",name:'Electric Generator',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.16,base:true},
  {n:'171',artist:"Studio Bora Inc.",name:'Energy Retrieval',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.24,base:true},
  {n:'172',artist:"Toyste Beach",name:'Energy Search',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.50,base:true},
  {n:'173',artist:"Studio Bora Inc.",name:'Energy Switch',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.50,base:true},
  {n:'174',artist:"Toyste Beach",name:'Exp. Share',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.15,base:true},
  {n:'175',artist:"GIDORA",name:'Jacq',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'176',artist:"Hideki Ishikawa",name:'Judge',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.93,base:true},
  {n:'177',artist:"Akira Komayama",name:'Katy',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'178',artist:"Oswaldo KATO",name:'Mesagoza',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'179',artist:"Sanosuke Sakuma",name:'Miriam',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'180',artist:"Sanosuke Sakuma",name:'Nemona',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'181',artist:"Toyste Beach",name:'Nest Ball',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.17,base:true},
  {n:'182',artist:"Studio Bora Inc.",name:'Pal Pad',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.20,base:true},
  {n:'183',artist:"yuu",name:'Penny',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.27,base:true},
  {n:'184',artist:"OKACHEKE",name:'Picnic Basket',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.25,base:true},
  {n:'185',artist:"Studio Bora Inc.",name:'Poké Ball',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.10,base:true},
  {n:'186',artist:"Toyste Beach",name:'Pokégear 3.0',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:2.00,base:true},
  {n:'187',artist:"Studio Bora Inc.",name:'Pokémon Catcher',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.29,base:true},
  {n:'188',artist:"Ayaka Yoshida",name:'Potion',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.09,base:true},
  {n:'189',artist:"kirisAki",name:'Professor\'s Research (Professor Sada)',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.14,base:true},
  {n:'190',artist:"kirisAki",name:'Professor\'s Research (Professor Turo)',type:'Incolor',color:'#9E9E9E',rare:'Rara',price:0.10,base:true},
  {n:'191',artist:"Studio Bora Inc.",name:'Rare Candy',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.19,base:true},
  {n:'192',artist:"Toyste Beach",name:'Rock Chestplate',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'193',artist:"Ayaka Yoshida",name:'Rocky Helmet',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'194',artist:"Studio Bora Inc.",name:'Switch',type:'Incolor',color:'#9E9E9E',rare:'Comum',price:0.09,base:true},
  {n:'195',artist:"nagimiso",name:'Team Star Grunt',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.10,base:true},
  {n:'196',artist:"Ayaka Yoshida",name:'Ultra Ball',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.13,base:true},
  {n:'197',artist:"Studio Bora Inc.",name:'Vitality Band',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.20,base:true},
  {n:'198',artist:"Hitoshi Ariga",name:'Youngster',type:'Incolor',color:'#9E9E9E',rare:'Incomum',price:0.08,base:true},
  {n:'199',dex:917,artist:"Miki Tanaka",name:'Tarountula',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:29.90,base:false,important:true},
  {n:'200',dex:929,artist:"Oswaldo KATO",name:'Dolliv',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:28.90,base:false},
  {n:'201',dex:948,artist:"Akira Komayama",name:'Toedscool',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:20.00,base:false},
  {n:'202',dex:952,artist:"KIYOTAKA OSHIYAMA",name:'Scovillain',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada',price:25.50,base:false},
  {n:'203',dex:936,artist:"nagimiso",name:'Armarouge',type:'Fogo',color:'#F44336',rare:'Rara Ilustrada',price:44.99,base:false,important:true},
  {n:'204',dex:79,artist:"Toshinao Aoki",name:'Slowpoke',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:99.90,base:false,important:true},
  {n:'205',dex:692,artist:"Shinya Komatsu",name:'Clauncher',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:20.00,base:false},
  {n:'206',dex:960,artist:"You Iribi",name:'Wiglett',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:40.00,base:false,important:true},
  {n:'207',dex:977,artist:"AKIRA EGAWA",name:'Dondozo',type:'Aquático',color:'#2196F3',rare:'Rara Ilustrada',price:59.99,base:false,important:true},
  {n:'208',dex:417,artist:"zig",name:'Pachirisu',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:53.11,base:false,important:true},
  {n:'209',dex:922,artist:"Kouki Saitou",name:'Pawmot',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada',price:19.90,base:false,important:true},
  {n:'210',dex:96,artist:"Tomokazu Komiya",name:'Drowzee',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:119.90,base:false,important:true},
  {n:'211',dex:280,artist:"Jiro Sasumo",name:'Ralts',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:69.90,base:false,important:true},
  {n:'212',dex:281,artist:"Jiro Sasumo",name:'Kirlia',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:97.90,base:false,important:true},
  {n:'213',dex:926,artist:"Tika Matsuno",name:'Fidough',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:159.90,base:false,important:true},
  {n:'214',dex:971,artist:"sowsow",name:'Greavard',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada',price:55.82,base:false,important:true},
  {n:'215',dex:447,artist:"Nelnal",name:'Riolu',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:79.99,base:false,important:true},
  {n:'216',dex:551,artist:"Nurikabe",name:'Sandile',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:25.00,base:false},
  {n:'217',dex:950,artist:"Mina Nakai",name:'Klawf',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada',price:15.30,base:false},
  {n:'218',dex:943,artist:"OKACHEKE",name:'Mabosstiff',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:24.90,base:false},
  {n:'219',dex:962,artist:"Shibuzoh.",name:'Bombirdier',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:22.50,base:false},
  {n:'220',dex:983,artist:"Shin Nagasawa",name:'Kingambit',type:'Sombrio',color:'#607D8B',rare:'Rara Ilustrada',price:22.00,base:false,important:true},
  {n:'221',dex:396,artist:"saino misaki",name:'Starly',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:34.00,base:false,important:true},
  {n:'222',dex:819,artist:"Teeziro",name:'Skwovet',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada',price:19.90,base:false},
  {n:'223',dex:918,artist:"takuyoa",name:'Spidops ex',type:'Planta',color:'#4CAF50',rare:'Ultra Rara',price:5.50,base:false},
  {n:'224',dex:59,artist:"5ban Graphics",name:'Arcanine ex',type:'Fogo',color:'#F44336',rare:'Ultra Rara',price:39.00,base:false,important:true},
  {n:'225',dex:130,artist:"5ban Graphics",name:'Gyarados ex',type:'Aquático',color:'#2196F3',rare:'Ultra Rara',price:49.99,base:false,important:true},
  {n:'226',dex:462,artist:"PLANETA Tsuji",name:'Magnezone ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:8.99,base:false},
  {n:'227',dex:1008,artist:"5ban Graphics",name:'Miraidon ex',type:'Raio',color:'#FFEB3B',rare:'Ultra Rara',price:16.00,base:false},
  {n:'228',dex:282,artist:"N-DESIGN Inc.",name:'Gardevoir ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:29.75,base:false},
  {n:'229',dex:354,artist:"PLANETA Mochizuki",name:'Banette ex',type:'Psíquico',color:'#9C27B0',rare:'Ultra Rara',price:14.90,base:false},
  {n:'230',dex:984,artist:"5ban Graphics",name:'Great Tusk ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:6.99,base:false},
  {n:'231',dex:1007,artist:"aky CG Works",name:'Koraidon ex',type:'Lutador',color:'#FF9800',rare:'Ultra Rara',price:6.89,base:false},
  {n:'232',dex:454,artist:"PLANETA Hiiragi",name:'Toxicroak ex',type:'Sombrio',color:'#607D8B',rare:'Ultra Rara',price:11.50,base:false},
  {n:'233',dex:990,artist:"5ban Graphics",name:'Iron Treads ex',type:'Metal',color:'#78909C',rare:'Ultra Rara',price:6.90,base:false},
  {n:'234',dex:916,artist:"aky CG Works",name:'Oinkologne ex',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8.10,base:false},
  {n:'235',artist:"GIDORA",name:'Arven',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:24.00,base:false},
  {n:'236',artist:"GIDORA",name:'Jacq',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8.99,base:false},
  {n:'237',artist:"Akira Komayama",name:'Katy',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:14.00,base:false},
  {n:'238',artist:"Sanosuke Sakuma",name:'Miriam',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:36.00,base:false},
  {n:'239',artist:"yuu",name:'Penny',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:28.55,base:false},
  {n:'240',artist:"kirisAki",name:'Professor\'s Research (Professor Sada)',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:19.99,base:false},
  {n:'241',artist:"kirisAki",name:'Professor\'s Research (Professor Turo)',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:14.99,base:false},
  {n:'242',artist:"nagimiso",name:'Team Star Grunt',type:'Incolor',color:'#9E9E9E',rare:'Ultra Rara',price:8.99,base:false},
  {n:'243',dex:918,artist:"Miki Tanaka",name:'Spidops ex',type:'Planta',color:'#4CAF50',rare:'Rara Ilustrada Especial',price:24.90,base:false,important:true},
  {n:'244',dex:1008,artist:"kantaro",name:'Miraidon ex',type:'Raio',color:'#FFEB3B',rare:'Rara Ilustrada Especial',price:89.99,base:false,important:true},
  {n:'245',dex:282,artist:"Jiro Sasumo",name:'Gardevoir ex',type:'Psíquico',color:'#9C27B0',rare:'Rara Ilustrada Especial',price:335.00,base:false,important:true},
  {n:'246',dex:984,artist:"Pani Kobayashi",name:'Great Tusk ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:34.90,base:false,important:true},
  {n:'247',dex:1007,artist:"Ryota Murayama",name:'Koraidon ex',type:'Lutador',color:'#FF9800',rare:'Rara Ilustrada Especial',price:68.90,base:false,important:true},
  {n:'248',dex:990,artist:"KEIICHIRO ITO",name:'Iron Treads ex',type:'Metal',color:'#78909C',rare:'Rara Ilustrada Especial',price:13.50,base:false},
  {n:'249',artist:"kantaro",name:'Arven',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:38.72,base:false},
  {n:'250',artist:"Oswaldo KATO",name:'Jacq',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:20.00,base:false},
  // Cartas 251-258 completadas em 15/jul/2026 (generate_set.js tinha pageSize=250 sem
  // paginação — perdia o final do set). Preços via api.pokemontcg.io, USD/BRL 5.8.
  {n:'251',artist:"Akira Komayama",name:'Miriam',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:39.90,base:false,important:true},
  {n:'252',artist:"OKACHEKE",name:'Penny',type:'Incolor',color:'#9E9E9E',rare:'Rara Ilustrada Especial',price:26.60,base:false},
  {n:'253',dex:1008,artist:"5ban Graphics",name:'Miraidon ex',type:'Raio',color:'#FFEB3B',rare:'Hiper Rara',price:38.80,base:false},
  {n:'254',dex:1007,artist:"aky CG Works",name:'Koraidon ex',type:'Lutador',color:'#FF9800',rare:'Hiper Rara',price:24.00,base:false},
  {n:'255',artist:"Toyste Beach",name:'Nest Ball',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:30.00,base:false},
  {n:'256',artist:"Studio Bora Inc.",name:'Rare Candy',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:40.00,base:false},
  {n:'257',name:'Basic Lightning Energy',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:28.99,base:false},
  {n:'258',name:'Basic Fighting Energy',type:'Incolor',color:'#9E9E9E',rare:'Hiper Rara',price:49.99,base:false}
];

// Exporta para uso global
if(typeof window !== 'undefined') window.CARDS_SV1 = CARDS_SV1;